PAR_DESC = Fixed length
col_desc = Enter the name, start column, and end column for all fields, separated by commas and each on a single line (e.g fieldName, 1, 12...)
col_label = Column Description
trim_desc = Remove leading and trailing spaces from fields read.
trim_label = Trim Values
set_desc = Character Encoding to be used
set_label = Character Encoding
PAR_TITLE = Fixed Record Parser
Advanced = Advanced
