CONN_DESC = SNMP
host_label = SNMP Host
host_desc = The host to send SNMP messages to.
comm_label = Community String
comm_desc = The SNMP Community
oid_label = SNMP Walk OID (iterate)
oid_desc = Indicates the OID tree to walk.
get_label = SNMP Port
get_desc = Not used in Trap mode.
trap_label = SNMP Trap Port
trap_desc = The connector will listen for traps on this port, or send traps to this port.
time_label = Trap wait timeout
time_desc = Milliseconds ( 0 \= forever )
mode_label = SNMP Mode
mode_desc = Specifies if the connector should listen for traps, send traps, or use SNMP Get/Set requests.
CONN_TITLE = SNMP Connector
Localized.Client = Client
Localized.Trap.Listener = Trap Listener
Localized.Trap.Sender = Trap Sender
Advanced = Advanced
