/*
 * Copyright IBM Corp. 2025
 *
 * SPDX-License-Identifier: Apache-2.0
 */
package com.ibm.di.api.remote;

import java.rmi.Remote;
import java.rmi.RemoteException;
import java.util.Date;
import java.util.List;
import java.util.Map;

import com.ibm.di.api.DIException;
import com.ibm.di.config.interfaces.ExternalPropertiesConfig;
import com.ibm.di.config.interfaces.MetamergeConfig;
import com.ibm.di.config.interfaces.PoolDefConfig;
import com.ibm.di.config.interfaces.SchemaConfig;
import com.ibm.di.entry.Entry;
import com.ibm.di.server.TaskCallBlock;

/**
 * 
 * ConfigInstance MBean interface that defines public methods exposed through
 * Server API remote session.
 * 
 */
public interface ConfigInstance extends Remote {

	/**
	 * Returns the configuration ID generated by the server.
	 * <p>
	 * <b>Example</b>
	 * </p>
	 * 
	 * <pre>
	 *  var sessionFactory = java.rmi.Naming.lookup(&quot;rmi://127.0.0.1:1099/SessionFactory&quot;);
	 *  var remoteSession = sessionFactory.createSession();
	 *  for( ci in remoteSession.getConfigInstances()){
	 *    task.logmsg(&quot;Name: &quot; + ci.getConfigId());
	 *  }
	 * </pre>
	 * 
	 * @return String object representing the configuration ID.
	 * @throws DIException
	 *             if an error occurs while getting the configuration ID.
	 * @throws RemoteException
	 *             if a communication-related exception occurs.
	 */
	public String getConfigId() throws DIException, RemoteException;

	// access to the Config Instance configuration

	/**
	 * Returns configuration instance representing this configuration.
	 * 
	 * @return MetamergeConfig object representing this configuration.
	 * @throws DIException
	 *             if an error occurs while getting the configuration.
	 * @throws RemoteException
	 *             if a communication-related exception occurs.
	 */
	public MetamergeConfig getConfiguration() throws DIException, RemoteException;

	/**
	 * Sets given configuration to this configuration.
	 * 
	 * @param aConfiguration
	 *            The new configuration.
	 * @throws DIException
	 *             if an error occurs while setting the configuration.
	 * @throws RemoteException
	 *             if a communication-related exception occurs.
	 */
	public void setConfiguration(MetamergeConfig aConfiguration) throws DIException, RemoteException;

	/**
	 * @deprecated Not supported.
	 */
	@Deprecated
	public void saveConfiguration() throws DIException, RemoteException;

	/**
	 * @deprecated Not supported.
	 */
	@Deprecated
	public void saveConfiguration(boolean aEncrypt) throws DIException, RemoteException;

	// external properties access

	/**
	 * Returns the external properties of the configuration.
	 * 
	 * @return ExternalPropertiesConfig object representing the configuration's
	 *         external properties.
	 * @throws DIException
	 *             if an error occurs while getting the external properties.
	 * @throws RemoteException
	 *             if a communication-related exception occurs.
	 * @deprecated use {@link #getTDIProperties()} instead
	 */
	@Deprecated
	public ExternalPropertiesConfig getExternalProperties() throws DIException, RemoteException;

	/**
	 * Returns the ExternalPropertiesConfig object for the named external
	 * properties object.
	 * 
	 * @param aKey
	 *            The external property object name.
	 * @return ExternalPropertiesConfig object representing the configuration's
	 *         external properties specified by the external property object
	 *         name.
	 * @throws DIException
	 *             if an error occurs while getting the external properties.
	 * @throws RemoteException
	 *             if a communication-related exception occurs.
	 * @deprecated use {@link #getTDIProperties()} instead
	 */
	@Deprecated
	public ExternalPropertiesConfig getExternalProperties(String aKey) throws DIException, RemoteException;

	/**
	 * Returns the external properties object names.
	 * 
	 * @return String array each value representing one external property object
	 *         name.
	 * @throws DIException
	 *             if an error occurs while getting the external properties
	 *             names.
	 * @throws RemoteException
	 *             if a communication-related exception occurs.
	 * @deprecated use {@link #getTDIProperties()} instead
	 */
	@Deprecated
	public String[] getExternalPropertiesKeys() throws DIException, RemoteException;

	/**
	 * @deprecated Not supported.
	 */
	@Deprecated
	public void setExternalProperties(ExternalPropertiesConfig aExPropConfig) throws DIException, RemoteException;

	/**
	 * @deprecated Not supported.
	 */
	@Deprecated
	public void setExternalProperties(String aKey, ExternalPropertiesConfig aExPropConfig) throws DIException, RemoteException;

	/**
	 * @deprecated Not supported.
	 */
	@Deprecated
	public void saveExternalProperties() throws DIException, RemoteException;

	// quering for available AssemblyLines

	/**
	 * @deprecated Use {@link #getAssemblyLineNames()}.
	 */
	@Deprecated
	public String[] getAssemblyLinesNames() throws DIException, RemoteException;

	/**
	 * Returns the AssemblyLines' names.
	 * <p>
	 * <b>Example</b>
	 * </p>
	 * 
	 * <pre>
	 *  var sessionFactory = java.rmi.Naming.lookup(&quot;rmi://127.0.0.1:1099/SessionFactory&quot;);
	 *  var remoteSession = sessionFactory.createSession();
	 *  var configInstances = remoteSession.getConfigInstances();
	 *  if (configInstances != null){
	 *    for (ci in configInstances){
	 *      for(al in ci.getAssemblyLineNames()){
	 *        task.logmsg(&quot;Al name: &quot; + al);
	 *      }
	 *    }
	 *  } else {
	 *    task.logmsg(&quot;no available config instances&quot;);
	 *  }
	 * </pre>
	 * 
	 * @return String array each value representing AssemblyLine name.
	 * @throws DIException
	 *             if an error occurs while getting the AssemblyLines' names.
	 * @throws RemoteException
	 *             if a communication-related exception occurs.
	 */
	public String[] getAssemblyLineNames() throws DIException, RemoteException;

	/**
	 * Returns a list of integers uniquely identify all the AssemblyLines within
	 * the ConfigInstance.
	 * <p>
	 * <b>Example:</b>
	 * 
	 * <pre>
	 * 	var ci = session.getConfigInstance(&quot;C__Documents and Settings_username_My Documents_TDI_rs.xml&quot;);
	 * 
	 * 	for(al in ci.getAssemblyLineUniqueCodes()){
	 * 	task.logmsg(&quot;Al id: &quot; + al);
	 * 	}
	 * 
	 *  //Sample output:Al name: csv2xml
	 * 		Al id: 2312
	 * </pre>
	 * 
	 * @return integer list each value representing AssemblyLine id.
	 * @throws DIException
	 *             if an error occurs while getting the AssemblyLines' IDs.
	 * @throws RemoteException
	 *             if a communication-related exception occurs.
	 */
	public int[] getAssemblyLineUniqueCodes() throws DIException, RemoteException;

	/**
	 * Searches the list of AssemblyLines for the specified unique code (one
	 * returned by the {@link #getAssemblyLineUniqueCodes()} method)
	 * 
	 * @param alId
	 *            the AssemblyLine ID uniquely identifying the AssemblyLine
	 *            instance in the scope of the ConfigInstance.
	 * 
	 * @return the AssemblyLine found or null
	 * @throws DIException
	 *             if an error occurs while getting the AssemblyLine.
	 * @throws RemoteException
	 *             if a communication-related exception occurs.
	 */
	public AssemblyLine getAssemblyLineByUniqueCode(int alId) throws DIException, RemoteException;

	/**
	 * Returns the AssemblyLine's input parameters.
	 * 
	 * @param aAssemblyLineName
	 *            the name of the AssemblyLine.
	 * @return SchemaConfig representing the schema input of the AssemblyLine.
	 * @throws DIException
	 *             if an error occurs while getting the AssemblyLine's input
	 *             parameters.
	 * @throws RemoteException
	 *             if a communication-related exception occurs.
	 */
	public SchemaConfig getAssemblyLineInputParameters(String aAssemblyLineName) throws DIException, RemoteException;

	/**
	 * Returns the AssemblyLine's output parameters.
	 * 
	 * @param aAssemblyLineName
	 *            the name of the AssemblyLine.
	 * @return SchemaConfig representing the schema output of the AssemblyLine.
	 * @throws DIException
	 *             if an error occurs while getting the AssemblyLine's output
	 *             parameters.
	 * @throws RemoteException
	 *             if a communication-related exception occurs.
	 */
	public SchemaConfig getAssemblyLineOutputParameters(String aAssemblyLineName) throws DIException, RemoteException;

	// access to running processes within this instance

	/**
	 * Returns currently started AssemblyLines of the configuration instance.
	 * <p>
	 * <b>Example</b>
	 * </p>
	 * 
	 * <pre>
	 *  var sessionFactory = java.rmi.Naming.lookup(&quot;rmi://127.0.0.1:1099/SessionFactory&quot;);
	 *  var remoteSession = sessionFactory.createSession();
	 *  var configInstances = remoteSession.getConfigInstances();
	 *  if (configInstances != null){
	 *    for (ci in configInstances){
	 *      for(al in ci.getAssemblyLines()){
	 *        task.logmsg(&quot;Al name: &quot; + al.getName());
	 *      }
	 *    }
	 *  } else {
	 *    task.logmsg(&quot;no available config instances&quot;);
	 *  }
	 * </pre>
	 * 
	 * @return AssemblyLine array object each value represents currently started
	 *         AssemblyLine.
	 * @throws DIException
	 *             if an error occurs while getting the AssemblyLines.
	 * @throws RemoteException
	 *             if a communication-related exception occurs.
	 */
	public AssemblyLine[] getAssemblyLines() throws DIException, RemoteException;

	// AssemblyLine operations

	// simple starting of AssemblyLines

	/**
	 * Starts the specified AssemblyLine asynchronously.
	 * <p>
	 * <b>Example</b>
	 * </p>
	 * 
	 * <pre>
	 * var sessionFactory = java.rmi.Naming.lookup(&quot;rmi://127.0.0.1:1099/SessionFactory&quot;);
	 * var remoteSession = sessionFactory.createSession();
	 * var ci = remoteSession.getConfigInstance(&quot;exampleCI&quot;);
	 * 
	 * 	var al = ci.startAssemblyLine(&quot;exampleAL&quot;);
	 * </pre>
	 * 
	 * @param aAssemblyLineName
	 *            The name of the AssemblyLine.
	 * @return the AssemblyLine object.
	 * @throws DIException
	 *             if an error occurs when starting the AssemblyLine.
	 * @throws RemoteException
	 *             if a communication-related exception occurs.
	 */
	public AssemblyLine startAssemblyLine(String aAssemblyLineName) throws DIException, RemoteException;

	/**
	 * Starts the specified AssemblyLine.
	 * <p>
	 * <b>Example</b>
	 * </p>
	 * 
	 * <pre>
	 * var sessionFactory = java.rmi.Naming.lookup(&quot;rmi://127.0.0.1:1099/SessionFactory&quot;);
	 * var remoteSession = sessionFactory.createSession();
	 * var ci = remoteSession.getConfigInstance(&quot;exampleCI&quot;);
	 * 
	 * 	var al = ci.startAssemblyLine(&quot;exampleAL&quot;, false);
	 * </pre>
	 * 
	 * @param aAssemblyLineName
	 *            The name of the AssemblyLine.
	 * @param aSync
	 *            when <code>true</code> the AssemblyLine is started
	 *            synchronously, when <code>false</code> the AssemblyLine is
	 *            started asynchronously.
	 * @return the AssemblyLine object.
	 * @throws DIException
	 *             if an error occurs when starting the AssemblyLine.
	 * @throws RemoteException
	 *             if a communication-related exception occurs.
	 */
	public AssemblyLine startAssemblyLine(String aAssemblyLineName, boolean aSync) throws DIException, RemoteException;

	// start the AssemblyLine with input data

	/**
	 * Starts the specified AssemblyLine with the given input data
	 * asynchronously.
	 * <p>
	 * <b>Example</b>
	 * </p>
	 * 
	 * <pre>
	 * var sessionFactory = java.rmi.Naming.lookup(&quot;rmi://127.0.0.1:1099/SessionFactory&quot;);
	 * var remoteSession = sessionFactory.createSession();
	 * var mAssemblyLine = remoteSession.getAssemblyLines()[0];
	 * 
	 * if (mAssemblyLine != null) {
	 * 	var ci = mAssemblyLine.getConfigInstance();
	 * 	var al = ci.startAssemblyLine(&quot;exampleAL&quot;, work);
	 * } else {
	 * 	main.logmsg(&quot;No Remote Assembly Lines Running&quot;);
	 * }
	 * </pre>
	 * 
	 * @param aAssemblyLineName
	 *            The name of the AssemblyLine.
	 * @param aInputData
	 *            Initial Work Entry to run the AssemblyLine with.
	 * @return the AssemblyLine object.
	 * @throws DIException
	 *             if an error occurs when starting the AssemblyLine.
	 * @throws RemoteException
	 *             if a communication-related exception occurs.
	 */
	public AssemblyLine startAssemblyLine(String aAssemblyLineName, Entry aInputData) throws DIException, RemoteException;

	/**
	 * Starts the specified AssemblyLine with the given input data.
	 * <p>
	 * When the AssemblyLine is started synchronously it waits the current
	 * thread to die and starts after that.
	 * <p>
	 * <b>Example</b>
	 * </p>
	 * 
	 * <pre>
	 * var sessionFactory = java.rmi.Naming.lookup(&quot;rmi://127.0.0.1:1099/SessionFactory&quot;);
	 * var remoteSession = sessionFactory.createSession();
	 * var mAssemblyLine = remoteSession.getAssemblyLines()[0];
	 * 
	 * if (mAssemblyLine != null) {
	 * 	var ci = mAssemblyLine.getConfigInstance();
	 * 	var al = ci.startAssemblyLine(&quot;exampleAL&quot;, work, false);
	 * } else {
	 * 	main.logmsg(&quot;No Remote Assembly Lines Running&quot;);
	 * }
	 * </pre>
	 * 
	 * @param aAssemblyLineName
	 *            The name of the AssemblyLine.
	 * @param aInputData
	 *            Initial Work Entry to run the AssemblyLine with.
	 * @param aSync
	 *            when <code>true</code> the AssemblyLine is started
	 *            synchronously, when <code>false</code> the AssemblyLine is
	 *            started asynchronously.
	 * @return the AssemblyLine object.
	 * @throws DIException
	 *             if an error occurs when starting the AssemblyLine.
	 * @throws RemoteException
	 *             if a communication-related exception occurs.
	 */
	public AssemblyLine startAssemblyLine(String aAssemblyLineName, Entry aInputData, boolean aSync) throws DIException,
			RemoteException;

	// start the AssemblyLine with input data and get results through callbacks

	/**
	 * Starts asynchronously the specified AssemblyLine with the given input
	 * data and results listener.
	 * 
	 * @param aAssemblyLineName
	 *            The name of the AssemblyLine.
	 * @param aInputData
	 *            Initial Work Entry to run the AssemblyLine with.
	 * @param aListener
	 *            A listener for Entries produced by the AssemblyLine.
	 * @param aGetLogs
	 *            when <code>true</code> the AssemblyLineListener is delivered
	 *            log messages, when <code>false</code> log messages are not
	 *            delivered.
	 * @return the AssemblyLine object.
	 * @throws DIException
	 *             if an error occurs when starting the AssemblyLine.
	 * @throws RemoteException
	 *             if a communication-related exception occurs.
	 */
	public AssemblyLine startAssemblyLine(String aAssemblyLineName, Entry aInputData, AssemblyLineListener aListener,
			boolean aGetLogs) throws DIException, RemoteException;

	/**
	 * Starts the specified AssemblyLine with the given input data and results
	 * listener.
	 * <p>
	 * When the AssemblyLine is started synchronously it waits the current
	 * thread to die and starts after that.
	 * 
	 * @param aAssemblyLineName
	 *            The name of the AssemblyLine.
	 * @param aInputData
	 *            Initial Work Entry to run the AssemblyLine with.
	 * @param aListener
	 *            A listener for Entries produced by the AssemblyLine.
	 * @param aGetLogs
	 *            when <code>true</code> the AssemblyLineListener delivers log
	 *            messages, when <code>false</code> log messages are not
	 *            delivered.
	 * @param aSync
	 *            when <code>true</code> the AssemblyLine is started
	 *            synchronously, when <code>false</code> the AssemblyLine is
	 *            started asynchronously.
	 * @return the AssemblyLine object.
	 * @throws DIException
	 *             if an error occurs when starting the AssemblyLine.
	 * @throws RemoteException
	 *             if a communication-related exception occurs.
	 */
	public AssemblyLine startAssemblyLine(String aAssemblyLineName, Entry aInputData, AssemblyLineListener aListener,
			boolean aGetLogs, boolean aSync) throws DIException, RemoteException;

	/**
	 * Starts the specified AssemblyLine with the given input data and results
	 * listener.
	 * <p>
	 * When the AssemblyLine is started synchronously it waits the current
	 * thread to die and starts after that.
	 * 
	 * @param aAssemblyLineName
	 *            The name of the AssemblyLine.
	 * @param aInputData
	 *            Initial Work Entry to run the AssemblyLine with.
	 * @param aListener
	 *            A listener for Entries produced by the AssemblyLine.
	 * @param aGetLogs
	 *            when <code>true</code> the AssemblyLineListener delivers log
	 *            messages, when <code>false</code> log messages are not
	 *            delivered.
	 * @param aSync
	 *            when <code>true</code> the AssemblyLine is started
	 *            synchronously, when <code>false</code> the AssemblyLine is
	 *            started asynchronously.
	 * @param aGetEntryOnEachCycle
	 *            when <code>true</code> the AssemblyLineListener delivers the
	 *            current entry on each AssemblyLine cycle, when
	 *            <code>false</code> the entries are not delivered.
	 * @return the AssemblyLine object.
	 * @throws DIException
	 *             if an error occurs when starting the AssemblyLine.
	 * @throws RemoteException
	 *             if a communication-related exception occurs.
	 */
	public AssemblyLine startAssemblyLine(String aAssemblyLineName, Entry aInputData, AssemblyLineListener aListener,
			boolean aGetLogs, boolean aSync, boolean aGetEntryOnEachCycle) throws DIException, RemoteException;

	// start the AssemblyLine in manual mode

	/**
	 * Starts the specified AssemblyLine with the given input data in manual
	 * mode.
	 * 
	 * @param aAssemblyLineName
	 *            The name of the AssemblyLine.
	 * @param aInputData
	 *            Initial Work Entry to run the AssemblyLine with.
	 * @return the AssemblyLineHandler object for AssemblyLine manipulation in
	 *         manual mode.
	 * @throws DIException
	 *             if an error occurs when starting the AssemblyLine.
	 * @throws RemoteException
	 *             if a communication-related exception occurs.
	 */
	public AssemblyLineHandler startAssemblyLineManual(String aAssemblyLineName, Entry aInputData) throws DIException,
			RemoteException;

	// the following two methods are for advanced use

	/**
	 * Starts asynchronously the specified AssemblyLine with the given
	 * TaskCallBlock.
	 * 
	 * @param aAssemblyLineName
	 *            The name of the AssemblyLine.
	 * @param aTcb
	 *            The TaskCallBlock object to start the AL with.
	 * @return the AssemblyLine object.
	 * @throws DIException
	 *             if an error occurs when starting the AssemblyLine.
	 * @throws RemoteException
	 *             if a communication-related exception occurs.
	 */
	public AssemblyLine startAssemblyLine(String aAssemblyLineName, TaskCallBlock aTcb) throws DIException, RemoteException;

	/**
	 * Starts the specified AssemblyLine with the given TaskCallBlock.
	 * 
	 * @param aAssemblyLineName
	 *            The name of the AssemblyLine.
	 * @param aTcb
	 *            The TaskCallBlock object to start the AL with.
	 * @param aSync
	 *            when <code>true</code> the AssemblyLine is started
	 *            synchronously, when <code>false</code> the AssemblyLine is
	 *            started asynchronously.
	 * @return the AssemblyLine object.
	 * @throws DIException
	 *             if an error occurs when starting the AssemblyLine.
	 * @throws RemoteException
	 *             if a communication-related exception occurs.
	 */
	public AssemblyLine startAssemblyLine(String aAssemblyLineName, TaskCallBlock aTcb, boolean aSync) throws DIException,
			RemoteException;

	//Starting Sequences
	/**
	 * Starts the specified Sequence.
	 * <p>
	 * <b>Example:</b>
	 * 
	 * <pre>
	 * var ci = session.getConfigInstance(&quot;C__Documents and Settings_username_My Documents_TDI_rs.xml&quot;);
	 * 
	 * var seq = ci.startSequence(&quot;csv2xml&quot;);//Sequence is started
	 * </pre>
	 * 
	 * @param name
	 *            The name of the Sequence.
	 * @return the Sequence object.
	 * @throws DIException
	 *             if an error occurs when starting the Sequence.
	 * @throws RemoteException
	 *             if a communication-related exception occurs.
	 * @since 7.2
	 */
	public Sequence startSequence(String name) throws DIException, RemoteException;

	/**
	 * Starts the specified Sequence specifying a TaskCallBlock, synchronous or asynchronous.
	 * <p>
	 * <b>Example:</b>
	 * 
	 * <pre>
	 * var ci = session.getConfigInstance(&quot;C__Documents and Settings_username_My Documents_TDI_rs.xml&quot;);
	 * 
	 * var seq = ci.startSequence(&quot;csv2xml&quot;, null, true);//Sequence is started in new thread, and has now run to completion
	 * //do something with seq
	 * </pre>
	 * 
	 * @param name
	 *            The name of the Sequence.
	 * @param tcb
	 *            The TaskCallBlock object to start the Sequence with. If null, ignored.
	 * @param sync
	 *            when <code>true</code> the Sequence is started
	 *            synchronously, when <code>false</code> the Sequence is
	 *            started asynchronously.
	 * @return the Sequence object.
	 * @throws DIException
	 *             if an error occurs when starting the Sequence.
	 * @throws RemoteException
	 *             if a communication-related exception occurs.
	 * @since 7.2
	 */
	public Sequence startSequence(String name, TaskCallBlock tcb, boolean sync) throws DIException, RemoteException;

	/**
	 * Starts the specified Sequence with the given TaskCallBlock and a Listener
	 * 
	 * @param name
	 *            The name of the Sequence.
	 * @param tcb
	 *            The TaskCallBlock object to start the Sequence with.
	 * @param listener
	 *            A listener to know when the Sequence has stopped.
	 * @return the Sequence object.
	 * @throws DIException
	 *             if an error occurs when starting the Sequence.
	 * @throws RemoteException
	 *             if a communication-related exception occurs.
	 * @since 7.2
	 */
	public Sequence startSequence(String name, TaskCallBlock tcb, AssemblyLineListener listener) throws DIException, RemoteException;

	// Config Instance operations

	/**
	 * Reloads the Config Instance with its current configuration.
	 * 
	 * @throws DIException
	 *             if an error occurs while reloading the server.
	 * @throws RemoteException
	 *             if a communication-related exception occurs.
	 */
	public void reload() throws DIException, RemoteException;

	/**
	 * Stops the Config Instance.
	 * <p>
	 * <b>Example</b>
	 * </p>
	 * 
	 * <pre>
	 * var sessionFactory = java.rmi.Naming.lookup(&quot;rmi://127.0.0.1:1099/SessionFactory&quot;);
	 * var remoteSession = sessionFactory.createSession();
	 * var configInstances = remoteSession.getConfigInstances();
	 * if (configInstances != null){
	 *   for (ci in configInstances){
	 *     ci.stop();
	 *   }
	 * } else {
	 *   task.logmsg(&quot;no available config instances&quot;);
	 * }
	 * </pre>
	 * 
	 * @throws DIException
	 *             if an error occurs while stopping.
	 * @throws RemoteException
	 *             if a communication-related exception occurs.
	 */
	public void stop() throws DIException, RemoteException;

	/**
	 * Stops the Config Instance, and all AssemblyLines started by it, and waits
	 * a while for the stopping.
	 * <p>
	 * <b>Example</b>
	 * </p>
	 * 
	 * <pre>
	 * var sessionFactory = java.rmi.Naming.lookup(&quot;rmi://127.0.0.1:1099/SessionFactory&quot;);
	 * var remoteSession = sessionFactory.createSession();
	 * var configInstances = remoteSession.getConfigInstances();
	 * if (configInstances != null){
	 *   for (ci in configInstances){
	 *     ci.stop(false);
	 *   }
	 * } else {
	 *   task.logmsg(&quot;no available config instances&quot;);
	 * }
	 * </pre>
	 * 
	 * @param sync
	 *            If true, creates new Threads on the server to do the waiting.
	 * @throws DIException
	 *             if an error occurs while stopping.
	 * @throws RemoteException
	 *             if a communication-related exception occurs.
	 * @since 7.1
	 */
	public void stop(boolean sync) throws DIException, RemoteException;

	// System Log convenience calls

	// AssemblyLines system log

	/**
	 * Returns the names of all available log files for a given AssemblyLine.
	 * 
	 * @param aALName
	 *            the name of the AssemblyLine.
	 * @return a </code>String</code> array, each of its elements specifying the
	 *         name of a log file.
	 * @throws DIException
	 *             if an error occurs while obtaining AssemblyLine's log file
	 *             names.
	 * @throws RemoteException
	 *             if a communication-related exception occurs.
	 */
	public String[] getALLogFileNames(String aALName) throws DIException, RemoteException;

	/**
	 * Returns the name of the log file created on the last run of a given
	 * AssemblyLine.
	 * 
	 * @param aALName
	 *            the name of the AssemblyLine.
	 * @return the name of the log file created on the last AssemblyLine's run.
	 * @throws DIException
	 *             if an error occurs while obtaining the log file name.
	 * @throws RemoteException
	 *             if a communication-related exception occurs.
	 */
	public String getALLastLogFileName(String aALName) throws DIException, RemoteException;

	/**
	 * Given an AssemblyLine name, and a log file name, retrieves the log of
	 * this AssemblyLine, stored in the specified file.
	 * 
	 * @param aALName
	 *            the name of the AssemblyLine.
	 * @param aLogFileName
	 *            the name of the log file; no file path should be specified -
	 *            just the file name.
	 * @return the specified log of the AssemblyLine.
	 * @throws DIException
	 *             if an error occurs while obtaining AssemblyLine's log.
	 * @throws RemoteException
	 *             if a communication-related exception occurs.
	 */
	public String getALLog(String aALName, String aLogFileName) throws DIException, RemoteException;

	/**
	 * Retrieves the last chunk from a specified AssemblyLine's log file.
	 * 
	 * @param aALName
	 *            the name of the AssemblyLine.
	 * @param aLogFileName
	 *            the name of the log file; no file path should be specified -
	 *            just the file name.
	 * @param aKilobytes
	 *            specifies in kilobytes the size of the log's last chunk that
	 *            will be read.
	 * @return the last chunk of the specified AssemblyLine's log.
	 * @throws DIException
	 *             if an error occurs while obtaining AssemblyLine's log.
	 * @throws RemoteException
	 *             if a communication-related exception occurs.
	 */
	public String getALLogLastChunk(String aALName, String aLogFileName, int aKilobytes) throws DIException, RemoteException;

	/**
	 * Returns the Instance boot time.
	 * 
	 * @return a <code>java.util.Date</code> specifying the date and time the
	 *         instance was started.
	 * @throws DIException
	 *             if an error occurs while retrieving instance's boot time.
	 * @throws RemoteException
	 *             if a communication-related exception occurs.
	 */
	public Date getInstanceBootTime() throws DIException, RemoteException;

	/**
	 * Returns the Config Instance GUID. The GUID is a string value that is
	 * unique for each component ever created by a particular TDI Server.
	 * <p>
	 * <b>Example</b>
	 * </p>
	 * 
	 * <pre>
	 * var sessionFactory = java.rmi.Naming.lookup(&quot;rmi://127.0.0.1:1099/SessionFactory&quot;);
	 * var remoteSession = sessionFactory.createSession();
	 * var configInstances = remoteSession.getConfigInstances();
	 * if (configInstances != null){
	 *   for (ci in configInstances){
	 *     task.logmsg(&quot;CI path: &quot; + ci.getGlobalUniqueID());
	 *   }
	 * } else {
	 *   task.logmsg(&quot;no available config instances&quot;);
	 * }
	 * </pre>
	 * 
	 * @return The Config Instance GUID value.
	 * @throws DIException
	 *             if an error occurs while retrieving Config Instance GUID
	 *             value.
	 * @throws RemoteException
	 *             if a communication-related exception occurs.
	 */
	public String getGlobalUniqueID() throws DIException, RemoteException;

	// Connector Pool calls

	/**
	 * Returns the names of all Connector Pools in the Config Instance.
	 * 
	 * @return String array containing the Connector Pool names.
	 * @throws DIException
	 *             if an error occurs while retrieving Connector Pool names.
	 * @throws RemoteException
	 *             if a communication-related exception occurs.
	 */
	public String[] getConnectorPoolNames() throws DIException, RemoteException;

	/**
	 * Returns the size of the specified Connector Pool.
	 * 
	 * @param aConnectorPoolName
	 *            the name of the Connector Pool.
	 * @return The current size of the specified Connector Pool.
	 * @throws DIException
	 *             if an error occurs while retrieving the size of the specified
	 *             Connector Pool.
	 * @throws RemoteException
	 *             if a communication-related exception occurs.
	 */
	public int getConnectorPoolSize(String aConnectorPoolName) throws DIException, RemoteException;

	/**
	 * Returns the number of free Connectors in the specified Connector Pool.
	 * 
	 * @param aConnectorPoolName
	 *            the name of the Connector Pool.
	 * @return The number of free Connectors in the specified Connector Pool.
	 * @throws DIException
	 *             if an error occurs while retrieving the number of free
	 *             Connectors in the specified Connector Pool.
	 * @throws RemoteException
	 *             if a communication-related exception occurs.
	 */
	public int getConnectorPoolFreeNum(String aConnectorPoolName) throws DIException, RemoteException;

	/**
	 * Returns the Connector Pool configuration object.
	 * 
	 * @param aConnectorPoolName
	 *            the name of the Connector Pool.
	 * @return The configuration object for the specified Connector Pool.
	 * @throws DIException
	 *             if an error occurs while retrieving Connector Pool
	 *             configuration object.
	 * @throws RemoteException
	 *             if a communication-related exception occurs.
	 */
	public PoolDefConfig getConnectorPoolConfig(String aConnectorPoolName) throws DIException, RemoteException;

	/**
	 * Unused Connectors will be released so that the Pool is shrunk to its
	 * minimum size.
	 * 
	 * @param aConnectorPoolName
	 *            the name of the Connector Pool.
	 * @return The size of the Connector Pool after shrinking.
	 * @throws DIException
	 *             if an error occurs while shrinking the Connector Pool.
	 * @throws RemoteException
	 *             if a communication-related exception occurs.
	 */
	public int purgeConnectorPool(String aConnectorPoolName) throws DIException, RemoteException;

	/**
	 * Returns the TDIProperties object associated with the current
	 * configuration. The TDIProperties can then be used to obtain list of
	 * property stores, get/set/remove property values,etc.
	 * 
	 * @return TDIProperties object associated with the current configuration.
	 * @throws Exception
	 *             if an error occurs while retrieving TDIProperties object.
	 * @throws RemoteException
	 *             if a communication-related exception occurs.
	 */
	public TDIProperties getTDIProperties() throws Exception, RemoteException;

	/**
	 * Retrieves absolut configuration path.
	 * <p>
	 * <b>Example</b>
	 * </p>
	 * 
	 * <pre>
	 * var sessionFactory = java.rmi.Naming.lookup(&quot;rmi://127.0.0.1:1099/SessionFactory&quot;);
	 * var remoteSession = sessionFactory.createSession();
	 * var configInstances = remoteSession.getConfigInstances();
	 * if (configInstances != null){
	 *   for (ci in configInstances){
	 *     task.logmsg(&quot;CI path: &quot; + ci.getConfigPath());
	 *   }
	 * } else {
	 *   task.logmsg(&quot;no available config instances&quot;);
	 * }
	 * </pre>
	 * 
	 * @return The absolute path of the configuration file.
	 * @throws RemoteException
	 *             if a communication-related exception occurs.
	 */
	public String getConfigPath() throws RemoteException;

	/**
	 * Retrieves a reference to the Configuration file used to load this
	 * instance from. This string is in the form of what
	 * {@link Session#listAllConfigurations()} would return. It could be either
	 * a solution name or a path relative to the base config folder.
	 * 
	 * @return the configuration file reference or null if this is a temporary
	 *         instance from an in-memory configuration.
	 * @throws DIException
	 *             if an error occurs while retrieving configuration file
	 *             reference
	 * @throws RemoteException
	 *             if a communication-related exception occurs.
	 * @since 7.2
	 */
	public String getConfigurationFile() throws DIException, RemoteException;

	/**
	 * Register listener for messages logged by this configuration instance. You
	 * must be admin to execute this method.
	 * 
	 * @param listener
	 *            Listener for logged messages.
	 * @throws DIException
	 *             If an error occurs during registration, e.g. the listener is
	 *             null.
	 * @throws RemoteException
	 *             If a communication-related exception occurs.
	 * @see #removeLogListener(LogListener)
	 * @since 7.0
	 */
	public void addLogListener(LogListener listener) throws DIException, RemoteException;

	/**
	 * <p>
	 * Unregister listener for messages logged by this configuration instance.
	 * You must be admin to execute this method.
	 * </p>
	 * <p>
	 * Listeners are associated with the API object, not with the AssemblyLine
	 * in the Server, so you can remove only listeners added with the
	 * {@link #addLogListener(LogListener)} method on the same object.
	 * </p>
	 * <p>
	 * Do not invoke this method from within the listener while the listener is
	 * being notified because a deadlock may occur.
	 * </p>
	 * 
	 * @param listener
	 *            Registered listener.
	 * @throws DIException
	 *             If an error occurs while unregistering the listener, e.g. the
	 *             listener is null or is not registered.
	 * @throws RemoteException
	 *             If a communication-related exception occurs.
	 * @see #addLogListener(LogListener)
	 * @since 7.0
	 */
	public void removeLogListener(LogListener listener) throws DIException, RemoteException;

    /**
     * Returns information about the named Scheduler.
     * If the Scheduler is not found, returns null.
     * @see Scheduler.getInfo();
     * @param name - Name of Scheduler
     * @since 7.1.1
     */
    public Map<String, Object> getSchedulerInfo(String name) throws RemoteException;
    
    /**
     * Returns information about all Schedulers in this RS.
     * If no Schedulers are found, returns an empty List.
     * @see Scheduler.getInfo();
     * @since 7.1.1
     */
    public List<Map<String, Object>> getSchedulersInfo() throws RemoteException;
}
