###################################################################
# Action Manager Configuration File
###################################################################

## Location of the database from where AM will work as reference. (networked mode)
## This should be the same as the one where AMC has stored its AM details
## It is best to give the complete path of AMC's database. For example:
## jdbc:derby://localhost:1528/C:/Program Files/IBM/AppSrv/profiles/amcprofile/tdiamcdb;create=false
##

com.ibm.di.amc.am.jdbc.database=jdbc:derby://localhost:1528/tdiamcdb;create=false

com.ibm.di.amc.am.jdbc.driver=org.apache.derby.jdbc.ClientDriver
com.ibm.di.amc.am.jdbc.urlprefix=jdbc:derby:
com.ibm.di.amc.am.jdbc.user=APP
{protect}-com.ibm.di.amc.am.jdbc.password=APP
com.ibm.di.amc.am.jdbc.start.mode=automatic
com.ibm.di.amc.am.jdbc.sysibm=true
com.ibm.di.amc.am.jdbc.networkserver.host=localhost
com.ibm.di.amc.am.jdbc.networkserver.port=1528

# Specifies the database being used by the Action Manager
am.db.type=derby

# Action Manager SSL properties
javax.net.ssl.trustStore=../../serverapi/testadmin.jks
{protect}-javax.net.ssl.trustStorePassword=administrator
javax.net.ssl.trustStoreType=jks
javax.net.ssl.keyStore=../../serverapi/testadmin.jks
{protect}-javax.net.ssl.keyStorePassword=administrator
javax.net.ssl.keyStoreType=jks

# Action Manager encryption properties
com.ibm.di.amc.am.encryption.keystore=ActionManager/key.jks
com.ibm.di.amc.am.encryption.key.alias=am_key
com.ibm.di.amc.am.encryption.keystoretype=jks
com.ibm.di.amc.am.encryption.transformation=RSA
com.ibm.di.amc.am.stash.file=ActionManager/idiam.sth

#Action manager RMI port
am.api.port=13104

#################################################
# ACTION MANAGER THREAD INTERVAL TIME (seconds)
#################################################

# Controls the sleep time for server API failure listerer threads
com.ibm.di.amc.am.serverapi.fail.interval.time=120

# Controls the sleep time for query AL result threads
com.ibm.di.amc.am.queryAL.interval.time=120

# Controls the sleep time for query property value threads
com.ibm.di.amc.am.queryProperty.interval.time=600

# Controls the frequeny of triggering the Health ALs
com.ibm.di.amc.am.healthAL.interval.time=5

# Controls the frequency of triggering AM update thread
com.ibm.di.amc.am.statusUpdate.interval.time=60

# SMTP server properties
smtp.host=
smtp.port=
smtp.user=
smtp.password=
