PAR_DESC = DSMLv2 Parser
BA_LBL = Binary Attributes
BA_DESC = User defined binary attributes delimited by ",".\nThese attributes will be Base64 decoded when parsing DSML messages.
MODE_LBL = Mode
MODE_DESC = Specify Server or Client mode. In Server mode requests are read and responses are written.\nIn Client mode requests are written and responses are read.
ONERR_LBL = On Error
ONERR_DESC = Sets the value of the "onError" DSML attribute for Batch Requests.
PROC_LBL = Processing
PROC_DESC = Sets the value of the "processing" DSML attribute for Batch Requests.
RESPORD_LBL = Response Order
RESPORD_DESC = Sets the value of the "responseOrder" DSML attribute for Batch Requests.
INDOUT_LBL = Indent Output
INDOUT_DESC = Indents XML on output
OMITXML_LBL = Omit XML Declaration
OMITXML_DESC = Omit XML declaration header in output stream
SOAP_LBL = Soap Binding
SOAP_DESC = This parameter enables parser compatibility with SOAP protocol. \nWhen "soapbinding" is turned on - parser process the XML like SOAP message. \nWhen "soapbinding" is turned off, the XML will be processed like ordinary DSML message.
PAR_TITLE = DSMLv2 Parser
set_label = Character Encoding
set_desc = Character encoding to use when reading or writing
Localized.Client = Client
Localized.Server = Server
Localized.exit = exit
Localized.resume = resume
Localized.sequential = sequential
Localized.parallel = parallel
Localized.unordered = unordered
Advanced = Advanced
