/*
 * Copyright contributors to the SyncWeave project
 *
 * SPDX-License-Identifier: Apache-2.0
 */
package com.ibm.di.api.local;

import java.util.Date;
import java.util.List;
import java.util.Map;

import com.ibm.di.api.DIException;
import com.ibm.di.config.interfaces.ExternalPropertiesConfig;
import com.ibm.di.config.interfaces.MetamergeConfig;
import com.ibm.di.config.interfaces.PoolDefConfig;
import com.ibm.di.config.interfaces.SchemaConfig;
import com.ibm.di.entry.Entry;
import com.ibm.di.server.TaskCallBlock;

/**
 * 
 * Represents a configuration instance and provides various methods for
 * manipulating the configuration.
 * 
 */
public interface ConfigInstance {

	/**
	 * Returns the configuration ID generated by the server.
	 * <p>
	 * <b>Example:</b>
	 * 
	 * <pre>
	 * 	for( ci in session.getConfigInstances()){
	 * 	task.logmsg(&quot;Name: &quot; + ci.getConfigId());
	 * 	}
	 * //Sample output: Name: C__Documents and Settings_username_My Documents_TDI_rs.xml
	 * </pre>
	 * 
	 * @return String object representing the configuration ID.
	 * @throws DIException
	 *             if an error occurs while getting the configuration ID.
	 */
	public String getConfigId() throws DIException;

	// access to the Config Instance configuration

	/**
	 * Returns configuration instance representing this configuration.
	 * 
	 * @return MetamergeConfig object representing this configuration.
	 * @throws DIException
	 *             if an error occurs while getting the configuration.
	 */
	public MetamergeConfig getConfiguration() throws DIException;

	/**
	 * Sets given configuration to this configuration.
	 * 
	 * @param aConfiguration
	 *            The new configuration.
	 * @throws DIException
	 *             if an error occurs while setting the configuration.
	 */
	public void setConfiguration(MetamergeConfig aConfiguration) throws DIException;

	/**
	 * @deprecated Not supported.
	 */
	@Deprecated
	public void saveConfiguration() throws DIException;

	/**
	 * @deprecated Not supported.
	 */
	@Deprecated
	public void saveConfiguration(boolean aEncrypt) throws DIException;

	// external properties access

	/**
	 * Returns the external properties of the configuration.
	 * 
	 * @return ExternalPropertiesConfig object representing the configuration's
	 *         external properties.
	 * @throws DIException
	 *             if an error occurs while getting the external properties.
	 * @deprecated use {@link #getTDIProperties()} instead
	 */
	@Deprecated
	public ExternalPropertiesConfig getExternalProperties() throws DIException;

	/**
	 * Returns the ExternalPropertiesConfig object for the named external
	 * properties object.
	 * 
	 * @param aKey
	 *            The external property object name.
	 * @return ExternalPropertiesConfig object representing the configuration's
	 *         external properties specified by the external property object
	 *         name.
	 * @throws DIException
	 *             if an error occurs while getting the external properties.
	 * @deprecated use {@link #getTDIProperties()} instead
	 */
	@Deprecated
	public ExternalPropertiesConfig getExternalProperties(String aKey) throws DIException;

	/**
	 * Returns the external properties object names.
	 * 
	 * @return String array each value representing one external property object
	 *         name.
	 * @throws DIException
	 *             if an error occurs while getting the external properties
	 *             names.
	 * @deprecated use {@link #getTDIProperties()} instead
	 */
	@Deprecated
	public String[] getExternalPropertiesKeys() throws DIException;

	/**
	 * @deprecated Not supported.
	 */
	@Deprecated
	public void setExternalProperties(ExternalPropertiesConfig aExPropConfig) throws DIException;

	/**
	 * @deprecated Not supported.
	 */
	@Deprecated
	public void setExternalProperties(String aKey, ExternalPropertiesConfig aExPropConfig) throws DIException;

	/**
	 * @deprecated Not supported.
	 */
	@Deprecated
	public void saveExternalProperties() throws DIException;

	// Querying for available AssemblyLines

	/**
	 * @deprecated Use {@link #getAssemblyLineNames()}.
	 */
	@Deprecated
	public String[] getAssemblyLinesNames() throws DIException;

	/**
	 * Returns the AssemblyLines' names.
	 * <p>
	 * <b>Example:</b>
	 * 
	 * <pre>
	 * 	var ci = session.getConfigInstance(&quot;C__Documents and Settings_username_My Documents_TDI_rs.xml&quot;);
	 * 
	 * 	for(al in ci.getAssemblyLineNames()){
	 * 	task.logmsg(&quot;Al name: &quot; + al);
	 * 	}
	 * 
	 *  //Sample output:Al name: csv2xml
	 * 		Al name: test
	 * </pre>
	 * 
	 * @return String array each value representing AssemblyLine name.
	 * @throws DIException
	 *             if an error occurs while getting the AssemblyLines' names.
	 */
	public String[] getAssemblyLineNames() throws DIException;

	/**
	 * Returns a list of integers uniquely identify all the AssemblyLines within
	 * the ConfigInstance.
	 * <p>
	 * <b>Example:</b>
	 * 
	 * <pre>
	 * 	var ci = session.getConfigInstance(&quot;C__Documents and Settings_username_My Documents_TDI_rs.xml&quot;);
	 * 
	 * 	for(al in ci.getAssemblyLineUniqueCodes()){
	 * 	task.logmsg(&quot;Al id: &quot; + al);
	 * 	}
	 * 
	 *  //Sample output:Al name: csv2xml
	 * 		Al id: 2312
	 * </pre>
	 * 
	 * @return integer list each value representing AssemblyLine id.
	 * @throws DIException
	 *             if an error occurs while getting the AssemblyLines' IDs.
	 */
	public int[] getAssemblyLineUniqueCodes() throws DIException;

	/**
	 * Searches the list of AssemblyLines for the specified unique code (one
	 * returned by the {@link #getAssemblyLineUniqueCodes()} method)
	 * 
	 * @param alId
	 *            the AssemblyLine id uniquely identifying the AssemblyLine
	 *            instance in the scope of the ConfigInstance.
	 * 
	 * @return the AssemblyLine found or null
	 * @throws DIException
	 *             if an error occurs while getting the AssemblyLine.
	 */
	public AssemblyLine getAssemblyLineByUniqueCode(int alId) throws DIException;

	/**
	 * Returns the AssemblyLine's input parameters.
	 * 
	 * @param aAssemblyLineName
	 *            the name of the AssemblyLine.
	 * @return SchemaConfig representing the schema input of the AssemblyLine.
	 * @throws DIException
	 *             if an error occurs while getting the AssemblyLine's input
	 *             parameters.
	 */
	public SchemaConfig getAssemblyLineInputParameters(String aAssemblyLineName) throws DIException;

	/**
	 * Returns the AssemblyLine's output parameters.
	 * 
	 * @param aAssemblyLineName
	 *            the name of the AssemblyLine.
	 * @return SchemaConfig representing the schema output of the AssemblyLine.
	 * @throws DIException
	 *             if an error occurs while getting the AssemblyLine's output
	 *             parameters.
	 */
	public SchemaConfig getAssemblyLineOutputParameters(String aAssemblyLineName) throws DIException;

	// access to running processes within this instance

	/**
	 * Returns currently started AssemblyLines of the configuration instance.
	 * <p>
	 * <b>Example:</b>
	 * 
	 * <pre>
	 * 	var ci = session.getConfigInstance(&quot;C__Documents and Settings_username_My Documents_TDI_rs.xml&quot;);
	 * 
	 * 	for(al in ci.getAssemblyLines()){
	 * 	task.logmsg(&quot;Al running: &quot; + al.getName());
	 * 	}
	 * 
	 *  //Sample output: Al running: AssemblyLines/test
	 * 
	 * </pre>
	 * 
	 * @return AssemblyLine array object each value represents currently started
	 *         AssemblyLine.
	 * @throws DIException
	 *             if an error occurs while getting the AssemblyLines.
	 */
	public AssemblyLine[] getAssemblyLines() throws DIException;

	// AssemblyLine operations

	// simple starting of AssemblyLines

	/**
	 * Starts the specified AssemblyLine asynchronously.
	 * <p>
	 * <b>Example:</b>
	 * 
	 * <pre>
	 * var ci = session.getConfigInstance(&quot;C__Documents and Settings_username_My Documents_TDI_rs.xml&quot;);
	 * 
	 * var al = ci.startAssemblyLine(&quot;csv2xml&quot;);//assembly line is started
	 * //do something with al
	 * </pre>
	 * 
	 * @param aAssemblyLineName
	 *            The name of the AssemblyLine.
	 * @return the AssemblyLine object.
	 * @throws DIException
	 *             if an error occurs when starting the AssemblyLine.
	 */
	public AssemblyLine startAssemblyLine(String aAssemblyLineName) throws DIException;

	/**
	 * Starts the specified AssemblyLine.
	 * <p>
	 * <b>Example:</b>
	 * 
	 * <pre>
	 * var ci = session.getConfigInstance(&quot;C__Documents and Settings_username_My Documents_TDI_rs.xml&quot;);
	 * 
	 * var al = ci.startAssemblyLine(&quot;csv2xml&quot;, false);//assembly line is started in new thread
	 * //do something with al
	 * </pre>
	 * 
	 * @param aAssemblyLineName
	 *            The name of the AssemblyLine.
	 * @param aSync
	 *            when <code>true</code> the AssemblyLine is started
	 *            synchronously, when <code>false</code> the AssemblyLine is
	 *            started asynchronously.
	 * @return the AssemblyLine object.
	 * @throws DIException
	 *             if an error occurs when starting the AssemblyLine.
	 */
	public AssemblyLine startAssemblyLine(String aAssemblyLineName, boolean aSync) throws DIException;

	// start the AssemblyLine with input data

	/**
	 * Starts the specified AssemblyLine with the given input data
	 * asynchronously.
	 * <p>
	 * <b>Example:</b>
	 * 
	 * <pre>
	 * var ci = session.getConfigInstance(&quot;C__Documents and Settings_username_My Documents_TDI_rs.xml&quot;);
	 * 
	 * var al = ci.startAssemblyLine(&quot;csv2xml&quot;, work);
	 * 
	 * //assembly line &quot;csv2xml&quot; is started with the current entry of the current running assembly line
	 * //do something with al
	 * </pre>
	 * 
	 * @param aAssemblyLineName
	 *            The name of the AssemblyLine.
	 * @param aInputData
	 *            Initial Work Entry to run the AssemblyLine with.
	 * @return the AssemblyLine object.
	 * @throws DIException
	 *             if an error occurs when starting the AssemblyLine.
	 */
	public AssemblyLine startAssemblyLine(String aAssemblyLineName, Entry aInputData) throws DIException;

	/**
	 * Starts the specified AssemblyLine with the given input data.
	 * <p>
	 * <b>Example:</b>
	 * 
	 * <pre>
	 * var ci = session.getConfigInstance(&quot;C__Documents and Settings_username_My Documents_TDI_rs.xml&quot;);
	 * 
	 * var al = ci.startAssemblyLine(&quot;csv2xml&quot;, work, false);
	 * 
	 * //assembly line &quot;csv2xml&quot; is started with the current entry of the current running assembly line
	 * //do something with al
	 * </pre>
	 * 
	 * @param aAssemblyLineName
	 *            The name of the AssemblyLine.
	 * @param aInputData
	 *            Initial Work Entry to run the AssemblyLine with.
	 * @param aSync
	 *            when <code>true</code> the AssemblyLine is started
	 *            synchronously, when <code>false</code> the AssemblyLine is
	 *            started asynchronously.
	 * @return the AssemblyLine object.
	 * @throws DIException
	 *             if an error occurs when starting the AssemblyLine.
	 */
	public AssemblyLine startAssemblyLine(String aAssemblyLineName, Entry aInputData, boolean aSync) throws DIException;

	// start the AssemblyLine with input data and get results through callbacks

	/**
	 * Starts asynchronously the specified AssemblyLine with the given input
	 * data and results listener.
	 * 
	 * @param aAssemblyLineName
	 *            The name of the AssemblyLine.
	 * @param aInputData
	 *            Initial Work Entry to run the AssemblyLine with.
	 * @param aListener
	 *            A listener for Entries produced by the AssemblyLine.
	 * @param aGetLogs
	 *            when <code>true</code> the AssemblyLineListener is delivered
	 *            log messages, when <code>false</code> log messages are not
	 *            delivered.
	 * @return the AssemblyLine object.
	 * @throws DIException
	 *             if an error occurs when starting the AssemblyLine.
	 */
	public AssemblyLine startAssemblyLine(String aAssemblyLineName, Entry aInputData, AssemblyLineListener aListener,
			boolean aGetLogs) throws DIException;

	/**
	 * Starts the specified AssemblyLine with the given input data and results
	 * listener.
	 * 
	 * @param aAssemblyLineName
	 *            The name of the AssemblyLine.
	 * @param aInputData
	 *            Initial Work Entry to run the AssemblyLine with.
	 * @param aListener
	 *            A listener for Entries produced by the AssemblyLine.
	 * @param aGetLogs
	 *            when <code>true</code> the AssemblyLineListener delivers log
	 *            messages, when <code>false</code> log messages are not
	 *            delivered.
	 * @param aSync
	 *            when <code>true</code> the AssemblyLine is started
	 *            synchronously, when <code>false</code> the AssemblyLine is
	 *            started asynchronously.
	 * @return the AssemblyLine object.
	 * @throws DIException
	 *             if an error occurs when starting the AssemblyLine.
	 */
	public AssemblyLine startAssemblyLine(String aAssemblyLineName, Entry aInputData, AssemblyLineListener aListener,
			boolean aGetLogs, boolean aSync) throws DIException;

	/**
	 * Starts the specified AssemblyLine with the given input data and results
	 * listener.
	 * 
	 * @param aAssemblyLineName
	 *            The name of the AssemblyLine.
	 * @param aInputData
	 *            Initial Work Entry to run the AssemblyLine with.
	 * @param aListener
	 *            A listener for Entries produced by the AssemblyLine.
	 * @param aGetLogs
	 *            when <code>true</code> the AssemblyLineListener delivers log
	 *            messages, when <code>false</code> log messages are not
	 *            delivered.
	 * @param aSync
	 *            when <code>true</code> the AssemblyLine is started
	 *            synchronously, when <code>false</code> the AssemblyLine is
	 *            started asynchronously.
	 * @param aGetEntryOnEachCycle
	 *            when <code>true</code> the AssemblyLineListener delivers the
	 *            current entry on each AssemblyLine cycle, when
	 *            <code>false</code> the entries are not delivered.
	 * @return the AssemblyLine object.
	 * @throws DIException
	 *             if an error occurs when starting the AssemblyLine.
	 */
	public AssemblyLine startAssemblyLine(String aAssemblyLineName, Entry aInputData, AssemblyLineListener aListener,
			boolean aGetLogs, boolean aSync, boolean aGetEntryOnEachCycle) throws DIException;

	// start the AssemblyLine in manual mode

	/**
	 * Starts the specified AssemblyLine with the given input data in manual
	 * mode.
	 * 
	 * @param aAssemblyLineName
	 *            The name of the AssemblyLine.
	 * @param aInputData
	 *            Initial Work Entry to run the AssemblyLine with.
	 * @return the AssemblyLineHandler object for AssemblyLine manipulation in
	 *         manual mode.
	 * @throws DIException
	 *             if an error occurs when starting the AssemblyLine.
	 */
	public AssemblyLineHandler startAssemblyLineManual(String aAssemblyLineName, Entry aInputData) throws DIException;

	// the following two methods are for advanced use

	/**
	 * Starts asynchronously the specified AssemblyLine with the given
	 * TaskCallBlock.
	 * 
	 * @param aAssemblyLineName
	 *            The name of the AssemblyLine.
	 * @param aTcb
	 *            The TaskCallBlock object to start the AL with.
	 * @return the AssemblyLine object.
	 * @throws DIException
	 *             if an error occurs when starting the AssemblyLine.
	 */
	public AssemblyLine startAssemblyLine(String aAssemblyLineName, TaskCallBlock aTcb) throws DIException;

	/**
	 * Starts the specified AssemblyLine with the given TaskCallBlock.
	 * 
	 * @param aAssemblyLineName
	 *            The name of the AssemblyLine.
	 * @param aTcb
	 *            The TaskCallBlock object to start the AL with.
	 * @param aSync
	 *            when <code>true</code> the AssemblyLine is started
	 *            synchronously, when <code>false</code> the AssemblyLine is
	 *            started asynchronously.
	 * @return the AssemblyLine object.
	 * @throws DIException
	 *             if an error occurs when starting the AssemblyLine.
	 */
	public AssemblyLine startAssemblyLine(String aAssemblyLineName, TaskCallBlock aTcb, boolean aSync) throws DIException;
	
	//Starting Sequences
	/**
	 * Starts the specified Sequence.
	 * <p>
	 * <b>Example:</b>
	 * 
	 * <pre>
	 * var ci = session.getConfigInstance(&quot;C__Documents and Settings_username_My Documents_TDI_rs.xml&quot;);
	 * 
	 * var seq = ci.startSequence(&quot;csv2xml&quot;);//Sequence is started
	 * </pre>
	 * 
	 * @param name
	 *            The name of the Sequence.
	 * @return the Sequence object.
	 * @throws DIException
	 *             if an error occurs when starting the Sequence.
	 * @since 7.2
	 */
	public Sequence startSequence(String name) throws DIException;

	/**
	 * Starts the specified Sequence specifying a TaskCallBlock, synchronous or asynchronous.
	 * <p>
	 * <b>Example:</b>
	 * 
	 * <pre>
	 * var ci = session.getConfigInstance(&quot;C__Documents and Settings_username_My Documents_TDI_rs.xml&quot;);
	 * 
	 * var seq = ci.startSequence(&quot;csv2xml&quot;, null, true);//Sequence is started in new thread, and has now run to completion
	 * //do something with seq
	 * </pre>
	 * 
	 * @param name
	 *            The name of the Sequence.
	 * @param tcb
	 *            The TaskCallBlock object to start the Sequence with. If null, ignored.
	 * @param sync
	 *            when <code>true</code> the Sequence is started
	 *            synchronously, when <code>false</code> the Sequence is
	 *            started asynchronously.
	 * @return the Sequence object.
	 * @throws DIException
	 *             if an error occurs when starting the Sequence.
	 * @since 7.2
	 */
	public Sequence startSequence(String name, TaskCallBlock tcb, boolean sync) throws DIException;

	/**
	 * Starts the specified Sequence with the given TaskCallBlock and a Listener
	 * 
	 * @param name
	 *            The name of the Sequence.
	 * @param tcb
	 *            The TaskCallBlock object to start the Sequence with.
	 * @param listener
	 *            A listener to know when the Sequence has stopped.
	 * @return the Sequence object.
	 * @throws DIException
	 *             if an error occurs when starting the Sequence.
	 * @since 7.2
	 */
	public Sequence startSequence(String name, TaskCallBlock tcb, AssemblyLineListener listener) throws DIException;

	
	// Config Instance operations

	/**
	 * Reloads the Config Instance with its current configuration.
	 * 
	 * @throws DIException
	 *             if an error occurs while reloading the server.
	 */
	public void reload() throws DIException;

	/**
	 * Stops the Config Instance.
	 * <p>
	 * <b>Example:</b>
	 * 
	 * <pre>
	 * var ci = session.getConfigInstance(&quot;C__Documents and Settings_username_My Documents_TDI_rs.xml&quot;);
	 * ci.stop();
	 * </pre>
	 * 
	 * @throws DIException
	 *             if an error occurs while stopping.
	 */
	public void stop() throws DIException;

	/**
	 * Stops the Config Instance and all AssemblyLines run by it, and waits a
	 * while for the stopping to finish.
	 * <p>
	 * <b>Example:</b>
	 * 
	 * <pre>
	 * var ci = session.getConfigInstance(&quot;myProject&quot;);
	 * ci.stop(false);
	 * </pre>
	 * 
	 * @param sync
	 *            If true, waiting will occur in new Threads.
	 * @throws DIException
	 *             if an error occurs while stopping.
	 * @since 7.1
	 */
	public void stop(boolean sync) throws DIException;

	// System Log convenience calls

	// AssemblyLines system log

	/**
	 * Returns the names of all available log files for a given AssemblyLine.
	 * 
	 * @param aALName
	 *            the name of the AssemblyLine.
	 * @return a </code>String</code> array, each of its elements specifying the
	 *         name of a log file.
	 * @throws DIException
	 *             if an error occurs while obtaining AssemblyLine's log file
	 *             names.
	 */
	public String[] getALLogFileNames(String aALName) throws DIException;

	/**
	 * Returns the name of the log file created on the last run of a given
	 * AssemblyLine.
	 * 
	 * @param aALName
	 *            the name of the AssemblyLine.
	 * @return the name of the log file created on the last AssemblyLine's run.
	 * @throws DIException
	 *             if an error occurs while obtaining the log file name.
	 */
	public String getALLastLogFileName(String aALName) throws DIException;

	/**
	 * Given an AssemblyLine name, and a log file name, retrieves the log of
	 * this AssemblyLine, stored in the specified file.
	 * 
	 * @param aALName
	 *            the name of the AssemblyLine.
	 * @param aLogFileName
	 *            the name of the log file; no file path should be specified -
	 *            just the file name.
	 * @return the specified log of the AssemblyLine.
	 * @throws DIException
	 *             if an error occurs while obtaining AssemblyLine's log.
	 */
	public String getALLog(String aALName, String aLogFileName) throws DIException;

	/**
	 * Retrieves the last chunk from a specified AssemblyLine's log file.
	 * 
	 * @param aALName
	 *            the name of the AssemblyLine.
	 * @param aLogFileName
	 *            the name of the log file; no file path should be specified -
	 *            just the file name.
	 * @param aKilobytes
	 *            specifies in kilobytes the size of the log's last chunk that
	 *            will be read.
	 * @return the last chunk of the specified AssemblyLine's log.
	 * @throws DIException
	 *             if an error occurs while obtaining AssemblyLine's log.
	 */
	public String getALLogLastChunk(String aALName, String aLogFileName, int aKilobytes) throws DIException;

	/**
	 * Returns the Instance boot time.
	 * 
	 * @return a <code>java.util.Date</code> specifying the date and time the
	 *         instance was started.
	 * @throws DIException
	 *             if an error occurs while retrieving instance's boot time.
	 */
	public Date getInstanceBootTime() throws DIException;

	/**
	 * Returns the Config Instance GUID. The GUID is a string value that is
	 * unique for each component ever created by a particular TDI Server.
	 * <p>
	 * <b>Example:</b>
	 * 
	 * <pre>
	 * var ci = session.getConfigInstance(&quot;C__Documents and Settings_username_My Documents_TDI_rs.xml&quot;);
	 * task.logmsg(&quot;Config ID: &quot; + ci.getGlobalUniqueID());
	 * 
	 * //Sample output: Config ID: 19245595421206360821315
	 * </pre>
	 * 
	 * @return The Config Instance GUID value.
	 * @throws DIException
	 *             if an error occurs while retrieving the Config Instance GUID
	 *             value.
	 */
	public String getGlobalUniqueID() throws DIException;

	// Connector Pool calls

	/**
	 * Returns the names of all Connector Pools in the Config Instance.
	 * 
	 * @return String array containing the Connector Pool names.
	 * @throws DIException
	 *             if an error occurs while retrieving the names of all
	 *             Connector Pools.
	 */
	public String[] getConnectorPoolNames() throws DIException;

	/**
	 * Returns the size of the specified Connector Pool.
	 * 
	 * @param aConnectorPoolName
	 *            the name of the Connector Pool.
	 * @return The current size of the specified Connector Pool.
	 * @throws DIException
	 *             if an error occurs while retrieving the size of the specified
	 *             Connector Pool.
	 */
	public int getConnectorPoolSize(String aConnectorPoolName) throws DIException;

	/**
	 * Returns the number of free Connectors in the specified Connector Pool.
	 * 
	 * @param aConnectorPoolName
	 *            the name of the Connector Pool.
	 * @return The number of free Connectors in the specified Connector Pool.
	 * @throws DIException
	 *             if an error occurs while retrieving the number of free
	 *             Connectors in the specified Connector Pool.
	 */
	public int getConnectorPoolFreeNum(String aConnectorPoolName) throws DIException;

	/**
	 * Returns the Connector Pool configuration object.
	 * 
	 * @param aConnectorPoolName
	 *            the name of the Connector Pool.
	 * @return The configuration object for the specified Connector Pool.
	 * @throws DIException
	 *             if an error occurs while retrieving the Connector Pool
	 *             configuration object.
	 */
	public PoolDefConfig getConnectorPoolConfig(String aConnectorPoolName) throws DIException;

	/**
	 * Unused Connectors will be released so that the Pool is shrunk to its
	 * minimum size.
	 * 
	 * @param aConnectorPoolName
	 *            the name of the Connector Pool.
	 * @return The size of the Connector Pool after shrinking.
	 * @throws DIException
	 *             if an error occurs while shrinking the Connector Pool.
	 */
	public int purgeConnectorPool(String aConnectorPoolName) throws DIException;

	/**
	 * Used to obtain a reference to TDIProperties for managing properties /
	 * property stores.
	 * 
	 * @return A reference to the TDIProperties interface.
	 * 
	 * @throws Exception
	 *             if an error occurs while obtaining a reference to
	 *             TDIProperties.
	 */
	public TDIProperties getTDIProperties() throws Exception;

	/**
	 * Retrieves the absolute path of the configuration.
	 * <p>
	 * <b>Example:</b>
	 * 
	 * <pre>
	 * var ci = session.getConfigInstance(&quot;C__Documents and Settings_Username_My Documents_TDI_rs.xml&quot;);
	 * 
	 * task.logmsg(&quot;CI path: &quot; + ci.getConfigPath());
	 * //Sample output: CI path: &quot;C:\Documents and Settings\Username\My Documents\TDI&quot;
	 * 
	 * </pre>
	 * 
	 * @return the absolute path of the configuration file.
	 */
	public String getConfigPath();

	/**
	 * Retrieves a reference to the Configuration file used to load this
	 * instance from. This string is in the form of what
	 * {@link Session#listAllConfigurations()} would return. It could be either
	 * a solution name or a path relative to the base config folder.
	 * 
	 * @return the configuration file reference or null if this is a temporary
	 *         instance from an in-memory configuration.
	 * @throws DIException
	 *             if an error occurs while retrieving configuration file
	 *             reference
	 * @since 7.2
	 */
	public String getConfigurationFile() throws DIException;

	/**
	 * Register listener for messages logged by this configuration instance. You
	 * must be admin to execute this method.
	 * 
	 * @param listener
	 *            Listener for logged messages.
	 * @throws DIException
	 *             If an error occurs during registration, e.g. the listener is
	 *             null.
	 * @see #removeLogListener(LogListener)
	 * @since 7.0
	 */
	public void addLogListener(LogListener listener) throws DIException;

	/**
	 * <p>
	 * Unregister listener for messages logged by this configuration instance.
	 * You must be admin to execute this method.
	 * </p>
	 * <p>
	 * Listeners are associated with the API object, not with the AssemblyLine
	 * in the Server, so you can remove only listeners added with the
	 * {@link #addLogListener(LogListener)} method on the same object.
	 * </p>
	 * <p>
	 * Do not invoke this method from within the listener while the listener is
	 * being notified because a deadlock may occur.
	 * </p>
	 * 
	 * @param listener
	 *            Registered listener.
	 * @throws DIException
	 *             If an error occurs while unregistering the listener, e.g. the
	 *             listener is null or is not registered.
	 * @see #addLogListener(LogListener)
	 * @since 7.0
	 */
	public void removeLogListener(LogListener listener) throws DIException;
	
    /**
     * Returns information about the named Scheduler.
     * If the Scheduler is not found, returns null.
     * @see Scheduler.getInfo();
     * @param name - Name of Scheduler
     * @since 7.1.1
     */
    public Map<String, Object> getSchedulerInfo(String name);
    
    /**
     * Returns information about all Schedulers in this RS.
     * If no Schedulers are found, returns an empty List.
     * @see Scheduler.getInfo();
     * @since 7.1.1
     */
    public List<Map<String, Object>> getSchedulersInfo();
}
