/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ibm_di_fc_zOSTSOCommandLine */

#ifndef _Included_com_ibm_di_fc_zOSTSOCommandLine
#define _Included_com_ibm_di_fc_zOSTSOCommandLine
#ifdef __cplusplus
extern "C" {
#endif
#undef com_ibm_di_fc_zOSTSOCommandLine_CONSOLE_LOG
#define com_ibm_di_fc_zOSTSOCommandLine_CONSOLE_LOG 0L
#undef com_ibm_di_fc_zOSTSOCommandLine_PARM_PARTNERTP_ID
#define com_ibm_di_fc_zOSTSOCommandLine_PARM_PARTNERTP_ID 0L
#undef com_ibm_di_fc_zOSTSOCommandLine_PARM_DEST_LU_NAME_ID
#define com_ibm_di_fc_zOSTSOCommandLine_PARM_DEST_LU_NAME_ID 1L
#undef com_ibm_di_fc_zOSTSOCommandLine_PARM_SRC_LU_NAME_ID
#define com_ibm_di_fc_zOSTSOCommandLine_PARM_SRC_LU_NAME_ID 2L
#undef com_ibm_di_fc_zOSTSOCommandLine_PARM_MODE_NAME_ID
#define com_ibm_di_fc_zOSTSOCommandLine_PARM_MODE_NAME_ID 3L
#undef com_ibm_di_fc_zOSTSOCommandLine_PARM_USER_ID_ID
#define com_ibm_di_fc_zOSTSOCommandLine_PARM_USER_ID_ID 4L
#undef com_ibm_di_fc_zOSTSOCommandLine_PARM_USER_PSW_ID
#define com_ibm_di_fc_zOSTSOCommandLine_PARM_USER_PSW_ID 5L
/* Inaccessible static: PARAMS_LEN */
/* Inaccessible static: isLibLoaded */
/*
 * Class:     com_ibm_di_fc_zOSTSOCommandLine
 * Method:    initConversation
 * Signature: ([B[Ljava/lang/String;[B)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_di_fc_zOSTSOCommandLine_initConversation
  (JNIEnv *, jobject, jbyteArray, jobjectArray, jbyteArray);

/*
 * Class:     com_ibm_di_fc_zOSTSOCommandLine
 * Method:    executeCommand
 * Signature: ([BLjava/lang/String;Ljava/io/ByteArrayOutputStream;)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_di_fc_zOSTSOCommandLine_executeCommand
  (JNIEnv *, jobject, jbyteArray, jstring, jobject);

/*
 * Class:     com_ibm_di_fc_zOSTSOCommandLine
 * Method:    deallocConversation
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_di_fc_zOSTSOCommandLine_deallocConversation
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_ibm_di_fc_zOSTSOCommandLine
 * Method:    getCMOK
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ibm_di_fc_zOSTSOCommandLine_getCMOK
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
