## This file determines the set of events that will be
## received by the Server Notifications Connector
## Note that some events include other. This means that
## if you have set event.al.all=true then you will receice
## AL start and stop events (even if you have set event.al.start = false)



## Determine if all Server API events will be received.
## Note that when the value is set to true all other property values but event.customNotifications
## are considered true, too.
event.all=true

## Determine if all Config Instance events are receiced
event.ci.all=false

## Determine if Config Instance start events are received
event.ci.start=false

## Determine if Config Instance stop events are received
event.ci.stop=false

## Determine if Config Instance File Updated events are received
event.ci.fileUpdated=false

## Determine if all AssemblyLine events are received
event.al.all=false

## Determine if AssemblyLine start events are received
event.al.start=false

## Determine if AssemblyLine stop events are received
event.al.stop=false

##Determine if Server Shutdown events are received
event.server.stop=false

##Determine what Custom Notification events are received
##This property is used only if event.hasCustomNotofications is enabled
##Note that all custom notifications are prefixed with "user."
event.customNotifications=

##Determine if Custom Notification events are received
event.hasCustomNotifications=false
