CCMDB_CONNECTOR_TITLE = CCMDB Connector
CONN_DESC = COnnection description .
#
CCMDB_CONN_CI = Configuration Item
CCMDB_CONN_RELATIONSHIP = Relationship
CCMDB_CONN_JDBCURL_DESC = The JDBC URL used for connecting to the CCMDB database.
CCMDB_CONN_JDBCURL_LABEL = JDBC URL
CCMDB_CONN_JDBCDRIVER_DESC = The database driver used for connecting to the IT registry database. 
CCMDB_CONN_JDBCDRIVER_LABEL = JDBC Driver
CCMDB_CONN_DBUSERNAME_DESC = The username used when connecting to the IT registry database.
CCMDB_CONN_DBUSERNAME_LABEL = Username
CCMDB_CONN_DBPASSWORD_DESC = The password used when connecting to the IT registry database.
CCMDB_CONN_DBPASSWORD_LABEL = Password
CCMDB_CONN_CLASS_LABEL = Classification
CCMDB_CONN_CLASS_DESC = Classification name  
CCMDB_CONN_QUERYDB_SCRIPT_LABEL = Test Connection
CCMDB_CONN_QUERYDB_SCRIPT_HELP = Test whether the IT registry database is accessible using the supplied parameters.
CCMDB_CONN_ARTIFACTTYPE_DESC = Determines the type of artifact that this Connector will work with.
CCMDB_CONN_ARTIFACTTYPE_LABEL = Artifact Type
CCMDB_CONN_CLASSTYPE_DESC = The type of Configuration Item or Relationship that will be processed.
CCMDB_CONN_CLASSTYPE_LABEL = Class Type
CCMDB_CONN_CLASSTYPE_SCRIPT_LABEL = Select...
CCMDB_CONN_CLASSTYPE_SCRIPT_HELP = Choose one of the supported classes.
CCMDB_CONN_IDMLMODE_DESC = If checked the Connector will only work with IdML compatible data.
CCMDB_CONN_IDMLMODE_LABEL = IdML Mode
#
CCMDB_CONN_RELSRC_DESC = Show source relations
CCMDB_CONN_RELSRC_LABEL = Source relations
CCMDB_CONN_RELTRG_DESC = Show target relations
CCMDB_CONN_RELTRG_LABEL = Target relations
#
Advanced = Advanced
