FC_TITLE = Wrap Soap Function Component
FUNCTION_DESC = This component is used to generate a complete SOAP message given the SOAP Body and optionally a SOAP Header
IXT_LBL = Input the SOAP Body and Header as
IXT_DESC = specifies the input type
RXT_LBL = Return the SOAP message as
RXT_DESC = specifies the return type
HABTP_LBL = Header and Body tags present
HABTP_DESC = If checked the input Header and Body must include the <Header> and <Body> tags as well as their corresponding closing tags.
SEA_LBL = Attributes to add to the SOAP Envelope
SEA_DESC = Specifies attributes to add to the SOAP Envelope
SEND_LBL = Namespace declarations to add to the SOAP Envelope
SEND_DESC = Specifies Namespace declarations to add to the SOAP Envelope
SBA_LBL = Attributes to add to the SOAP Body
SBA_DESC = Specifies attributes to add to the SOAP Body
SBND_LBL = Namespace declarations to add to the SOAP Body
SBND_DESC = Specifies Namespace declarations to add to the SOAP Body
SHA_LBL = Attributes to add to the SOAP Header
SHA_DESC = Specifies attributes to add to the SOAP Header
SHND_LBL = Namespace declarations to add to the SOAP Header
SHND_DESC = Specifies Namespace declarations to add to the SOAP Header
Localized.String = String
Localized.DOMElement = DOMElement
Advanced = Advanced
