CONN_DESC = A Server Connector for processing incoming TCP connections
TCP_PORT_DESC = TCP Port for incoming requests
TCP_PORT_LABEL = TCP Port
TCP_BACKLOG_DESC = The maximum queue length for incoming connections. If a connection request arrives when the queue is full, the connection will be refused.
TCP_BACKLOG_LABEL = Connection Backlog
TCP_USESSL_DESC = If checked the Connector will only accept SSL connections.
TCP_USESSL_LABEL = Use SSL
TCP_CLIENTAUTH_DESC = If checked clients will be required to provide SSL certificates for client authentication.
TCP_CLIENTAUTH_LABEL = Require Client Authentication
CONN_TITLE = TCP Server Connector
Advanced = Advanced
