CONN_TITLE = Tpae IF Change Detection Connector
CONN_DESC = Connector for Tpae IF change detection over HTTP
TCP_PORT_LABEL = TCP Port
TCP_PORT_DESC = Port for incoming HTTP requests for change detection.
TIMEOUT_LBL = Timeout
TIMEOUT_DESC = Max number of seconds before returning EOF (0 \= Wait Forever, otherwise this value should be greater than the Sleep Interval).
SLEEP_INTERVAL_LBL = Sleep Interval
SLEEP_INTERVAL_DESC = Number of seconds between each poll. Note that this should be less than the Timeout setting.
HTTP_AUTH_LABEL = HTTP Basic Authentication
HTTP_AUTH_DESC = Request HTTP Basic authentication
AUTH_REALM_LBL = Auth Realm
AUTH_REALM_DESC = The basic-realm sent to the client when authentication is requested.
USE_SSL_LBL = Use SSL
USE_SSL_DESC = Use SSL when accepting client connections.
CLIENT_AUTH_LBL = Require Client Authentication
CLIENT_AUTH_DESC = Mandate client authentication using SSL
TCP_BACKLOG_DESC = The maximum queue length for incoming connections. If a connection request arrives when the queue is full, the connection will be refused.
TCP_BACKLOG_LABEL = Connection Backlog
ERRORDETECT_SECTION = Error detection
source_desc = Tpae database JDBC URL
source_label = JDBC URL
driver_desc = JDBC Driver Class
driver_label = JDBC Driver
login_desc = Tpae database login user
login_label = Username
pass_desc = Password for Tpae database login user
pass_label = Password
schema_desc = Tpae database schema
schema_label = Schema
EXT_SYS_LABEL = External Systems
EXT_SYS_DESC = Name of the External systems sending change notifications as HTTP POST requests.
CHECK_INTERVAL_LABEL = Error check interval
CHECK_INTERVAL_DESC = Minimal interval in seconds between last notification and check for stalled messages.
ACTION_LABEL = Action on error
ACTION_DESC = Indicates which action will be performed for all held messages sent by the specified External systems.
Localized.None = None
Localized.Retry = Retry
Localized.Delete = Delete
Advanced = Advanced
