/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ibm_di_connector_DominoChangeDetectionConnector */

#ifndef _Included_com_ibm_di_connector_DominoChangeDetectionConnector
#define _Included_com_ibm_di_connector_DominoChangeDetectionConnector
#ifdef __cplusplus
extern "C" {
#endif
#undef com_ibm_di_connector_DominoChangeDetectionConnector_PROTOCOL_DELIMITER
#define com_ibm_di_connector_DominoChangeDetectionConnector_PROTOCOL_DELIMITER 58L
/*
 * Class:     com_ibm_di_connector_DominoChangeDetectionConnector
 * Method:    initNotes
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ibm_di_connector_DominoChangeDetectionConnector_initNotes
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     com_ibm_di_connector_DominoChangeDetectionConnector
 * Method:    getModifiedNotes
 * Signature: (Ljava/lang/String;Ljava/lang/StringBuffer;)Ljava/util/Vector;
 */
JNIEXPORT jobject JNICALL Java_com_ibm_di_connector_DominoChangeDetectionConnector_getModifiedNotes
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     com_ibm_di_connector_DominoChangeDetectionConnector
 * Method:    termNotes
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ibm_di_connector_DominoChangeDetectionConnector_termNotes
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
