CONN_DESC = Connector for managing Domino users
CONN_TITLE = Domino Users Connector
domsrv_desc = IP address (or hostname)of the Domino Server where the 'Name and Address Book' Database is located
domsrv_label = Domino Server IP Address
user_desc = User's Internet name for login on the Domino Server
user_label = Username
pass_desc = Either the Notes ID file password or the user's Internet password, depending on the Authentication Method setting.
pass_label = Password
data_desc = The name of the 'Name and Address Book' Database; usually 'names.nsf'.
data_label = Name and Address Book Database
use_label = Use full-text search
use_desc = If checked the Iterator and Lookup Connector modes will use full-text \nsearch in view; otherwise regular database search is performed.
full_label = Full-text filter
full_desc = Full-text query that will filter the users in Iterator mode. \nLeave blank if no filtering is needed. \n\nThis parameter's value is taken into account only when "useFTSearch" is "true".
for_label = Formula filter
for_desc = Lotus formula that will filter the users in Iterator mode. \nThe Connector will automatically append (Form \= "Person") to the formula, \nso the filter will be applied to user documents only. \n\nThis parameter's value is taken into account only when "useFTSearch" is "false".
ssl_label = Use SSL
ssl_desc = Enables encrypted communications with the Domino server
IOR_DESC = The IOR string used to create the IIOP session
IOR_LBL = IOR String
SESSIONTYPE_DESC = Specifies whether the Connector will create IIOP session or perform Local calls
SESSIONTYPE_LBL = Session Type
HTTPPORT_DESC = The port on which the HTTP task of the Domino Server is running
HTTPPORT_LBL = HTTP Port
Localized.IIOP = IIOP
Localized.LocalClient = LocalClient
Localized.LocalServer = LocalServer
Advanced = Advanced
