/*
 * Copyright IBM Corp. 2025
 *
 * SPDX-License-Identifier: Apache-2.0
 */
package com.ibm.di.tp.server.handler.node;

import java.util.Arrays;
import java.util.Date;
import java.util.List;

import javax.servlet.ServletContext;
import javax.ws.rs.Path;
import javax.ws.rs.PathParam;
import javax.ws.rs.core.Context;
import javax.ws.rs.core.Request;
import javax.ws.rs.core.Response;
import javax.ws.rs.core.UriInfo;

import org.apache.wink.common.annotations.Workspace;
import org.apache.wink.common.categories.Categories;
import org.apache.wink.common.categories.CollectionCategories;

import com.ibm.di.jaxrs.storage.atom.AtomStorage;
import com.ibm.di.tp.server.Constants;
import com.ibm.di.tp.server.ServerActivator;
import com.ibm.di.tp.server.TPServerApplication;
import com.ibm.di.tp.server.config.TPServerConfig;
import com.ibm.di.tp.server.config.node.TdiNodeConfig;
import com.ibm.di.tp.server.context.TPServerContext;
import com.ibm.di.tp.server.handler.base.Feed;
import com.ibm.di.tp.server.model.ConnectivityProvider;
import com.ibm.di.tp.server.model.ConnectivityProviderFactory;
import com.ibm.di.tp.server.util.SCMPUtils;

/**
 * This is the immutable "tp-node" feed containing a fixed set of TP Node
 * entries. This feed is not persisted because it is configured each time based
 * on the read configuration. <br>
 * <br>
 * The APP Service Document (the root Atom entry of the TP Server which is
 * accessible at "/tp") is automatically generated by Wink (see the
 * {@link Workspace} annotation and the {@link CollectionCategories} interface). <br>
 * <br>
 * <b>Note:</b> This class is for internal usage only. Any dependency from the
 * end-user will not be supported. Changes to this class will happen without a
 * warning.
 * 
 * @since 7.1
 */
@Workspace(workspaceTitle = "Security Verify Directory Integrator Workspace", collectionTitle = "Connectivity Providers Collection")
@Path(TPNodeFeed.URL)
public class TPNodeFeed extends Feed<TPNodeEntry> implements CollectionCategories {

	/**
	 * Copyright.
	 */
	@SuppressWarnings("unused")
	private static final String COPYRIGHT = com.ibm.di.CopyRight.OBJECT_CODE;

	public static final String URL = "tp-node";

	private final List<Categories> categories;

	// injected by the JAX-RS runtime
	@Context
	private ServletContext sCtx;

	private volatile boolean initialized;

	public TPNodeFeed() {
		categories = Arrays.asList(new Categories(Arrays.asList(Constants.CAT_CONN_PROVIDER)));
		getFeedTemplate().getCategories().add(Constants.CAT_CONN_PROVIDER_SYND);
		getFeedTemplate().setUpdated(new Date(System.currentTimeMillis()));
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see
	 * com.ibm.di.tp.server.handler.base.Feed#getRepresentation(javax.ws.rs.
	 * core.Request, javax.ws.rs.core.UriInfo)
	 */
	@Override
	public Response getRepresentation(Request request, UriInfo uriInfo) throws Exception {
		checkInitialized();
		return super.getRepresentation(request, uriInfo);
	}

	@Path("{node}")
	public Object getNodeEntry(@PathParam("node") String node, @Context UriInfo uriInfo) throws Exception {
		checkInitialized();
		TPNodeEntry entry = lookupEntry(node);
		return entry != null ? entry : notFoundEntry;
	}

	private void checkInitialized() throws Exception {
		if (!initialized) {
			synchronized (this) {
				if (!initialized) {
					// we are initializing on the first request as the ctx field
					// is not available during construction.
					initialized = true;

					// initialize TPServerContext
					TPServerContext tpCtx = (TPServerContext) sCtx.getAttribute(TPServerContext.class.getCanonicalName());
					if (tpCtx == null) {
						throw new IllegalStateException(TPServerContext.class.getCanonicalName());
					}

					// initialize TPServerConfig
					TPServerConfig cfg = (TPServerConfig) tpCtx.getAttribute(TPServerConfig.class.getCanonicalName());
					if (cfg == null) {
						throw new IllegalStateException(TPServerConfig.class.getCanonicalName());
					}

					// initialize the AtomStorage
					AtomStorage as = (AtomStorage) tpCtx.getAttribute(AtomStorage.class.getCanonicalName());
					if (as == null) {
						throw new IllegalStateException(AtomStorage.class.getCanonicalName());
					}

					ConnectivityProvider cp = null;
					String escapedId = null;
					TPNodeEntry entry = null;
					if (cfg != null) {
						// TODO: make this use NodeConfig instead of
						// TdiNodeConfig
						for (TdiNodeConfig node : cfg.getNodeConfigs().getTdiNodeConfigs()) {
							try {
								// create a connectivity provider object
								cp = ConnectivityProviderFactory.createConnectivityProvider(node, tpCtx);

								// escape the raw id and postfix it with an
								// index to make it unique if needed.
								escapedId = SCMPUtils.getUniqueKey(getTpEntries().keySet(), SCMPUtils.escapeId(cp.getId()));
								entry = new TPNodeEntry(cp, escapedId, node, tpCtx);

								// keep a map of IDs pointing to the document
								putEntry(entry.getEscapedId(), entry);
							} catch (Exception e) {
								TPServerApplication.getLog().error(
										ServerActivator.L10N.getString("TP.SERVER.RESOURCE.ERROR.CREATING.NODE", node.getId()), e);
							}
						}
					}
				}
			}
		}
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see
	 * org.apache.wink.common.categories.CollectionCategories#getCategories()
	 */
	public List<Categories> getCategories() {
		return categories;
	}
}
