#
# Copyright contributors to the SyncWeave project
# Documentation on available configuration
# https://cloud.ibm.com/docs/devsecops?topic=devsecops-cd-devsecops-apps-byoa
# https://cloud.ibm.com/docs/devsecops?topic=devsecops-custom-scripts

version: '2'

# PR Pipeline: pr-code-checks
tasks:
  pr-code-checks:
    include:
      - dind
    steps:
      - name: checks-setup
        image: icr.io/continuous-delivery/base-images/base:v1.19.0
        script: |
          #!/usr/bin/env bash
          if [[ "$PIPELINE_DEBUG" == 1 ]]; then
            trap env EXIT
            env
            set -x
          fi

          if [[ "$(get_env pipeline_namespace)" == *"pr"* ||  "$(get_env pipeline_namespace)" == *"ci"* ]]; then
            # setup branch protection for the app repo branch
            # see https://us-south.git.cloud.ibm.com/open-toolchain/compliance-commons/-/blob/master/doc/utils__setup_branch-protection.md
            ${COMMONS_PATH}/utils/setup_branch-protection.sh
          fi    
      - name: detect-secrets
        include:
          - docker-socket
      - name: compliance-checks
        include:
          - docker-socket
      # Even though we are not currently performing a static code scan,
      # we still need to add in this 'empty' step so that the code-ci-finish
      # stage can successfully complete.
      - name: static-scan
        include:
          - docker-socket
        image: icr.io/continuous-delivery/pipeline/pipeline-base-ubi:3.64
        script: |
          #!/usr/bin/env bash

          echo "No static-scan required."
finally:
  code-pr-finish:
    steps:
      - name: run-stage
        image: icr.io/continuous-delivery/base-images/base:v1.19.0
        script: |
          #!/usr/bin/env bash

          if [[ "$PIPELINE_DEBUG" == 1 ]]; then
            trap env EXIT
            env
            set -x
          fi
          echo "Running code-ci-finish"
          exit 0
