CONN_DESC = Change Detection Connector for Microsoft Active Directory via LDAP
CONN_TITLE = Active Directory Change Detection Connector
auth_desc = Type of LDAP authentication
auth_label = Authentication Method
pass_desc = Password associated with Login username
pass_label = Login password
url_desc = URL to the LDAP service for Active Directory (AD hostname or IP address, followed by the LDAP port)
url_label = LDAP URL
user_desc = LDAP distinguished name for login (leave blank for Anonymous)
user_label = Login username
search_label = LDAP Search Base
search_desc = The directory branch to poll for changes (e.g. "dc\=yourdomain,dc\=com"). Must be a Naming Context.
search_script_help = Query Active Directory for its naming contexts
search_script_label = Query
pagesize_label = Page Size
pagesize_desc = Specifies the number of entires per page returned by this request (default value is 500).
isk_label = Iterator State Key
isk_desc = A key (which should be unique) used to keep track of the last change processed by this Connector.
isk_script_label = Delete
isk_script_help = Deletes Iterator State information
startat_label = Start at
startat_desc = Specify a start USN value; "EOD" means report only new changes.\nOnly taken into account when the parameter specified by "Iterator State Key" is blank or not found\nin the System Store. 
usessl_desc = Check to use Secure Sockets Layer for communication with Active Directory
usessl_label = Use SSL
timeout_label = Timeout
timeout_desc = Max number of seconds before returning EOF (0 \= Wait Forever, otherwise this value should be greater than the Sleep Interval). Note also that if Use Notifications is selected, then this parameter is ignored.
sleep_label = Sleep Interval
sleep_desc = Number of seconds between each poll. Note that this should be less than the Timeout setting. Note also that if Use Notifications is selected, then this parameter is ignored.
Localized.Simple = Simple
Localized.Anonymous = Anonymous
Localized.SASL = SASL
Localized.EOD = EOD
JNDI_XTRA_PROVIDER_DESC = Additional JNDI provider parameters (name\:value one for each line)
JNDI_XTRA_PROVIDER_LABEL = Extra Provider Parameters
BIN_ATTRIB_DESC = List of attributes that are treated as binary (one attribute per line)
BIN_ATTRIB_LABEL = Binary Attributes
STATE_KEY_PERSIST_LBL = State Key Persistence
STATE_KEY_PERSIST_DESCR = Determines when Iterator State is saved. The recommended setting is End of Cycle.
USE_NOTIFICATIONS_DESC = Check to enable real-time notification of changes instead of polling. If enabled then the sleep interval and timeout parameters are ignored.
USE_NOTIFICATIONS_LBL = Use Notifications
Localized.After.read = After read
Localized.End.of.cycle = End of cycle
Localized.Manual = Manual
Advanced = Advanced
