CONN_DESC = Connector for sourcing SAP ALE IDoc data into SyncWeave
CONN_TITLE = SAP ALE IDoc Connector
SAPIDOC_SRVR_GWHOST_DESC = IDoc Server SAP Gateway hostname or IP address
SAPIDOC_SRVR_GWHOST_LABEL = IDoc Server SAP Gateway Host
SAPIDOC_SRVR_GWSERV_DESC = IDoc Server SAP Gateway service name
SAPIDOC_SRVR_GWSERV_LABEL = IDoc Server SAP Gateway Service
SAPIDOC_SRVR_PROGID_DESC = IDoc Server Program ID used for TCP/IP RFC Destination registration
SAPIDOC_SRVR_PROGID_LABEL = IDoc Server Program ID
SAPIDOC_SRVR_UNICODE_DESC = IDoc Server Unicode Connection designator. 1\=ON 0\=OFF
SAPIDOC_SRVR_UNICODE_LABEL = IDoc Server Unicode Connection?
SAPIDOC_SRVR_OPTIONAL_DESC = IDoc Server optional connection parameters. Delimited with space char. i.e. "jco.server.trace\=1 jco.server.sysnr\=00"
SAPIDOC_SRVR_OPTIONAL_LABEL = IDoc Server Optional Connection Parameters
SAPIDOC_SRVR_POLL_DESC = IDoc Server Pole time in seconds for checking if inbound IDocs requests have been received
SAPIDOC_SRVR_POLL_LABEL = IDoc Server Pole Time
SAPIDOC_CL_CLIENT_DESC = Client number for SAP system acting as IDoc Server
SAPIDOC_CL_CLIENT_LABEL = IDoc Client Number
SAPIDOC_CL_USER_DESC = IDoc Client Communication/CPIC SAP User Account logon id
SAPIDOC_CL_USER_LABEL = IDoc Client User
SAPIDOC_CL_PWD_DESC = IDoc Client Communication/CPIC SAP User Account's password
SAPIDOC_CL_PWD_LABEL = IDoc Client Password
SAPIDOC_CL_LANG_DESC = IDoc Client logon language
SAPIDOC_CL_LANG_LABEL = IDoc Client Lang
SAPIDOC_CL_AHOST_DESC = IDoc Client target SAP System's hostname or IP address
SAPIDOC_CL_AHOST_LABEL = IDoc Client Hostname
SAPIDOC_CL_SYSNR_DESC = IDoc Client target SAP System number
SAPIDOC_CL_SYSNR_LABEL = IDoc Client System Number
SAPIDOC_CL_GWSERV_DESC = IDoc Client SAP Gateway service name
SAPIDOC_CL_GWSERV_LABEL = IDoc Client SAP Gateway Service
SAPIDOC_CL_GWHOST_DESC = IDoc Client SAP Gateway hostname or IP address
SAPIDOC_CL_GWHOST_LABEL = IDoc Client SAP Gateway Host
SAPIDOC_CL_MAX_CONN_DESC = IDoc Client Pool maximum allowed connections
SAPIDOC_CL_MAX_CONN_LABEL = IDoc Client Max Connections
SAPIDOC_CL_OPTIONAL_DESC = IDoc Client optional connection parameters. Delimited with space char. i.e. "jco.client.trace\=1 jco.client.use_sapgui\=1"
SAPIDOC_CL_OPTIONAL_LABEL = IDoc Client Optional Connection Parameters
SAPIDOC_IDOC_XML_ONLY_DESC = Only populate Entry with the IDoc as XML attribute.
SAPIDOC_IDOC_XML_ONLY_LABEL = IDoc As XML Only?
SAPIDOC_RFM_XML_DESC = Process Remote Function Method calls as an XML valued SyncWeave attribute.
SAPIDOC_RFM_XML_LABEL = Process SAP RFM Requests?
SAPIDOC_PARSE_XML_DESC = If set to 'Yes' the Connector use the attached XML Parser to parse the XML into Entry Attributes based on XML Elements.
SAPIDOC_PARSE_XML_LABEL = Parse IDoc or RFM XML?
SAPIDOC_IDOC_JCO_TRACE_DESC = Enable or disable JCo middleware trace logging
SAPIDOC_IDOC_JCO_TRACE_LABEL = Enable JCo Middleware Trace Logging?
SAPIDOC_IDOC_JCO_TRACELEVEL_DESC = The JCo middleware trace level.
SAPIDOC_IDOC_JCO_TRACELEVEL_LABEL = JCo Middleware Trace Level
SAPIDOC_IDOC_JCO_TRACEPATH_DESC = Path where the JCo middleware trace files will be created
SAPIDOC_IDOC_JCO_TRACEPATH_LABEL = JCo Middleware Trace File Path
SAPIDOC_YES = Yes
SAPIDOC_NO = No
SAPIDOC_T0 = No Trace
SAPIDOC_T1 = Trace Level 1
SAPIDOC_T2 = Trace Level 2
SAPIDOC_T3 = Trace Level 3
SAPIDOC_T4 = Trace Level 4
Advanced = Advanced
