PAR_DESC = A parser that handles requests complying with the SPMLv2 schema
BA_LBL = Binary Attributes
BA_DESC = User defined binary attributes delimited by ",".\nThese attributes will be Base64 decoded when parsing SPML messages.
PAR_TITLE = SPMLv2 Parser
CHAR_DESC = Character encoding to use when reading or writing
CHAR_TITLE = Character Encoding
Advanced = Advanced
