FC_DESC = The Remote Command Line Function Component connects to a remote target machine and executes a command.
FC_TITLE = Remote Command Line Function Component
HOST_LBL = Target Machine Hostname
HOST_DESC = Hostname of the remote target machine
USER_LBL = Remote User
USER_DESC = Target login user ID
PASSWD_LBL = Password
PASSWD_DESC = Target user password
KS_LBL = Keyfile Path
KS_DESC = Path to the OpenSSH Private key file
PHRASE_LBL = Passphrase
PHRASE_DESC = Passphrase that protects the private key
CONNECT_LBL = Connection Protocol
CONNECT_DESC = Allows the user to select what protocol to use when connecting to the remote machine
Localized.CONNECT_OPT1 = ANY
Localized.CONNECT_OPT2 = SSH
Localized.CONNECT_OPT3 = RSH
Localized.CONNECT_OPT4 = REXEC
Localized.CONNECT_OPT5 = AS400
Localized.CONNECT_OPT6 = WIN
CMD_LBL = Command
CMD_DESC = The command to be executed on the target
PORT_LBL = Port
PORT_DESC = Port to use when connecting to target
SRC_LBL = Stdin source file (local)
SRC_DESC = The path to the local file containing the standard input for the command
DEST_LBL = Stdin destination directory (remote)
DEST_DESC = The path to the remote file where the standard input should be stored
TIME_LBL = Execution timeout (ms)
TIME_DESC = Timeout duration for command execution
AS400SSL_LBL = Enable SSL for AS400?
AS400SSL_DESC = If checked an SSL connection will be attempted to the AS400 target (SSL must be installed and configured on the AS400 target)
AS400PROX_LBL = AS400 Proxy Server Name
AS400PROX_DESC = If required, the hostname or IP address an AS400 proxy server
AS400RPROG_LBL = Run AS400 Program?
AS400RPROG_DESC = Secondary mechanism for executing AS400 Programs
AS400ARGENC_LBL = AS400 Command Line Arguments Character Encoding
AS400ARGENC_DESC = The character encoding to use for AS400 command line arguments. The default character encoding of jvm is used if not specified.
RXALOG_LBL = Enable RXA Internal Logging?
RXALOG_DESC = If checked, RXA internal logging will be directed to the Security Verify Directory Integrator Log.
Advanced = Advanced
HANDLE_AS_TEXT_FILE_DESC = If checked, the Stdin source file will be converted to the character set of the target system; otherwise, the current encoding of file will be maintained.
HANDLE_AS_TEXT_FILE_LBL = Convert Stdin source file to character set of target system
CONN_TIME_DESC = Timeout duration for the initial connection to the target system.
CONN_TIME_LBL = Initial connection timeout (ms)
