/*
 * Copyright IBM Corp. 2025
 *
 * SPDX-License-Identifier: Apache-2.0
 */
package com.ibm.di.fc.webservice;

import java.util.HashMap;
import java.util.Map;
import java.util.Vector;
import javax.xml.namespace.QName;
import javax.xml.stream.XMLStreamException;

import org.apache.axiom.om.OMElement;
import org.apache.axiom.om.OMXMLBuilderFactory;
import org.apache.axis2.AxisFault;
import org.apache.axis2.addressing.EndpointReference;
import org.apache.axis2.client.Options;
import org.w3c.dom.Element;

import com.ibm.di.entry.Attribute;
import com.ibm.di.entry.Entry;
import com.ibm.di.fc.Function;
import com.ibm.di.fc.webservice.axis2.WSDLData;
import com.ibm.di.fc.webservice.axis2.WSDLLocator;
import com.ibm.di.fc.webservice.axis2.WebServiceClient;
import com.ibm.di.server.ResourceHash;

/**
 * The Axis Soap-to-Java Function Component (FC) is part of the 
 * TDI Web Services suite.This component can be used both on the web 
 * service client and on the web service server side. This FC uses 
 * Axis2's mechanism for parsing SOAP response (when on the client) 
 * or SOAP request (when on the server) to Java objects - as a 
 * complementary component to the AxisJavaToSoap FC. It is given a 
 * SOAP response/request message and returns the parsed Java objects 
 * either as standalone Java object(s) or capsulated in an 
 * Entry object.This component supports both RPC and Document style.
 *
 */
public class AxisSoapToJava extends Function {
	/**
	 * Copyright.
	 */
	@SuppressWarnings("unused")
	private static final String COPYRIGHT = com.ibm.di.server.CopyRight.OBJECT_CODE;

	/**
	 * The name of the properties file
	 */
	private static final String PROPERTIES_FILE = "axissoaptojavafc";

	/**
	 * The WSDL URL
	 */
	private String mWsdlUrl = null;

	/**
	 * The SOAP Operation
	 */
	private String mSoapOperation = null;

	/**
	 * The data the WSDL contains
	 */
	private WSDLData mWsdlData = null;

	/**
	 * The class which is used to call a webservice
	 */
	private WebServiceClient mClient = null;

	/**
	 * A Vector with the classes which are given in the "complexTypes" parameter.
	 */
	private Vector<Class<?>> mClasses = null;

	/**
	 * The input XML type
	 */
	private String mInputXMLType = null;

	/**
	 * The input attributes
	 */
	private String mInputAttr = null;

	/**
	 * The type of the message
	 */
	private String mMsgType = null;

	/**
	 * The WSDL URL parameter
	 */
	public static final String PARAM_WSDL_URL = "wsdlUrl";

	/**
	 * The name of the SOAP operation as described in the WSDL file
	 */
	public static final String PARAM_SOAP_OPERATION = "soapOperation";

	/**
	 * specifies the input type
	 */
	public static final String PARAM_INPUT_TYPE = "inputType";

	/**
	 * The list of fully qualified Java classes generated by WSDL2Java from the WSDL file
	 */
	public static final String PARAM_COMPLEX_TYPES = "complexTypes";

	/**
	 * specifies whether this Function Component handles a SOAP request or a SOAP response
	 */
	public static final String PARAM_MODE = "mode";

	/**
	 * The value of the request mode
	 */
	public static final String MODE_REQUEST = "Request";

	/**
	 * The value of the response attribute 
	 */
	public static final String MODE_RESPONSE = "Response";

	/**
	 * The name of the output attribute
	 */
	private static final String OUT_ATTR_PARAMS = "return";

	/**
	 * The name of the SOAP Fault attribute
	 */
	private static final String OUT_ATTR_SOAP_FAULT = "soapFault";

	/**
	 * The name of the returnXMLType attribute when String is chosen
	 */
	private static final String ATTR_XML_STRING = "xmlString";

	/**
	 * The name of the XML DOMElement attribute
	 */
	private static final String ATTR_XML_DOM = "xmlDOMElement";

	/**
	 * The name of the returnXMLType attribute when String is chosen
	 */
	public static final String INPUT_XML_STRING = "String";

	/**
	 * The name of the returnXMLType attribute when DOMElement is chosen
	 */
	public static final String INPUT_XML_DOM = "DOMElement";

	/**
	 * NLS Property set holding name-value pairs for the resource.
	 */
	private static ResourceHash sResHash = null;

	static {
		sResHash = new ResourceHash(PROPERTIES_FILE);
	}

	/**
	 * Initializes the function component by using the parameters in the Config Tab.
	 * 
	 * @param obj not used in this method
	 * @throws Exception
	 */
	public void initialize(Object obj) throws Exception {

		mWsdlUrl = (String) getParam(PARAM_WSDL_URL);
		if (getDebug()) {
			debug(sResHash.getString("FC.AXISSOAPTOJAVA.PARAMETER.WSDLURL",
					new Object[] { mWsdlUrl }));
		}
		if (mWsdlUrl == null) {
			throw new Exception(sResHash
					.getString("FC.AXISSOAPTOJAVA.PARAMETER.WSDLURL.EMPTY"));
		}
		mSoapOperation = (String) getParam(PARAM_SOAP_OPERATION);
		if (getDebug()) {
			debug(sResHash.getString(
					"FC.AXISSOAPTOJAVA.PARAMETER.SOAP.OPERATION",
					new Object[] { mSoapOperation }));
		}
		if (mSoapOperation == null) {
			throw new Exception(
					sResHash
							.getString("FC.AXISSOAPTOJAVA.PARAMETER.SOAP.OPERATION.EMPTY"));
		}
		String complexTypes = (String) getParam(PARAM_COMPLEX_TYPES);
		if (getDebug()) {
			debug(sResHash.getString(
					"FC.AXISSOAPTOJAVA.PARAMETER.COMPLEX.TYPES",
					new Object[] { complexTypes }));
		}
		mClasses = WebServiceClient.convertComplexTypeList(complexTypes);
		String mode = (String) getParam(PARAM_MODE);
		if (getDebug()) {
			debug(sResHash.getString("FC.AXISSOAPTOJAVA.PARAMETER.MODE",
					new Object[] { mode }));
		}
		if (mode == null) {
			throw new Exception(sResHash
					.getString("FC.AXISSOAPTOJAVA.PARAMETER.MODE.EMPTY"));
		}
		if (mode.equals(MODE_REQUEST)) {
			mMsgType = "REQUEST";
		} else if (mode.equals(MODE_RESPONSE)) {
			mMsgType = "RESPONSE";
		} else {
			throw new Exception(sResHash.getString(
					"FC.AXISSOAPTOJAVA.PARAMETER.MODE.INVALID",
					new Object[] { mode }));
		}
		mInputXMLType = (String) getParam(PARAM_INPUT_TYPE);
		if (getDebug()) {
			debug(sResHash.getString("FC.AXISSOAPTOJAVA.PARAMETER.INPUT.TYPE",
					new Object[] { mInputXMLType }));
		}
		if (mInputXMLType != null) {
			mInputXMLType = mInputXMLType.trim();
		}
		if (mInputXMLType == null
				|| (!mInputXMLType.equalsIgnoreCase(INPUT_XML_DOM) && !mInputXMLType
						.equalsIgnoreCase(INPUT_XML_STRING))) {
			// todo: log error
			throw new Exception(sResHash.getString(
					"FC.AXISSOAPTOJAVA.INPUT.TYPE.INVALID",
					new Object[] { mInputXMLType }));
		}

		if (mInputXMLType.equalsIgnoreCase(INPUT_XML_DOM)) {
			mInputAttr = ATTR_XML_DOM;
		} else if (mInputXMLType.equalsIgnoreCase(INPUT_XML_STRING)) {
			mInputAttr = ATTR_XML_STRING;
		}

		if (getDebug()) {
			debug(sResHash.getString(
					"FC.AXISSOAPTOJAVA.PARSED.JAVA.OBJECT.ATTRIBUTE",
					mInputAttr));
		}

		String wsdlAuthUser = (String) getParam("wsdlAuthUser");
		String wsdlAuthPass = (String) getParam("wsdlAuthPass");

		if (wsdlAuthUser != null && wsdlAuthUser.trim().length() > 0) {
			// Create WebServiceClient with authentication
			mClient = WebServiceClient.createWebServiceClient(mWsdlUrl, null, null, 
					mSoapOperation, wsdlAuthUser, wsdlAuthPass, logger);
		} else {
			// Create WebServiceClient without authentication
			mClient = WebServiceClient.createWebServiceClient(mWsdlUrl, null, null, 
					mSoapOperation, logger);
		}

		// Get WSDL data
		mWsdlData = WSDLData.getWsdlData(mWsdlUrl, mSoapOperation);

		// Set style and use
		String operationStyle = mWsdlData.getStyle();
		if (operationStyle != null && !operationStyle.isEmpty()) {
			mClient.setStyle(operationStyle);
		}
		
		String encoding = mWsdlData.getEncoding();
		if (encoding != null && !encoding.isEmpty()) {
			mClient.setUse(encoding);
		}

		super.initialize(null);
	}

	/**
	 * Parses a SOAP message and turns it into a Java Object
	 * 
	 * If this FC is passed a SOAP Fault message to parse, this 
	 * FC returns a Java object of type org.apache.axis2.AxisFault. In 
	 * case this FC returns an org.apache.axis2.AxisFault object, the 
	 * FC stores this object in the "soapFault" Attribute if an Entry 
	 * is passed to the FC; and if a java.lang.Object was passed then 
	 * this FC returns the org.apache.axis2.AxisFault object. 
	 * 
	 * If the value of the "Input the SOAP message as" FC parameter is String 
	 * then the SOAP message to parse is read from the "xmlString" 
	 * Attribute as a java.lang.String, provided an Entry is passed to 
	 * the FC. 
	 * 
	 * If the value of the "Input the SOAP message as" FC parameter 
	 * is DOMElement then the SOAP message to parse is read from the 
	 * "xmlDOMElement" Attribute as an org.w3c.dom.Element object, 
	 * provided an Entry is passed to the FC. 
	 * 
	 * If a Java Object is passed to this FC, then the SOAP message to 
	 * parse is assumed to be the value of the passed Java Object as 
	 * either a java.lang.String object (when the value of the 
	 * "Input the SOAP message as" FC parameter is String) or as 
	 * an org.w3c.dom.Element object (when the value of the 
	 * "Input the SOAP message as" FC parameter is DOMElement).
	 * 
	 * @param obj
	 * @return a Java object
	 * @throws Exception
	 */
	public Object perform(Object obj) throws Exception {
		verifyInitialized();

		Object unwrappedObject = obj;
		if (obj instanceof Entry) {
			Entry e = (Entry) obj;
			Attribute attrSoap = e.getAttribute(mInputAttr);
			if (attrSoap != null) {
				unwrappedObject = attrSoap.getValue(0);
			} else {
				throw new Exception(sResHash
						.getString("FC.AXISSOAPTOJAVA.ENTRY.ATTRIBUTE.MISSING",
								mInputAttr));
			}
		}

		String soapMsg = null;
		try {
			if (mInputXMLType.equalsIgnoreCase(INPUT_XML_DOM)) {
				soapMsg = WebServiceClient.getAsString((Element) unwrappedObject);
			} else if (mInputXMLType.equalsIgnoreCase(INPUT_XML_STRING)) {
				soapMsg = (String) unwrappedObject;
			}
		} catch (ClassCastException e) {
			throw new Exception(sResHash.getString(
					"FC.AXISSOAPTOJAVA.INVALID.OBJECT", this.toString()));
		}

		if (getDebug()) {
			debug(sResHash
					.getString("FC.AXISSOAPTOJAVA.ABOUT.TO.PARSE.A.SOAP.MESSAGE.USING"));
			debug(sResHash.getString("FC.AXISSOAPTOJAVA.COMPLEX.TYPES",
					mClasses));
			debug(sResHash.getString("FC.AXISSOAPTOJAVA.SOAP.MESSAGE", soapMsg));
		}

		// Convert the SOAP string to an OMElement
		OMElement soapElement = null;
		try {
			// Create a StAXOMBuilder from the SOAP message string
			java.io.StringReader reader = new java.io.StringReader(soapMsg);
			javax.xml.stream.XMLInputFactory factory = javax.xml.stream.XMLInputFactory.newInstance();
			javax.xml.stream.XMLStreamReader xmlReader = factory.createXMLStreamReader(reader);
			soapElement = OMXMLBuilderFactory.createStAXOMBuilder(xmlReader).getDocumentElement();
		} catch (XMLStreamException e) {
			throw new Exception(sResHash.getString(
					"FC.AXISSOAPTOJAVA.FAILED.TO.PARSE.SOAP", e.getMessage()));
		}

		// Process the SOAP message
		Object resObj = null;
		
		// Check if this is a fault
		if (soapElement.getLocalName().equals("Fault")) {
			// Handle fault - create a fault from the element text
			AxisFault fault = new AxisFault(soapElement.getText());
			resObj = fault;
		} else {
			// For REQUEST mode (server-side), we receive just the operation element (body content)
			// For RESPONSE mode (client-side), we receive a complete SOAP envelope
			if (mMsgType.equals("REQUEST")) {
				// Server-side: Parse the operation element directly
				// The soapElement is already the operation element (e.g., <ns1:A_times_B_FlexibleWebService>)
				// We need to extract parameters from it
				resObj = parseOperationElement(soapElement);
			} else {
				// Client-side: Extract body from SOAP envelope and parse
				// Check if this is a complete SOAP envelope or just the body content
				if (soapElement.getLocalName().equals("Envelope") ||
				    soapElement.getLocalName().equals("Body")) {
					// Extract the body content
					OMElement bodyElement = null;
					if (soapElement.getLocalName().equals("Envelope")) {
						// Find the Body element
						java.util.Iterator<?> children = soapElement.getChildElements();
						while (children.hasNext()) {
							Object child = children.next();
							if (child instanceof OMElement) {
								OMElement childElement = (OMElement) child;
								if (childElement.getLocalName().equals("Body")) {
									bodyElement = childElement;
									break;
								}
							}
						}
					} else {
						bodyElement = soapElement;
					}
					
					if (bodyElement != null) {
						// Get the first child of Body (the operation element)
						java.util.Iterator<?> bodyChildren = bodyElement.getChildElements();
						if (bodyChildren.hasNext()) {
							Object firstChild = bodyChildren.next();
							if (firstChild instanceof OMElement) {
								resObj = parseOperationElement((OMElement) firstChild);
							}
						}
					}
				} else {
					// Already the operation element
					resObj = parseOperationElement(soapElement);
				}
			}
		}

		logmsg(sResHash.getString("FC.AXISSOAPTOJAVA.PARSED.SOAP"));

		if (getDebug()) {
			debug(sResHash.getString("FC.AXISSOAPTOJAVA.PARSED.JAVA.OBJECT",
					resObj));
		}

		if (resObj instanceof AxisFault) {
			AxisFault axisFault = (AxisFault) resObj;
			logmsg(sResHash
					.getString(
							"FC.AXISSOAPTOJAVA.THE.MESSAGE.PARSED.IS.A.SOAP.FAULT.MESSAGE",
							axisFault.getMessage()));
		}

		Object returnObject = null;
		if (obj instanceof Entry) {
			Entry entry = new Entry();
			if (resObj instanceof AxisFault) {
				entry.setAttribute(OUT_ATTR_SOAP_FAULT, resObj);
			} else {
				// For REQUEST mode (server-side), if resObj is a Map, create attributes from the map
				if (mMsgType.equals("REQUEST") && resObj instanceof java.util.Map) {
					@SuppressWarnings("unchecked")
					java.util.Map<String, Object> paramMap = (java.util.Map<String, Object>) resObj;
					// Create attributes for each parameter using the actual parameter names from XML
					for (java.util.Map.Entry<String, Object> paramEntry : paramMap.entrySet()) {
						entry.setAttribute(paramEntry.getKey(), paramEntry.getValue());
					}
					// Also set the return attribute with the first parameter for backward compatibility
					if (!paramMap.isEmpty()) {
						entry.setAttribute(OUT_ATTR_PARAMS, paramMap.values().iterator().next());
					}
				}  
				else if (mMsgType.equals("RESPONSE") && resObj instanceof java.util.Map) {
						// For RESPONSE mode (client-side), if resObj is a Map, create attributes from the map
						@SuppressWarnings("unchecked")
						java.util.Map<String, Object> paramMap = (java.util.Map<String, Object>) resObj;
						// Create attributes for each output parameter using the WSDL parameter names
						for (java.util.Map.Entry<String, Object> paramEntry : paramMap.entrySet()) {
							entry.setAttribute(paramEntry.getKey(), paramEntry.getValue());
						}
						// Also set the return attribute with the first parameter for backward compatibility
						if (!paramMap.isEmpty()) {
							entry.setAttribute(OUT_ATTR_PARAMS, paramMap.values().iterator().next());
						}
					} else {
						// For other cases, use the standard approach
						String resultAttrName = OUT_ATTR_PARAMS;
						if (mClient.getReturnParamQName() != null) {
							resultAttrName = mClient.getReturnParamQName().getLocalPart();
						}
						entry.setAttribute(resultAttrName, resObj);
					}
				HashMap<QName, Object> outParams = mClient.getOutParams();
				// Only process outParams if not null (it will be null when using parseOperationElement)
				if (outParams != null) {
					java.util.Iterator<Map.Entry<QName, Object>> iterParams = outParams.entrySet().iterator();
					while (iterParams.hasNext()) {
						Map.Entry<QName, Object> mpEntry = iterParams.next();
						QName paramQName = mpEntry.getKey();
						Object paramValue = mpEntry.getValue();
						String paramName = paramQName.getLocalPart();
						if (getDebug()) {
							debug(sResHash
									.getString(
											"FC.AXISSOAPTOJAVA.ADDITIONAL.OUTPUT.PARAMETER.NAME.VALUE",
											new Object[] { paramName, paramValue }));
						}
						entry.setAttribute(paramName, paramValue);
					}
				}
			}
			returnObject = entry;
		} else {
			if (resObj instanceof AxisFault) {
				returnObject = resObj;
			} else {
				HashMap<QName, Object> outParams = mClient.getOutParams();
				Object[] returnObjArray = null;
				// Only process outParams if not null (it will be null when using parseOperationElement)
				if (outParams != null && outParams.size() > 0) {
					returnObjArray = new Object[outParams.size() + 1];
					returnObjArray[0] = resObj;
					java.util.Iterator<Map.Entry<QName, Object>> iterParams = outParams.entrySet().iterator();
					int i = 1;
					while (iterParams.hasNext() && (i <= outParams.size())) {
						Map.Entry<QName, Object> mpEntry = iterParams.next();
						QName paramName = mpEntry.getKey();
						Object paramValue = mpEntry.getValue();
						if (getDebug()) {
							debug(sResHash
									.getString(
											"FC.AXISSOAPTOJAVA.ADDITIONAL.OUTPUT.PARAMETER.NAME.VALUE.2",
											new Object[] { paramName,
													paramValue }));
						}
						returnObjArray[i++] = paramValue;
					}
				} else {
					returnObjArray = new Object[] { resObj };
				}
				returnObject = returnObjArray;
			}
		}

		return returnObject;
	}

	/**
		* Parse an operation element to extract parameters.
		* This method handles both REQUEST mode (server-side) and RESPONSE mode (client-side).
		* For REQUEST mode, returns a Map of parameter names to values.
		* For RESPONSE mode, returns an array or single object.
		*
		* @param operationElement The operation element (e.g., <ns1:A_times_B_FlexibleWebService>)
		* @return The parsed result - Map for REQUEST mode, array/object for RESPONSE mode
		* @throws Exception if parsing fails
		*/
	private Object parseOperationElement(OMElement operationElement) throws Exception {
		if (operationElement == null) {
			throw new Exception("Operation element is null");
		}
		
		// For REQUEST mode (server-side), return a Map with WSDL parameter names
		if (mMsgType.equals("REQUEST")) {
			java.util.LinkedHashMap<String, Object> paramMap = new java.util.LinkedHashMap<String, Object>();
			
			// Get WSDL-defined parameter names
			java.util.List<String> wsdlParamNames = null;
			if (mWsdlData != null) {
				wsdlParamNames = mWsdlData.getInputParameterNames();
			}
			
			// Collect parameter values in order
			java.util.List<Object> paramValues = new java.util.ArrayList<Object>();
			java.util.Iterator<?> children = operationElement.getChildElements();
			
			while (children.hasNext()) {
				Object child = children.next();
				if (child instanceof OMElement) {
					OMElement paramElement = (OMElement) child;
					String paramValue = paramElement.getText();
					
					// Try to convert to appropriate type
					try {
						if (paramValue != null && paramValue.matches("-?\\d+(\\.\\d+)?")) {
							paramValues.add(Double.parseDouble(paramValue));
						} else {
							paramValues.add(paramValue);
						}
					} catch (NumberFormatException e) {
						paramValues.add(paramValue);
					}
				}
			}
			
			// Map positional values to WSDL parameter names
			if (wsdlParamNames != null && !wsdlParamNames.isEmpty()) {
				// Use WSDL-defined parameter names
				for (int i = 0; i < paramValues.size() && i < wsdlParamNames.size(); i++) {
					paramMap.put(wsdlParamNames.get(i), paramValues.get(i));
				}
			} else {
				// Fallback: use XML element names if WSDL parameter names not available
				java.util.Iterator<?> childrenAgain = operationElement.getChildElements();
				int index = 0;
				while (childrenAgain.hasNext() && index < paramValues.size()) {
					Object child = childrenAgain.next();
					if (child instanceof OMElement) {
						OMElement paramElement = (OMElement) child;
						String paramName = paramElement.getLocalName();
						paramMap.put(paramName, paramValues.get(index));
						index++;
					}
				}
			}
			
			return paramMap;
		} else {
			// For RESPONSE mode (client-side), return a Map with WSDL parameter names
			java.util.LinkedHashMap<String, Object> paramMap = new java.util.LinkedHashMap<String, Object>();
			
			// Get WSDL-defined output parameter names
			java.util.List<String> wsdlParamNames = null;
			if (mWsdlData != null) {
				wsdlParamNames = mWsdlData.getOutputParameterNames();
			}
			
			// Collect parameter values in order
			java.util.List<Object> paramValues = new java.util.ArrayList<Object>();
			java.util.Iterator<?> children = operationElement.getChildElements();
			
			while (children.hasNext()) {
				Object child = children.next();
				if (child instanceof OMElement) {
					OMElement paramElement = (OMElement) child;
					String paramValue = paramElement.getText();
					
					// Try to convert to appropriate type
					try {
						if (paramValue != null && paramValue.matches("-?\\d+(\\.\\d+)?")) {
							paramValues.add(Double.parseDouble(paramValue));
						} else {
							paramValues.add(paramValue);
						}
					} catch (NumberFormatException e) {
						paramValues.add(paramValue);
					}
				}
			}
			
			// Map positional values to WSDL output parameter names
			if (wsdlParamNames != null && !wsdlParamNames.isEmpty()) {
				// Use WSDL-defined output parameter names
				for (int i = 0; i < paramValues.size() && i < wsdlParamNames.size(); i++) {
					paramMap.put(wsdlParamNames.get(i), paramValues.get(i));
				}
			} else {
				// Fallback: use XML element names if WSDL parameter names not available
				java.util.Iterator<?> childrenAgain = operationElement.getChildElements();
				int index = 0;
				while (childrenAgain.hasNext() && index < paramValues.size()) {
					Object child = childrenAgain.next();
					if (child instanceof OMElement) {
						OMElement paramElement = (OMElement) child;
						String paramName = paramElement.getLocalName();
						paramMap.put(paramName, paramValues.get(index));
						index++;
					}
				}
			}
			
			return paramMap;
		}
	}

	/**
		* This method is analogous to the 'registerTypeMapping' method in
	 * org.apache.axis2.client.ServiceClient. It can be used for configuring
	 * serialization/deserialization of Java types.
	 * 
	 * @param javaType
	 *            java type to handle
	 * @param xmlType
	 *            XML mapping
	 * @param serializerFactory
	 *            a factory of the serializers
	 * @param deserializerFactory
	 *            a factory of deserializers
	 */
	public void registerTypeMapping(Class<?> javaType, QName xmlType,
			Object serializerFactory, Object deserializerFactory) {
		mClient.registerCustomTypeMapping(javaType, xmlType, serializerFactory,
				deserializerFactory);
		
		// Apply type mappings
		mClient.applyCustomTypeMappings();

		if (getDebug()) {
			debug(sResHash.getString("FC.AXISSOAPTOJAVA.REGISTER.TYPE.MAPPING",
					new Object[] { javaType, xmlType, serializerFactory,
							deserializerFactory }));
		}
	}

	/**
	 * Version information.
	 *  @return version information
	 */ 
	public String getVersion() {
		return "3.0-di7.1.1 1.29 2025/10/08";
	}
	
	/**
	 * Cleanup resources when this function component is no longer needed.
	 */
	@Override
	public void terminate() throws Exception {
		if (mClient != null) {
			try {
				mClient.close();
				mClient = null;
			} catch (Exception e) {
				if (logger != null) {
					logger.logerror("Error closing WebServiceClient", e);
				}
			}
		}
		super.terminate();
	}
}
