/*
 * Copyright IBM Corp. 2025
 *
 * SPDX-License-Identifier: Apache-2.0
 */
package com.ibm.di.fc.webservice;

import java.text.NumberFormat;
import java.text.ParseException;
import java.util.HashMap;
import java.util.Map;
import java.util.Vector;

import javax.xml.namespace.QName;

import org.apache.axis2.AxisFault;
import org.apache.axis2.addressing.EndpointReference;
import org.apache.axis2.client.Options;

import com.ibm.di.entry.Attribute;
import com.ibm.di.entry.Entry;
import com.ibm.di.fc.Function;
import com.ibm.di.fc.webservice.axis2.WSDLData;
import com.ibm.di.fc.webservice.axis2.WebServiceClient;
import com.ibm.di.server.ResourceHash;

/**
 * The Axis EasyInvokeSoapWS Function Component (FC) is part of the TDI Web
 * Services suite. This is a "simplified" web service invocation component: it
 * is a stand-alone FC with its own Config screen, but internally instantiates,
 * configures and uses the WebServiceClient class. The functionality provided is 
 * the same as if you chain and configure multiple FCs in an AssemblyLine. 
 * When using this FC you lose the possibility to hook custom processing, but 
 * you gain simplicity of setup and use.
 * 
 * Authentication: The AxisEasyInvokeSoapWS FC uses Axis2's authentication mechanism. 
 * When username and password parameters of the FC are specified, then they are set 
 * to be used by the ServiceClient object. This information is sent to the server 
 * and if it requires authentication it takes these two parameters for username and password.
 *
 */
public class AxisEasyInvokeSoapWS extends Function {
	/**
	 * Copyright.
	 */
	@SuppressWarnings("unused")
	private static final String COPYRIGHT = com.ibm.di.server.CopyRight.OBJECT_CODE;

	/**
	 * The name of the properties file
	 */
	private static final String PROPERTIES_FILE = "axiseasyinvokesoapwsfc";

	/**
	 * The WSDL URL
	 */
	private String mWsdlUrl = null;

	/**
	 * The SOAP Operation
	 */
	private String mSoapOperation = null;

	/**
	 * The data the WSDL contains
	 */
	private WSDLData mWsdlData = null;

	/**
	 * The class which is used to call a webservice
	 */
	private WebServiceClient mClient = null;

	/**
	 * A Vector with the classes which are given in the "complexTypes" parameter.
	 */
	private Vector<Class<?>> mClasses = null;

	/**
	 * The list of ordered SOAP operation parameter names
	 */
	private String[] mOperationParamList = new String[] {};

	/**
	 * The WSDL URL parameter
	 */
	public static final String PARAM_WSDL_URL = "wsdlUrl";

	/**
	 * The name of the SOAP operation as described in the WSDL file
	 */
	public static final String PARAM_SOAP_OPERATION = "soapOperation";

	/**
	 * The list of fully qualified Java classes generated by WSDL2Java from the
	 * WSDL file
	 */
	public static final String PARAM_COMPLEX_TYPES = "complexTypes";

	/**
	 * The list of ordered SOAP operation parameter names
	 */
	public static final String PARAM_OPERATION_PARAM_LIST = "operationParamList";

	/**
	 * The operation style of the document
	 */
	private static final String OPERATION_STYLE_DOCUMENT = "document";

	/**
	 * The name of the output attribute
	 */
	private static final String OUT_ATTR_PARAMS = "return";

	/**
	 * NLS Property set holding name-value pairs for the resource.
	 */
	private static ResourceHash sResHash = null;

	static {
		sResHash = new ResourceHash(PROPERTIES_FILE);
	}

	/**
	 * Initializes the function component by using the parameters in the Config
	 * Tab.
	 *
	 * @param obj
	 *            not used in this method
	 * @throws Exception
	 */
	public void initialize(Object obj) throws Exception {

		mWsdlUrl = (String) getParam(PARAM_WSDL_URL);
		if (getDebug()) {
			debug(sResHash.getString(
					"FC.AXISEASYINVOKESOAPWS.PARAMETER.WSDL.URL",
					new Object[] { mWsdlUrl }));
		}
		if (mWsdlUrl == null) {
			throw new Exception(
					sResHash
							.getString("FC.AXISEASYINVOKESOAPWS.PARAMETER.WSDL.URL.EMPTY"));
		}
		mSoapOperation = (String) getParam(PARAM_SOAP_OPERATION);
		if (getDebug()) {
			debug(sResHash.getString(
					"FC.AXISEASYINVOKESOAPWS.PARAMETER.SOAP.OPERATION",
					new Object[] { mSoapOperation }));
		}
		if (mSoapOperation == null) {
			throw new Exception(
					sResHash
							.getString("FC.AXISEASYINVOKESOAPWS.PARAMETER.SOAP.OPERATION.EMPTY"));
		}
		String complexTypes = (String) getParam(PARAM_COMPLEX_TYPES);
		if (getDebug()) {
			debug(sResHash.getString(
					"FC.AXISEASYINVOKESOAPWS.PARAMETER.COMPLEX.TYPES",
					new Object[] { complexTypes }));
		}
		mClasses = WebServiceClient.convertComplexTypeList(complexTypes);
		String paramList = (String) getParam(PARAM_OPERATION_PARAM_LIST);
		if (getDebug()) {

			debug(sResHash.getString(
					"FC.AXISEASYINVOKESOAPWS.PARAMETER.OPERATION.PARAM.LIST",
					new Object[] { paramList }));
		}
		if (paramList != null) {
			mOperationParamList = WebServiceClient
					.convertOperationParams(paramList);
		}

		String username = (String) getParam("Username");
		String password = (String) getParam("Password");

		String wsdlAuthUser = (String) getParam("wsdlAuthUser");
		String wsdlAuthPass = (String) getParam("wsdlAuthPass");

		if (wsdlAuthUser != null && wsdlAuthUser.trim().length() > 0) {
			// Create WebServiceClient with authentication for WSDL
			mClient = WebServiceClient.createWebServiceClient(mWsdlUrl, null, null, 
					mSoapOperation, wsdlAuthUser, wsdlAuthPass, logger);
		} else {
			// Create WebServiceClient without authentication
			mClient = WebServiceClient.createWebServiceClient(mWsdlUrl, null, null, 
					mSoapOperation, logger);
		}

		// Get WSDL data
		mWsdlData = WSDLData.getWsdlData(mWsdlUrl, mSoapOperation);

		// Set style
		String operationStyle = mWsdlData.getStyle();
		if (operationStyle != null && operationStyle.equals(OPERATION_STYLE_DOCUMENT)) {
			mClient.setStyle("document");
		}

		// Set username/password if provided
		if (username != null && username.length() > 0) {
			Options options = mClient.getOptions();
			options.setUserName(username);
			options.setPassword(password);
		}

		String timeOut = (String) getParam("timeOut");
		if (timeOut != null && timeOut.trim().length() > 0) {
			try {
				NumberFormat nf = NumberFormat.getInstance();
				Number num = nf.parse(timeOut);
				int time = (int) (num.doubleValue() * 1000);

				if (time == 0) {
					logmsg(sResHash
							.getString("FC.AXISEASYINVOKESOAPWS.WAIT.FOREVER"));
				}

				mClient.getOptions().setTimeOutInMilliSeconds(time);
			} catch (ParseException pe) {
				logmsg(sResHash.getString(
						"FC.AXISEASYINVOKESOAPWS.INVALID.TIMEOUT.VALUE",
						new Object[] { timeOut }));
			}
		}

		super.initialize(null);
	}

	/**
	 * Provides a relatively simple way of invoking SOAP over HTTP web services.
	 * <p>
	 * If this FC is passed a Java Object array (Object[]) then it passes to the
	 * SOAP operation each Java Object from this array in the order in which the
	 * Objects are stored in the array. If this FC is passed an Entry, then the
	 * order and values of the parameters passed to the SOAP operation are
	 * determined by the value of the "SOAP Operation" FC parameter.
	 * <p>
	 * If an Entry is passed to this FC and the SOAP response message returned
	 * by the server is not a SOAP Fault message and there is a single output
	 * parameter of the "SOAP Operation", then this FC returns the parameter in
	 * the "return" Attribute.
	 * <p>
	 * If an Entry is passed to this FC and the SOAP response message returned
	 * by the server is not a SOAP Fault message and there are several output
	 * parameters of the SOAP Operation, then this FC returns the output
	 * parameters in Entry Attributes, whose names match the names of the SOAP
	 * Operation output parameters.
	 * <p>
	 * If an Object[] with the input parameters of the SOAP operation is passed
	 * to this FC and the SOAP response message returned by the server is not a
	 * SOAP Fault message, the result is of type Object[], where the first
	 * element is the return value of the SOAP operation (null if the operation
	 * is void) and the rest are the output parameters of the operation.
	 * Object[] -> AxisEasyInvokeSoapWS FC -> Object[] or Entry ->
	 * AxisEasyInvokeSoapWS FC -> Entry
	 *
	 * @param obj
	 * @return a Java object
	 * @throws Exception
	 */
	public Object perform(Object obj) throws Exception {
		verifyInitialized();

		Object[] params = null;
		if (obj instanceof Entry) {
			params = new Object[mOperationParamList.length];
			Entry e = (Entry) obj;
			for (int i = 0; i < mOperationParamList.length; i++) {
				Attribute param = e.getAttribute(mOperationParamList[i]);
				if (param != null) {
					params[i] = param.getValue(0);
				} else {
					throw new Exception(sResHash.getString(
							"FC.AXISEASYINVOKESOAPWS.ENTRY.ATTRIBUTE.MISSING",
							mOperationParamList[i]));
				}
			}
		} else if (obj instanceof Object[]) {
			params = (Object[]) obj;
		} else {
			throw new Exception(sResHash.getString(
					"FC.AXISEASYINVOKESOAPWS.EXPECTED.EITHER.ENTRY.OR.OBJECT",
					new Object[] { obj.getClass() }));
		}

		Object resObj = null;
		try {
			if (getDebug()) {
				debug(sResHash
						.getString("FC.AXISEASYINVOKESOAPWS.ABOUT.TO.CALL.WEB.SERVICE"));
			}
			
			// Register complex types
			if (mClasses != null && !mClasses.isEmpty()) {
				for (Class<?> cls : mClasses) {
					mClient.registerClassMapping(cls);
				}
			}
			
			// Invoke the web service
			resObj = mClient.invoke(params);

			logmsg(sResHash.getString("FC.AXISEASYINVOKESOAPWS.WSSUCCESS"));

			if (getDebug()) {
				debug(sResHash.getString(
						"FC.AXISEASYINVOKESOAPWS.SOAP.RESPONSE.JAVA.OBJECT",
						resObj));
			}
		} catch (AxisFault axisFault) {
			Throwable throwable = axisFault.getCause();
			if (throwable == null) {
				// in this case axisFault represents a SOAP Fault message
				// received from the web service

				String funcmsg = sResHash
						.getString(
								"FC.AXISEASYINVOKESOAPWS.THIS.WEB.SERVICE.RETURNED.A.SOAP.FAULT",
								axisFault.getMessage());
				logmsg(funcmsg);

				throw new Exception(funcmsg, axisFault);
			} else {
				// in this case axisFault represents an Exception which has
				// occurred on the local machine,
				// and *not* a SOAP Fault message received from the web service

				String funcmsg = sResHash
						.getString(
								"FC.AXISEASYINVOKESOAPWS.THE.INVOCATION.OF.THIS.WEB.SERVICE.FAILED",
								new Object[] { throwable.getClass().getName(),
										throwable.getMessage() });
				logmsg(funcmsg);

				throw new Exception(funcmsg);
			}
		}

		Object returnObject = null;
		if (obj instanceof Entry) {
			Entry entry = new Entry();
			entry.addAttributeValue(OUT_ATTR_PARAMS, resObj);
			HashMap<QName, Object> outParams = mClient.getOutParams();
			java.util.Iterator<Map.Entry<QName, Object>> iterParams = outParams.entrySet().iterator();
			while (iterParams.hasNext()) {
				Map.Entry<QName, Object> mpEntry = iterParams.next();
				QName paramName = mpEntry.getKey();
				Object paramValue = mpEntry.getValue();
				if (getDebug()) {
					debug(sResHash
							.getString(
									"FC.AXISEASYINVOKESOAPWS.ADDITIONAL.OUTPUT.PARAMETER.NAME.VALUE",
									new Object[] { paramName, paramValue }));
				}
				entry.addAttributeValue(paramName.getLocalPart(), paramValue);
			}
			returnObject = entry;
		} else {
			HashMap<QName, Object> outParams = mClient.getOutParams();
			Object[] returnObjArray;
			int i = 0;

			if (resObj != null) {
				/*
				 * make sure that there is enough space for the output
				 * parameters including the result object of the invocation if
				 * it is not null
				 */
				returnObjArray = new Object[outParams.size() + 1];
				returnObjArray[i++] = resObj;
			} else {
				returnObjArray = new Object[outParams.size()];
			}

			java.util.Iterator<Map.Entry<QName, Object>> iterParams = outParams.entrySet().iterator();
			while (iterParams.hasNext() && (i < outParams.size())) {
				Map.Entry<QName, Object> mpEntry = iterParams.next();
				QName paramName = mpEntry.getKey();
				Object paramValue = mpEntry.getValue();
				if (getDebug()) {
					debug(sResHash
							.getString(
									"FC.AXISEASYINVOKESOAPWS.ADDITIONAL.OUTPUT.PARAMETER.NAME.VALUE.2",
									new Object[] { paramName, paramValue }));
				}
				returnObjArray[i++] = paramValue;
			}
			returnObject = returnObjArray;
		}

		return returnObject;
	}

	/**
	 * Version information.
	 *
	 * @return version information
	 */
	public String getVersion() {
		return "3.0-di7.1.1 1.29 2025/10/08";
	}
	
	/**
	 * Cleanup resources when this function component is no longer needed.
	 */
	@Override
	public void terminate() throws Exception {
		if (mClient != null) {
			try {
				mClient.close();
				mClient = null;
			} catch (Exception e) {
				if (logger != null) {
					logger.logerror("Error closing WebServiceClient", e);
				}
			}
		}
		super.terminate();
	}
}
