/*
 * Copyright IBM Corp. 2025
 *
 * SPDX-License-Identifier: Apache-2.0
 */
package com.ibm.di.fc.webservice;

import java.util.Vector;

import javax.xml.namespace.QName;

import org.apache.axis2.AxisFault;

import com.ibm.di.entry.Attribute;
import com.ibm.di.entry.Entry;
import com.ibm.di.fc.Function;
import com.ibm.di.fc.webservice.axis2.WSDLData;
import com.ibm.di.fc.webservice.axis2.WSDLLocator;
import com.ibm.di.fc.webservice.axis2.WebServiceClient;
import com.ibm.di.server.ResourceHash;

/**
 * The Axis Java-to-Soap Function Component (FC) is part of the TDI Web Services
 * suite. This component can be used both on the web service client and on the
 * web service server side. This component receives an Entry or a Java object
 * and produces the SOAP request (when on the client) or response (when on the
 * server) message. It will provide the whole SOAP message, as well as
 * separately the SOAP Header and the SOAP Body to facilitate processing and
 * customization.The component supports both RPC and Document style.
 * 
 */
public class AxisJavaToSoap extends Function {
	/**
	 * Copyright.
	 */
	@SuppressWarnings("unused")
	private static final String COPYRIGHT = com.ibm.di.server.CopyRight.OBJECT_CODE;

	/**
	 * The name of the properties file
	 */
	private static final String PROPERTIES_FILE = "axisjavatosoapfc";

	/**
	 * The WSDL URL
	 */
	private String mWsdlUrl = null;

	/**
	 * The SOAP Operation
	 */
	private String mSoapOperation = null;

	/**
	 * The data the WSDL contains
	 */
	private WSDLData mWsdlData = null;

	/**
	 * The class which is used to call a webservice
	 */
	private WebServiceClient mClient = null;

	/**
	 * The XML return type - DOMElement or String
	 */
	private String mReturnXMLType = null;

	/**
	 * The return attributes
	 */
	private String mReturnAttr = null;

	/**
	 * A Vector with the classes which are given in the "complexTypes"
	 * parameter.
	 */
	private Vector<Class<?>> mClasses = null;

	/**
	 * specifies whether this Function Component handles a SOAP request or a
	 * SOAP response
	 */
	private String mMode = null;

	/**
	 * The list of ordered SOAP operation parameter names
	 */
	private String[] mOperationParamList = new String[] {};

	/**
	 * Whether is in request mode
	 */
	private boolean mIsRequest = true;

	/**
	 * The WSDL URL parameter
	 */
	public static final String PARAM_WSDL_URL = "wsdlUrl";

	/**
	 * The name of the SOAP operation as described in the WSDL file
	 */
	public static final String PARAM_SOAP_OPERATION = "soapOperation";

	/**
	 * The XML return type - DOMElement or String
	 */
	public static final String PARAM_RETURN_XML_TYPE = "returnXMLType";

	/**
	 * The list of fully qualified Java classes generated by WSDL2Java from the
	 * WSDL file
	 */
	public static final String PARAM_COMPLEX_TYPES = "complexTypes";

	/**
	 * specifies whether this Function Component handles a SOAP request or a
	 * SOAP response
	 */
	public static final String PARAM_MODE = "mode";

	/**
	 * The list of ordered SOAP operation parameter names
	 */
	public static final String PARAM_OPERATION_PARAM_LIST = "operationParamList";

	/**
	 * If checked the generated SOAP message will use multi-refs.
	 */
	public static final String PARAM_USE_MULTI_REFS = "useMultiRefs";

	/**
	 * The value of the request mode
	 */
	public static final String MODE_REQUEST = "Request";

	/**
	 * The value of the response attribute
	 */
	public static final String MODE_RESPONSE = "Response";

	/**
	 * The name of the SOAP Fault attribute
	 */
	private static final String ATTR_SOAP_FAULT = "soapFault";

	/**
	 * The name of the returnXMLType attribute when String is chosen
	 */
	private static final String OUT_ATTR_XML_STRING = "xmlString";

	/**
	 * The name of the returnXMLType attribute when DOMElement is chosen
	 */
	private static final String OUT_ATTR_XML_DOM = "xmlDOMElement";

	/**
	 * The name of the returnXMLType attribute when String is chosen
	 */
	public static final String RETURN_XML_STRING = "String";

	/**
	 * The name of the returnXMLType attribute when DOMElement is chosen
	 */
	public static final String RETURN_XML_DOM = "DOMElement";

	/**
	 * The operation style of the document
	 */
	private static final String OPERATION_STYLE_DOCUMENT = "document";

	/**
	 * NLS Property set holding name-value pairs for the resource.
	 */
	private static ResourceHash sResHash = null;

	static {
		sResHash = new ResourceHash(PROPERTIES_FILE);
	}

	/**
	 * Initializes the function component by using the parameters in the Config
	 * Tab.
	 * 
	 * @param obj
	 *            not used in this method
	 */
	@Override
	public void initialize(Object obj) throws Exception {

		mWsdlUrl = (String) getParam(PARAM_WSDL_URL);

		if (mWsdlUrl == null) {
			throw new Exception(sResHash
					.getString("FC.AXISJAVATOSOAP.PARAMETER.WSDL.URL.EMPTY"));
		} else {
			if (getDebug()) {
				debug(sResHash.getString(
						"FC.AXISJAVATOSOAP.PARAMETER.WSDL.URL",
						new Object[] { mWsdlUrl }));
			}
		}

		mSoapOperation = (String) getParam(PARAM_SOAP_OPERATION);

		if (mSoapOperation == null) {
			throw new Exception(
					sResHash
							.getString("FC.AXISJAVATOSOAP.PARAMETER.SOAP.OPERATION.EMPTY"));
		} else {
			if (getDebug()) {
				debug(sResHash.getString(
						"FC.AXISJAVATOSOAP.PARAMETER.SOAP.OPERATION",
						new Object[] { mSoapOperation }));
			}
		}

		String complexTypes = (String) getParam(PARAM_COMPLEX_TYPES);

		if (getDebug()) {
			debug(sResHash.getString(
					"FC.AXISJAVATOSOAP.PARAMETER.COMPLEX.TYPES", new Object[] {
							PARAM_COMPLEX_TYPES, complexTypes }));
		}
		mClasses = WebServiceClient.convertComplexTypeList(complexTypes);

		mMode = (String) getParam(PARAM_MODE);

		if (mMode == null) {
			throw new Exception(sResHash
					.getString("FC.AXISJAVATOSOAP.PARAMETER.MODE.EMPTY"));
		} else {
			if (getDebug()) {
				debug(sResHash.getString("FC.AXISJAVATOSOAP.PARAMETER.MODE",
						new Object[] { mMode }));
			}
		}

		if (mMode.equals(MODE_REQUEST)) {
			mIsRequest = true;
		} else if (mMode.equals(MODE_RESPONSE)) {
			mIsRequest = false;
		} else {
			throw new Exception(sResHash.getString(
					"FC.AXISJAVATOSOAP.PARAMETER.MODE.INVALID",
					new Object[] { mMode }));
		}

		String paramList = (String) getParam(PARAM_OPERATION_PARAM_LIST);
		if (getDebug()) {
			debug(sResHash.getString(
					"FC.AXISJAVATOSOAP.PARAMETER.OPERATION.PARAM.LIST",
					new Object[] { paramList }));
		}
		if (paramList != null) {
			mOperationParamList = WebServiceClient
					.convertOperationParams(paramList);
		}
		mReturnXMLType = (String) getParam(PARAM_RETURN_XML_TYPE);

		if (getDebug()) {
			debug(sResHash.getString(
					"FC.AXISJAVATOSOAP.PARAMETER.RETURN.XML.TYPE",
					new Object[] { mReturnXMLType }));
		}
		if (mReturnXMLType != null) {
			mReturnXMLType = mReturnXMLType.trim();
		}
		if (mReturnXMLType == null
				|| (!mReturnXMLType.equalsIgnoreCase(RETURN_XML_DOM) && !mReturnXMLType
						.equalsIgnoreCase(RETURN_XML_STRING))) {
			// todo: log error
			throw new Exception(sResHash.getString(
					"FC.AXISJAVATOSOAP.INVALID.VALUE.FOR.RETURN.XML.TYPE",
					new Object[] { mReturnXMLType }));
		}

		if (mReturnXMLType.equalsIgnoreCase(RETURN_XML_DOM)) {
			mReturnAttr = OUT_ATTR_XML_DOM;
		} else if (mReturnXMLType.equalsIgnoreCase(RETURN_XML_STRING)) {
			mReturnAttr = OUT_ATTR_XML_STRING;
		}

		if (getDebug()) {
			debug(sResHash.getString(
					"FC.AXISJAVATOSOAP.GENERATED.SOAP.MESSAGE.ATTRIBUTE",
					mReturnAttr));
		}

		String wsdlAuthUser = (String) getParam("wsdlAuthUser");
		String wsdlAuthPass = (String) getParam("wsdlAuthPass");

		if (wsdlAuthUser != null && wsdlAuthUser.trim().length() > 0) {
			// Create WebServiceClient with authentication
			mClient = WebServiceClient.createWebServiceClient(mWsdlUrl, null, null, 
					mSoapOperation, wsdlAuthUser, wsdlAuthPass, logger);
		} else {
			// Create WebServiceClient without authentication
			mClient = WebServiceClient.createWebServiceClient(mWsdlUrl, null, null, 
					mSoapOperation, logger);
		}

		// Get WSDL data
		mWsdlData = WSDLData.getWsdlData(mWsdlUrl, mSoapOperation);

		// Set style
		String operationStyle = mWsdlData.getStyle();
		if (operationStyle != null && operationStyle.equals(OPERATION_STYLE_DOCUMENT)) {
			mClient.setStyle("document");
		}

		// Set use multi-refs
		String useMultiRefs = (String) getParam(PARAM_USE_MULTI_REFS);
		if (useMultiRefs != null) {
			Boolean bMultiRefs = Boolean.valueOf(useMultiRefs);
			// Note: Axis2 doesn't have direct equivalent for PROP_DOMULTIREFS
			// We'll set it as a custom property
			mClient.getOptions().setProperty("multiRefs", bMultiRefs);

			if (getDebug()) {
				debug(sResHash.getString(
						"FC.AXISJAVATOSOAP.AXIS.HREF.MULTIREF.IS.TURNED", ""
								+ bMultiRefs.booleanValue()));
			}
		}

		super.initialize(null);
	}

	/**
	 * Generates a SOAP message from the given Java code.
	 * 
	 * If this FC is passed (a) an Entry with a "soapFault" Attribute, whose
	 * value is an object of type org.apache.axis2.AxisFault, or (b) a Java
	 * object of type org.apache.axis2.AxisFault, then the FC generates a SOAP
	 * Fault message containing the information stored in the passed AxisFault
	 * object.
	 * 
	 * If the value of the Return XML as FC parameter is String then the SOAP
	 * response message is stored in the "xmlString" Attribute, if an Entry was
	 * passed to the FC. However, if the value of the "Return XML as" FC
	 * parameter is DOMElement then the generated SOAP message is stored in the
	 * "xmlDOMElement" Attribute, if an Entry was passed to the FC. If a Java
	 * Object array (Object[]) was passed to this FC, then the return value of
	 * the FC is either a java.lang.String object (when the value of the "Return
	 * XML as" FC parameter is String) or an org.w3c.dom.Element object (when
	 * the value is DOMElement).
	 * 
	 * @param obj
	 * @return a Java object
	 * @throws Exception
	 */
	public Object perform(Object obj) throws Exception {
		verifyInitialized();

		Object[] params = null;
		if (obj instanceof Entry) {
			Entry entry = (Entry) obj;
			Attribute attrSoapFault = entry.getAttribute(ATTR_SOAP_FAULT);
			if (attrSoapFault != null) {
				Object fault = attrSoapFault.getValue(0);
				if (fault instanceof AxisFault) {
					AxisFault axisFault = (AxisFault) fault;
					params = new Object[] { axisFault };
				} else {
					throw new Exception(
							sResHash
									.getString(
											"FC.AXISJAVATOSOAP.THE.VALUE.OF.THE.ATTR.SOAP.FAULT",
											new Object[] { fault.getClass()
													.getName() }));
				}
			} else {
				// For RESPONSE mode (server-side), reorder parameters according to WSDL
				if (!mIsRequest && mWsdlData != null) {
					java.util.List<String> wsdlOutputParams = mWsdlData.getOutputParameterNames();
					if (wsdlOutputParams != null && !wsdlOutputParams.isEmpty()) {
						// Use WSDL order for output parameters
						params = new Object[wsdlOutputParams.size()];
						for (int i = 0; i < wsdlOutputParams.size(); i++) {
							String paramName = wsdlOutputParams.get(i);
							Attribute param = entry.getAttribute(paramName);
							if (param != null) {
								params[i] = param.getValue(0);
							} else {
								throw new Exception(sResHash.getString(
										"FC.AXISJAVATOSOAP.ENTRY.ATTRIBUTE.MISSING",
										paramName));
							}
						}
					} else {
						// Fallback to configured order if WSDL data not available
						params = new Object[mOperationParamList.length];
						for (int i = 0; i < mOperationParamList.length; i++) {
							Attribute param = entry
									.getAttribute(mOperationParamList[i]);
							if (param != null) {
								params[i] = param.getValue(0);
							} else {
								throw new Exception(sResHash.getString(
										"FC.AXISJAVATOSOAP.ENTRY.ATTRIBUTE.MISSING",
										mOperationParamList[i]));
							}
						}
					}
				} else {
					// For REQUEST mode (client-side), use configured order
					params = new Object[mOperationParamList.length];
					for (int i = 0; i < mOperationParamList.length; i++) {
						Attribute param = entry
								.getAttribute(mOperationParamList[i]);
						if (param != null) {
							params[i] = param.getValue(0);
						} else {
							throw new Exception(sResHash.getString(
									"FC.AXISJAVATOSOAP.ENTRY.ATTRIBUTE.MISSING",
									mOperationParamList[i]));
						}
					}
				}
			}
		} else if (obj instanceof Object[]) {
			params = (Object[]) obj;
		} else {
			throw new Exception(sResHash.getString(
					"FC.AXISJAVATOSOAP.EXPECTED.EITHER.ENTRY.OR.OBJECT",
					new Object[] { obj.getClass() }));
		}

		if (getDebug()) {
			debug(sResHash
					.getString("FC.AXISJAVATOSOAP.ABOUT.TO.GENERATE.A.SOAP.MESSAGE"));
			debug(sResHash.getString("FC.AXISJAVATOSOAP.TARGET.NAMESPACE",
					mWsdlData.getTargetNamespace()));
			debug(sResHash.getString("FC.AXISJAVATOSOAP.SOAP.OPERATION.IS",
					mSoapOperation));
			debug(sResHash.getString("FC.AXISJAVATOSOAP.COMPLEX.TYPES.ARE",
					mClasses));
			debug(sResHash.getString(
					"FC.AXISJAVATOSOAP.SOAP.OPERATION.PARAMETERS.ARE",
					WebServiceClient.objectArrayToString(params)));
			debug(sResHash.getString("FC.AXISJAVATOSOAP.THIS.IS.A.REQ.RES",
					(mIsRequest ? "request" : "response")));
		}

		String soapMsg = mClient.generateSOAP(mClasses, params, mIsRequest);

		logmsg(sResHash.getString("FC.AXISJAVATOSOAP.GENERATE.SOAP"));

		if (getDebug()) {
			debug(sResHash.getString(
					"FC.AXISJAVATOSOAP.GENERATED.SOAP.MESSAGE", soapMsg));
		}

		// For RESPONSE mode (server-side), extract only the body content
		// to match what WSReceiverServerConnector expects to send back
		String finalSoapMsg = soapMsg;
		if (!mIsRequest) {
			// Server-side response: extract body content only
			try {
				finalSoapMsg = extractSoapBodyContent(soapMsg);
				if (getDebug()) {
					debug("Extracted SOAP body content for server response: " + finalSoapMsg);
				}
			} catch (Exception e) {
				// If extraction fails, use the full SOAP message
				if (getDebug()) {
					debug("Failed to extract body content, using full SOAP: " + e.getMessage());
				}
			}
		}

		Object result = null;
		if (mReturnXMLType.equalsIgnoreCase(RETURN_XML_DOM)) {
			result = WebServiceClient.getAsDOM(finalSoapMsg);
		} else if (mReturnXMLType.equalsIgnoreCase(RETURN_XML_STRING)) {
			result = finalSoapMsg;
		}

		Object returnObj = null;
		if (obj instanceof Entry) {
			Entry resultEntry = new Entry();
			resultEntry.addAttributeValue(mReturnAttr, result);
			returnObj = resultEntry;
		} else {
			returnObj = result;
		}

		return returnObj;
	}

	/**
	 * Extract only the body content from a complete SOAP envelope.
	 * This is used for server-side responses to avoid nesting issues.
	 *
	 * @param soapEnvelope The complete SOAP envelope as a string
	 * @return The body content only (without Envelope and Body tags)
	 * @throws Exception if extraction fails
	 */
	private String extractSoapBodyContent(String soapEnvelope) throws Exception {
		try {
			// Parse the SOAP envelope
			javax.xml.parsers.DocumentBuilderFactory factory =
				javax.xml.parsers.DocumentBuilderFactory.newInstance();
			factory.setNamespaceAware(true);
			javax.xml.parsers.DocumentBuilder builder = factory.newDocumentBuilder();
			
			java.io.ByteArrayInputStream input =
				new java.io.ByteArrayInputStream(soapEnvelope.getBytes("UTF-8"));
			org.w3c.dom.Document doc = builder.parse(input);
			
			// Find the Body element
			org.w3c.dom.NodeList bodyList = doc.getElementsByTagNameNS("*", "Body");
			if (bodyList.getLength() == 0) {
				// Try without namespace
				bodyList = doc.getElementsByTagName("Body");
			}
			
			if (bodyList.getLength() > 0) {
				org.w3c.dom.Element bodyElement = (org.w3c.dom.Element) bodyList.item(0);
				
				// Get the first child of Body (the operation response element)
				org.w3c.dom.NodeList children = bodyElement.getChildNodes();
				for (int i = 0; i < children.getLength(); i++) {
					org.w3c.dom.Node child = children.item(i);
					if (child.getNodeType() == org.w3c.dom.Node.ELEMENT_NODE) {
						// Convert this element to string
						javax.xml.transform.TransformerFactory tf =
							javax.xml.transform.TransformerFactory.newInstance();
						javax.xml.transform.Transformer transformer = tf.newTransformer();
						transformer.setOutputProperty(javax.xml.transform.OutputKeys.OMIT_XML_DECLARATION, "yes");
						
						java.io.StringWriter writer = new java.io.StringWriter();
						transformer.transform(
							new javax.xml.transform.dom.DOMSource(child),
							new javax.xml.transform.stream.StreamResult(writer));
						
						return writer.toString();
					}
				}
			}
			
			// If we couldn't extract, return the original
			return soapEnvelope;
		} catch (Exception e) {
			throw new Exception("Failed to extract SOAP body content: " + e.getMessage(), e);
		}
	}

	/**
	 * This method is analogous to the 'registerTypeMapping' method in
	 * org.apache.axis2.client.ServiceClient. It can be used for configuring
	 * serialization/deserialization of Java types.
	 *
	 * @param javaType
	 *            java type to handle
	 * @param xmlType
	 *            XML mapping
	 * @param serializerFactory
	 *            a factory of the serializers
	 * @param deserializerFactory
	 *            a factory of deserializers
	 */
	public void registerTypeMapping(Class<?> javaType, QName xmlType,
			Object serializerFactory, Object deserializerFactory) {
		mClient.registerCustomTypeMapping(javaType, xmlType, serializerFactory,
				deserializerFactory);

		if (getDebug()) {
			debug(sResHash.getString("FC.AXISJAVATOSOAP.REGISTER.TYPE.MAPPING",
					new Object[] { javaType, xmlType, serializerFactory,
							deserializerFactory }));
		}
	}

	/**
	 * Version information.
	 * 
	 * @return version information
	 */
	public String getVersion() {
		return "3.0-di7.1.1 1.31 2025/10/08";
	}
	
	/**
	 * Cleanup resources when this function component is no longer needed.
	 */
	@Override
	public void terminate() throws Exception {
		if (mClient != null) {
			try {
				mClient.close();
				mClient = null;
			} catch (Exception e) {
				if (logger != null) {
					logger.logerror("Error closing WebServiceClient", e);
				}
			}
		}
		super.terminate();
	}
}