CONN_DESC = A Server Connector acting as an SNMP Agent
SNMP_PORT_DESC = The UDP port on which the Connector receives incoming SNMP request packets and from which sends SNMP response packets. The standard port for SNMP GET/SET operations is 161.
SNMP_PORT_LABEL = UDP Port
SNMP_COMMUNITY_DESC = If set, the Connector discards all messages not matching this community string. If blank, the Connector allows all community strings.
SNMP_COMMUNITY_LABEL = Verify Community
CONN_TITLE = SNMP Server Connector
Advanced = Advanced
