# this is a sample virtdir properties file.
#properties for the VirtDir 
VIRTDIR_PORT:389
VIRTDIR_SSL_ON:false
VIRTDIR_CHAR_ENC:UTF-8
VIRTDIR_BIN_ATTRS:
VIRTDIT_COMMENTS:
VIRTDIR_DETAIL_LOG:false

# properties used to set the LDAP Connector params
CONN_1:IDSConnect
LDAP_URL_1:<ldapurl>
SEARCH_BASE_1:O=IBM,C=US
SEARCH_FLT_1:objectclass=*
SEARCH_SCOPE_1:subtree
SEARCH_TIMELIM_1:0
SIZE_LIM_1:0
PAGE_SIZE_1:0
AUTH_MECH_1:simple
USE_SSL_1:false
REF_1:follow
BINDDN_1:<binddn>
BINDPASSWD_1:<passwd>

# properties used for the LDAP connector params
CONN_2:ADConnect
LDAP_URL_2:<ldapurl>
SEARCH_BASE_2:o=ibm,c=us
SEARCH_FLT_2:objectclass=*
SEARCH_SCOPE_2:subtree
SEARCH_TIMELIM_2:0
SIZE_LIM_2:0
PAGE_SIZE_2:0
AUTH_MECH_2:simple
USE_SSL_2:false
REF_2:follow
BINDDN_2:<binddn>	
BINDPASSWD_2:<passwd>


# properties used for the MemQ connector params
MEMQ:memQ
QNAME:qName
INSTANCE:
RD_TIMEOUT:0
WATER_MARK:100
PAGE_ENABLE:false
TABLE_NAME:memTbl