CONN_DESC = RDBMS Change Detection Connector
CONN_TITLE = RDBMS Change Detection Connector
source_desc = JDBC URL to the target database.
source_label = JDBC URL
login_desc = Username used to connect to the database.
login_label = Username
pass_label = Password
pass_desc = Password used to connect to the database.
schema_label = Schema
schema_desc = Schema for the 'change table' to be monitored. If blank then the value of Username is applied.
table_desc = Name of the 'change table' to monitor.
table_label = Table Name
table_script_label = Select...
table_script_help = Query server for a list of available tables (may be a big one\!)
driver_desc = JDBC Driver Class
driver_label = JDBC Driver
removep_desc = Check to remove processed rows. This cleanup is done when Iterator State is persisted.
removep_label = Remove Processed Rows
posk_desc = A key (which should be unique) used to keep track of the last change processed by this Connector.
posk_label = Iterator State Key
posk_BTN_LBL = Delete
posk_BTN_HLP = Deletes Iterator State information
poll_desc = The number of seconds between each time the 'change table' is polled looking for new changes.
poll_label = Sleep Interval
startat_label = Start at
startat_desc = Specify a start value in the 'change table'; "EOD" means report only new changes.\nOnly taken into account when the parameter specified by "Iterator State Key" is blank or not found\nin the System Store.
CNUMBER_BTN_LBL = Query
CNUMBER_BTN_HLP = Query server for the range of record in the 'change table'.
maxw_desc = The maximum number of seconds to wait for the next 'change' row (0 \= wait forever).
maxw_label = Timeout
commit_desc = Controls when database transactions are commited. Manual means user must call the commit method
commit_label = Commit
Localized.After.every.database.operation = After every database operation
Localized.On.Connector.close = On Connector close
Localized.Manual = Manual
STATE_KEY_PERSIST_LBL = State Key Persistence
STATE_KEY_PERSIST_DESC = Determines when Iterator State is saved. The recommended setting is End of Cycle.
Localized.After.read = After read
Localized.EOD = EOD
Localized.End.of.cycle = End of cycle
Advanced = Advanced
