# NLS_ENCODING=UTF-8
# NLS_MESSAGEFORMAT_NONE

# #####################################################################
# TRNOTE: The product name "SyncWeave " should not be translated.
# #####################################################################
com.ibm.esupport.client.product.SSCQGF61.feature.description = This feature contains the SyncWeave configuration information for the IBM Support Assistant application.\n \
This feature may be uninstalled.\n \
If upgrades are available, you can upgrade this feature.
  
com.ibm.esupport.client.product.SSCQGF61.feature.license = Feature License Agreement\n\n\
INSTALLATION TERMS:\n\
\n\
By clicking on the "I accept" button, you agree that:\n\
1. IBM product features for the IBM Support Assistant are subject to the terms of the license agreement which accompanied the IBM Support Assistant application\n\
2. You have read and accepted those terms when you obtained the IBM Support Assistant application.\n

com.ibm.esupport.client.product.SSCQGF61.feature.label = SyncWeave
com.ibm.esupport.client.product.SSCQGF61.feature.URL = description/featureDesc.html
# #####################################################################
# TRNOTE: end translation
# #####################################################################

com.ibm.esupport.client.product.SSCQGF61.feature.copyright = \n\n\
Copyright contributors to the SyncWeave project
All Rights Reserved.\n\
US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
