######################################################
# Resource Strings
#
# TRNOTE: 
#
# cmvc_en_version_level=1.13,0,08/04/25,19:01:45 
# Generic (Common) resource strings
######################################################
# NLS_MESSAGEFORMAT_NONE
FIXEDDAILYROLLER_TITLE=Fixed Rolling File Logger
FIXEDDAILYROLLER_FILE_LABEL=File Path
FIXEDDAILYROLLER_FILE_DESC=The path name for the base log file
FIXEDDAILYROLLER_APPEND_LABEL=Append to file
FIXEDDAILYROLLER_APPEND_DESC=Specify true to append to the file when the log is initialized, false to overwrite
FIXEDDAILYROLLER_DATEP_LABEL=Date Pattern
FIXEDDAILYROLLER_DATEP_DESC=Date pattern that logfile names are suffixed with, and which controls when rollover occurs (i.e. when the filename changes).
FIXEDDAILYROLLER_ENCODING_DESC=Character Encoding to be used (e.g. UTF-8).
FIXEDDAILYROLLER_ENCODING_LABEL=Character Encoding
FIXEDDAILYROLLER_NUMBERFILES_LABEL=Number of files:
FIXEDDAILYROLLER_NUMBERFILES_DESC=Set the number of files to roll.
FIXEDDAILYROLLER_SELECT_FILE_LABEL=Select...
FIXEDDAILYROLLER_SELECT_FILE_DESC=Choose the file name to use
MISERVER.FIXEDDAILYROLLINGFILEAPPENDER.CANNOT.DELETE.FILE=FixedDailyRollerFileAppender: Cannot delete file: {0} 