/*
 * Copyright contributors to the SyncWeave project
 *
 * SPDX-License-Identifier: Apache-2.0
 */
package com.ibm.di.api.jmx.mbeans;

import com.ibm.di.api.DIException;
import com.ibm.di.config.interfaces.AssemblyLineConfig;
import com.ibm.di.entry.Entry;
import com.ibm.di.server.TaskStatistics;

/**
 * Represents an AssemblyLine instance.
 */
public interface AssemblyLineMBean extends BaseAdminMBean {

	/**
	 * Returns ObjectName generated from the AssemblyLine's configuration ID,
	 * gotten from the AssemblyLine's configuration instance.
	 * 
	 * @return ObjectName object generated from the AssemblyLine's configuration
	 *         ID.
	 * @throws DIException
	 *             if an error occurs while generating the ObjectName.
	 */
	public javax.management.ObjectName getConfigInstance() throws DIException;

	/**
	 * Returns the name of the AssemblyLine.
	 * 
	 * @return String object representing the AssemblyLine's name.
	 * @throws DIException
	 *             if an error occurs while retrieving the name of the
	 *             AssemblyLine.
	 */
	public String getName() throws DIException;

	/**
	 * Returns the unique code of the AssemblyLine.
	 * 
	 * @return Integer object representing the unique code of the AssemblyLine.
	 * @throws DIException
	 *             if an error occurs while retrieving the unique code of the
	 *             AssemblyLine.
	 */
	public Integer getUniqueCode() throws DIException;

	// AssemblyLine configuration

	/**
	 * Returns configuration information about the AssemblyLine.
	 * 
	 * @return AssemblyLineConfig representing the configuration information of
	 *         the AssemblyLine.
	 * @throws DIException
	 *             if an error occurs while retrieving the configuration
	 *             information of the AssemblyLine.
	 */
	public AssemblyLineConfig getConfig() throws DIException;

	/**
	 * Gets the nullBehavior attribute of the AssemblyLine object
	 * 
	 * @return String object representing the nullBehavior attribute value or
	 *         null if no setting values are available for the AssemblyLine.
	 * @throws DIException
	 *             if an error occurs while getting the nullBehavior attribute.
	 */
	public String getNullBehavior() throws DIException;

	/**
	 * Gets the nullBehaviorValue attribute of the AssemblyLine object.
	 * 
	 * @return String object representing the nullBehaviorValue attribute value
	 *         or null if no setting values are available for the AssemblyLine.
	 * @throws DIException
	 *             if an error occurs while getting the nullBehaviorValue
	 *             attribute.
	 */
	public String getNullBehaviorValue() throws DIException;

	// AssemblyLine statistics

	/**
	 * This method returns the TaskStatistics object for this AssemblyLine.
	 * 
	 * @return The accumulated TaskStatistics object.
	 * @throws DIException
	 *             if an error occurs while getting the AssemblyLine statistics.
	 */
	public TaskStatistics getStatistics() throws DIException;

	// Operations

	/**
	 * Checks if the AssemblyLine is active.
	 * 
	 * @return true if the AssemblyLine's thread is alive, false otherwise.
	 * @throws DIException
	 *             if an error occurs while getting the AssemblyLine state.
	 */
	public Boolean isActive() throws DIException;

	/**
	 * This method returns the result entry object. This object is a copy of the
	 * working entry as it were when the AssemblyLine finished processing the
	 * connectors.
	 * 
	 * @return The last "work" entry object.
	 * @throws DIException
	 *             if an error occurs while getting the result Entry.
	 */
	public Entry getResult() throws DIException;

	/**
	 * Stops the execution of the AssemblyLine.
	 * 
	 * @throws DIException
	 *             if an error occurs while stopping the AssemblyLine.
	 */
	public void stop() throws DIException;

	// System Log

	/**
	 * Returns the fully-qualified path of the log file of the AssemblyLine.
	 * 
	 * @return the fully-qualified log file path.
	 * @throws DIException
	 *             if an error occurs while obtaining AssemblyLine log file
	 *             path.
	 */
	public String getSystemLogFilePath() throws DIException;

	/**
	 * Returns the name of the log file of the AssemblyLine (not prefixed by
	 * folders path).
	 * 
	 * @return the log file name.
	 * @throws DIException
	 *             if an error occurs while obtaining AssemblyLine log file
	 *             name.
	 */
	public String getSystemLogFileName() throws DIException;

	/**
	 * Retrieves the current AssemblyLine's system log.
	 * 
	 * @return the log generated by the AssemblyLine so far.
	 * @throws DIException
	 *             if an error occurs while obtaining AssemblyLine's log.
	 */
	public String getSystemLog() throws DIException;

	/**
	 * Retrieves the last chunk from the current AssemblyLine's system log.
	 * 
	 * @param aLastKilobytes
	 *            specifies in kilobytes the size of the log's last chunk that
	 *            will be read.
	 * 
	 * @return The last chunk of the AssemblyLine's log, generated so far.
	 * @throws DIException
	 *             if an error occurs while obtaining AssemblyLine's log.
	 */
	public String getSystemLogLastChunk(Integer aLastKilobytes)
			throws DIException;

	/**
	 * Returns AssemblyLine GUID. The GUID is a string value that is unique for
	 * each component ever created by a particular TDI Server.
	 * 
	 * @return The AssemblyLine GUID value.
	 * @throws DIException
	 *             if an error occurs while obtaining the GUID.
	 */
	public String getGlobalUniqueID() throws DIException;

	/**
	 * Attach a debugger to the AssemblyLine. You must be admin to execute this
	 * method.
	 * 
	 * @param port
	 *            Port of the debugger.
	 * @param host
	 *            Host of the debugger.
	 * @param onerror
	 *            If true breakpoints are disabled except when there is an
	 *            error.
	 * @throws DIException
	 *             If the AssemblyLine is already being debugged or the
	 *             AssemblyLine cannot connect to the debugger.
	 * @since 7.0
	 */
	public void attachDebugger(int port, String host, boolean onerror)
			throws DIException;

	/**
	 * Detach the current debugger from the AssemblyLine. You must be admin to
	 * execute this method.
	 * 
	 * @param msg
	 *            This object will be sent to the debugger before the detaching
	 *            occurs. Must be serializable. If null, nothing will be sent.
	 * @throws DIException
	 *             If an error occurs while detaching the debugger.
	 * @since 7.0
	 */
	public void detachDebugger(Object msg) throws DIException;
}
