/*
 * Copyright IBM Corp. 2025
 *
 * SPDX-License-Identifier: Apache-2.0
 */
package com.ibm.di.api.jmx.mbeans;

import java.util.Date;

import javax.management.ObjectName;

import com.ibm.di.api.DIException;
import com.ibm.di.config.interfaces.ExternalPropertiesConfig;
import com.ibm.di.config.interfaces.MetamergeConfig;
import com.ibm.di.config.interfaces.PoolDefConfig;
import com.ibm.di.config.interfaces.SchemaConfig;
import com.ibm.di.entry.Entry;
import com.ibm.di.server.TaskCallBlock;

/**
 * ConfigInstance MBean interface that defines public methods exposed through
 * JMX layer.
 * 
 */
public interface ConfigInstanceMBean extends BaseAdminMBean {

	/**
	 * Returns the configuration ID generated by the server.
	 * <p>
	 * <b>Example</b>
	 * </p>
	 * 
	 * <pre>
	 * //for local access to jmx layer use: var jmxMBeanServer = com.ibm.di.api.jmx.JMXAgent.getMBeanServer();
	 * 	
	 * 	var jmxUrl = new 
	 * 		javax.management.remote.JMXServiceURL(&quot;service:jmx:rmi://localhost/jndi/rmi://localhost:1099/jmxconnector&quot;);
	 * 	var jmxConnector = javax.management.remote.JMXConnectorFactory.connect(jmxUrl);
	 * 	var jmxMBeanServer = jmxConnector.getMBeanServerConnection();
	 * 	mBeans = jmxMBeanServer.queryMBeans(null, null).iterator(); 
	 * 	while (mBeans.hasNext()) {
	 * 	var mb = mBeans.next();
	 * 	if (mb.getClassName()==&quot;com.ibm.di.api.jmx.mbeans.ConfigInstance&quot;)
	 * 	break; 
	 * 	}
	 * 
	 * 	var on = mb.getObjectName();
	 * 	var res = jmxMBeanServer.getAttribute(on,&quot;ConfigId&quot;);
	 * 	task.logmsg(&quot;Result &quot;+ res);
	 *  }
	 *  
	 *  Sample output: Result C__Documents and Settings_username_My Documents_TDI_rs.xml
	 * </pre>
	 * 
	 * @return String object representing the configuration ID.
	 * @throws DIException
	 *             if an error occurs while getting the configuration ID.
	 */
	public String getConfigId() throws DIException;

	// access to the Config Instance configuration

	/**
	 * Returns configuration instance representing this configuration.
	 * 
	 * @return MetamergeConfig object representing this configuration.
	 * @throws DIException
	 *             if an error occurs while getting the configuration.
	 */
	public MetamergeConfig getConfiguration() throws DIException;

	/**
	 * Sets given configuration to this configuration.
	 * 
	 * @param aConfiguration
	 *            The new configuration.
	 * @throws DIException
	 *             if an error occurs while setting the configuration.
	 */
	public void setConfiguration(MetamergeConfig aConfiguration)
			throws DIException;

	/**
	 * @deprecated Not supported.
	 */
	@Deprecated
	public void saveConfiguration() throws DIException;

	/**
	 * @deprecated Not supported.
	 */
	@Deprecated
	public void saveConfiguration(Boolean aEncrypt) throws DIException;

	// external properties access

	/**
	 * Returns the external properties of the configuration.
	 * 
	 * @return ExternalPropertiesConfig object representing the configuration's
	 *         external properties.
	 * @throws DIException
	 *             if an error occurs while getting the external properties.
	 * @deprecated use {@link #getTDIProperties()} instead
	 */
	@Deprecated
	public ExternalPropertiesConfig getExternalProperties() throws DIException;

	/**
	 * Returns the ExternalPropertiesConfig object for the named external
	 * properties object.
	 * 
	 * @param aKey
	 *            The external property object name.
	 * @return ExternalPropertiesConfig object representing the configuration's
	 *         external properties specified by the external property object
	 *         name.
	 * @throws DIException
	 *             if an error occurs while getting the external properties.
	 * @deprecated use {@link #getTDIProperties()} instead
	 */
	@Deprecated
	public ExternalPropertiesConfig getExternalProperties(String aKey)
			throws DIException;

	/**
	 * Returns the external properties object names.
	 * 
	 * @return String array each value representing one external property object
	 *         name.
	 * @throws DIException
	 *             if an error occurs while getting the external properties
	 *             names.
	 * @deprecated use {@link #getTDIProperties()} instead
	 */
	@Deprecated
	public String[] getExternalPropertiesKeys() throws DIException;

	/**
	 * @deprecated Not supported.
	 */
	@Deprecated
	public void setExternalProperties(ExternalPropertiesConfig aExPropConfig)
			throws DIException;

	/**
	 * @deprecated Not supported.
	 */
	@Deprecated
	public void setExternalProperties(String aKey,
			ExternalPropertiesConfig aExPropConfig) throws DIException;

	/**
	 * @deprecated Not supported.
	 */
	@Deprecated
	public void saveExternalProperties() throws DIException;

	// quering for available AssemblyLines

	/**
	 * @deprecated Use {@link #getAssemblyLineNames()}.
	 */
	public String[] getAssemblyLinesNames() throws DIException;

	/**
	 * Returns the AssemblyLines' names.
	 * 
	 * @return String array each value representing AssemblyLine name.
	 * @throws DIException
	 *             if an error occurs while getting the AssemblyLines' names.
	 */
	public String[] getAssemblyLineNames() throws DIException;

	/**
	 * Returns the AssemblyLine's input parameters.
	 * 
	 * @param aAssemblyLineName
	 *            the name of the AssemblyLine.
	 * @return SchemaConfig representing the schema input of the AssemblyLine.
	 * @throws DIException
	 *             if an error occurs while getting the AssemblyLine's input
	 *             parameters.
	 */
	public SchemaConfig getAssemblyLineInputParameters(String aAssemblyLineName)
			throws DIException;

	/**
	 * Returns the AssemblyLine's output parameters.
	 * 
	 * @param aAssemblyLineName
	 *            the name of the AssemblyLine.
	 * @return SchemaConfig representing the schema output of the AssemblyLine.
	 * @throws DIException
	 *             if an error occurs while getting the AssemblyLine's output
	 *             parameters.
	 */
	public SchemaConfig getAssemblyLineOutputParameters(String aAssemblyLineName)
			throws DIException;

	// access to running processes within this instance

	/**
	 * Returns the names of currently started AssemblyLines of the configuration
	 * each represented as ObjectName generated from AssemblyLine's name and
	 * unique code.
	 * <p>
	 * <b>Example</b>
	 * </p>
	 * 
	 * <pre>
	 * //for local access to jmx layer use: var jmxMBeanServer = com.ibm.di.api.jmx.JMXAgent.getMBeanServer();
	 * 	
	 * 	var jmxUrl = new 
	 * 		javax.management.remote.JMXServiceURL(&quot;service:jmx:rmi://localhost/jndi/rmi://localhost:1099/jmxconnector&quot;);
	 * 	var jmxConnector = javax.management.remote.JMXConnectorFactory.connect(jmxUrl);
	 * 	var jmxMBeanServer = jmxConnector.getMBeanServerConnection();
	 * 	mBeans = jmxMBeanServer.queryMBeans(null, null).iterator(); 
	 * 	while (mBeans.hasNext()) {
	 * 	var mb = mBeans.next();
	 * 	if (mb.getClassName()==&quot;com.ibm.di.api.jmx.mbeans.ConfigInstance&quot;)
	 * 	break; 
	 * 	}
	 * 
	 * 	var on = mb.getObjectName();
	 * 	var res = jmxMBeanServer.getAttribute(on,&quot;AssemblyLines&quot;);
	 * 	task.logmsg(&quot;Result &quot;+ res);
	 *  }
	 *  
	 *  Sample output: Result ServerAPI:type=AssemblyLine,id=AssemblyLines/test.2
	 * </pre>
	 * 
	 * @return ObjectName array each value representing ObjectName object of an
	 *         AssemblyLine.
	 * @throws DIException
	 *             if an error occurs while getting the AssemblyLines' names.
	 */
	public ObjectName[] getAssemblyLines() throws DIException;

	// AssemblyLine operations

	// simple starting of AssemblyLines

	/**
	 * Starts the specified AssemblyLine asynchronously.
	 * <p>
	 * <b>Example</b>
	 * </p>
	 * 
	 * <pre>
	 * //for local access to jmx layer use: var jmxMBeanServer = com.ibm.di.api.jmx.JMXAgent.getMBeanServer();
	 * 
	 * var jmxUrl = new javax.management.remote.JMXServiceURL(
	 * 		&quot;service:jmx:rmi://localhost/jndi/rmi://localhost:1099/jmxconnector&quot;);
	 * var jmxConnector = javax.management.remote.JMXConnectorFactory.connect(jmxUrl);
	 * var jmxMBeanServer = jmxConnector.getMBeanServerConnection();
	 * mBeans = jmxMBeanServer.queryMBeans(null, null).iterator();
	 * while (mBeans.hasNext()) {
	 * 	var mb = mBeans.next();
	 * 	if (mb.getClassName() == &quot;com.ibm.di.api.jmx.mbeans.ConfigInstance&quot;)
	 * 		break;
	 * }
	 * 
	 * var on = mb.getObjectName();
	 * jmxMBeanServer.invoke(on, &quot;startAssemblyLine&quot;, new Array(&quot;csv2xml&quot;), new Array(
	 * 		&quot;java.lang.String&quot;));
	 * 
	 * </pre>
	 * 
	 * @param aAssemblyLineName
	 *            The name of the AssemblyLine.
	 * @return ObjectName generated from the name and the unique code of the
	 *         given AssemblyLine.
	 * @throws DIException
	 *             if an error occurs when starting the AssemblyLine.
	 */
	public ObjectName startAssemblyLine(String aAssemblyLineName)
			throws DIException;

	/**
	 * Starts the specified AssemblyLine.
	 * <p>
	 * <b>Example</b>
	 * </p>
	 * 
	 * <pre>
	 * //for local access to jmx layer use: var jmxMBeanServer = com.ibm.di.api.jmx.JMXAgent.getMBeanServer();
	 * 
	 * var jmxUrl = new javax.management.remote.JMXServiceURL(
	 * 		&quot;service:jmx:rmi://localhost/jndi/rmi://localhost:1099/jmxconnector&quot;);
	 * var jmxConnector = javax.management.remote.JMXConnectorFactory.connect(jmxUrl);
	 * var jmxMBeanServer = jmxConnector.getMBeanServerConnection();
	 * mBeans = jmxMBeanServer.queryMBeans(null, null).iterator();
	 * while (mBeans.hasNext()) {
	 * 	var mb = mBeans.next();
	 * 	if (mb.getClassName() == &quot;com.ibm.di.api.jmx.mbeans.ConfigInstance&quot;)
	 * 		break;
	 * }
	 * 
	 * var on = mb.getObjectName();
	 * jmxMBeanServer.invoke(on, &quot;startAssemblyLine&quot;, new Array(&quot;csv2xml&quot;,
	 * 		new Boolean(&quot;false&quot;)), new Array(&quot;java.lang.String&quot;,
	 * 		&quot;java.lang.Boolean&quot;));
	 * 
	 * </pre>
	 * 
	 * @param aAssemblyLineName
	 *            The name of the AssemblyLine.
	 * @param aSync
	 *            when <code>true</code> the AssemblyLine is started
	 *            synchronously, when <code>false</code> the AssemblyLine is
	 *            started asynchronously.
	 * @return ObjectName generated from the name and the unique code of the
	 *         given AssemblyLine.
	 * @throws DIException
	 *             if an error occurs when starting the AssemblyLine.
	 */
	public ObjectName startAssemblyLine(String aAssemblyLineName, Boolean aSync)
			throws DIException;

	// start the AssemblyLine with input data

	/**
	 * Starts the specified AssemblyLine with the given input data
	 * asynchronously.
	 * <p>
	 * <b>Example</b>
	 * </p>
	 * 
	 * <pre>
	 * //for local access to jmx layer use: var jmxMBeanServer = com.ibm.di.api.jmx.JMXAgent.getMBeanServer();
	 * 
	 * var jmxUrl = new javax.management.remote.JMXServiceURL(
	 * 		&quot;service:jmx:rmi://localhost/jndi/rmi://localhost:1099/jmxconnector&quot;);
	 * var jmxConnector = javax.management.remote.JMXConnectorFactory.connect(jmxUrl);
	 * var jmxMBeanServer = jmxConnector.getMBeanServerConnection();
	 * mBeans = jmxMBeanServer.queryMBeans(null, null).iterator();
	 * while (mBeans.hasNext()) {
	 * 	var mb = mBeans.next();
	 * 	if (mb.getClassName() == &quot;com.ibm.di.api.jmx.mbeans.ConfigInstance&quot;)
	 * 		break;
	 * }
	 * 
	 * var on = mb.getObjectName();
	 * jmxMBeanServer.invoke(on, &quot;s&quot;, new Array(&quot;csv2xml&quot;, work), new Array(
	 * 		&quot;java.lang.String&quot;, &quot;com.ibm.di.entry.Entry&quot;));
	 * 
	 * </pre>
	 * 
	 * @param aAssemblyLineName
	 *            The name of the AssemblyLine.
	 * @param aInputData
	 *            Initial Work Entry to run the AssemblyLine with.
	 * @return ObjectName generated from the name and the unique code of the
	 *         given AssemblyLine.
	 * @throws DIException
	 *             if an error occurs when starting the AssemblyLine.
	 */
	public ObjectName startAssemblyLine(String aAssemblyLineName,
			Entry aInputData) throws DIException;

	/**
	 * Starts the specified AssemblyLine with the given input data.
	 * <p>
	 * <b>Example</b>
	 * </p>
	 * 
	 * <pre>
	 * //for local access to jmx layer use: var jmxMBeanServer = com.ibm.di.api.jmx.JMXAgent.getMBeanServer();
	 * 
	 * var jmxUrl = new javax.management.remote.JMXServiceURL(
	 * 		&quot;service:jmx:rmi://localhost/jndi/rmi://localhost:1099/jmxconnector&quot;);
	 * var jmxConnector = javax.management.remote.JMXConnectorFactory.connect(jmxUrl);
	 * var jmxMBeanServer = jmxConnector.getMBeanServerConnection();
	 * mBeans = jmxMBeanServer.queryMBeans(null, null).iterator();
	 * while (mBeans.hasNext()) {
	 * 	var mb = mBeans.next();
	 * 	if (mb.getClassName() == &quot;com.ibm.di.api.jmx.mbeans.ConfigInstance&quot;)
	 * 		break;
	 * }
	 * 
	 * jmxMBeanServer.invoke(on, &quot;startAssemblyLine&quot;, new Array(&quot;csv2xml&quot;, work,
	 * 		new Boolean(&quot;true&quot;)), new Array(&quot;java.lang.String&quot;,
	 * 		&quot;com.ibm.di.entry.Entry&quot;, &quot;java.lang.Boolean&quot;));
	 * 
	 * </pre>
	 * 
	 * @param aAssemblyLineName
	 *            The name of the AssemblyLine.
	 * @param aInputData
	 *            Initial Work Entry to run the AssemblyLine with.
	 * @param aSync
	 *            when <code>true</code> the AssemblyLine is started
	 *            synchronously, when <code>false</code> the AssemblyLine is
	 *            started asynchronously.
	 * @return ObjectName generated from the name and the unique code of the
	 *         given AssemblyLine.
	 * @throws DIException
	 *             if an error occurs when starting the AssemblyLine.
	 */
	public ObjectName startAssemblyLine(String aAssemblyLineName,
			Entry aInputData, Boolean aSync) throws DIException;

	// start the AssemblyLine with input data and get results through callbacks

	/**
	 * Starts asynchronously the specified AssemblyLine with the given input
	 * data and results listener.
	 * 
	 * @param aAssemblyLineName
	 *            The name of the AssemblyLine.
	 * @param aInputData
	 *            Initial Work Entry to run the AssemblyLine with.
	 * @param aListener
	 *            A listener for Entries produced by the AssemblyLine.
	 * @param aGetLogs
	 *            when <code>true</code> the AssemblyLineListener delivers log
	 *            messages, when <code>false</code> log messages are not
	 *            delivered.
	 * @return ObjectName generated from the name and the unique code of the
	 *         given AssemblyLine.
	 * @throws DIException
	 *             if an error occurs when starting the AssemblyLine.
	 */
	public ObjectName startAssemblyLine(String aAssemblyLineName,
			Entry aInputData, AssemblyLineListener aListener, Boolean aGetLogs)
			throws DIException;

	/**
	 * Starts the specified AssemblyLine with the given input data and results
	 * listener.
	 * 
	 * @param aAssemblyLineName
	 *            The name of the AssemblyLine.
	 * @param aInputData
	 *            Initial Work Entry to run the AssemblyLine with.
	 * @param aListener
	 *            A listener for Entries produced by the AssemblyLine.
	 * @param aGetLogs
	 *            when <code>true</code> the AssemblyLineListener delivers log
	 *            messages, when <code>false</code> log messages are not
	 *            delivered.
	 * @param aSync
	 *            when <code>true</code> the AssemblyLine is started
	 *            synchronously, when <code>false</code> the AssemblyLine is
	 *            started asynchronously.
	 * @return ObjectName generated from the name and the unique code of the
	 *         given AssemblyLine.
	 * @throws DIException
	 *             if an error occurs when starting the AssemblyLine.
	 */
	public ObjectName startAssemblyLine(String aAssemblyLineName,
			Entry aInputData, AssemblyLineListener aListener, Boolean aGetLogs,
			Boolean aSync) throws DIException;

	/**
	 * Starts the specified AssemblyLine with the given input data and results
	 * listener.
	 * 
	 * @param aAssemblyLineName
	 *            The name of the AssemblyLine.
	 * @param aInputData
	 *            Initial Work Entry to run the AssemblyLine with.
	 * @param aListener
	 *            A listener for Entries produced by the AssemblyLine.
	 * @param aGetLogs
	 *            when <code>true</code> the AssemblyLineListener delivers log
	 *            messages, when <code>false</code> log messages are not
	 *            delivered.
	 * @param aSync
	 *            when <code>true</code> the AssemblyLine is started
	 *            synchronously, when <code>false</code> the AssemblyLine is
	 *            started asynchronously.
	 * @param aGetEntryOnEachCycle
	 *            when <code>true</code> the AssemblyLineListener delivers the
	 *            current entry on each AssemblyLine cycle, when
	 *            <code>false</code> the entries are not delivered.
	 * @return ObjectName generated from the name and the unique code of the
	 *         given AssemblyLine..
	 * @throws DIException
	 *             if an error occurs when starting the AssemblyLine.
	 */
	public ObjectName startAssemblyLine(String aAssemblyLineName,
			Entry aInputData, AssemblyLineListener aListener, Boolean aGetLogs,
			Boolean aSync, Boolean aGetEntryOnEachCycle) throws DIException;
	
	// start the AssemblyLine in manual mode

	/**
	 * Starts the specified AssemblyLine with the given input data in manual
	 * mode.
	 * 
	 * @param aAssemblyLineName
	 *            The name of the AssemblyLine.
	 * @param aInputData
	 *            Initial Work Entry to run the AssemblyLine with.
	 * @return ObjectName generated from the mbean server domain name and the
	 *         key property list of the AssemblyLineHandler of the given
	 *         AssemblyLine.
	 * @throws DIException
	 *             if an error occurs when starting the AssemblyLine.
	 */
	public ObjectName startAssemblyLineManual(String aAssemblyLineName,
			Entry aInputData) throws DIException;

	// the following two methods are for advanced use

	/**
	 * Starts asynchronously the specified AssemblyLine with the given
	 * TaskCallBlock.
	 * 
	 * @param aAssemblyLineName
	 *            The name of the AssemblyLine.
	 * @param aTcb
	 *            The TaskCallBlock object to start the AL with.
	 * @return ObjectName generated from the name and the unique code of the
	 *         given AssemblyLine.
	 * @throws DIException
	 *             if an error occurs when starting the AssemblyLine.
	 */
	public ObjectName startAssemblyLine(String aAssemblyLineName,
			TaskCallBlock aTcb) throws DIException;

	/**
	 * Starts the specified AssemblyLine with the given TaskCallBlock.
	 * 
	 * @param aAssemblyLineName
	 *            The name of the AssemblyLine.
	 * @param aTcb
	 *            The TaskCallBlock object to start the AL with.
	 * @param aSync
	 *            when <code>true</code> the AssemblyLine is started
	 *            synchronously, when <code>false</code> the AssemblyLine is
	 *            started asynchronously.
	 * @return ObjectName generated from the name and the unique code of the
	 *         given AssemblyLine.
	 * @throws DIException
	 *             if an error occurs when starting the AssemblyLine.
	 */
	public ObjectName startAssemblyLine(String aAssemblyLineName,
			TaskCallBlock aTcb, Boolean aSync) throws DIException;

	// Config Instance operations

	/**
	 * Reloads the Config Instance with its current configuration.
	 * 
	 * @throws DIException
	 *             if an error occurs while reloading the server.
	 */
	public void reload() throws DIException;

	/**
	 * Stops the Config Instance.
	 * <p>
	 * <b>Example</b>
	 * </p>
	 * 
	 * <pre>
	 * //for local access to jmx layer use: var jmxMBeanServer = com.ibm.di.api.jmx.JMXAgent.getMBeanServer();
	 * 
	 * var jmxUrl = new javax.management.remote.JMXServiceURL(
	 * 		&quot;service:jmx:rmi://localhost/jndi/rmi://localhost:1099/jmxconnector&quot;);
	 * var jmxConnector = javax.management.remote.JMXConnectorFactory.connect(jmxUrl);
	 * var jmxMBeanServer = jmxConnector.getMBeanServerConnection();
	 * mBeans = jmxMBeanServer.queryMBeans(null, null).iterator();
	 * while (mBeans.hasNext()) {
	 * 	var mb = mBeans.next();
	 * 	if (mb.getClassName() == &quot;com.ibm.di.api.jmx.mbeans.ConfigInstance&quot;)
	 * 		break;
	 * }
	 * 
	 * var on = mb.getObjectName();
	 * jmxMBeanServer.invoke(on, &quot;stop&quot;, null, null);
	 * 
	 * </pre>
	 * 
	 * @throws DIException
	 *             if an error occurs while stopping.
	 */
	public void stop() throws DIException;

	// System Log convenience calls

	// AssemblyLines system log

	/**
	 * Returns the names of all available log files for a given AssemblyLine.
	 * 
	 * @param aALName
	 *            the name of the AssemblyLine.
	 * @return a </code>String</code> array, each of its elements specifying
	 *         the name of a log file.
	 * @throws DIException
	 *             if an error occurs while obtaining AssemblyLine's log file
	 *             names.
	 */
	public String[] getALLogFileNames(String aALName) throws DIException;

	/**
	 * Returns the name of the log file created on the last run of a given
	 * AssemblyLine.
	 * 
	 * @param aALName
	 *            the name of the AssemblyLine.
	 * @return the name of the log file created on the last AssemblyLine's run.
	 * @throws DIException
	 *             if an error occurs while obtaining the log file name.
	 */
	public String getALLastLogFileName(String aALName) throws DIException;

	/**
	 * Given an AssemblyLine name, and a log file name, retrieves the log of
	 * this AssemblyLine, stored in the specified file.
	 * 
	 * @param aALName
	 *            the name of the AssemblyLine.
	 * @param aLogFileName
	 *            the name of the log file; no file path should be specified -
	 *            just the file name.
	 * @return the specified log of the AssemblyLine.
	 * @throws DIException
	 *             if an error occurs while obtaining AssemblyLine's log.
	 */
	public String getALLog(String aALName, String aLogFileName)
			throws DIException;

	/**
	 * Retrieves the last chunk from a specified AssemblyLine's log file.
	 * 
	 * @param aALName
	 *            the name of the AssemblyLine.
	 * @param aLogFileName
	 *            the name of the log file; no file path should be specified -
	 *            just the file name.
	 * @param aKilobytes
	 *            specifies in kilobytes the size of the log's last chunk that
	 *            will be read.
	 * @return the last chunk of the specified AssemblyLine's log.
	 * @throws DIException
	 *             if an error occurs while obtaining AssemblyLine's log.
	 */
	public String getALLogLastChunk(String aALName, String aLogFileName,
			Integer aKilobytes) throws DIException;

	/**
	 * Returns the Instance boot time.
	 * 
	 * @return a <code>java.util.Date</code> specifying the date and time the
	 *         instance was started.
	 * @throws DIException
	 *             if an error occurs while retrieving instance's boot time.
	 */
	public Date getInstanceBootTime() throws DIException;

	/**
	 * Returns the Config Instance GUID. The GUID is a string value that is
	 * unique for each component ever created by a particular TDI Server.
	 * <p>
	 * <b>Example</b>
	 * </p>
	 * 
	 * <pre>
	 * //for local access to jmx layer use: var jmxMBeanServer = com.ibm.di.api.jmx.JMXAgent.getMBeanServer();
	 * 	
	 * 	var jmxUrl = new 
	 * 		javax.management.remote.JMXServiceURL(&quot;service:jmx:rmi://localhost/jndi/rmi://localhost:1099/jmxconnector&quot;);
	 * 	var jmxConnector = javax.management.remote.JMXConnectorFactory.connect(jmxUrl);
	 * 	var jmxMBeanServer = jmxConnector.getMBeanServerConnection();
	 * 	mBeans = jmxMBeanServer.queryMBeans(null, null).iterator(); 
	 * 	while (mBeans.hasNext()) {
	 * 	var mb = mBeans.next();
	 * 	if (mb.getClassName()==&quot;com.ibm.di.api.jmx.mbeans.ConfigInstance&quot;)
	 * 	break; 
	 * 	}
	 * 
	 * 	var on = mb.getObjectName();
	 * 	var res = jmxMBeanServer.getAttribute(on,&quot;GlobalUniqueID&quot;);
	 * 	task.logmsg(&quot;Result &quot;+ res);
	 *  }
	 *  
	 *  Sample output:Result 17135304020
	 * </pre>
	 * 
	 * @return The Config Instance GUID value.
	 * @throws DIException
	 *             if an error occurs while retrieving GlobalUniqueID.
	 */
	public String getGlobalUniqueID() throws DIException;

	// Connector Pool calls

	/**
	 * Returns the names of all Connector Pools in the Config Instance.
	 * 
	 * @return String array containing the Connector Pool names.
	 * @throws DIException
	 *             if an error occurs while retrieving Connector Pool names.
	 */
	public String[] getConnectorPoolNames() throws DIException;

	/**
	 * Returns the size of the specified Connector Pool.
	 * 
	 * @param aConnectorPoolName
	 *            the name of the Connector Pool.
	 * @return The current size of the specified Connector Pool.
	 * @throws DIException
	 *             if an error occurs while retrieving Connector Pool size.
	 */
	public int getConnectorPoolSize(String aConnectorPoolName)
			throws DIException;

	/**
	 * Returns the number of free Connectors in the specified Connector Pool.
	 * 
	 * @param aConnectorPoolName
	 *            the name of the Connector Pool.
	 * @return The number of free Connectors in the specified Connector Pool.
	 * @throws DIException
	 *             if an error occurs while retrieving Connector Pool free
	 *             Connectors.
	 */
	public int getConnectorPoolFreeNum(String aConnectorPoolName)
			throws DIException;

	/**
	 * Returns the Connector Pool configuration object.
	 * 
	 * @param aConnectorPoolName
	 *            the name of the Connector Pool.
	 * @return The configuration object for the specified Connector Pool.
	 * @throws DIException
	 *             if an error occurs while retrieving Connector Pool
	 *             configuration object.
	 */
	public PoolDefConfig getConnectorPoolConfig(String aConnectorPoolName)
			throws DIException;

	/**
	 * Unused Connectors will be released so that the Pool is shrunk to its
	 * minimum size.
	 * 
	 * @param aConnectorPoolName
	 *            the name of the Connector Pool.
	 * @return The size of the Connector Pool after shrinking.
	 * @throws DIException
	 *             if an error occurs while shrinking the Connector Pool to its
	 *             minimum size.
	 */
	public int purgeConnectorPool(String aConnectorPoolName) throws DIException;

	/**
	 * Access to the TDIProperies for the particular config.
	 * 
	 * @return ObjectName containing the TDI Properties of the Config.
	 * @throws Exception
	 *             if an error occurs while getting TDI Properties
	 */
	public ObjectName getTDIProperties() throws Exception;

	/**
	 * Retrieves the config path.
	 * <p>
	 * <b>Example</b>
	 * </p>
	 * 
	 * <pre>
	 * //for local access to jmx layer use: var jmxMBeanServer = com.ibm.di.api.jmx.JMXAgent.getMBeanServer();
	 * 	
	 * 	var jmxUrl = new 
	 * 		javax.management.remote.JMXServiceURL(&quot;service:jmx:rmi://localhost/jndi/rmi://localhost:1099/jmxconnector&quot;);
	 * 	var jmxConnector = javax.management.remote.JMXConnectorFactory.connect(jmxUrl);
	 * 	var jmxMBeanServer = jmxConnector.getMBeanServerConnection();
	 * 	mBeans = jmxMBeanServer.queryMBeans(null, null).iterator(); 
	 * 	while (mBeans.hasNext()) {
	 * 	var mb = mBeans.next();
	 * 	if (mb.getClassName()==&quot;com.ibm.di.api.jmx.mbeans.ConfigInstance&quot;)
	 * 	break; 
	 * 	}
	 * 
	 * 	var on = mb.getObjectName();
	 * 	var res = jmxMBeanServer.getAttribute(on,&quot;ConfigPath&quot;);
	 * 	task.logmsg(&quot;Result &quot;+ res);
	 *  }
	 *  
	 *  Sample output:Result C:\Documents and Settings\Username\My Documents\TDI\rs.xml
	 * </pre>
	 * 
	 * @return The absolute path of the configuration file.
	 */
	public String getConfigPath();

}
