FC_DESC = Function Component that sends mails.
FC_TITLE = SendEMail Function Component
FROM_LBL = From
FROM_DESC = Specifies the "From" field in the mail
RCP_LBL = Recipients
RCP_DESC = List of the recipients
RPLT_LBL = ReplyTo
RPLT_DESC = List of the 'Reply To' addresses
SMTP_HOST_LBL = SMTP Server Host
SMTP_HOST_DESC = The address of the SMTP Server used for sending mails
SMTP_PORT_LBL = SMTP Server Port
SMTP_PORT_DESC = The port of the SMTP Server used for sending mails
SMTP_USER_LBL = Username
SMTP_USER_DESC = User name used for SMTP authentication
SMTP_PASS_LBL = Password
SMTP_PASS_DESC = Password used for SMTP authentication
SMTP_SSL_LBL = Use SSL
SMTP_SSL_DESC = Uses secure sockets layer for communication with SMTP server
SMTP_ENCD_LBL = MIME Charset
SMTP_ENCD_DESC = Specify the MIME charset to use for encoded words and text parts. If left blank the default system charset is used.
SMTP_ATTC_LBL = Attachments
SMTP_ATTC_DESC = Attach any files(s) you want to include with your message.
SMTP_ATTC_SLBL = Select...
SMTP_ATTC_SHLP = Browse file system.
SUBJECT_LBL = Subject
SUBJECT_DESC = Type a subject in the Subject field.
SMTP_CONT_LBL = MIME Content Type
SMTP_CONT_DESC = Set e-mail body part's MIME content type. 'text/plain' is used if left empty.
Advanced = Advanced
Cc = Cc
CC_DESC = Additional 'Cc' addresses
Bcc = Bcc
BCC_DESC = Additional 'Bcc' addresses
