CONN_DESC = Roll your own Connector using scripts
CONN_TITLE = Script Connector
pro_label = Include Global Scripts
pro_desc = Include selected scripts from the Script Library
pro_script_label = Select ...
pro_script_help = Press this button to add more Global Scripts
SCRIPT_CONN_KEEP_GLOBAL_STATE_LABEL = Keep Global State
SCRIPT_CONN_KEEP_GLOBAL_STATE_DESC = If checked, the global variables defined in the script are kept after the Connector is reinitialized.
Advanced = Advanced
