PAR_DESC = Parse/Generate HTTP content headers and data
mode_desc = For output, check here to write a client HTTP response instead of a server response.
mode_label = Client Mode
prop_desc = Stores HTTP headers as properties, else stores them as Attributes.
prop_label = Headers as Properties
set_desc = Character Encoding to be used
set_label = Character Encoding
PAR_TITLE = HTTP Parser
Advanced = Advanced
