<?xml version="1.0" encoding="UTF-8"?><MetamergeConfig Cycle="8" UUID="d1ffc8a0-3289-4a35-9c86-be6eb4ebb705" created="Mon Dec 30 13:03:44 CET 2013" createdBy="Administrator" main="continueTheReadLoop" modified="Fri Apr 04 10:56:17 CEST 2014" modifiedBy="Administrator" project="LDAPSync" version="7.1.1">
    <Script name="continueTheReadLoop">
        <ModTime>1396601776776</ModTime>
        <parameter name="includeFiles"/>
        <parameter name="script">abortFlow = "true".equalsIgnoreCase(work.getString("$stopFlow"));</parameter>
    </Script>
</MetamergeConfig>