<?xml version="1.0" encoding="UTF-8"?><MetamergeConfig Cycle="1" UUID="913faceb-720d-4fe5-aeac-532393229e2e" created="Mon Dec 30 13:03:44 CET 2013" createdBy="Administrator" main="customScript" modified="Mon Dec 30 13:03:44 CET 2013" modifiedBy="Administrator" project="LDAPSync" version="7.1.1">
    <Script name="customScript">
        <ModTime>1388405024466</ModTime>
        <parameter name="autoInclude">true</parameter>
        <parameter name="includeFiles">LDAPSync/customScript.js</parameter>
    </Script>
</MetamergeConfig>