<?xml version="1.0" encoding="UTF-8"?><MetamergeConfig Cycle="3" UUID="c54af2fd-b60d-4b18-ad6c-dc17ede722c4" created="Mon Dec 30 13:03:44 CET 2013" createdBy="Administrator" main="initializeResultToSkipped" modified="Wed Aug 06 16:00:56 CEST 2014" modifiedBy="Administrator" project="LDAPSync" version="7.1.1">
    <Script name="initializeResultToSkipped">
        <ModTime>1407333655649</ModTime>
        <parameter name="includeFiles"/>
        <parameter name="script"><![CDATA[work["$writeStatus"] = "skipped"

change = false

if (deBug) logmsg("\n                  --@--->> entry passed in: " + work.getString("$dn")
					+ " (" + work.getOperation() + ")"
					+ " ---------------------------------------------")]]></parameter>
    </Script>
</MetamergeConfig>