<?xml version="1.0" encoding="UTF-8"?><MetamergeConfig Cycle="4" UUID="71afba85-ef2a-4624-b6a6-e8338780b8c2" created="Fri Feb 28 11:24:16 CET 2014" createdBy="Administrator" main="libAfterModify" modified="Wed Mar 05 14:56:55 CET 2014" modifiedBy="Administrator" project="LDAPSync" version="7.1.1">
    <Script name="libAfterModify">
        <ModTime>1394027814713</ModTime>
        <parameter name="includeFiles"/>
        <parameter name="script">updateStatusFromTCB(targetTCB);</parameter>
    </Script>
</MetamergeConfig>