<?xml version="1.0" encoding="UTF-8"?><MetamergeConfig Cycle="5" UUID="a869d05f-f58a-43f9-9019-8721a8831e15" created="Fri Feb 28 11:25:11 CET 2014" createdBy="Administrator" main="libAfterDelete" modified="Mon May 11 13:08:16 CEST 2015" modifiedBy="Administrator" project="LDAPSync" version="7.1.1">
    <Script name="libAfterDelete">
        <ModTime>1431342496603</ModTime>
        <parameter name="includeFiles"/>
        <parameter name="script"><![CDATA[updateStatusFromTCB(targetTCB);

simEntry = system.newEntry();
simEntry.merge(conn);
simEntry.setOperation("delete");]]></parameter>
    </Script>
</MetamergeConfig>