<?xml version="1.0" encoding="UTF-8"?><MetamergeConfig Cycle="3" UUID="a869d05f-f58a-43f9-9019-8721a8831e15" created="Fri Feb 28 11:25:11 CET 2014" createdBy="Administrator" main="libAfterAdd" modified="Wed Mar 05 14:56:40 CET 2014" modifiedBy="Administrator" project="LDAPSync" version="7.1.1">
    <Script name="libAfterAdd">
        <ModTime>1394027800315</ModTime>
        <parameter name="includeFiles"/>
        <parameter name="script">updateStatusFromTCB(targetTCB);</parameter>
    </Script>
</MetamergeConfig>