<?xml version="1.0" encoding="UTF-8"?><MetamergeConfig Cycle="1" UUID="0d29e170-6d79-4717-90d6-04f5677f100c" created="Mon Dec 30 13:03:44 CET 2013" createdBy="Administrator" main="libBeforeExecute" modified="Mon Dec 30 13:03:44 CET 2013" modifiedBy="Administrator" project="LDAPSync" version="7.1.1">
    <Script name="libBeforeExecute">
        <ModTime>1388405024778</ModTime>
        <parameter name="includeFiles"/>
        <parameter name="script"><![CDATA[if (failed.get(flowKey + "_" + thisConnector.getName()) != null)
	system.ignoreEntry()]]></parameter>
    </Script>
</MetamergeConfig>