<?xml version="1.0" encoding="UTF-8"?><MetamergeConfig Cycle="1" UUID="7543321c-9bac-4a97-98d0-ba2ac4e3a6e5" created="Mon Dec 30 13:03:44 CET 2013" createdBy="Administrator" main="libBeforeGetNext" modified="Mon Dec 30 13:03:44 CET 2013" modifiedBy="Administrator" project="LDAPSync" version="7.1.1">
    <Script name="libBeforeGetNext">
        <ModTime>1388405024481</ModTime>
        <parameter name="includeFiles"/>
        <parameter name="script">logmsg("..." + resource.getString("LDAPSYNC.READING.DATA"))</parameter>
    </Script>
</MetamergeConfig>