<?xml version="1.0" encoding="UTF-8"?><MetamergeConfig Cycle="1" UUID="ad4a5b6e-4717-4edf-bdf6-79556333a7ec" created="Mon Dec 30 13:03:44 CET 2013" createdBy="Administrator" main="libBeforeSelection" modified="Mon Dec 30 13:03:44 CET 2013" modifiedBy="Administrator" project="LDAPSync" version="7.1.1">
    <Script name="libBeforeSelection">
        <ModTime>1388405024232</ModTime>
        <parameter name="includeFiles"/>
        <parameter name="script">logmsg("..." + resource.getString("LDAPSYNC.PERFORMING.SEARCH"))</parameter>
    </Script>
</MetamergeConfig>