<?xml version="1.0" encoding="UTF-8"?><MetamergeConfig Cycle="8" UUID="fb68ccc7-dfe0-4a79-b6e4-81422d46eb93" created="Mon Dec 30 13:03:44 CET 2013" createdBy="Administrator" main="libInitError" modified="Wed May 06 11:00:52 CEST 2015" modifiedBy="Administrator" project="LDAPSync" version="7.1.1">
    <Script name="libInitError">
        <ModTime>1430902852582</ModTime>
        <parameter name="includeFiles"/>
        <parameter name="script"><![CDATA[change = false;
if (typeof(work) != "undefined" && work != null) {
	work["$status"] = "failed";
	work["$error"] = error;
}	
defaultInitErrorHandling("ERROR");]]></parameter>
    </Script>
</MetamergeConfig>