<?xml version="1.0" encoding="UTF-8"?><MetamergeConfig Cycle="5" UUID="9bea79ba-1567-46db-85c6-0c2aafcef1a5" created="Fri Feb 28 11:23:08 CET 2014" createdBy="Administrator" main="libOnNoChanges" modified="Wed Mar 05 14:57:14 CET 2014" modifiedBy="Administrator" project="LDAPSync" version="7.1.1">
    <Script name="libOnNoChanges">
        <ModTime>1394027833865</ModTime>
        <parameter name="includeFiles"/>
        <parameter name="script"><![CDATA[change = false;
updateStatusFromTCB(targetTCB, false);]]></parameter>
    </Script>
</MetamergeConfig>