<?xml version="1.0" encoding="UTF-8"?><MetamergeConfig Cycle="13" UUID="63319ab3-086d-4b8a-be53-3306ad516d67" created="Mon Dec 30 13:03:44 CET 2013" createdBy="Administrator" main="libPrologHook" modified="Wed Mar 05 14:19:54 CET 2014" modifiedBy="Administrator" project="LDAPSync" version="7.1.1">
    <Script name="libPrologHook">
        <ModTime>1394025593463</ModTime>
        <parameter name="includeFiles"/>
        <parameter name="script">initUtils();</parameter>
    </Script>
</MetamergeConfig>