<?xml version="1.0" encoding="UTF-8"?><MetamergeConfig Cycle="2" UUID="4180d838-4606-486e-adae-48b4732fe8e2" created="Thu Aug 14 13:36:46 CEST 2014" createdBy="Administrator" main="libSkipThisEntry" modified="Thu Aug 14 13:37:21 CEST 2014" modifiedBy="Administrator" project="LDAPSync" version="7.1.1">
    <Script name="libSkipThisEntry">
        <ModTime>1408016241440</ModTime>
        <parameter name="includeFiles"/>
        <parameter name="script"><![CDATA[if (typeof skipThisEntry !== "undefined" && skipThisEntry) {
	work["$writeStatus"] = "skipped";
	system.ignoreEntry();
}]]></parameter>
    </Script>
</MetamergeConfig>