<?xml version="1.0" encoding="UTF-8"?><MetamergeConfig Cycle="10" UUID="efc89121-6a5a-495e-82c2-a6b4cf33e07d" created="Mon Dec 30 13:03:44 CET 2013" createdBy="Administrator" main="passSyncReportViaTCB" modified="Fri May 15 14:32:07 CEST 2015" modifiedBy="Administrator" project="LDAPSync" version="7.1.1">
    <Script name="passSyncReportViaTCB">
        <ModTime>1431693126073</ModTime>
        <parameter name="includeFiles"/>
        <parameter name="script"><![CDATA[tcb = thisConnector.getFunction().getTCB();
tcb.removeAttribute("$error");
tcb.removeAttribute("$errorLogged");
passGlobalVariablesViaTCB(tcb);
if (doTiming) timing("calling WriteToTarget - before call hook")]]></parameter>
    </Script>
</MetamergeConfig>