<?xml version="1.0" encoding="UTF-8"?><MetamergeConfig Cycle="1" UUID="8546ecf5-ff73-4d20-865e-69a9e0d67391" created="Mon Dec 30 13:03:44 CET 2013" createdBy="Administrator" main="prepareToLoop" modified="Mon Dec 30 13:03:44 CET 2013" modifiedBy="Administrator" project="LDAPSync" version="7.1.1">
    <Script name="prepareToLoop">
        <ModTime>1388405024840</ModTime>
    </Script>
</MetamergeConfig>