<?xml version="1.0" encoding="UTF-8"?><MetamergeConfig Cycle="6" UUID="b847c991-d585-4583-a159-f8145c66ce4a" created="Mon Dec 30 13:03:44 CET 2013" createdBy="Administrator" main="prepareForLooping" modified="Fri Apr 04 11:34:06 CEST 2014" modifiedBy="Administrator" project="LDAPSync" version="7.1.1">
    <Script name="prepareForLooping">
        <ModTime>1396604045737</ModTime>
        <parameter name="includeFiles"/>
        <parameter name="script"><![CDATA[// reset these flags for the current entry type
abortFlow = false;
endOfData = false;]]></parameter>
    </Script>
</MetamergeConfig>