<?xml version="1.0" encoding="UTF-8"?><MetamergeConfig Cycle="3" UUID="d1882ce0-d1e2-457e-a72a-b072ce516a95" created="Fri Apr 04 11:29:56 CEST 2014" createdBy="Administrator" main="signalEndOfData" modified="Fri Apr 04 11:36:03 CEST 2014" modifiedBy="Administrator" project="LDAPSync" version="7.1.1">
    <Script name="signalEndOfData">
        <ModTime>1396604163336</ModTime>
        <parameter name="includeFiles"/>
        <parameter name="script">endOfData = work.size() === 0 &amp;&amp; !skipEntry;</parameter>
    </Script>
</MetamergeConfig>