<?xml version="1.0" encoding="UTF-8"?><MetamergeConfig Cycle="1" UUID="2005b546-445f-46dd-a3ec-32590a45a9ff" created="Mon Dec 30 13:03:44 CET 2013" createdBy="Administrator" main="stopReadALFC" modified="Mon Dec 30 13:03:44 CET 2013" modifiedBy="Administrator" project="LDAPSync" version="7.1.1">
    <Script name="stopReadALFC">
        <ModTime>1388405024450</ModTime>
        <parameter name="script"><![CDATA[if (typeof(readALFC) != "undefined" && readALFC != null) {
	readALFC.terminate()
}]]></parameter>
    </Script>
</MetamergeConfig>