<?xml version="1.0" encoding="UTF-8"?><MetamergeConfig Cycle="2" UUID="5b19b372-ba4e-4f87-9e7d-584a908dda5e" created="Mon Dec 30 13:03:45 CET 2013" createdBy="Administrator" main="waitForALsToComplete" modified="Mon Mar 30 12:24:33 CEST 2015" modifiedBy="Administrator" project="LDAPSync" version="7.1.1">
    <Script name="waitForALsToComplete">
        <ModTime>1427711072487</ModTime>
        <parameter name="includeFiles"/>
        <parameter name="script"><![CDATA[for (cnt = 0; cnt < al.length; cnt++) {
	try {
		al[cnt].join()
	} catch (ex) {
		setException(ex, "fatal")
	}	
}

if (al.length == 1) {
	ex = getException("fatal")

	if (ex == null) {
		ex = getException("error")
	}
			
	if (ex != null) {
		task.getStats().exception(new java.lang.Exception(ex))
//		throw ex
	}
}]]></parameter>
    </Script>
</MetamergeConfig>