######################################################
#  Resource Strings
#
# TRNOTE: 
#
#  cmvc_en_version_level=1.13,0,08/01/23,03:46:20 
# Generic (Common) resource strings
######################################################
# NLS_MESSAGEFORMAT_NONE
path_desc=Path where file/directory scanning starts
path_label=Path
recur_desc=Recurse sub directories
recur_label=Recurse
want_desc=Return Directories
want_label=Check to return directory names as well as file names
read_desc=Read-Only files
read_label=Only return read-only files
hid_desc=Hidden Files
hid_label=Return hidden files
filpath_desc=Check regex patterns agains the full path (uncheck to check the last path component only)
filpath_label=Apply Regex filters to path
fil_desc=<html>List of regular expressions (one per line; see also java.util.regex) to filter out file/directory names.<br>These tests are performed after the other selection options succeed</html>
fil_label=Regex selection filters
CONN_TITLE=Sample File & Directory Connector

