CONN_DESC = JMS access to IBM MQ Series (need additional jars from IBM)
CONN_TITLE = IBM MQ Series Connector
JMS_BROKER_LABEL = Broker
JMS_BROKER_DESC = JMS Server address (ip host and tcp port number)
JMS_SERVER_CHANNEL_LABEL = Server Channel
JMS_SERVER_CHANNEL_DESC = MQ Server Channel
JMS_SSL_SERVER_CHANNEL_LABEL = SSL Server Channel
JMS_SSL_SERVER_CHANNEL_DESC = MQ SSL Server Channel
JMS_QUEUE_MANAGER_LABEL = Queue Manager
JMS_QUEUE_MANAGER_DESC = MQ Queue Manger Name
JMS_SSL_USE_FLAG_LABEL = Use SSL Connection 
JMS_SSL_USE_FLAG_DESC = If checked, you must have a properly configured Server Channel
JMS_SSL_CIPHERSUITE_LABEL = SSL CipherSuite
JMS_SSL_CIPHERSUITE_DESC = CipherSuite names supported by WebSphere MQ
JMS_DURABLE_LABEL = Durable Topic Subscriber
JMS_DURABLE_DESC = Check if you dont want to miss out on messages when you are disconnected
JMS_USERNAME_LABEL = User Name
JMS_USERNAME_DESC = Login username for specified topic
JMS_PW_LABEL = Password
JMS_PW_DESC = Login password for specified topic
JMS_TOPIC_LABEL = Topic/Queue
JMS_TOPIC_DESC = JMS topic/queue
JMS_MSGFLT_LABEL = Message Selection Filter
JMS_MSGFLT_DESC = Used for Iterator mode only and specifies a message filter selection for those messages you want returned
JMS_CONNTYPE_LABEL = Connection Type
JMS_CONNTYPE_DESC = Specify whether you are connecting to a Queue or Topic (Pub/Sub)
JMS_CLIENTID_LABEL = Client ID
JMS_CLIENTID_DESC = The client ID to use for Topic connections (mandatory for durable).
JMS_AUTOACK_LABEL = Auto Acknowledge
JMS_AUTOACK_DESC = If not checked you must manually acknowledge receipt of messages
JMS_USEMSG_LABEL = Use Textmessage
JMS_USEMSG_DESC = Send TextMessage (true)or BytesMessage (false) to the JMS bus.
JMS_LOOKUPMSG_LABEL = Lookup Removes
JMS_LOOKUPMSG_DESC = If checked Lookup operation removes matching messages from the queue
JMS_LOOKUPRETRY_LABEL = Lookup Retries
JMS_LOOKUPRETRY_DESC = Number of lookup retries
JMS_LOOKUPTIMEOUT_LABEL = Lookup Timeout
JMS_LOOKUPTIMEOUT_DESC = Lookup TimeoutNumber milliseconds between each lookup retry 
JMS_HEADERATTRIB_LABEL = JMS Headers as attributes
JMS_HEADERATTRIB_DESC = Set/Get all JMS headers from/to attributes (prefixed by jms.)
JMS_SPECIFIC_HEADERATTRIB_LABEL = Specific JMS Headers
JMS_SPECIFIC_HEADERATTRIB_DESC = Set/Get specific JMS headers from/to attributes (prefixed by jms.)
JMS_PROPERTIESATTRIB_LABEL = JMS Properties as attributes
JMS_PROPERTIESATTRIB_DESC = Set/Get all JMS properties from/to attributes (prefixed by jms.)
JMS_SPECIFIC_PROPERTIESATTRIB_LABEL = Specific JMS Properties
JMS_SPECIFIC_PROPERTIESATTRIB_DESC = Set/Get specific JMS properties from/to attributes (prefixed by jms.)
JMS_TIMEOUT_LABEL = GetNext Timeout
JMS_TIMEOUT_DESC = Number milliseconds to wait for a new entry in Iterator mode (-1 \=\= forever) 
Localized.subscriber = subscriber
Localized.publisher = publisher
Localized.Topic = Topic
Localized.Queue = Queue
Advanced = Advanced
