conn_DESC = JMS Password Store Connector
conn_TITLE = JMS Password Store Connector
getNextTimeout_LBL = GetNext Timeout
getNextTimeout_DESC = Number of milliseconds to wait for a new entry in Iterator mode (-1 \=\= forever, 0 \=\= return immediately if no message available).
storageNotification_LBL = Storage notification server(s)
storageNotification_DESC = <host>\:<port> identifications of the Storage Component notification servers. Specify each server on a separate line.
JMS_AUTOACK_LABEL = Auto Acknowledge
JMS_AUTOACK_DESC = If checked each message is automatically acknowledged, otherwise messages are acknowledged manually\n through the Connector's "acknowledge()" method.
decryptMessages_LBL = Decrypt messages
decryptMessages_DESC = Specify whether password update messages need decryption
keyStoreFilePath_LBL = Key Store File
keyStoreFilePath_DESC = Key Store file that will be used for decryption
keyStoreFilePassword_LBL = Key Store File Password
keyStoreFilePassword_DESC = Key Store file password
keyStoreCertificateAlias_LBL = Key Store Certificate Alias
keyStoreCertificateAlias_DESC = Key Store certificate alias
keyStoreCertificatePassword_LBL = Key Store Certificate Password
keyStoreCertificatePassword_DESC = Key Store certificate Password
defaultstorageNotification = <storage host>\:41002
usePkcs7_LBL = PKCS7
usePkcs7_DESC = Use Pkcs7 signing and encription.
pkcs7KeyStoreFilePath_LBL = PKCS7 Key Store File
pkcs7KeyStoreFilePath_DESC = Path and Name of the JMSPasswordStoreConnector's JKS file
pkcs7KeyStoreFilePassword_LBL = PKCS7 Key Store File Password
pkcs7KeyStoreFilePassword_DESC = JMSPasswordStoreConnector's JKS Password
pkcs7MqeConnectorCertificateAlias_LBL = JMSPasswordStoreConnector's Certificate Alias
pkcs7MqeConnectorCertificateAlias_DESC = JMSPasswordStoreConnector's certificate alias
# new properties
JMS_BROKER_LABEL = Broker
JMS_BROKER_DESC = JMS Server address (ip host and tcp port number)
JMS_SERVER_CHANNEL_LABEL = Server Channel
JMS_SERVER_CHANNEL_DESC = MQ Server Channel
JMS_SSL_USE_FLAG_LABEL = Use SSL Connection 
JMS_SSL_USE_FLAG_DESC = If checked, you must have a properly configured JMS provider
JMS_SSL_SERVER_CHANNEL_LABEL = SSL Server Channel
JMS_SSL_SERVER_CHANNEL_DESC = MQ SSL Server Channel
JMS_QUEUE_MANAGER_LABEL = Queue Manager
JMS_QUEUE_MANAGER_DESC = Specifies MQ Queue Manager Name
JMS_SSL_CIPHERSUITE_LABEL = SSL CipherSuite
JMS_SSL_CIPHERSUITE_DESC = CipherSuite names supported by IBM WebSphere MQ
JMS_USERNAME_LABEL = User Name
JMS_USERNAME_DESC = Login username for specified topic
JMS_PW_LABEL = Password
JMS_PW_DESC = Login password for specified topic
JMS_CLIENTID_LABEL = Client ID
JMS_CLIENTID_DESC = The client ID to use for Topic connections (mandatory for durable).
JMS_DRIVER_LABEL = JMS Server Type
JMS_DRIVER_DESC = The full name of class implementing JMSDriver interface
JMS_DRV_ATTR_LABEL = Specific Driver Attributes
JMS_DRV_ATTR_DESC = Specific JMS Driver Attributes
Advanced = Advanced
