#Eclipse Runtime Configuration File
osgi.bundles=org.eclipse.equinox.common@start, \
        org.eclipse.update.configurator@start, \
	com.ibm.icu, \
	jakarta.activation-api, \
	jakarta.servlet-api, \
	javax.servlet, \
	javax.xml.bind@start, \
	jakarta.xml.bind-api@start, \
	org.glassfish.jaxb.runtime@start, \
	jakarta.validation.jakarta.validation-api@start, \
	com.ibm.di.jaxrs@start, \
	com.fasterxml.jackson.core.jackson-annotations@start, \
	com.fasterxml.jackson.core.jackson-core@start, \
	com.fasterxml.jackson.core.jackson-databind@start, \
	com.fasterxml.jackson.jaxrs.jackson-jaxrs-base@start, \
	com.fasterxml.jackson.jaxrs.jackson-jaxrs-json-provider@start, \
	com.fasterxml.jackson.module.jackson-module-jaxb-annotations@start, \
	slf4j.jdk14, \
	slf4j.api, \
	org.eclipse.jetty.security, \
	org.eclipse.jetty.io, \
	org.eclipse.osgi, \
	org.osgi.service.event, \
	org.eclipse.osgi.services, \
	org.eclipse.jetty.server, \
	org.eclipse.jetty.util, \
	org.eclipse.jetty.http, \
	org.eclipse.jetty.servlet, \
	org.osgi.util.function, \
	org.osgi.util.promise, \
	org.osgi.service.component, \
	org.osgi.service.cm, \
	org.osgi.service.device, \
	org.osgi.service.metatype, \
	org.osgi.service.provisioning, \
	org.osgi.service.upnp, \
	org.osgi.service.useradmin, \
	org.osgi.service.wireadmin, \
	org.eclipse.equinox.http.servlet, \
	org.eclipse.equinox.http.servletbridge, \
	org.osgi.service.log.stream, \
	org.eclipse.equinox.http.jetty.listener, \
	org.eclipse.equinox.http.jetty, \
        org.eclipse.core.runtime, \
        org.eclipse.core.jobs, \
        org.eclipse.equinox.registry, \
        org.eclipse.equinox.preferences, \
        org.eclipse.core.contenttype, \
        org.osgi.service.prefs, \
        org.eclipse.equinox.app, \
	org.apache.felix.scr@start, \
	javax.ws.rs-api@start, \
	javax.persistence-api@start, \
	javax.annotation-api@start, \
	javax.inject@start, \
	javassist@start, \
	org.apache.aries.util@start, \
	org.ow2.asm@start, \
	org.ow2.asm.commons@start, \
	org.ow2.asm.tree@start, \
	org.ow2.asm.util@start, \
	org.ow2.asm.analysis@start, \
	org.apache.aries.spifly.dynamic.bundle@start, \
	org.glassfish.hk2.external.aopalliance-repackaged@start, \
	org.glassfish.hk2.utils@start, \
	org.glassfish.hk2.api@start, \
	org.glassfish.hk2.osgi-resource-locator@start, \
	org.glassfish.hk2.locator@start, \
	org.glassfish.jersey.inject.jersey-hk2@start, \
	org.glassfish.jersey.core.jersey-common@start, \
	org.glassfish.jersey.core.jersey-client@start, \
	org.glassfish.jersey.core.jersey-server@start, \
	org.glassfish.jersey.containers.jersey-container-servlet-core@start, \
	org.glassfish.jersey.containers.jersey-container-servlet@start, \
	org.glassfish.jersey.ext.jersey-entity-filtering@start, \
	org.glassfish.jersey.media.jersey-media-json-jackson@start, \
	org.apache.wink.common, \
	com.ibm.di.jaxrs.impl, \
	com.ibm.di.jaxrs.jackson, \
	com.ibm.di.log.slf4j, \
	com.ibm.di.bundle, \
	com.ibm.di.http.jetty.listener, \
	com.ibm.di.jaxrs.storage.atom, \
	com.ibm.di.schema, \
	com.ibm.di.util, \
	com.ibm.di.api, \
	com.ibm.di.config, \
	com.ibm.di.server, \
	com.ibm.di.server.entry, \
	com.ibm.di.log, \
	com.ibm.di.web.common, \
	com.ibm.di.api.connection, \
	com.ibm.di.systemqueue, \
	com.ibm.di.api.impl, \
	com.ibm.di.connector.taddm, \
	com.ibm.di.log.slf4j-tdi, \
	com.ibm.tdi.rest@start, \
	com.ibm.di.api.rest@start, \
	com.ibm.di.component, \
	com.ibm.di.api.bind, \
	com.ibm.di.config.bind, \
	com.ibm.di.ui.easyetl@start, \
	com.ibm.di.ui.webui@start
osgi.noShutdown=true
eclipse.ignoreApp=true

# We are using fwk because this is the only classloader that could gives us access to the IDILoader and all of the jars loaded by it
# The classloader hierarchy in the JVM looks like this: app->ext->boot->{IDILoader}->{DynamicClassLoader=fwk}
# if using app, ext or boot we will loose the ability to communicate with the Local Server API
osgi.parentClassloader=fwk
osgi.contextClassLoaderParent=fwk

org.osgi.framework.bootdelegation=org.apache.wink.common.model.atom,org.apache.wink.common.model.app,javax.xml.bind.*
