CONN_DESC = A Connector capable of listening to and reporting either local or remote JMX notifications (as per the JMX Remote API 1.0 specification)
JMX_MODE_DESC = Specifies whether the Connector will listen for local or remote JMX notifications (as per the JMX Remote API 1.0 specification).
JMX_MODE_LABEL = Mode
JMX_URL_DESC = The URL used to connect to the remote JMX system. This URL is registered by the remote MBeanServer on startup.
JMX_URL_LABEL = Remote JMX URL
JMX_ALLMBEANS_DESC = If checked the Connector will listen for notifications emitted by any registered MBean.
JMX_ALLMBEANS_LABEL = Listen to all MBeans
JMX_MBEANTYPES_DESC = A list of MBean object names, which specify the MBeans the Connector will register with for notifications. The fully qualified MBean object names are required. Type each MBean object name on a separate line.
JMX_MBEANTYPES_LABEL = MBeans to listen to
JMX_EVENTTYPES_DESC = The types of JMX notifications which the JMX Connector will listen to. Notifications whose types are not specified will not be reported by the Connector. Each notification type must be typed on a separate line.
JMX_EVENTTYPES_LABEL = Notification types
CONN_TITLE = JMX Connector
Localized.remote = remote
Localized.local = local
Advanced = Advanced
