CONN_DESC = IBM Security Access Manager Connector
USERNAME_DESC = ISAM Administrative ID
USERNAME_LABEL = ISAM ID
DOMAIN_DESC = ISAM Domain
DOMAIN_LABEL = Domain
DOMAIN_SCRIPT_LABEL = Domains
DOMAIN_SCRIPT_HELP = Query ISAM server for a list of domains
PASSWORD_DESC = Password for ISAM Administrative User ID
PASSWORD_LABEL = ISAM password
PROGNAME_DESC = ISAM Program Name specified in the SvrSslCfg configuration utility
PROGNAME_LABEL = ISAM Program Name
CONFIGURL_DESC = Configuration file created by the SvrSslCfg configuration utility
CONFIGURL_LABEL = ISAM Configuration File
CONFIGURL_SCRIPT_LABEL = Select...
CONFIGURL_SCRIPT_HELP = Browse file system
ENTRY_TYPE_DESC = Specifies the object type to work with
ENTRY_TYPE_LABEL = Entry Type
ENTRY_TYPE_OPT1 = User
ENTRY_TYPE_OPT2 = Group
ENTRY_TYPE_OPT3 = Policy
ENTRY_TYPE_OPT4 = Domain
ENTRY_TYPE_OPT5 = SSOCred
ENTRY_TYPE_OPT6 = SSOResource
ENTRY_TYPE_OPT7 = SSOResourceGroup
IMPORT_CREATE_DESC = If checked, users/groups will be imported from the registry
IMPORT_CREATE_LABEL = Import users/groups from registry
DEL_REG_DESC = If checked, users/groups/domains will also be deleted from the registry
DEL_REG_LABEL = Delete users/groups/domains from registry
FILTER_LABEL = Filter users/groups
FILTER_DESC = If present users/groups will be filtered with this value before iteration
SELECT_DOMAIN = Select Domain
