PAR_DESC = Simple DSML 1.0 parser
att_desc = The attribute used for the distinguished name
att_label = DN Attribute
fix_desc = prefix used on XML elements to indicate that they belong to the DSML namespace
fix_label = DSML prefix
uri_desc = the URI which identifies this namespace
uri_label = DSML namespace URI
set_desc = Character Encoding to be used
set_label = Character Encoding
PAR_TITLE = DSMLv1 Parser
Advanced = Advanced
