/*
 * Copyright IBM Corp. 2025
 *
 * SPDX-License-Identifier: Apache-2.0
 */
package com.ibm.di.entry;

import java.io.Serializable;

import org.w3c.dom.CDATASection;
import org.w3c.dom.DOMException;
import org.w3c.dom.Node;
import org.w3c.dom.Text;

/**
 * The AttributeValue class is used in conjunction with the Attribute object to
 * store information about an attribute value. The class has a value and an
 * operation properties associated with the value.
 */

public class AttributeValue extends CharacterDataImpl implements Serializable,
		Text, CDATASection, Cloneable {

	static final long serialVersionUID = 100100L;

	/**
	 * Used when a value does not have a defined operation code
	 */
	public final static int AV_UNDEFINED = -1;

	/**
	 * Used when a value is not changed
	 */
	public final static int AV_UNCHANGED = 0;

	/**
	 * Used when a value has been added
	 */
	public final static int AV_ADD = 1;

	/**
	 * Used when a value has been deleted
	 */
	public final static int AV_DELETE = 2;

	/**
	 * Used when a value has been modified.
	 */
	public final static int AV_REPLACE = 3;

	/**
	 * Internal buffer with string representations of above constants
	 */
	private final static String[] OPER = { "unchanged", "add", "delete",
			"replace" };

	/**
	 * The local name which will be returned if the AttributeValue is of type
	 * cdata_node
	 */
	private static final String CDATA_NAME = "#cdata-section";

	/**
	 * The local name which will be returned if the AttributeValue is of type
	 * text_node
	 */
	private static final String TEXT_NAME = "#text";

	/**
	 * The value this object represents
	 */
	private Object value;

	/**
	 * The operation code for the value
	 */
	private int oper;

	/**
	 * Specifies whether the AttributeValue is either a CDATA section node or a
	 * Text node.
	 */
	private boolean isTextNode = true;

	/**
	 * Creates an AttributeValue giving a value to be wrapped. The operation
	 * code assigned by default is AV_REPLACE.
	 * 
	 * @param value
	 *            the value to be wrapped as an AttributeValue.
	 */
	public AttributeValue(Object value) {
		this(value, AV_REPLACE);
	}

	public AttributeValue(Object value, int oper) {
		this.value = value;
		setOper(oper);
	}

	public AttributeValue(Object value, int oper, boolean isText) {
		this(value, oper);
		this.isTextNode = isText;
	}

	public Object getValue() {
		return value;
	}

	public void setValue(Object value) {
		this.value = value;
	}

	public int getOper() {
		if (oper < AV_UNDEFINED || oper > AV_REPLACE)
			return AV_UNDEFINED;
		else
			return oper;
	}

	/**
	 * Return the operation code. This only has meaning if this value is inside
	 * an Entry generated by an Iterator with Delta enabled.
	 * 
	 * @return - The operation code. Possible return values are : <br>
	 *         "unchanged" - Used when a value is not changed<br>
	 *         "add" - Used when a value has been added<br>
	 *         "delete" - Used when a value has been deleted<br>
	 *         "" - Used when a value does not have a defined operation code
	 */
	public String getOperation() {
		if (oper >= 0 && oper < OPER.length)
			return OPER[oper];
		else
			return "";
	}

	public void setOper(int oper) {
		if (oper == 'a')
			oper = AV_ADD;
		else if (oper == 'd')
			oper = AV_DELETE;
		else if (oper == 'u')
			oper = AV_UNCHANGED;
		else if (oper == 'r')
			oper = AV_REPLACE;

		this.oper = oper;
	}

	public void setOperation(String oper) {
		this.oper = stringToOper(oper);
	}

	public static int stringToOper(String oper) {
		if (oper == null || oper.length() == 0)
			return AV_UNDEFINED;

		char c = oper.charAt(0);
		if (c == 'a' || c == 'A')
			return AV_ADD;
		else if (c == 'd' || c == 'D')
			return AV_DELETE;
		else if (c == 'u' || c == 'U')
			return AV_UNCHANGED;
		else if (c == 'r' || c == 'R')
			return AV_REPLACE;

		return AV_UNDEFINED;
	}

	public String toString() {
		return getData();
	}

	public String toDeltaString() {
		return getOperation() + ": " + toString();
	}

	/**
	 * Changes the type of the node.
	 * 
	 * @param value
	 *            - if this is true, subsequent calls to {@link #getNodeType()}
	 *            will return {@link Node#TEXT_NODE}, otherwise will return
	 *            {@link Node#CDATA_SECTION_NODE}. *
	 * @since 7.0
	 */
	public void setNodeTypeText(boolean value) {
		isTextNode = value;
	}

	@Override
	public AttributeValue clone() {
		try {
			return (AttributeValue) super.clone();
		} catch (CloneNotSupportedException e) {
			return null;
		}
	}

	// DOM implementation starts here...

	public String getData() throws DOMException {
		return value != null ? value.toString() : null;
	}

	public void setData(String data) throws DOMException {
		value = data;
	}

	public Node cloneNode(boolean deep) {
		return clone();
	}

	@Override
	public String getNodeName() {
		return getLocalName();
	}

	public String getLocalName() {
		return isTextNode ? TEXT_NAME : CDATA_NAME;
	}

	public String getNamespaceURI() {
		return null;
	}

	public short getNodeType() {
		return isTextNode ? Node.TEXT_NODE : Node.CDATA_SECTION_NODE;
	}

	public String getPrefix() {
		return null;
	}

	public void setPrefix(String prefix) throws DOMException {
	}
}
