DCS_FC_TITLE = Data Cleanser Function Component
DCS_FC_DESC = The Data Cleanser FC maps a given string to a standard CDM string value.
DCS_FC_STRING_ATTRIBUTE_TYPES_DESC = The Attribute Type of the String which needs to be cleansed.
DCS_FC_STRING_ATTRIBUTE_TYPES_LABEL = Attribute Type
DCS_FC_GET_STRING_ATTRIBUTE_TYPES_SCRIPT_LABEL = Select...
DCS_FC_GET_STRING_ATTRIBUTE_TYPES_SCRIPT_DESC = Choose one of supported attribute type.
Advanced = Advanced
