#################################################################################################
# This file contains default values for the parameters needed to connect to a IT registry system.
# The values of these properties will be used by the IdML and IT registry Components.     
#################################################################################################

it_registry.jdbcUrl=
it_registry.jdbcDriver=
it_registry.dbUsername=
it_registry.dbPassword=