###########################################################################################################
# This file controls the tracing and First Failure Data Capture (FFDC) strategy for ITDI 7.1
# See the IDI documentation for more information on the contents of this file.
###########################################################################################################

#----------------------------------------------------------------------------------------------------------
# Enable the JLOG's command server
#
# 	If the jlog.noLogCmd is set to false, then the JLOG LogManager will listen on the 
# 	default port (9992) for JLOG log commands. 
# 	Setting this property to false will enable you to modify the JLOG properties dynamically using the 
#	logcmd scripts. The logcmd scripts are placed under ITDI_HOME directory.
# 	The default value is set to true.
#----------------------------------------------------------------------------------------------------------
jlog.noLogCmd=true

#----------------------------------------------------------------------------------------------------------
# Set listen port for JLOG's command server
#
#       If you want LogManager to listen on different port than the default one (9992) you should
#       uncomment the property jlog.logCmdPort and set it to the desired port. If not uncommented
#       the LogManager will listen on the default port - 9992.
#----------------------------------------------------------------------------------------------------------
#jlog.logCmdPort=9992

#----------------------------------------------------------------------------------------------------------
# Configure Jlog FileHandler for tracing into a file.
#
# 	By default the FileHandler is not attached to the Jlog Logger. 
#	Uncomment the properties with the prefix jlog.filehandler below to configure a FileHandler.
#	After uncommenting this you need to add the filehandler to the logger's listeners names as shown
#	below
#	e.g: jlog.logger.listenerNames=jlog.snapmemory jlog.snaphandler jlog.filehandler
#----------------------------------------------------------------------------------------------------------
jlog.filehandler.className=com.ibm.log.FileHandler
#jlog.filehandler.description=JLOG File Handler for Logging and Tracing
#jlog.filehandler.encoding=UTF8
#jlog.filehandler.maxFiles=10
#jlog.filehandler.maxFileSize=2048
#jlog.filehandler.appending=true
#jlog.filehandler.fileDir=logs/
#jlog.filehandler.trace.fileName=trace.log
#-----------------------------------------------------------------------------------------------------------

#-----------------------------------------------------------------------------------------------------------
# create a level filter. 
#	The level filter is used to define the level at which JFFDC action will be triggered.
#	For JFFDC to be meaningful this should be set to either FATAL or ERROR (case-insensitive).
#	NOTE: Setting the trigger level to other levels such as DEBUG_MIN will trigger unwanted JFFDC
#		action causing a performance drop. 
#-----------------------------------------------------------------------------------------------------------
jlog.levelflt.className=com.ibm.log.LevelFilter
jlog.levelflt.level=FATAL

#-----------------------------------------------------------------------------------------------------------
# Configure the SnapMemoryHandler for tracing into a memory buffer.
#	The SnapMemoryHandler traces into a memory buffer and dumps the contents of the memory to a file on
#	trigger of a event (as defined by the level filter above) and writes the content to the specified 
#	file
# Properties:
# jlog.snapmemory.queueCapacity	: Sets the nnumber of LogEvents that can be buffered in the memory
# jlog.snapmemory.snapFile		: name of the file to which the contents of the memory will be dumped
# jlog.snapmemory.baseDir		: The directory where the snapFile is placed.
#						  daily subdirectories will be created under this base directory, as:
# 						  [baseDir]/[YYYY-MM-DD]/
# 						  Note: MS-DOS style path names need to be be escaped with backslashes
#							  eg: c:\\CTGI\\FFDC
# jlog.snapmemory.userSnapFile	: The name of the file to which the user initiated (from logcmd) dumps
#						  will be written to.	
# jlog.snapmemory.userSnapDir		: The directory where the userSnapfile is placed.
# jlog.snapmemory.msgIds		: The list of TMS IDs
# jlog.snapmemory.msgIDRepeatTime   : The minimum time, in milliseconds, after passing a log event with a 
#						  given TMS message id, before another log event with the same id can 
#						  be passed.					  						  
#-----------------------------------------------------------------------------------------------------------
jlog.snapmemory.className=com.tivoli.log.SnapMemoryHandler
jlog.snapmemory.description=Memory handler used to trace to memory
jlog.snapmemory.queueCapacity=10000
jlog.snapmemory.dumpEvents=true
jlog.snapmemory.snapFile=trace.log
jlog.snapmemory.baseDir=CTGDI/FFDC/
jlog.snapmemory.userSnapFile=userTrace.log
jlog.snapmemory.userSnapDir=CTGDI/FFDC/user/
jlog.snapmemory.triggerFilter=jlog.levelflt
jlog.snapmemory.msgIds=*E
jlog.snapmemory.msgIDRepeatTime=10000

#-----------------------------------------------------------------------------------------------------------
# Configure the JLogSnapHandler taking a snapshot of the SnapMemoryHanlders buffer
#	The JLogSnapHanlder takes a snapshot of the associated SnapMemoryBuffer.
#-----------------------------------------------------------------------------------------------------------
jlog.snaphandler.className=com.tivoli.log.JLogSnapHandler
jlog.snaphandler.description=snaphandler to dump the memory trace
jlog.snaphandler.baseDir=CTGDI/FFDC/
jlog.snaphandler.snapMemoryHandler=jlog.snapmemory
jlog.snaphandler.triggerFilter=jlog.levelflt

#-----------------------------------------------------------------------------------------------------------
# Configure the PDLogger (Problem Determination) Object and attach the Listeners to it.
#	jlog.logger.level can be FATAL | ERROR | WARNING | INFO | DEBUG_MIN | DEBUG_MID | DEBUG_MAX
#	The heirarchy of the log levels is from the most severe (FATAL) to the least severe (DEBUG_MAX)
#	The value for this property is case-insensitive
#-----------------------------------------------------------------------------------------------------------
jlog.logger.level=FATAL
#jlog.logger.listenerNames=jlog.snapmemory jlog.snaphandler
jlog.logger.listenerNames=jlog.filehandler.trace
jlog.logger.className=com.ibm.log.PDLogger

#-----------------------------------------------------------------------------------------------------------
# Configure the PDLogger for the Config Editor and attach the Listeners to it.
# By default, no listeners are attached
#-----------------------------------------------------------------------------------------------------------
jlog.logger.config-editor.level=FATAL
jlog.logger.config-editor.listenerNames=
