#
# This file controls the logging strategy for the update installer.
# -----------------------------------------------------------------

log4j.rootCategory=INFO, Default
log4j.appender.Default=org.apache.log4j.FileAppender
log4j.appender.Default.layout=org.apache.log4j.PatternLayout
log4j.appender.Default.layout.ConversionPattern=%d{DEFAULT} %-5p [applyUpdates] - %m%n

#
# The file to log the messages to.
#

log4j.appender.Default.File=logs/updateinstaller.log

#
# Decides whether the messages should be appended to the log file.
#

log4j.appender.Default.append=false

