CONN_DESC = Web Service Receiver Server Connector
CONN_TITLE = Web Service Receiver Server Connector
TP_DESC = The port number the service is running (listening) on
TP_LBL = TCP Port
IT_LBL = Input the SOAP message as
IT_DESC = Specifies the type of the SOAP Request message input to the AssemblyLine
RXT_LBL = Return the SOAP message as
RXT_DESC = Specifies the type of the SOAP Response message output from the AssemblyLine
US_DESC = If checked the server will only accept SSL (https) connections
US_LBL = Use SSL
WTGFN_LBL = WSDL Output to Filename
WTGFN_DESC = The name of the WSDL file to be generated when the "Generate WSDL" button is clicked
WSL_LBL = Web Service provider URL
WSL_DESC = The address on which web service clients will send web service requests
RGWSB_SCRLBL = Generate WSDL
RGWSB_SCRHLP = When this button is clicked a utility generates a WSDL file.
ALERT_WFGS = WSDL file generated successfully.
Localized.String = String
Localized.DOMElement = DOMElement
REQUIRE_CLIENT_AUTHENTICATION = Require Client Authentication
REQUIRE_CLIENT_AUTHENTICATION_DESC = If checked clients will be required to provide SSL certificates for client authentication
TCP_BACKLOG_DESC = The maximum queue length for incoming connections. If a connection request arrives when the queue is full, the connection will be refused.
TCP_BACKLOG_LABEL = Connection Backlog
TOE_LBL = Tag Op-Entry
TOE_DESC = Specifies whether the $operation attribute of the op-entry is set to the name of the web service operation.
AUTH_REALM_LBL = Auth Realm
AUTH_REALM_DESC = The basic-realm sent to the client in case authentication is requested.
AUTH_REALM_DEF = IBM Security Verify Directory Integrator
UBA_LBL = Use HTTP Basic Authentication
UBA_DESC = If checked the server will require HTTP Basic Authentication.
Advanced = Advanced
