#################################################################
# benchmark.properties: Set the properties to start the 	#
# ibmdisrvtp.sh and ibmdibenchmark.sh utilities			#
#								#
#################################################################

# ibmditp.sh properties
ibmdiroot="$change$"
solutiondir="$soldir$"
configfile=
assemblyline=
eventhandlers=
cmdoptions=
jvmcmdoptions=

# benchmark.sh properties
duration=-1
interval=5
ios=n
vms=y
nets=n

debug=false
