<?xml version="1.0"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
	xmlns:xalan2="http://xml.apache.org/xalan"
	xmlns:fixquote="com.tivoli.tmsxml.tools.FixQuote"
	xmlns:fixbackslash="com.tivoli.tmsxml.tools.FixBackslash"
	xmlns:fixquotationmark="com.tivoli.tmsxml.tools.FixQuotationMark"
        xmlns:str="http://exslt.org/strings"
	extension-element-prefixes="xalan2 str" version="1.0">

	<!--
		*********************************************************************
		*   Licensed materials - Property of IBM
		*   (C) . 2000-2009
		*
		*   US Government Users Restricted Rights - Use, duplication, or
		*   disclosure restricted by GSA ADP Schedule Contract with
		*   IBM Corp.
		*********************************************************************
	-->

	<xsl:variable name="versionlevel2">
		Filename: javaText.xsl Version: 1.23 Date: 09/06/02 Time: 10:15:09 Release:
		1
	</xsl:variable>

	<!--================================================================-->
	<!-- commentCopyright                                               -->
	<!--                                                                -->
	<!-- Get copyright statement from file, and output as block comment -->
	<!--================================================================-->
	<xsl:template name="commentCopyright">
		<xsl:if test="$comment_start='*'">
			<xsl:text>/*</xsl:text>
		</xsl:if>

		<xsl:if test="string-length($copyright)=0">
			<xsl:text>&#xa;</xsl:text>
			<xsl:value-of select="$comment_start" />
			<xsl:text> OCO Source Materials&#xa;</xsl:text>
			<xsl:value-of select="$comment_start" />
			<xsl:text>&#xa;</xsl:text>
			<xsl:value-of select="$comment_start" />
			<xsl:text> Licensed Materials - Property of IBM&#xa;</xsl:text>
			<xsl:value-of select="$comment_start" />
			<xsl:text>&#xa;</xsl:text>
			<xsl:value-of select="$comment_start" />
			<xsl:text> . 2000-2009. All Rights Reserved&#xa;</xsl:text>
			<xsl:value-of select="$comment_start" />
			<xsl:text>&#xa;</xsl:text>
			<xsl:value-of select="$comment_start" />
			<xsl:text> US Government Users Restricted Rights - Use, duplication or&#xa;</xsl:text>
			<xsl:value-of select="$comment_start" />
			<xsl:text> disclosure restricted by GSA ADP Schedule Contract with IBM Corp.&#xa;</xsl:text>
			<xsl:value-of select="$comment_start" />
			<xsl:text>&#xa;</xsl:text>
		</xsl:if>

		<xsl:if test="string-length($copyright)>0">
			<xsl:for-each
				select="str:tokenize(document($copyright),'&#xa;')">
				<xsl:text>&#xa;</xsl:text>
				<xsl:value-of select="$comment_start" />
				<xsl:text></xsl:text>
				<xsl:value-of select="." />
			</xsl:for-each>
		</xsl:if>
		<xsl:if test="$comment_start='*'">
			<xsl:text>&#xa;*/</xsl:text>
		</xsl:if>
	</xsl:template>


	<!--================================================================-->
	<!-- commentGeneratedBy                                             -->
	<!--                                                                -->
	<!-- Output a block comment identifying this program as the maker   -->
	<!-- of the Resource Bundle                                         -->
	<!--================================================================-->
	<xsl:template name="commentGeneratedBy">
		<xsl:if test="$comment_start='*'">
			<xsl:text>
				/*************************************************************
			</xsl:text>
		</xsl:if>
		<xsl:text></xsl:text>
		<xsl:value-of select="$comment_start" />
		<xsl:text> This file was generated by:</xsl:text>
		<xsl:for-each select="str:tokenize($versionlevel,'&#xa;')">
			<xsl:text>&#xa;</xsl:text>
			<xsl:value-of select="$comment_start" />
			<xsl:text></xsl:text>
			<xsl:value-of select="." />
		</xsl:for-each>
		<xsl:text>&#xa;</xsl:text>
		<xsl:value-of select="$comment_start" />
		<xsl:text> which included:</xsl:text>
		<xsl:for-each
			select="str:tokenize($versionlevel2,'&#xa;')">
			<xsl:text>&#xa;</xsl:text>
			<xsl:value-of select="$comment_start" />
			<xsl:text></xsl:text>
			<xsl:value-of select="." />
		</xsl:for-each>
		<xsl:if test="$comment_start='*'">
			<xsl:text>
				*************************************************************/
			</xsl:text>
		</xsl:if>
		<xsl:text>&#xa;</xsl:text>

	</xsl:template>



	<!--================================================================-->
	<!-- MsgText or LabelText                                           -->
	<!--                                                                -->
	<!--                                                                -->
	<!--================================================================-->
	<xsl:template match="MsgText | LabelText">
		<xsl:apply-templates select="*|text()" mode="msgText" />
	</xsl:template>

	<!--================================================================-->
	<!-- Explanation                                                    -->
	<!--                                                                -->
	<!--                                                                -->
	<!--================================================================-->
	<xsl:template match="Explanation">
		<xsl:apply-templates select="*|text()" mode="explanation" />
	</xsl:template>

	<!--================================================================-->
	<!-- SystemAction                                                   -->
	<!--                                                                -->
	<!--                                                                -->
	<!--================================================================-->
	<xsl:template match="SystemAction">
		<xsl:apply-templates select="*|text()" mode="explanation" />
	</xsl:template>

	<!--================================================================-->
	<!-- Action                                                         -->
	<!--                                                                -->
	<!--                                                                -->
	<!--================================================================-->
	<xsl:template match="Action">
		<xsl:apply-templates select="*|text()" mode="explanation" />
	</xsl:template>

	<!--================================================================-->
	<!-- OperatorResponse                                               -->
	<!--                                                                -->
	<!--                                                                -->
	<!--================================================================-->
	<xsl:template match="OperatorResponse">
		<xsl:apply-templates select="*|text()" mode="explanation" />
	</xsl:template>

	<!--================================================================-->
	<!-- AdminResponse                                                  -->
	<!--                                                                -->
	<!--                                                                -->
	<!--================================================================-->
	<xsl:template match="AdminResponse">
		<xsl:apply-templates select="*|text()" mode="explanation" />
	</xsl:template>

	<!--================================================================-->
	<!-- ProgrammerResponse                                             -->
	<!--                                                                -->
	<!--                                                                -->
	<!--================================================================-->
	<xsl:template match="ProgrammerResponse">
		<xsl:apply-templates select="*|text()" mode="explanation" />
	</xsl:template>

	<!--================================================================-->
	<!-- Level3Support                                                  -->
	<!--                                                                -->
	<!--                                                                -->
	<!--================================================================-->
	<xsl:template match="Level3Support">
		<xsl:apply-templates select="*|text()" mode="explanation" />
	</xsl:template>


	<!--================================================================-->
	<!-- mode=msgText                                                   -->
	<!--================================================================-->
	<!-- text()                                                         -->
	<!--                                                                -->
	<!--                                                                -->
	<!--================================================================-->
	<xsl:template match="text()" mode="msgText">
		<xsl:variable name="string" select="." />

		<!--================================================================-->
		<!--  Check to see if a whitespace character exists after a         -->
		<!--  Variable, backslash or q.  If one does, add a blank           -->
		<!--  since it will be removed with the normalize-space function.   -->
		<!--================================================================-->
		<xsl:if
			test="((starts-with($string, '&#x20;'))
                  or (starts-with($string, '&#x9;'))
                  or (starts-with($string, '&#xa0;'))
                  or (starts-with($string, '&#xa;'))
                  or (starts-with($string, '&#xD;')))
                  and (preceding-sibling::*[1][self::Variable or self::backslash or self::q]
                  or preceding-sibling::processing-instruction()[1])">
			<xsl:text> </xsl:text>
		</xsl:if>

		<xsl:if test="contains($string, '&#x22;')">
			<xsl:message terminate="no">
				WARNING: You should not have &quot; or &#x26;quot; in
				your MsgText or LabelText. Use &lt;q/&gt; instead.

				The
				<xsl:value-of select="name(../..)" />
				<xsl:text>with ID</xsl:text>
				<xsl:value-of select="../../@ID" />
				has a child element of type
				<xsl:value-of select="name(..)" />
				that contains the string:
				<xsl:value-of select="." />
			</xsl:message>
		</xsl:if>

		<xsl:choose>
			<xsl:when
				test="(translate($doubleapos,'true','TRUE')='TRUE') and
                      (translate(ancestor-or-self::*/@doubleapos,'false','FALSE')!='FALSE') and
                      ((translate($varonly,'true','TRUE')!='TRUE') or ((following-sibling::Variable) or (preceding-sibling::Variable)))">
				<xsl:variable name="string1"
					select='fixquote:fixQuote(.)' />
				<xsl:value-of select="normalize-space($string1)" />
			</xsl:when>
			<xsl:otherwise>
				<xsl:value-of select="normalize-space($string)" />
			</xsl:otherwise>
		</xsl:choose>

		<!--================================================================-->
		<!--  Check to see if a whitespace character exists before a        -->
		<!--  Variable, backslash or q.  If one does, add a blank           -->
		<!--  since it will be removed with the normalize-space function.   -->
		<!--================================================================-->

		<xsl:if
			test="(position() != 1) or
              (string-length(normalize-space(.))>0)">
			<xsl:if
				test="((substring($string,string-length($string),1)='&#x20;')
     or (substring($string, string-length($string), 1) = '&#x9;')
     or (substring($string, string-length($string), 1) = '&#xa0;')
     or (substring($string, string-length($string), 1) = '&#xa;')
     or (substring($string, string-length($string), 1) = '&#xD;'))
     and (following-sibling::*[1][self::Variable or self::backslash or self::q]
          or following-sibling::processing-instruction()[1])">
				<xsl:text> </xsl:text>
			</xsl:if>
		</xsl:if>

	</xsl:template>



	<!--================================================================-->
	<!-- <br> template                                                  -->
	<!-- Creates a new line in the output.                              -->
	<!--================================================================-->
	<xsl:template match="br" mode="msgText">
		<xsl:text>\n</xsl:text>
	</xsl:template>


	<!--================================================================-->
	<!-- <Variable> template                                            -->
	<!-- Creates a Variable element in the output.                      -->
	<!--================================================================-->
	<xsl:template match="Variable" mode="msgText">
		<xsl:value-of select="@formatSpec" />
	</xsl:template>

	<!--================================================================-->
	<!-- <q> template                                                   -->
	<!-- Creates double quote in the output.                            -->
	<!--================================================================-->
	<xsl:template match="q" mode="msgText">
		<xsl:text>\"</xsl:text>
	</xsl:template>

	<!--================================================================-->
	<!-- <backslash> template                                           -->
	<!-- Creates an escaped backslash ( \\ )                            -->
	<!--================================================================-->
	<xsl:template match="backslash" mode="msgText">
		<xsl:text>\\</xsl:text>
	</xsl:template>

	<!--================================================================-->
	<!-- <tab> template                                                 -->
	<!-- Creates a tab character                                        -->
	<!--================================================================-->
	<xsl:template match="tab" mode="msgText">
		<xsl:text>\t</xsl:text>
	</xsl:template>

	<!--================================================================-->
	<!-- <pre> template                                                 -->
	<!-- output each line of text, suffixed with a newline character    -->
	<!--================================================================-->
	<xsl:template match="pre | Pre" mode="msgText">
		<xsl:choose>
			<xsl:when test="contains(.,'&#xa;')">
				<xsl:for-each select="str:tokenize(.,'&#xa;')">
					<xsl:value-of select="." />
					<xsl:text>\n</xsl:text>
				</xsl:for-each>
			</xsl:when>
			<xsl:otherwise>
				<xsl:value-of select="." />
			</xsl:otherwise>
		</xsl:choose>
	</xsl:template>

	<!--================================================================-->
	<!-- mode=explanation                                               -->
	<!--================================================================-->
	<!-- text()                                                         -->
	<!--                                                                -->
	<!--                                                                -->
	<!--================================================================-->
	<xsl:template match="text()" mode="explanation">
		<xsl:variable name="string" select="." />


		<!--================================================================-->
		<!--  Check to see if a whitespace character exists after a         -->
		<!--  Variable, backslash or q.  If one does, add a blank           -->
		<!--  since it will be removed with the normalize-space function.   -->
		<!--================================================================-->
		<xsl:if
			test="((starts-with($string, '&#x20;'))
                  or (starts-with($string, '&#x9;'))
                  or (starts-with($string, '&#xa0;'))
                  or (starts-with($string, '&#xa;'))
                  or (starts-with($string, '&#xD;')))
                  and (preceding-sibling::*[1][self::Variable or self::backslash or self::q
                                               or self::var  or self::kbd  or self::strong
                                               or self::samp or self::sub  or self::sup
                                               or self::code or self::cite or self::em]
                       or preceding-sibling::processing-instruction()[1])">
			<xsl:text> </xsl:text>
		</xsl:if>

		<xsl:if test="contains($string, '&#x22;')">
			<xsl:message terminate="no">
				WARNING: You should not have &quot; or &#x26;quot; in
				your
				<xsl:value-of select="name(../..)" />
				. Use &lt;q/&gt; instead.

				The
				<xsl:value-of select="name(../..)" />
				<xsl:text>with ID</xsl:text>
				<xsl:value-of select="ancestor-or-self::Message/@ID" />
				has a child element of type
				<xsl:value-of select="name(..)" />
				that contains the string:
				<xsl:value-of select="." />
			</xsl:message>
		</xsl:if>

		<!-- Fix quote -->
		<xsl:variable name="string1">
			<xsl:choose>
				<xsl:when
					test="(ancestor-or-self::Message) and
                  (translate($doubleapos,'true','TRUE')='TRUE') and
                  (translate(ancestor-or-self::MsgText/@doubleapos,'false','FALSE')!='FALSE') and
                  ((translate($varonly,'true','TRUE')!='TRUE') or ((following-sibling::Variable) or (preceding-sibling::Variable)))">
					'fixquote:fixQuote(.)'
				</xsl:when>
                <xsl:otherwise>
                   <xsl:value-of select="normalize-space($string)" />
                </xsl:otherwise>
			</xsl:choose>
		</xsl:variable>

		<!-- Fix backslash -->
		<!-- xsl:variable name="string2"
			select='fixbackslash:fixBackslash($string1)' / -->

		<!-- Fix quotationmark -->
		<!-- xsl:variable name="string3"
			select='fixquotationmark:fixQuotationMark($string2)' / -->
		<xsl:variable name="string3"
                  select='$string1' />

		<xsl:value-of select="normalize-space($string3)" />


		<!--================================================================-->
		<!--  Check to see if a whitespace character exists before a        -->
		<!--  Variable, backslash or q.  If one does, add a blank           -->
		<!--  since it will be removed with the normalize-space function.   -->
		<!--================================================================-->

		<xsl:if
			test="(position() != 1) or
              (string-length(normalize-space(.))>0)">
			<xsl:if
				test="((substring($string3,string-length($string3),1)='&#x20;')
     or (substring($string3, string-length($string3), 1) = '&#x9;')
     or (substring($string3, string-length($string3), 1) = '&#xa0;')
     or (substring($string3, string-length($string3), 1) = '&#xa;')
     or (substring($string3, string-length($string3), 1) = '&#xD;'))
     and (following-sibling::*[1][self::Variable or self::backslash or self::q
                                  or self::var  or self::kbd  or self::strong
                                  or self::samp or self::sub  or self::sup
                                  or self::code or self::cite or self::em]
          or following-sibling::processing-instruction()[1])">
				<xsl:text> </xsl:text>
			</xsl:if>
		</xsl:if>

	</xsl:template>



	<!--================================================================-->
	<!-- <br> template                                                  -->
	<!-- Creates a new line in the output.                              -->
	<!--================================================================-->
	<xsl:template match="br" mode="explanation">
		<xsl:text>\n</xsl:text>
	</xsl:template>


	<!--================================================================-->
	<!-- <Variable> template                                            -->
	<!-- Creates a Variable element in the output.                      -->
	<!--================================================================-->
	<xsl:template match="Variable" mode="explanation">
		<xsl:value-of select="@formatSpec" />
	</xsl:template>

	<!--================================================================-->
	<!-- <q> template                                                   -->
	<!-- Creates double quote in the output.                            -->
	<!--================================================================-->
	<xsl:template match="q" mode="explanation">
		<xsl:text>\"</xsl:text>
	</xsl:template>

	<!--================================================================-->
	<!-- <backslash> template                                           -->
	<!-- Creates an escaped backslash ( \\ )                            -->
	<!--================================================================-->
	<xsl:template match="backslash" mode="explanation">
		<xsl:text>\\</xsl:text>
	</xsl:template>

	<!--================================================================-->
	<!-- <tab> template                                                 -->
	<!-- Creates a tab character                                        -->
	<!--================================================================-->
	<xsl:template match="tab" mode="explanation">
		<xsl:text>\t</xsl:text>
	</xsl:template>

	<!--================================================================-->
	<!-- <pre> template                                                 -->
	<!-- output each line of text, suffixed with a newline character    -->
	<!--================================================================-->
	<xsl:template match="pre | Pre" mode="explanation">
		<xsl:choose>
			<xsl:when test="contains(.,'&#xa;')">
				<xsl:for-each select="str:tokenize(.,'&#xa;')">
					<xsl:value-of select="." />
					<xsl:text>\n</xsl:text>
				</xsl:for-each>
			</xsl:when>
			<xsl:otherwise>
				<xsl:value-of select="." />
			</xsl:otherwise>
		</xsl:choose>
	</xsl:template>

	<!--================================================================-->
	<!-- <p> template                                                   -->
	<!-- Prepend with "\n"                                              -->
	<!--================================================================-->
	<xsl:template match="p" mode="explanation">
		<!-- Do not add newline if this is the beginning of text -->
		<xsl:if test="preceding-sibling::*">
			<xsl:text>\n</xsl:text>
		</xsl:if>
		<xsl:apply-templates select="*|text()" mode="explanation" />
	</xsl:template>

	<!--================================================================-->
	<!-- <example> template                                             -->
	<!-- Prepend with "\n  "                                            -->
	<!--================================================================-->
	<xsl:template match="example|examples" mode="explanation">
		<xsl:text>\n  </xsl:text>
		<xsl:apply-templates select="*|text()" mode="explanation" />
	</xsl:template>

	<!--================================================================-->
	<!-- <li> template                                                  -->
	<!-- Prepend with "\n-"                                             -->
	<!--================================================================-->
	<xsl:template match="li" mode="explanation">
		<xsl:text>\n-</xsl:text>
		<xsl:apply-templates select="*|text()" mode="explanation" />
	</xsl:template>

	<!--================================================================-->
	<!-- <table> template                                               -->
	<!-- Tables are not supported.  Remove contents                     -->
	<!--================================================================-->
	<xsl:template match="table" mode="explanation"></xsl:template>

	<!--================================================================-->
	<!-- <img> template                                                 -->
	<!-- Inline images are not supported.  Remove contents              -->
	<!--================================================================-->
	<xsl:template match="img" mode="explanation"></xsl:template>

	<!--================================================================-->
	<!-- <a> template                                                   -->
	<!-- Anchors are not supported.  Remove contents                    -->
	<!--================================================================-->
	<xsl:template match="a" mode="explanation"></xsl:template>

	<!--================================================================-->
	<!-- <dl>, <dt>, <dd> template                                      -->
	<!--================================================================-->
	<xsl:template match="dl" mode="explanation">
		<xsl:text>\n</xsl:text>
		<xsl:text>\n</xsl:text>
		<xsl:apply-templates select="*|text()" mode="explanation" />
	</xsl:template>

	<xsl:template match="dt" mode="explanation">
		<xsl:apply-templates select="*|text()" mode="explanation" />
		<xsl:text>\n</xsl:text>
	</xsl:template>

	<xsl:template match="dd" mode="explanation">
		<xsl:text>    </xsl:text>
		<xsl:apply-templates select="*|text()" mode="explanation" />
		<xsl:text>\n</xsl:text>
	</xsl:template>

	<!--================================================================-->
	<!-- template for presentational tags                               -->
	<!--================================================================-->

	<xsl:template
		match="abbr|acronym|cite|code|dfn|em|kbd|samp|strong|var"
		mode="explanation">
		<xsl:text>\"</xsl:text>
		<xsl:apply-templates select="*|text()" mode="explanation" />
		<xsl:text>\"</xsl:text>
	</xsl:template>

</xsl:stylesheet>

