Advanced = Advanced
Connector.Title = System for Cross-Domain Identity Management (SCIM) Connector
URL.label = SCIM Server URL
URL.desc = The URL for the SCIM Server
Endpoint.label = Resource Endpoint
Username.label = User Name
Username.desc = Basic Authentication with SCIM Server
Password.label = Password
AttributeFilter.label = Attribute Filter
AttributeFilter.desc = A comma separated list of attributes that should be returned by the server.
ModifyMethod.label = Update Method
ModifyMethod.desc = Choose method to use when updating
METHOD_0 = Patch with provided entry
METHOD_1 = Replace entire entry
proxy_label = Proxy Server
proxy_desc = Specify proxyhost\:port if you use a proxy server for connections.
SortByLabel = Sort by
SortByDesc = Specify the attribute to sort results by
SortOrderLabel = Sort order
ascending = ascending
descending = descending
proxy_user_label = Proxy Server User Name
proxy_user_desc = Used to authenticate to the proxy server.
proxy_pass_label = Proxy Server Password
proxy_pass_desc = Used if the proxy server user name is specified.
Tenant.label = Tenant
Tenant.desc = Specifies the tenant name if the User Name is a superuser or an API user. This is an IBM extension to SCIM.
IteratorFilter.label = Iterator Filter
IteratorFilter.desc = A filter in SCIM syntax limiting the entries returned when iterating
characterSet_label = Character Encoding
characterSet_desc = Character Encoding to be used when reading or writing the SCIM Requests
