time_desc = For Iterator mode this parameter controls how long the Connector will wait for new lines to appear once the end-of-file has been reached.\nAdditionally, it also specifies how long the Connector will attempt to lock the file (if locking is specified). A value less than or equal to zero (<\= 0) means "Wait forever.
time_label = Timeout (in seconds)
append_desc = Append the file when writing, otherwise overwrite.
append_label = Append on Output
exlock_desc = Acquire an exclusive (shared if reading) lock on this file. Operating system dependant.
exlock_label = Lock file
path_desc = File Path to use. The special value <> means that the connector should use standard I/O streams
path_label = File Path
path_sript_label = Select...
path_script_help = Browse file system
CONN_TITLE = File Connector
Advanced = Advanced
