CONN_DESC = Lightweight Directory Access Protocol (v2/v3)
CONN_TITLE = JLDAP Connector
SORT_ATTRIBUTE_DESC = Sort search/selection on specific attribute
SORT_ATTRIBUTE_LABEL = Sort Attribute
VLV_PAGE_SIZE_DESC = Specify a page size for Virtual List View iteration
VLV_PAGE_SIZE_LABEL = Virtual List View Page Size
BER_TRACE_DESC = Trace LDAP BER packets to file
BER_TRACE_LABEL = LDAP Trace File
AD_PW_DESC = Map userPassword to unicodePwd for ActiveDirectory password update
AD_PW_LABEL = Auto Map AD Password
RENAME_DESC = If the server does not support rename, simulate it with delete/add operations
RENAME_LABEL = Simulate rename
JNDI_XTRA_PROVIDER_DESC = Additional JNDI provider parameters (name\:value one for each line)
JNDI_XTRA_PROVIDER_LABEL = Extra Provider Parameters
LDAP_AUTH_DESC = Type of LDAP authentication
LDAP_AUTH_LABEL = Authentication Method
BIN_ATTRIB_DESC = List of attributes that are treated as binary (one attribute per line)
BIN_ATTRIB_LABEL = Binary Attributes
PAGE_SIZE_DESC = If the server supports paged-find you can specify the number of entries returned pr page
PAGE_SIZE_LABEL = Page Size
PAGE_SIZE_SCRPT_LABEL = Check...
PW_DESC = Password associated with Login username
PW_LABEL = Login password
PUMP_DESC = Specify the filter used when pumping the directory (size limits)
PUMP_LABEL = Pump Filter
REFERRAL_DESC = How to treat referrals
REFERRAL_LABEL = Referrals
RETURN_ATTRIB_DESC = List of attributes to return (one attribute per line). Empty  all
RETURN_ATTRIB_LABEL = Return attributes
SCRPT_TEST_LABEL = Test Script
SEARCH_BASE_DESC = Search base in directory
SEARCH_BASE_LABEL = Search Base
SEARCH_BASE_SCRPT_LABEL = Contexts
SEARCH_BASE_SCRPT_HELP = Query LDAP server for a list of naming contexts (if server supports it)
SEARCH_FILTER_DESC = Search filter used when iterating the directory
SEARCH_FILTER_LABEL = Search Filter
SEARCH_SCOPE_DESC = * subtree\n\tsearch all levels from search base and below\n\n* onelevel\n\tsearch only immediate children of search base\n\n* baselevel\n\tsearch only exactly the search base\n\n
SEARCH_SCOPE_LABEL = Search Scope
SIZE_LIMIT_DESC = Max number of entries to return during a search (0  All)
SIZE_LIMIT_LABEL = Size Limit
TIME_LIMIT_DESC = Timeout in seconds (0  Forever)
TIME_LIMIT_LABEL = Time Limit
URL_DESC = The LDAP server host/port
URL_LABEL = LDAP URL
USE_SSL_DESC = Uses secure sockets layer for communication with LDAP server
USE_SSL_LABEL = Use SSL
USER_NAME_DESC = Distinguished name for login (leave blank for anonymous)
USER_NAME_LABEL = Login username
LDAP_ADD_ATTR_DESC = Add attributes to entry instead of Replace
LDAP_ADD_ATTR_LABEL = Add Attributes (instead of replace)
