CONN_DESC = A Connector capable of listening to or emiting local or remote Server API notifications
SNL_CONN_TYPE_DESC = Specifies whether the Connector will listen for or emit local or remote Server API notifications.
SNL_CONN_TYPE_LABEL = Connection Type
SNL_URL_DESC = The URL used to connect to the remote Security Verify Directory Integrator Server system (only relevant for remote ConnectionType).
SNL_URL_LABEL = RMI URL
SNL_USERNAME_DESC = The username the Connector uses to authenticate to the Security Verify Directory Integrator server.
SNL_USERNAME_LABEL = Username
SNL_PASSWORD_DESC = The password the Connector uses to authenticate to the Security Verify Directory Integrator server.
SNL_PASSWORD_LABEL = Password
SNL_CONFIG_INSTANCE_ID_DESC = If specified the Connector will only report notifications which have the specified Config Instance ID.
SNL_CONFIG_INSTANCE_ID_LABEL = Filter Config Instance ID
SNL_NOTIFICATION_ID_DESC = If specified the Connector will only report notifications which have the specified notification ID.
SNL_NOTIFICATION_ID_LABEL = Filter Notification ID
SNL_TIMEOUT_DESC = Max number of seconds to wait for a new notification to receive (0 \= Wait Forever).
SNL_TIMEOUT_LABEL = Timeout (seconds)
SNL_DI_ALL_DESC = If checked the Connector will receive 'di.*' event notifications.
SNL_DI_ALL_LABEL = Receive All Server API Events
SNL_DI_CI_ALL_DESC = If checked the Connector will receive 'di.ci.*' event notifications.
SNL_DI_CI_ALL_LABEL = Receive All Config Instance Events
SNL_DI_CI_START_DESC = If checked the Connector will receive 'di.ci.start' event notifications.
SNL_DI_CI_START_LABEL = Receive Config Instance Start Events
SNL_DI_CI_STOP_DESC = If checked the Connector will receive 'di.ci.stop' event notifications.
SNL_DI_CI_STOP_LABEL = Receive Config Instance Stop Events
SNL_DI_CI_FILE_UPDATED_DESC = If checked the Connector will receive 'di.ci.file.updated' event notifications.
SNL_DI_CI_FILE_UPDATED_LABEL = Receive Configuration Updated Events
SNL_DI_AL_ALL_DESC = If checked the Connector will receive 'di.al.*' event notifications.
SNL_DI_AL_ALL_LABEL = Receive All AssemblyLine Events
SNL_DI_AL_START_DESC = If checked the Connector will receive 'di.al.start' event notifications.
SNL_DI_AL_START_LABEL = Receive AssemblyLine Start Events
SNL_DI_AL_STOP_DESC = If checked the Connector will receive 'di.al.stop' event notifications.
SNL_DI_AL_STOP_LABEL = Receive AssemblyLine Stop Events
SNL_DI_SERVER_STOP_DESC = If checked the Connector will receive 'di.server.stop' event notifications.
SNL_DI_SERVER_STOP_LABEL = Receive Server Shutdown Event
SNL_HAS_CUSTOM_NOTIFICATIONS_DESC = If checked the Connector will receive the additional/custom notifications specified in the 'Custom Notification types' parameter.
SNL_HAS_CUSTOM_NOTIFICATIONS_LABEL = Use Custom Notification
SNL_CUSTOM_NOTIFICATIONS_DESC = The types of additional/custom Server API notifications which the Connector will listen to. Each notification type must be typed on a separate line.
SNL_CUSTOM_NOTIFICATIONS_LABEL = Custom Notification types
CONN_TITLE = Server Notifications Connector
Localized.remote = remote
Localized.local = local
Advanced = Advanced
