##{PropertiesConnector} savedBy=administrator, saveDate=Tue Apr 05 16:37:10 IST 2011
baseURLs=http://9.182.176.98
userid=maxadmin
{protect}-password={encr}PZaqpA9EaoMu17F5dnIJRv5OADW58ATk21SAsZ6Do5O4I41iJ1AO/61ldSaS3QHvDhKVZJF1O7FFjTgzwALbqDCCsVRVLsj5BHFNOwKINGKmcZb/bRyZ4YnlcZHcX6H9mm1In8hcMsE2UoEme3o7Bajw7nBVRiFnMfzXE449DQk=
objectStructure=MXASSET
externalSystem=EXTSYS1
queryEnterpriseService=QueryMXASSETInterface
syncEnterpriseService=SyncMXASSETInterface
