/*
 * Copyright IBM Corp. 2025
 *
 * SPDX-License-Identifier: Apache-2.0
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.15 at 03:01:16 PM CEST 
//

package com.ibm.di.ui.curi.bind;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ibm.di.ui.curi.bind package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Provider_QNAME = new QName("http://www.example.org/curi", "Provider");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ibm.di.ui.curi.bind
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Datasource }
     * 
     */
    public Datasource createDatasource() {
        return new Datasource();
    }

    /**
     * Create an instance of {@link DatasetColumns }
     * 
     */
    public DatasetColumns createDatasetColumns() {
        return new DatasetColumns();
    }

    /**
     * Create an instance of {@link ProviderItem }
     * 
     */
    public ProviderItem createProviderItem() {
        return new ProviderItem();
    }

    /**
     * Create an instance of {@link Datasources }
     * 
     */
    public Datasources createDatasources() {
        return new Datasources();
    }

    /**
     * Create an instance of {@link DatasetParameterValue }
     * 
     */
    public DatasetParameterValue createDatasetParameterValue() {
        return new DatasetParameterValue();
    }

    /**
     * Create an instance of {@link DatasetItemProperty }
     * 
     */
    public DatasetItemProperty createDatasetItemProperty() {
        return new DatasetItemProperty();
    }

    /**
     * Create an instance of {@link DatasetParameter }
     * 
     */
    public DatasetParameter createDatasetParameter() {
        return new DatasetParameter();
    }

    /**
     * Create an instance of {@link DatasetParameters }
     * 
     */
    public DatasetParameters createDatasetParameters() {
        return new DatasetParameters();
    }

    /**
     * Create an instance of {@link DatasetItems }
     * 
     */
    public DatasetItems createDatasetItems() {
        return new DatasetItems();
    }

    /**
     * Create an instance of {@link DatasetColumn }
     * 
     */
    public DatasetColumn createDatasetColumn() {
        return new DatasetColumn();
    }

    /**
     * Create an instance of {@link DatasetItem }
     * 
     */
    public DatasetItem createDatasetItem() {
        return new DatasetItem();
    }

    /**
     * Create an instance of {@link Provider }
     * 
     */
    public Provider createProvider() {
        return new Provider();
    }

    /**
     * Create an instance of {@link Dataset }
     * 
     */
    public Dataset createDataset() {
        return new Dataset();
    }

    /**
     * Create an instance of {@link Datasets }
     * 
     */
    public Datasets createDatasets() {
        return new Datasets();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Provider }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/curi", name = "Provider")
    public JAXBElement<Provider> createProvider(Provider value) {
        return new JAXBElement<Provider>(_Provider_QNAME, Provider.class, null, value);
    }

}
