/*
 * Copyright contributors to the SyncWeave project
 *
 * SPDX-License-Identifier: Apache-2.0
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.15 at 03:01:16 PM CEST 
//

package com.ibm.di.ui.curi.bind;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for ProviderItem complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProviderItem">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="label" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="baseUrl" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="uri" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *         &lt;element name="useFIPS" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="datasetsUri" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *         &lt;element name="datasourcesUri" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="remote" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="sso" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="externalProviderId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProviderItem", propOrder = {
    "id",
    "label",
    "baseUrl",
    "uri",
    "useFIPS",
    "datasetsUri",
    "datasourcesUri",
    "remote",
    "type",
    "description",
    "sso",
    "externalProviderId"
})
public class ProviderItem {

    @XmlElement(required = true)
    protected String id;
    @XmlElement(required = true)
    protected String label;
    @XmlElement(required = true)
    protected String baseUrl;
    @XmlElement(required = true)
    @XmlSchemaType(name = "anyURI")
    protected String uri;
    @XmlElement(defaultValue = "false")
    protected boolean useFIPS;
    @XmlElement(required = true)
    @XmlSchemaType(name = "anyURI")
    protected String datasetsUri;
    @XmlElement(required = true)
    protected String datasourcesUri;
    protected boolean remote;
    @XmlElement(required = true)
    protected String type;
    @XmlElement(required = true)
    protected String description;
    @XmlElement(defaultValue = "false")
    protected boolean sso;
    @XmlElement(required = true)
    protected String externalProviderId;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the label property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabel() {
        return label;
    }

    /**
     * Sets the value of the label property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabel(String value) {
        this.label = value;
    }

    /**
     * Gets the value of the baseUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBaseUrl() {
        return baseUrl;
    }

    /**
     * Sets the value of the baseUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBaseUrl(String value) {
        this.baseUrl = value;
    }

    /**
     * Gets the value of the uri property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUri() {
        return uri;
    }

    /**
     * Sets the value of the uri property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUri(String value) {
        this.uri = value;
    }

    /**
     * Gets the value of the useFIPS property.
     * 
     */
    public boolean isUseFIPS() {
        return useFIPS;
    }

    /**
     * Sets the value of the useFIPS property.
     * 
     */
    public void setUseFIPS(boolean value) {
        this.useFIPS = value;
    }

    /**
     * Gets the value of the datasetsUri property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatasetsUri() {
        return datasetsUri;
    }

    /**
     * Sets the value of the datasetsUri property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatasetsUri(String value) {
        this.datasetsUri = value;
    }

    /**
     * Gets the value of the datasourcesUri property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatasourcesUri() {
        return datasourcesUri;
    }

    /**
     * Sets the value of the datasourcesUri property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatasourcesUri(String value) {
        this.datasourcesUri = value;
    }

    /**
     * Gets the value of the remote property.
     * 
     */
    public boolean isRemote() {
        return remote;
    }

    /**
     * Sets the value of the remote property.
     * 
     */
    public void setRemote(boolean value) {
        this.remote = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the sso property.
     * 
     */
    public boolean isSso() {
        return sso;
    }

    /**
     * Sets the value of the sso property.
     * 
     */
    public void setSso(boolean value) {
        this.sso = value;
    }

    /**
     * Gets the value of the externalProviderId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExternalProviderId() {
        return externalProviderId;
    }

    /**
     * Sets the value of the externalProviderId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExternalProviderId(String value) {
        this.externalProviderId = value;
    }

}
