CONN_DESC = Server side HTTP Connector
CONN_TITLE = HTTP Server Connector
TCP_PORT_DESC = Port for incoming HTTP requests
TCP_PORT_LABEL = TCP Port
TCP_DATA_AS_PROP_DESC = Reads/Writes TCP Data as Entry Properties, else reads/writes them as Entry Attributes
TCP_DATA_AS_PROP_LABEL = TCP Data as Properties
HEADER_AS_PROP_LABEL = HTTP Headers as Properties
HEADER_AS_PROP_DESC = Reads/Writes HTTP headers and data as Entry Properties, else reads/writes them as Entry Attributes
AUTH_CONN_LABEL = Auth Connector
AUTH_CONN_DESCR = A Connector used for authentication via a successful Lookup with a Link Criteria matching the $username and $password attributes.
HTTP_AUTH_LABEL = HTTP Basic Authentication
HTTP_AUTH_DESC = Request HTTP Basic authentication
AUTH_REALM_LBL = Auth Realm
AUTH_REALM_DESC = The basic-realm sent to the client in case authentication is requested
USE_SSL_LBL = Use SSL
USE_SSL_DESC = Use SSL when accepting client connections
CLIENT_AUTH_LBL = Require Client Authentication
CLIENT_AUTH_DESC = Mandate client authentication using SSL
CONTENT_TYPE_LBL = Content Type
CONTENT_TYPE_DESC = Specifies the content-type HTTP header to use when sending data.
MSG_CHUNKED_DESC = If checked, the http body of the message is transferred as a series of chunks
MSG_CHUNKED_LBL = Chunked Transfer Encoding
TCP_BACKLOG_DESC = The maximum queue length for incoming connections. If a connection request arrives when the queue is full, the connection will be refused.
TCP_BACKLOG_LABEL = Connection Backlog
Localized.none = (none)
Advanced = Advanced
IDLE_TIMEOUT_LABEL = Idle Timeout
IDLE_TIMEOUT_DESC = Number of seconds before closing idle connections. Default is 120.
