CONN_DESC = JDBC & ODBC
CONN_TITLE = JDBC Connector
para_desc = Alter session statements
para_label = Alter Session Statements
query_desc = SQL select statement to discover meta data (update, lookup and addonly modes)
query_label = Meta Query
source_desc = JDBC URL
source_label = JDBC URL
login_desc = Login user
login_label = Username
pass_label = Password
schema_label = Schema
val_label = Return null values
select_desc = SQL Select for Iterator mode (also used as statement stub (without "WHERE" keyword) for Link Criteria)
select_label = SQL Select
find_desc = SQL Select for lookups
find_label = SQL Lookup
insert_desc = SQL Insert statement
insert_label = SQL Insert
update_desc = SQL Update statement
update_label = SQL Update
delete_desc = SQL Delete statement
delete_label = SQL Delete
table_desc = Database table name
table_label = Table Name
table_script_label = Select...
table_script_help = Query server for a list of available tables (may be a big one\!)
driver_desc = JDBC Driver Class
driver_label = JDBC Driver
format_desc = Default date format when converting strings to dates
format_label = Date Format
commit_desc = Controls when database transactions are commited. Manual means user must call commit()
commit_label = Commit
JDBC_PROVIDER_DESC = Additional JDBC provider parameters (name\:value one for each line)
JDBC_PROVIDER_LABEL = Extra Provider Parameters
prepared_label = Use Prepared Statement
prepared_description = Try to precompile SQL Statements, fall back to normal SQL
Localized.After.every.database.operation = After every database operation
Localized.After.every.database.operation.Including.Select = After every database operation (Including Select)
Localized.On.Connector.close = On Connector close
Localized.Manual = Manual
Localized.End.of.Cycle = End Of Cycle
inspad_label = Disable padding for Insert
inspad_description = Disables padding for the insert operation in the Add only and Delta modes.
updpad_label = Disable padding for Update
updpad_description = Disables padding for the update operation in the Update and Delta modes.
lookuppad_label = Disable padding for Lookup
lookuppad_description = Disables padding for the lookup operation in the Update, Lookup, Delete and Delta modes.
Advanced = Advanced
expose_null_desc = If the checkbox is enabled then null valued attributes return an empty value. If left unchecked then the defined null behavior is followed. The default null behavior will remove the attribute which receives null.
custom_prepared_description = Custom SQL statements are prepared statements
custom_prepared_label = Use custom SQL prepared statements
auto_create_label = Auto-create table
auto_create_description = If the specified table does not exist, a new table based on the attribute map or schema is created.
