Advanced = Advanced
Connector.title = QRadar Connector
useSyslog.label = Output to syslog
useSyslog.desc = Enable to send output to syslog, otherwise the Connector produces LEEF file(s)
splitOnEvents.label = Maximum events per file
splitOnEvents.desc = If left blank or value < 0 then no splitting will occur. Otherwise multiple files may be written, each with no more than this number of events
severity.label = Severity
severity.desc = Default severity
port.label = Port
port.desc = Default syslogd port
hostname.label = Hostname
hostname.desc = Default target hostname
filePath.label = File path
filePath.desc = Pathname of the output file to write. Note that if splitting is enabled, multiple files will be created using a numeric counter suffix
facility.label = Facility
facility.desc = Default facility
detailedLog.label = Detailed Log
detailedLog.desc = Enable this checkbox to get debugging messages written to the log
dateMask.label = Date format mask
dateMask.desc = Java SimpleDateFormat mask to use for writing date values (e.g. MMM dd yy HH\:mm\:ss.SSS z)
