<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://www.ibm.com/xmlns/prod/tdi/72/api"
	xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://www.ibm.com/xmlns/prod/tdi/72/api"
	elementFormDefault="qualified" attributeFormDefault="unqualified">


	<complexType name="CustomNotification">
		<sequence minOccurs="0" maxOccurs="1">
			<element name="data" type="tns:Data"></element>
		</sequence>
		<attribute name="type" type="string" use="required"></attribute>
		<attribute name="id" type="string" use="required"></attribute>
	</complexType>


	<complexType name="Data">
		<simpleContent>
			<extension base="string">
				<attribute name="type" type="tns:DataMediaType"
					use="optional" default="text/plain" />
			</extension>
		</simpleContent>
	</complexType>

	<simpleType name="DataMediaType">
		<restriction base="string">
			<pattern value="text/.+"></pattern>
			<pattern value=".+/xml"></pattern>
			<pattern value=".+/.+/json"></pattern>
			<pattern value=".+/.+\+xml"></pattern>
			<pattern value="application/octet-stream"></pattern>
			<pattern value=".+/.+"></pattern>
		</restriction>
	</simpleType>

	<element name="customNotification" type="tns:CustomNotification">
	</element>
</schema>