<?xml version="1.0" encoding="UTF-8"?><MetamergeConfig Cycle="3" UUID="9d59b7f3-ad9c-4866-b11b-96e9604f964d" created="Thu Sep 11 14:16:41 CEST 2014" createdBy="Administrator" main="GRC_Spec" modified="Thu Sep 11 14:17:13 CEST 2014" modifiedBy="Administrator" project="ScriptedComponents" version="7.1.1">
    <Script name="GRC_Spec">
        <ModTime>1410437833086</ModTime>
        <parameter name="includeFiles"/>
        <parameter name="script"><![CDATA[grcSpec = {  
   "OPSS-Inc:PotentExpDesc":{  
      "id":"493",
      "dataType":"STRING_TYPE"
   },
   "Orphan":{  
      "id":"65",
      "dataType":"STRING_TYPE"
   },
   "OPSS-Inc-IT:Severity":{  
      "id":"504",
      "dataType":"ENUM_TYPE"
   },
   "OPSS-Inc-IT:Host IP Address":{  
      "id":"507",
      "dataType":"STRING_TYPE"
   },
   "OPSS-Inc:RepToReg":{  
      "id":"496",
      "dataType":"ENUM_TYPE"
   },
   "OPSS-Inc:Occurrence Date":{  
      "id":"489",
      "dataType":"DATE_TYPE"
   },
   "Location":{  
      "id":"57",
      "dataType":"STRING_TYPE"
   },
   "OPSS-Inc:PotentExp":{  
      "id":"492",
      "dataType":"MULTI_VALUE_ENUM"
   },
   "Name":{  
      "id":"55",
      "dataType":"STRING_TYPE"
   },
   "Last Modified By":{  
      "id":"61",
      "dataType":"INTEGER_TYPE"
   },
   "OPSS-Inc:RegFine":{  
      "id":"497",
      "dataType":"ENUM_TYPE"
   },
   "OPSS-Inc:RegViolated":{  
      "id":"494",
      "dataType":"ENUM_TYPE"
   },
   "OPSS-Inc:Discovery Date":{  
      "id":"490",
      "dataType":"DATE_TYPE"
   },
   "Last Modification Date":{  
      "id":"60",
      "dataType":"DATE_TYPE"
   },
   "OPSS-Inc:Priority":{  
      "id":"488",
      "dataType":"ENUM_TYPE"
   },
   "OPSS-Inc-IT:Message":{  
      "id":"509",
      "dataType":"STRING_TYPE"
   },
   "OPSS-Inc-IT:Host":{  
      "id":"506",
      "dataType":"STRING_TYPE"
   },
   "OPSS-Inc:Owner":{  
      "id":"485",
      "dataType":"STRING_TYPE"
   },
   "Resource ID":{  
      "id":"28",
      "dataType":"ID_TYPE"
   },
   "Created By":{  
      "id":"59",
      "dataType":"INTEGER_TYPE"
   },
   "OPSS-Inc-IT:Host Status":{  
      "id":"508",
      "dataType":"ENUM_TYPE"
   },
   "OPSS-Inc-IT:Application":{  
      "id":"505",
      "dataType":"STRING_TYPE"
   },
   "OPSS-Inc:What Happened":{  
      "id":"487",
      "dataType":"STRING_TYPE"
   },
   "OPSS-Inc:Status":{  
      "id":"486",
      "dataType":"ENUM_TYPE"
   },
   "OPSS-Inc:Type":{  
      "id":"483",
      "dataType":"MULTI_VALUE_ENUM"
   },
   "OPSS-Inc:Source":{  
      "id":"484",
      "dataType":"MULTI_VALUE_ENUM"
   },
   "OPSS-Inc:PolViolated":{  
      "id":"495",
      "dataType":"ENUM_TYPE"
   },
   "OPSS-Inc:Fine Amount":{  
      "id":"503",
      "dataType":"CURRENCY_TYPE"
   },
   "OPSS-Inc:Closed Date":{  
      "id":"491",
      "dataType":"DATE_TYPE"
   },
   "Description":{  
      "id":"56",
      "dataType":"STRING_TYPE"
   },
   "Creation Date":{  
      "id":"58",
      "dataType":"DATE_TYPE"
   },
   "Comment":{  
      "id":"62",
      "dataType":"STRING_TYPE"
   }
}]]></parameter>
    </Script>
</MetamergeConfig>