##
## This file is read by ibmditk/ibmdisrv on startup
##
## Enter <name>=<value> to set system properties.
## Enter !include <file | url> to include other files
##

com.metamerge.securityTransformation=DES/ECB/NoPadding

##
## Modify the line below to add your own jar/zip files.
## The property may specify several directories or jar files, separated by the Java Property "path.separator",
## which is ":" on Linux and ";" on Windows
## Directories will be searched recursively by the TDILoader for jar files containing classes and resources.
## Only files with a ".zip" or ".jar" extension are searched.
# com.ibm.di.loader.userjars=c:\myjars

## Custom class for ibmjs options to let us choose regex library
ibmjs.options=com.ibm.di.script.ScriptEngineOptions

## Regex library selection (java or jakarta). Using jakarta requires the Jakarta regex library (not included)
com.ibm.di.scriptengine.regex=java

##
## Modify the line below to enable the config autoload feature. When this property is defined, the "ibmdisrv -d" command
## line will look for *.xml files in the directory specified by this property and start each one.
##
# com.ibm.di.server.autoload=autoload.tdi

##
## Modify the line below to specify the location of the Library Resources.
## The default value is <HOMEDIR>/tdilibrary
# com.ibm.di.admin.library.dir=

##
## SYSTEM STORE
##

## Location of the database (embedded mode) - Cloudscape 10
com.ibm.di.store.database=TDISysStore
com.ibm.di.store.jdbc.driver=org.apache.derby.jdbc.EmbeddedDriver
com.ibm.di.store.jdbc.urlprefix=jdbc:derby:
#com.ibm.di.store.jdbc.user=APP
#{protect}-com.ibm.di.store.jdbc.password=APP


## Location of the database to connect (networked mode) - Cloudscape 10 - DerbyClient driver
#com.ibm.di.store.database=jdbc:derby://localhost:1527/C:\dev\IBM\TDI\V6.1_060608a\TDISysStore;create=true
#com.ibm.di.store.jdbc.driver=org.apache.derby.jdbc.ClientDriver
#com.ibm.di.store.jdbc.urlprefix=jdbc:derby:
#com.ibm.di.store.jdbc.user=APP
#{protect}-com.ibm.di.store.jdbc.password=APP
#
## Details for starting Cloudscape in network mode.
## Note: If the com.ibm.di.store.hostname is set to localhost then remote connections will not be allowed.
## If it is set to the IP address of the local machine - then remote clients can access this Cloudscape
## instance by mentioning the IP address. The network server can only be started for the local machine.
#
#com.ibm.di.store.start.mode=automatic
#com.ibm.di.store.hostname=localhost
#com.ibm.di.store.port=1527
#com.ibm.di.store.sysibm=true


# the varchar(length) for the ID columns used in system store and pes connector tables
com.ibm.di.store.varchar.length=512


## create statements for system store tables (CloudScape 5.1)
#com.ibm.di.store.create.delta.systable=CREATE TABLE {0} (ID VARCHAR(VARCHAR_LENGTH) NOT NULL, SEQUENCEID int, VERSION int)
#com.ibm.di.store.create.delta.store=CREATE TABLE {0} (ID VARCHAR(VARCHAR_LENGTH) NOT NULL, SEQUENCEID int, ENTRY long varbinary )
#com.ibm.di.store.create.property.store=CREATE TABLE {0} (ID VARCHAR(VARCHAR_LENGTH) NOT NULL, ENTRY long varbinary )
#com.ibm.di.store.create.checkpoint.store=CREATE TABLE {0} (ID VARCHAR(VARCHAR_LENGTH) NOT NULL, ALSTATE long varbinary, ENTRY long varbinary, TCB long varbinary )
#com.ibm.di.store.create.sandbox.store=CREATE TABLE {0} (ID VARCHAR(VARCHAR_LENGTH) NOT NULL, ENTRY long varbinary )

## create statements for system store tables (CloudScape 10)
com.ibm.di.store.create.delta.systable=CREATE TABLE {0} (ID VARCHAR(VARCHAR_LENGTH) NOT NULL, SEQUENCEID int, VERSION int)
com.ibm.di.store.create.delta.store=CREATE TABLE {0} (ID VARCHAR(VARCHAR_LENGTH) NOT NULL, SEQUENCEID int, ENTRY BLOB )
com.ibm.di.store.create.property.store=CREATE TABLE {0} (ID VARCHAR(VARCHAR_LENGTH) NOT NULL, ENTRY BLOB )
com.ibm.di.store.create.checkpoint.store=CREATE TABLE {0} (ID VARCHAR(VARCHAR_LENGTH) NOT NULL, ALSTATE BLOB, ENTRY BLOB, TCB BLOB )
com.ibm.di.store.create.sandbox.store=CREATE TABLE {0} (ID VARCHAR(VARCHAR_LENGTH) NOT NULL, ENTRY BLOB )
com.ibm.di.store.create.recal.conops=CREATE TABLE {0} (METHOD varchar(VARCHAR_LENGTH), RESULT BLOB, ERROR BLOB)


# Set a customized SQL statement for creation of the Tombstone Manager table. Keep the same table and field names.
#com.ibm.di.store.create.tombstones=CREATE TABLE IDI_TOMBSTONE ( ID INT GENERATED ALWAYS AS IDENTITY, COMPONENT_TYPE_ID INT, EVENT_TYPE_ID INT, START_TIME TIMESTAMP, CREATED_ON TIMESTAMP, COMPONENT_NAME VARCHAR(1024), CONFIGURATION VARCHAR(1024), EXIT_CODE INT, ERROR_DESCR VARCHAR(1024), STATS LONG VARCHAR FOR BIT DATA, GUID VARCHAR(1024) NOT NULL, USER_MESSAGE VARCHAR(1024), UNIQUE (ID, GUID))


# the ibmsnap_commitseq column name used by the RDBMS changelog connector
com.ibm.di.conn.rdbmschlog.cdcolname=ibmsnap_commitseq

## server authentication
## example
## javax.net.ssl.trustStore=d:\test\KeyRings\namtp2.jks
## javax.net.ssl.trustStorePassword=secret
## javax.net.ssl.trustStoreType=jks

javax.net.ssl.trustStore=testadmin.jks
{protect}-javax.net.ssl.trustStorePassword={encr}O6+SCWHZykymtp6cUids1Jl0mRDa9g59kPYWQlJ7U4A4Xp9NpnJbOgRH5rchTeSclVey9uTOo+H4r5kCeMmrEjKCZM1s0yLcJcbuUbO/cdj7FTQL84UWaFFwMQ1IjmbX0rzuyDprEwKBxKbfB/Ai34X5vwB5p6FlO5Mvi/ZQAgs=
javax.net.ssl.trustStoreType=jks

## client authentication
## example
## javax.net.ssl.keyStore=d:\test\KeyRings\namtp2.jks
## javax.net.ssl.keyStorePassword=secret
## javax.net.ssl.keyStoreType=jks

javax.net.ssl.keyStore=testadmin.jks
{protect}-javax.net.ssl.keyStorePassword={encr}Qzq739lWe1OYYX118kmHrHdRvbotvTGgbnFIKryuOmqR3zDXNQ/zEys88Gqy33yZf7InWkk6PXsMpn7qy5zkdm2JtCivHwesTgKLhZ7qzVDV2ieFrktgIvKXlgTcOT85n4iPDCtzEH+S9BLQAZQbigI0s0W1K/tdyPhhjYSe9V8=
javax.net.ssl.keyStoreType=jks

SSL_PROVIDER_CLASS=progress.message.net.ssl.jsse.jsseSSLImpl
sonic.mq.ssl.keyStoreAlias=tdi

## Turns on java debug
# javax.net.debug=true

## java interpreter override
# com.ibm.di.javacmd=
# com.ibm.di.installdir=

# Location of directory where the JRE SDI will use is installed
com.ibm.di.jvmdir=C:\dev\IBM\TDI\V6.1_060608a/jvm

## Limits the number of threads IDI uses
## Must be set higher than 3 to have any effect

# com.ibm.di.server.maxThreadsRunning=500

com.ibm.di.server.securemode=false
com.ibm.di.server.keystore=testserver.jks
com.ibm.di.server.key.alias=server


## Server API properties
## ---------------------

api.on=true
api.user.registry=serverapi/registry.txt
api.user.registry.encryption.on=false

api.remote.on=false
api.remote.ssl.on=true
api.remote.ssl.client.auth.on=true
api.remote.naming.port=1099
api.truststore=testserver.jks
{protect}-api.truststore.pass={encr}dkN8mZoBIgJKycOOSrShqc08dpxnj2RWcXMTL5ut9Mt1S3vPpAMy5f6YQz2J/llH+fpNIYH7PbDLNUwr+1ym7Ga8aXRFkcf9eAFSjC8wkNB0hGB51ller4WYMR/LS5xdZH0xbdvQEcQUTAuS/kfxKrNp15IVlcfEGQ43D6SYJu0=

## Specifies a list of IP addresses to accept non SSL connections from (host names are not accepted).
## Use space, comma or semicolon as delimiter between IP addresses. This property is only taken into account
## when api.remote.ssl.on is set to false.
## api.remote.nonssl.hosts=

api.jmx.on=false
api.jmx.remote.on=false

## The configuration files placed in this folder can be edited through the Server API.
## Configuration files placed in other folders cannot be edited through the Server API.
api.config.folder=C:\dev\IBM\TDI\V6.1_060608a\configs

## Timeout in minutes for configuration locks. A value of 0 means no timeout.
api.config.lock.timeout=0

## Specifies if the Server API methods for custom method invocation (Session.invokeCustom(...)) are allowed to be used.
## When api.custom.method.invoke.on is set to false and the Server API methods for custom method invocation are used,
## then an exception will be thrown.
## Only classes listed in api.custom.method.invoke.allowed.classes are allowed to be directly invoked.
## The default value is false.
api.custom.method.invoke.on=false

## Specifies the list of classes which can be directly invoked by the Server API methods for custom
## method invocation (Session.invokeCustom(...)).
## This property is only taken into account if api.custom.method.invoke.on is set to true.
## The classes in this list must be separated by a space, a comma or a semicolon.
## Example:
## api.custom.method.invoke.allowed.classes=com.ibm.MyClass,com.ibm.MyOtherClass
## In the above example only methods from the com.ibm.MyClass and com.ibm.MyOtherClass classes are
## allowed to be directly invoked.
api.custom.method.invoke.allowed.classes=

## api.custom.authentication points to a JavaScript text file that contains custom authentication code.
## For example: api.custom.authentication=ldap_auth.js.
## To enable the built-in LDAP Authentication mechanism, set this property to "[ldap]".
## For example: api.custom.authentication=[ldap]

##api.custom.authentication=[ldap]

## LDAP Authnetication properties
## ---------------------

## If this parameter is set to "true" and the LDAP Authnetication initialization fails, the whole Server API will not be started.
## If this parameter is missing or is set to "false" any LDAP Authentication initialization errors will be logged and the Server API will be started.
api.custom.authentication.ldap.critical=false

## LDAP Server hostname.
api.custom.authentication.ldap.hostname=

## LDAP server port number. For example, 389 for non-SSL or 636 for SSL.
api.custom.authentication.ldap.port=

## Specifies whether SSL is used to communicate with the LDAP Server.
## When set to "true" SSL will be used, otherwise SSL will not be used.
api.custom.authentication.ldap.ssl=

## Specifies the LDAP directory location where user searches will be preformed.
## When this property is not specified user searches will not be performed.
api.custom.authentication.ldap.searchbase=

## Specifies the user id attribute to be used in searches.
## When this property is not specified user searches will not be performed.
api.custom.authentication.ldap.userattribute=

## Specifies an LDAP Server administrator distinguished name that will be used for user searches.
## When this property is not specified anonymous bind will be used for user searches.
api.custom.authentication.ldap.admindn=

## Password for the LDAP Server administrator distinguished name.
{protect}-api.custom.authentication.ldap.adminpassword=


## Tombstone Manager properties
## ---------------------

com.ibm.di.tm.on=false
com.ibm.di.tm.autodel.age=0
com.ibm.di.tm.autodel.records.trigger.on=10000
com.ibm.di.tm.autodel.records.max=5000
com.ibm.di.tm.create.all=false


## ----------------------
## Help system properties
## ----------------------

## Name of help server, comment out if you want local help system
## The Tivoli library is at the following URL:
## http://publib.boulder.ibm.com/infocenter/tiv2help/index.jsp?toc=/com.ibm.IBMDI.doc_6.1/toc.xml
com.ibm.di.helpHost=www.ibm.com/docs/en/vdi/11.0.0

## Port for help system
com.ibm.di.helpPort=80

## --------------------------------------------
## AssemblyLinePool: Connector pooling defaults
## --------------------------------------------
##
## Note! These settings are only used when an AssemblyLine uses
## an AssemblyLinePool in combination with a Server mode connector.

## The number of seconds before a pooled connector times (e.g. is closed and no longer reused)
##      Less than zero means disable connector pooling
##		Zero means never timeout
##		Greater than zero sets the number of seconds before a connector is closed
com.ibm.di.server.connectorpooltimeout=42

## Comma separated list of connector interfaces that we never pool
com.ibm.di.server.connectorpoolexclude=com.ibm.di.connector.FileConnector,com.ibm.di.connector.ScriptConnector


## Properties for Windows IPv6 communications.
## Uncomment these properties for Windows IPv6 communication only.
## These properties will not affect IPv4 communication or IPv6 communication on Unices.
#java.net.preferIPv4Stack=false
#java.net.preferIPv6Addresses=true

## --------------------------------------------
## Performance settings
## --------------------------------------------
##
## Enable/Disable performance logging
com.ibm.di.server.perfStats=false

### ------------------------------------------
### Used by Config Report
###-------------------------------------------
### set this is you want to override the local language for Config Reports
# com.ibm.di.admin.configreport.translation=en

##----------------------
## System Queue settings
##----------------------
## If set to "true" the System Queue is initialized on startup and can be used;
## otherwise the System Queue is not initialized and cannot be used.
systemqueue.on=true

## Specifies the fully qualified name of the class that will be used as a JMS Driver.
# systemqueue.jmsdriver.name=com.ibm.di.systemqueue.driver.IBMMQ
systemqueue.jmsdriver.name=com.ibm.di.systemqueue.driver.JMSScriptDriver
# systemqueue.jmsdriver.name=com.ibm.di.systemqueue.driver.IBMMQe

### MQe JMS driver initialization properties
## Specifies the location of the MQe initialization file.
## This file is used to initialize MQe on SDI server startup.
#  systemqueue.jmsdriver.param.mqe.file.ini=C:\dev\IBM\TDI\V6.1_060608a\MQePWStore\pwstore_server.ini

### MQ JMS driver initialization properties
# systemqueue.jmsdriver.param.jms.broker=<host:port>
# systemqueue.jmsdriver.param.jms.serverChannel=<channel_name>
# systemqueue.jmsdriver.param.jms.qManager=<queuemanger_name>
# systemqueue.jmsdriver.param.jms.sslCipher=<cipherSuite_name>

### JMS Javascript driver initialization properties
## Specifies the location of the script file
systemqueue.jmsdriver.param.js.jsfile=sonic_jms_driver.js
systemqueue.jmsdriver.param.jms.broker=localhost:2506
# systemqueue.jmsdriver.param.jms.sslUseFlag=true
systemqueue.jmsdriver.param.jms.username=
systemqueue.jmsdriver.param.jms.password=

## This is the place to put any JMS provider specific properties needed by a JMS Driver,
## which connects to a 3rd party JMS system.
## All JMS Driver properties should begin with the 'systemqueue.jmsdriver.param.' prefix.
## All properties having this prefix are passes to the JMS Driver on initialization after
## removing the 'systemqueue.jmsdriver.param.' prefix from the property name.
# systemqueue.jmsdriver.param.user.param1=value1
# systemqueue.jmsdriver.param.user.param2=value2
# ...

## Credentials used for authenticating to the target JMS system
# {protect}-systemqueue.auth.username=<username>
# {protect}-systemqueue.auth.password=<password>
