bin.includes = META-INF/,\
               plugin.xml,\
               .,\
               WEB-INF/configuration.properties,\
               WEB-INF/lib/diserverapi.jar,\
               WEB-INF/lib/diserverapirmi.jar,\
               WEB-INF/lib/jaxrs-api-1.0.jar,\
               WEB-INF/lib/miconfig.jar,\
               WEB-INF/lib/miserver.jar,\
               WEB-INF/lib/tdiresource.jar,\
               WEB-INF/lib/slf4j-api-7.36.jar,\
               WEB-INF/lib/slf4j-jdk14-1.7.36.jar,\
               WEB-INF/lib/ibm-wink-jaxrs-1.0.0.jar,\
               WEB-INF/lib/JSON4J.jar,\
               WEB-INF/classes/,\
               schema/,\
               NLS/
source.. = src/
