CONN_TITLE = System Store Connector
CONN_DESC = System Store Connector
dbname_desc = SystemStore database URL (leave blank to use default SystemStore settings).
dbname_label = Database
login_desc = User name used to connect to the SystemStore database.
login_label = Username
pass_label = Password
pass_desc = User password used to connect to the SystemStore database.
key_desc = The Attribute name used for unique key values. This must appear in the Output Map for AddOnly or Update mode.
key_label = Key Attribute Name
mode_desc = When Iterating this Connector return all, existing or deleted entries (Delta mode only)
mode_label = Selection Mode
tablename_desc = Provide the Table Name. It must be alphanumeric and start with a letter.
tablename_label = Table Name
table_sc_label = Select...
table_sc_help = Select a table in the specified database.
table_sc2_label = Delete
table_sc2_help = Delete the selected table.
seldriver_desc = JDBC driver used to connect to the SystemStore database (leave blank to use default SystemStore settings)
seldriver_label = JDBC Driver
createTable_desc = Create Table Statement.
createTable_label = Create table statement
SEARCH_BASE_SCRPT_LABEL = Delete
SEARCH_BASE_SCRPT_DESC = Delete the selected table.
delOnClose_desc = Delete the tables created by the Connector on close.
delOnClose_label = Delete table on close
searchFlt_desc = SQL Select statement (Iterator mode only)
searchFlt_label = SQL Select
pesCommit_desc = Controls when database transactions are commited. Manual means user must call commit()
pesCommit_label = Commit
mode_All = All Entries
mode_Existing = Existing Entries
mode_Deleted = Deleted Entries
Localized.After.every.database.operation = After every database operation
Localized.On.Connector.close = On Connector close
Localized.Manual = Manual
Localized.End.of.Cycle = End Of Cycle
Advanced = Advanced
