<?xml version="1.0" encoding="UTF-8"?><MetamergeConfig Cycle="127" UUID="beaf9012-92bd-404f-a787-f8424fdeeca1" created="Fri Nov 29 13:51:01 CET 2013" createdBy="Administrator" main="ISAM utils" modified="Fri Jun 20 11:00:27 CEST 2014" modifiedBy="Administrator" project="FDS_ISAM_Plugin" version="7.1.1">
    <Script name="ISAM utils">
        <ModTime>1403254826772</ModTime>
        <parameter name="includeFiles"/>
        <parameter name="script"><![CDATA[/*
var isamversion = "20140129 1052" // started history
var isamversion = "20140204 1205" // fixed update issue when entry moved/renamed
var isamversion = "20140207 1233" // handing operational atts passed in (prepended with '$')
var isamversion = "20140318 1217" // fixed mapfile handling
var isamversion = "20140416 1331" // fixed handling of "unchanged" operations for Groups
var isamversion = "20140514 1223" // changed so no messages are printed when deBug is false (Detailed Log for the Flow)
 *  *  * */
var isamversion = "20140620 1100" // fixed deletion of groups

task.logmsg("FDS_ISAM_Plugin util lib vrs. " + isamversion);
java.lang.System.out.println("FDS_ISAM_Plugin util lib vrs. " + isamversion);


var deBug = true;
var pluginConfigDirectory = "configs"
var flowKey = ""
var opEntry = task.getOpEntry();


// dummy functions
resource = {
	getString : function(key) {
		return key;
	}	
};

function getFlowKey(defValue) {
// First retrieve the opEntry and determine the flowKey
	flowKey = opEntry.getString("global.flows");
	return flowKey || defValue;
}

startLogMsg = "FDS_ISAM_Plugin/" + task.getShortName + "/ -> ";
function progLogmsg(msg, entry) {
	if (!deBug) {
		return;
	}
	var dbgMsg = ""
	if (deBug && typeof(entry) != "undefined" && entry != null && entry.size() > 0) {
		dbgMsg = ": " + entry.toJSON();
	}
	logmsg(startLogMsg + msg + dbgMsg);
	if (deBug) {
		java.lang.System.out.println("FDS_ISAM_Plugin -> " + msg + dbgMsg);
	}
}

function initISAMUtils() {
	flowKey = getFlowKey("Test");
/*
	readISAMProperties(flowKey);
	deBug = getProperty("global.debug")
	if (deBug == null || deBug.length == 0) {
		deBug = false;
	} else {
		deBug = "true".equalsIgnoreCase(deBug);
	}
*/		
}

// get ISAM principalName
function ISAMprincipalName(entry) {
	var dn = null;
	var principalNameProp = getProperty("isam.map.principalName");
	if ("targetRDN".equalsIgnoreCase(principalNameProp)) {
		dn = work.getString("$translatedDN");
		if (dn === null) {
			dn = work.getString("translatedDN");
		}
	} else	
	if ("sourceRDN".equalsIgnoreCase(principalNameProp)) {
		dn = work.getString("$dn");
	}
	
	if (dn !== null) {
		var ldapName = new javax.naming.ldap.LdapName(dn);
		var ldapRdns = ldapName.getRdns();
		var ldapRdn = ldapRdns[ldapRdns.size()-1];
		return ldapRdn.getValue();
	} else {
		return work.getString(principalNameProp);
	}
	
	// should never get here
}

function ISAMsecDN(rdnType, principalName, entry) {
	var secDNProp = getProperty("isam.map.secDN");
	if ("mapFile".equalsIgnoreCase(secDNProp)) {
		return null;
	} else
	if ("targetDN".equalsIgnoreCase(secDNProp)) {
		var dn = work.getString("$translatedDN");
		if (dn === null) {
			dn = work.getString("translatedDN");
		}
		return dn;
	} else
	if ("sourceDN".equalsIgnoreCase(secDNProp)) {
		return work.getString("$dn")
	} else
	if ("compute".equalsIgnoreCase(secDNProp) && "User".equalsIgnoreCase(entityType) && principalName != null) {
		var isamSuffix = getProperty("isam.user.container");
		return rdnType + "=" + principalName + "," + isamSuffix
	} else {
		return work.getString(secDNProp)
	}
	
	// should never get here
}

function setISAMMapFile() {
	try{
		mapFile = getProperty("isam.mapFile");
		
		if (mapFile === null) {
			// leave default map in place
			return;
		}
	
		thisConnector.useAttributeMap(mapFile, false, false);
		if (deBug) logmsg("--@@@ MAP FILE @@@--> using: " + mapFile)
	} catch (ex){
		var msg = resource.getString("LDAPSYNC.UNABLE.TO.FIND.ISAM.MAPFILE");
		var errormsg = msg + " - " + ex + " - " + mapFile;
		logmsg("ERROR", errormsg);
		addToStats(flowKey, "error","error");	
	
		throw (errormsg);
	}	
}

// Handle mapping of special attributes if necessary
function additionalAttributesForISAM(work, conn) {
	var principalName = work.getString("principalName");
	var rdnType = getProperty("isam.map.secDN.type")
	
	// handle secDN if the isam.map.secDN is set to other than 'mapFile'
	var secDN = ISAMsecDN(rdnType, principalName, work);
	if (secDN !== null) {
		conn.setAttribute("secDN", secDN);
	}
	
	conn.principalName = work.principalName;
}

function boolValue(strValue) {
	strValue = String(strValue).toLowerCase();
}

// Handle compute changes for ISAM boolean attributes ("TRUE" == true == "true", etc)
function computeChanges(conn, current) {
	var attNames = conn.getAttributeNames();
	for (var name in attNames) {
		var currentval = current.getString(name);
		var connval = conn.getString(name);
		if (name.toLowerCase().endsWith("valid") && String(currentval).equalsIgnoreCase(String(connval))) {
			conn.removeAttribute(name);
		}
	}	
}]]></parameter>
    </Script>
</MetamergeConfig>