<?xml version="1.0" encoding="UTF-8"?><MetamergeConfig Cycle="3" UUID="03de6f8f-d78f-4ea9-8ff8-efba435fb770" created="Sun Feb 09 12:46:44 CET 2014" createdBy="Administrator" main="libDefaultOnError" modified="Fri Apr 25 17:12:20 CEST 2014" modifiedBy="Administrator" project="FDS_ISAM_Plugin" version="7.1.1">
    <Script name="libDefaultOnError">
        <ModTime>1398438734101</ModTime>
        <parameter name="includeFiles"/>
        <parameter name="script">defaultErrorHandling("ERROR");</parameter>
    </Script>
</MetamergeConfig>