<?xml version="1.0" encoding="UTF-8"?><MetamergeConfig Cycle="1" UUID="f97a8c7c-45fe-4efa-bbde-b85dce5f44d5" created="Sun Feb 09 12:46:44 CET 2014" createdBy="Administrator" main="libInitError" modified="Sun Feb 09 12:46:44 CET 2014" modifiedBy="Administrator" project="FDS_ISAM_Plugin" version="7.1.1">
    <Script name="libInitError">
        <ModTime>1391946404099</ModTime>
        <parameter name="includeFiles"/>
        <parameter name="script"><![CDATA[change = false;
if (typeof(work) != "undefined" && work != null) {
	work["$status"] = "failed";
	work["$error"] = error;
}	
defaultInitErrorHandling("ERROR");]]></parameter>
    </Script>
</MetamergeConfig>