# 
# This file controls the logging strategy for the migpwsync command line utility.
# -------------------------------------------------------------------------------
log4j.rootCategory=INFO, Default
log4j.appender.Default=org.apache.log4j.FileAppender
log4j.appender.Default.layout=org.apache.log4j.PatternLayout
log4j.appender.Default.layout.ConversionPattern=%d{DEFAULT} %-5p [migpwsync] - %m%n
log4j.appender.Default.File=logs/migpwsync.log
log4j.appender.Default.append=false

log4j.appender.CONSOLE=org.apache.log4j.ConsoleAppender
log4j.appender.CONSOLE.layout=org.apache.log4j.SimpleLayout

log4j.logger.com.ibm.di.migration.verbose=INFO, CONSOLE
