#Eclipse Runtime Configuration
#Generated for Eclipse 4.39.0 headless PDE build
eclipse.product=org.eclipse.sdk.ide
osgi.splashPath=platform\:/base/plugins/org.eclipse.platform
org.eclipse.equinox.simpleconfigurator.configUrl=file\:org.eclipse.equinox.simpleconfigurator/bundles.info
osgi.bundles.defaultStartLevel=4
eclipse.application=org.eclipse.ui.ide.workbench
osgi.instance.area.default=@user.home/workspace
osgi.bundles=reference\:file\:org.eclipse.equinox.simpleconfigurator_1.5.700.v20251111-1031.jar@1\:start
eclipse.p2.data.area=@config.dir/../p2/
eclipse.p2.profile=SDKProfile
osgi.framework=file\:plugins/org.eclipse.osgi_3.24.100.v20251215-1416.jar
osgi.framework.extensions=reference\:file\:org.eclipse.osgi.compatibility.state_1.3.0.v20251022-1724.jar
eclipse.buildId=4.39.0
