bin.includes = plugin.xml,\
        META-INF/,\
        autoPDMenu.xml,\
        properties/,\
        plugin.properties,\
        plugin_en_US.properties,\
        scripts/
bin.excludes = .*,\
        build*.*
qualifier = context
