<?xml version="1.0" encoding="UTF-8"?><MetamergeConfig Cycle="14" UUID="d1a485dd-1194-453a-9396-5a900778226b" created="Thu Jul 03 12:52:27 CEST 2014" createdBy="Administrator" main="Prepare for search" modified="Mon Sep 08 12:08:56 CEST 2014" modifiedBy="Administrator" project="FDS_Target_SCIM" version="7.1.1">
    <Script name="Prepare for search">
        <ModTime>1410170935529</ModTime>
        <parameter name="includeFiles"/>
        <parameter name="script"><![CDATA[// if the adDn attribute is available, then use it. Otherwise grab the actual
// search crit passed to this AL
//
search = task.getTCB().getString("$search");
crit = search.getCriteria();
adDn = work.getString("adDn");

if (("externalId".equalsIgnoreCase(crit[0].name)
	  || "$dn".equalsIgnoreCase(crit[0].name)
	  || "adDn".equalsIgnoreCase(crit[0].name)) 
	 && adDn !== null) {
	work.setAttribute("$searchValue", adDn);
} else {
	work.setAttribute("$searchValue", crit[0].value);
}]]></parameter>
    </Script>
</MetamergeConfig>