<?xml version="1.0" encoding="UTF-8"?><MetamergeConfig Cycle="10" UUID="03d6d6bd-7cb1-4837-aac0-7e9bd1e43b0a" created="Thu Aug 07 21:35:37 CEST 2014" createdBy="Administrator" main="schema_group" modified="Fri Aug 08 14:57:08 CEST 2014" modifiedBy="Administrator" project="FDS_Target_SCIM" version="7.1.1">
    <Script name="schema_group">
        <ModTime>1407502627781</ModTime>
        <parameter name="includeFiles"/>
        <parameter name="script"><![CDATA[$dn=externalId
adDn=externalId
$id=id
uniqueMember=members.value
cn=displayName
description=description]]></parameter>
    </Script>
</MetamergeConfig>