<?xml version="1.0" encoding="UTF-8"?><MetamergeConfig Cycle="9" UUID="3a88051c-29d1-40c6-bece-06bc2bc34673" created="Thu Aug 07 21:35:26 CEST 2014" createdBy="Administrator" main="schema_person" modified="Fri Aug 08 14:12:10 CEST 2014" modifiedBy="Administrator" project="FDS_Target_SCIM" version="7.1.1">
    <Script name="schema_person">
        <ModTime>1407499929216</ModTime>
        <parameter name="includeFiles"/>
        <parameter name="script"><![CDATA[$dn=externalId
adDn=externalId
$id=id
$created=meta.created,date
$modified=meta.lastModified
$uri=meta.location
$version=meta.version
description=description
displayName=name.formatted
sn=name.familyName
givenName=name.givenName
uid=userName
telephoneNumber=phoneNumbers[type:work].value
homePhoneNumber=phoneNumbers[type:home].value
mail=emails
objectClass="inetOrgPerson"]]></parameter>
    </Script>
</MetamergeConfig>