##{PropertiesConnector} savedBy=Administrator, saveDate=Fri Jan 06 16:44:07 GMT+05:30 2012
jdbcURL=jdbc:db2://9.182.177.144:50005/MAXDB71
jdbcDriver=com.ibm.db2.jcc.DB2Driver
jdbcUsername=db2admin
{protect}-jdbcUserPassword={encr}OO4BmUAS/n79S4SPG03Z7fI9pK9lk/ktzdFoOBQT58FrCEzQ/ZQ8LtVlfy0VO6Qn+oDuK6ny7VwcxQzC2p9e98H6KQpqDfegicZYUZJS/iVlz2pxCQliKN47Ic0bYU2TgSV/UIbtCug9ByX6i/Tb+YXQnlWMtN/Dif3fd3tql14=
