# Baseline param.
# Determines the file where performance results will be written to.	
-baseline=PerfResults.xml

# Repeat count param
# Determines the number that tests will be repeated.
-repeat=1

# Precision param
# Determines the possible deviation in the performance results
-precision=2

# Performance Class param
# Determines the name of the test class to execute
# Test Suites are supported, too
-perfClass=com.ibm.di.server.AssemblyLineServerAPIIntPerf

# Compare param
# When running the tests for the second time on other version ot TDI
# this param determines the name of the file to which the current
# performance results will be compared.
# This param is used when running the tests for the first time.
-compare=true

# Context param
# Specifies the context the performance framework is running into.
# In this case we should always use "int" because we are running inside TDI's JVM.
-ctx=int
