CONN_DESC = Connector for detecting and retrieving changes in a Domino database
CONN_TITLE = Domino Change Detection Connector
SESSIONTYPE_DESC = Specifies whether the Connector will create an IIOP session or perform Local Client calls
SESSIONTYPE_LBL = Session Type
DOMINOSERVERIP_DESC = The IP address (or hostname)of the Domino Server where the database that will be polled for changes resides.
DOMINOSERVERIP_LBL = Domino Server IP address
IOR_DESC = The IOR string used to create the IIOP session. This parameter can optionally be used instead of requesting this value from the Domino server.
IOR_LBL = IOR String
HTTPPORT_DESC = The port on which the HTTP task of the Domino Server is running
HTTPPORT_LBL = HTTP Port
USERNAME_DESC = User name for session authentication. This must match the first value of the "User name" field of that user's Person document.
USERNAME_LBL = Username
INTERNETPASSWORD_DESC = User password for session authentication. This must match the "Internet Password" field of the user's Person document.
INTERNETPASSWORD_LBL = Password
DATABASE_DESC = The filename of the Domino database which will be polled for changes, for example "names.nsf".
DATABASE_LBL = Database
SYSTEMSTOREKEY_DESC = A key (which should be unique) used to keep track of the last change processed by this Connector.
SYSTEMSTOREKEY_LBL = Iterator State Key
SYSTEMSTOREKEY_SCR_LBL = Delete
SYSTEMSTOREKEY_SCR_HELP = Deletes Iterator State information
STARTAT_DESC = The type of starting condition. This parameter is taken into account only when the persistent parameter specified by "Iterator State Key" is blank or not found in the System Store.
STARTAT_LBL = Start at
STARTDATE_DESC = The "since" date and time. The Connector will retrieve documents which have been changed at or after this date/time.\nThis parameter accepts the following date/time formats\:\n  yyyy-MM-dd HH\:mm\:ss.SSS\n  yyyy-MM-dd HH\:mm\:ss\n  yyyy-MM-dd\nIt is only taken into account when the persistent parameter specified by "Iterator State Key"\nis not found in the System Store and the "Start At" parameter is set to "Specific date".
STARTDATE_LBL = Start Date (yyyy-MM-dd HH\:mm\:ss)
TIMEOUT_DESC = Specifies the maximum number of seconds the Connector waits for the next changed document.\nIf this parameter is 0, then the Connector waits forever.
TIMEOUT_LBL = Timeout
SLEEP_DESC = Specifies the number of seconds the Connector sleeps between successive polls for changes.
SLEEP_LBL = Sleep Interval
ssl_label = Use SSL
ssl_desc = Enables encrypted communications with the Domino server
Localized.Start.Of.Data = Start Of Data
Localized.End.Of.Data = End Of Data
Localized.Specific.date = Specific date
STATE_KEY_PERSIST_LBL = State Key Persistence
STATE_KEY_PERSIST_DESC = Determines when Iterator State is saved. The recommended setting is End of Cycle.
Localized.After.read = After read
Localized.End.of.cycle = End of cycle
Localized.Manual = Manual
Localized.IIOP = IIOP
Localized.LocalClient = LocalClient
sort_label = Deliver Sorted
sort_desc = If checked, the changed documents are delivered sorted by the date they were last modified on; otherwise the changed documents are delivered in random order.\n If the number of changed documents is large then sorting could slow SyncWeave performance.
Advanced = Advanced
