/*
 * Copyright contributors to the SyncWeave project
 *
 * SPDX-License-Identifier: Apache-2.0
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.27 at 12:35:38 PM CEST 
//

package com.ibm.di.ui.easyetl.bind;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for logqualifiers complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="logqualifiers">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="info" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="warn" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="error" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="debug" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "logqualifiers", propOrder = {
    "info",
    "warn",
    "error",
    "debug"
})
public class Logqualifiers {

    protected boolean info;
    protected boolean warn;
    protected boolean error;
    protected boolean debug;

    /**
     * Gets the value of the info property.
     * 
     */
    public boolean isInfo() {
        return info;
    }

    /**
     * Sets the value of the info property.
     * 
     */
    public void setInfo(boolean value) {
        this.info = value;
    }

    /**
     * Gets the value of the warn property.
     * 
     */
    public boolean isWarn() {
        return warn;
    }

    /**
     * Sets the value of the warn property.
     * 
     */
    public void setWarn(boolean value) {
        this.warn = value;
    }

    /**
     * Gets the value of the error property.
     * 
     */
    public boolean isError() {
        return error;
    }

    /**
     * Sets the value of the error property.
     * 
     */
    public void setError(boolean value) {
        this.error = value;
    }

    /**
     * Gets the value of the debug property.
     * 
     */
    public boolean isDebug() {
        return debug;
    }

    /**
     * Sets the value of the debug property.
     * 
     */
    public void setDebug(boolean value) {
        this.debug = value;
    }

}
