/*
 * Copyright contributors to the SyncWeave project
 *
 * SPDX-License-Identifier: Apache-2.0
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.30 at 02:24:47 PM CET 
//

package com.ibm.di.ui.easyetl.bind;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ibm.di.ui.easyetl.bind package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Logfiles_QNAME = new QName("http://www.ibm.com/xmlns/prod/tdi/72/api", "logfiles");
    private final static QName _Logsearch_QNAME = new QName("http://www.ibm.com/xmlns/prod/tdi/72/api", "logsearch");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ibm.di.ui.easyetl.bind
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Logfile }
     * 
     */
    public Logfile createLogfile() {
        return new Logfile();
    }

    /**
     * Create an instance of {@link Loglocation }
     * 
     */
    public Loglocation createLoglocation() {
        return new Loglocation();
    }

    /**
     * Create an instance of {@link Logsearchresult }
     * 
     */
    public Logsearchresult createLogsearchresult() {
        return new Logsearchresult();
    }

    /**
     * Create an instance of {@link Logfiles }
     * 
     */
    public Logfiles createLogfiles() {
        return new Logfiles();
    }

    /**
     * Create an instance of {@link Logsearch }
     * 
     */
    public Logsearch createLogsearch() {
        return new Logsearch();
    }

    /**
     * Create an instance of {@link Logqualifiers }
     * 
     */
    public Logqualifiers createLogqualifiers() {
        return new Logqualifiers();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Logfiles }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ibm.com/xmlns/prod/tdi/72/api", name = "logfiles")
    public JAXBElement<Logfiles> createLogfiles(Logfiles value) {
        return new JAXBElement<Logfiles>(_Logfiles_QNAME, Logfiles.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Logsearch }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ibm.com/xmlns/prod/tdi/72/api", name = "logsearch")
    public JAXBElement<Logsearch> createLogsearch(Logsearch value) {
        return new JAXBElement<Logsearch>(_Logsearch_QNAME, Logsearch.class, null, value);
    }

}
