/*
 * Copyright IBM Corp. 2025
 *
 * SPDX-License-Identifier: Apache-2.0
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.10 at 02:47:00 PM CET 
//

package com.ibm.di.ui.easyetl.bind;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for vmstatus complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="vmstatus">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="freeMemory" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="totalMemory" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="maxMemory" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="numProcessors" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="activeThreads" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "vmstatus", propOrder = {
    "freeMemory",
    "totalMemory",
    "maxMemory",
    "numProcessors",
    "activeThreads"
})
public class Vmstatus {

    protected long freeMemory;
    protected long totalMemory;
    protected long maxMemory;
    protected int numProcessors;
    protected int activeThreads;

    /**
     * Gets the value of the freeMemory property.
     * 
     */
    public long getFreeMemory() {
        return freeMemory;
    }

    /**
     * Sets the value of the freeMemory property.
     * 
     */
    public void setFreeMemory(long value) {
        this.freeMemory = value;
    }

    /**
     * Gets the value of the totalMemory property.
     * 
     */
    public long getTotalMemory() {
        return totalMemory;
    }

    /**
     * Sets the value of the totalMemory property.
     * 
     */
    public void setTotalMemory(long value) {
        this.totalMemory = value;
    }

    /**
     * Gets the value of the maxMemory property.
     * 
     */
    public long getMaxMemory() {
        return maxMemory;
    }

    /**
     * Sets the value of the maxMemory property.
     * 
     */
    public void setMaxMemory(long value) {
        this.maxMemory = value;
    }

    /**
     * Gets the value of the numProcessors property.
     * 
     */
    public int getNumProcessors() {
        return numProcessors;
    }

    /**
     * Sets the value of the numProcessors property.
     * 
     */
    public void setNumProcessors(int value) {
        this.numProcessors = value;
    }

    /**
     * Gets the value of the activeThreads property.
     * 
     */
    public int getActiveThreads() {
        return activeThreads;
    }

    /**
     * Sets the value of the activeThreads property.
     * 
     */
    public void setActiveThreads(int value) {
        this.activeThreads = value;
    }

}
