FC_TITLE = Complex Types Generator Function Component
FUNCTION_DESC = Used for generating a JAR file, which contains the Java class files implementing the complex data types defined in a schema either internal to or referenced by a WSDL
WU_LBL = WSDL URL
WU_DESC = Can be either a file system path (either absolute or relative) or a URL.
WU_SLBL = Select...
WU_SHLP = Browse file system
WTJO_LBL = WSDL2Java Options
WTJO_DESC = The options typed here will be passed to the WSDL2Java utility.
JF_LBL = JAR file name
JF_DESC = JAR file name - can be either relative or absolute
JP_LBL = JDK path
JP_DESC = The path to a Java Development Kit installation. If left empty the utlity assumes that the Java compiler "javac" and the "jar" tools are on the system executable path.
AGJSF_LBL = Generate Java Source Files
AGJSF_DESC = If set to TRUE, WSDL2Java will be run to generate Java source files out of the supplied WSDL. You can set this parameter to FALSE if you want to run this utility on manually edited or written Java source files.
RSB_SLBL = Generate complex types
RSB_SHLP = Generate complex types
WUMNBE = WSDL URL must not be empty\!
JFMNBE = JAR filename must not be empty\!
JFSG = JAR file successfully generated.
Advanced = Advanced
