CONSOLEAPPENDER_TITLE = Console Logger
NTAPPENDER_TITLE = NT Event Log ( Windows only )
NTAPPENDER_SOURCE_LABEL = Source
NTAPPENDER_SOURCE_DESC = Usually the title of the application doing the logging
FILEAPPENDER_TITLE = File Logger
FILEAPPENDER_FILEPATH_LABEL = File Path
FILEAPPENDER_FILEPATH_DESC = The file path for the log file
FILEAPPENDER_APPEND_LABEL = Append to file
FILEAPPENDER_APPEND_DESC = Specify true to append to the file when the log is initialized, false to overwrite
ENCODING_DESC = Character Encoding to be used (e.g. UTF-8).
ENCODING_LABEL = Character Encoding
FILEROLLER_TITLE = IBM Security Verify Directory Integrator File Roller
FILEROLLER_FILE_LABEL = File Path
FILEROLLER_FILE_DESC = This logger will write to <File Path>.1 and increment the extension of existing logfiles up to the specified number of backup files.
FILEROLLER_NUMBER_LABEL = Number of backup files
FILEROLLER_NUMBER_DESC = Number of files to keep before removing oldest log file
SYSTEMLOG_TITLE = SystemLog Logger
SYSTEMLOG_INFORMATION_LABEL = Information
SYSTEMLOG_INFORMATION_TEXT = Logfiles to be found under system_logs/{ConfigId}/AL_X/ where X is the name of the AssemblyLine being run. The filename will be X.timestamp.
DAILYROLLER_TITLE = Rolling File Logger
DAILYROLLER_FILE_LABEL = File Path
DAILYROLLER_FILE_DESC = The path name for the base log file
DAILYROLLER_APPEND_LABEL = Append to file
DAILYROLLER_APPEND_DESC = Specify true to append to the file when the log is initialized, false to overwrite
DAILYROLLER_DATEP_LABEL = Date Pattern
DAILYROLLER_DATEP_DESC = Date pattern that logfile names are suffixed with, and which controls when rollover occurs (i.e. when the filename changes).
CUSTOM_APPENDER_TITLE = Custom Logger
CUSTOM_APPENDER_LABEL = Appender Parameters
CUSTOM_APPENDER_DESCR = Parameters format is not defined and it is up to Appender implementation to parse this text field.
SYSLOG_TITLE = Syslog Logger
LOG_PATTERN_LABEL = Pattern
LOG_PATTERN_DESC = Substitution mask that defines log formatting. Only used when Layout is Pattern.
SYSLOG_HOST_LABEL = Host name/IP Address
SYSLOG_HOST_DESC = The hostname or IP address of the syslog daemon
SYSLOG_FACILITY_LABEL = Syslog Facility
SYSLOG_FACILITY_DESC = The facility name to use for logged messages
SYSLOG_FACILITY_PRINT_LABEL = Print Facility String
SYSLOG_FACILITY_PRINT_DESC = True if the facility should be printed
JUL_FILE_TITLE = File Logger (java.util.logging)
FORMATTER_LABEL = Formatter
FORMATTER_DESC = Choose a SimpleFormatter or a XMLFormatter
Localized.Simple = Simple
Localized.XML = XML
JUL_FILE_LABEL = File Name
JUL_FILE_DESC = The pattern for the log file name (see java.util.logging.FileHandler)
JUL_LIMIT_LABEL = Limit
JUL_LIMIT_DESC = The maximum number of bytes to write to any one file (default no limit)
JUL_COUNT_LABEL = Count
JUL_COUNT_DESC = The number of log files to use (default 1, meaning no backup)
JUL_APPEND_LABEL = Append
JUL_APPEND_DESC = Specify true to append to the file when the log is initialized, false to overwrite
LOG4J_CAT_TITLE = Category Based Log4j Logger
CATEGORY_LABEL = Category
CATEGORY_DESCRIPTION = Choose the category to use
JUL_CAT_TITLE = Category Based java.util.logging Logger
JLOG_FILEHANDLER_TITLE = JLog File Handler
JLOG_FILE_FORMATTER_LABEL = Formatter
JLOG_FILE_FORMATTER_DESC = Choose the CBE101Formatter, the EnhancedFormatter or a simple Formatter
Localized.CBE101 = CBE101
Localized.Enhanced = Enhanced
JLOG_CAT_TITLE = Category Based JLog Logger
SELECT_FILE_LABEL = Select...
SELECT_FILE_DESC = Choose the file name to use
MAX_GENERATIONS_LABEL = Max Generations
MAX_GENERATIONS_DESC = If specified, this is the maximum number of generations of log files that will be kept
