PS_TITLE = CBE Parser
PS_DESC = Simple CBE parser
CHAR_LBL = Character Encoding
CHAR_DESC = Character encoding to use when reading or writing.
VAL_LBL = Validate XML
VAL_DESC = Validate the XML with the XSD schema from the CBE specification.
SCHEMA_DESCRIPTION = Path to the element in the CBE Schema file. Each element path is separated by |
SCHEMA_LABEL = Path in the CBE Schema file
Advanced = Advanced
