CONN_DESC = A Connector for processing incoming e-mails
MAIL_SERVER_DESC = The pop/imap mail server address (e.g. hostname or ip-address)
MAIL_SERVER_LABEL = Mail Server
MAIL_USESSL_DESC = When checked the Connector uses SSL connections. When unchecked the Connector uses non-SSL connections.
MAIL_USESSL_LABEL = Use SSL
MAIL_USER_DESC = The username the Connector uses to authenticate to the mail server.
MAIL_USER_LABEL = Username
MAIL_PASSWORD_DESC = The password the Connector uses to authenticate to the mail server.
MAIL_PASSWORD_LABEL = Password
MAIL_FOLDER_DESC = The name of the user's mail folder on the mail server. For POP3 only INBOX is allowed. For IMAP choose any existing mail folder on the mail server.
MAIL_FOLDER_LABEL = Mail Folder
MAIL_CREATE_FOLDER_DESC = Auto create the specified Folder for Addonly mode, in case it does not exist.
MAIL_CREATE_FOLDER_LABEL = Create Folder
MAIL_GET_SUBFOLDER_DESC = Defines whether the Connector iterates through the subfolders of the specified Folder.
MAIL_GET_SUBFOLDER_LABEL = Get subfolders
MAIL_EXCLUDE_FOLDER_DESC = Presents a comma-separated list of folders that is excluded when iterating on the mailbox. Note\: In case a folder is specified as a value for the "mailFolder" parameter it cannot be excluded.
MAIL_EXCLUDE_FOLDER_LABEL = Exclude folders
MAIL_PROTOCOL_DESC = The mail protocol to use for communicating with the mail server.
MAIL_PROTOCOL_LABEL = Mail Protocol
MAIL_POLLINTERVAL_DESC = The amount of seconds that the Connector will sleep before polling the mail server for new mail messages. Set to -1 if you need the Connector to go through the mailbox and terminate without polling again.
MAIL_POLLINTERVAL_LABEL = Poll Interval (seconds)
CONN_TITLE = Mailbox Connector
Localized.pop3 = pop3
Localized.imap = imap
Advanced = Advanced
