/*
 * Copyright contributors to the SyncWeave project
 *
 * SPDX-License-Identifier: Apache-2.0
 */
package com.ibm.di.connector;

import java.util.HashMap;
import java.util.Map;
import java.util.Vector;
import javax.xml.namespace.QName;

import com.ibm.di.config.base.FunctionConfigImpl;
import com.ibm.di.config.interfaces.ConnectorConfig;
import com.ibm.di.config.interfaces.FunctionConfig;
import com.ibm.di.connector.WSReceiverServerConnector.WSReceiverServerConnector;
import com.ibm.di.entry.Attribute;
import com.ibm.di.entry.Entry;
import com.ibm.di.fc.webservice.AxisJavaToSoap;
import com.ibm.di.fc.webservice.AxisSoapToJava;
import com.ibm.di.fc.webservice.axis2.WebServiceClient;
import com.ibm.di.fc.webservice.axis2.WSDLData;
import com.ibm.di.server.AssemblyLine;
import com.ibm.di.server.Trace;
import com.ibm.di.server.ResourceHash;
import org.apache.axis2.AxisFault;
import org.w3c.dom.Element;

/**
 * The Axis Easy Web Service Server Connector is part of the SyncWeave
 * Web Services suite. It is a simplified version of the Web Service Receiver Server
 * Connector in that it internally instantiates, configures and uses the
 * {@link AxisSoapToJava} and {@link AxisJavaToSoap} FCs. The Axis Easy Web
 * Service Server Connector operates in Server mode only.
 * 
 * This version is compatible with Axis2.
 */
public class AxisEasyWSServerConnector extends WSReceiverServerConnector
		implements ConnectorInterface {
	/**
	 * Copyright.
	 */
	@SuppressWarnings("unused")
	private static final String COPYRIGHT = com.ibm.di.server.CopyRight.OBJECT_CODE;

	/**
	 * Component properties.
	 */
	private static final String PROPERTIES_FILE = "axiseasywsserverconnector";

	/**
	 * WSDL URL attribute.
	 */
	private String mWsdlUrl = null;

	/**
	 * WSDL File attribute.
	 */
	private String mWsdlFile = null;

	/**
	 * SOAP operation attribute.
	 */
	private String mSoapOperation = null;

	/**
	 * The list of fully qualified Java classes generated by WSDL2Java from the
	 * WSDL file
	 */
	private String mClasses = null;

	/**
	 * Current operation running in the AL.
	 */
	private String mCurrentOperation = null;

	/**
	 * SOAP operations for this WSDL URL.
	 */
	private Vector<String> mServiceOperations = null;

	/**
	 * Holds operation name and mechanism for parsing from SOAP to Java.
	 */
	private Map<String, AxisSoapToJava> mAxisSoapToJavaMap = null;
	/**
	 * Holds operation name and mechanism for parsing from Java to SOAP.
	 */
	private Map<String, AxisJavaToSoap> mAxisJavaToSoapMap = null;

	/**
	 * Parameter name: wsdlFile
	 */
	protected static final String PARAM_WSDL_FILE = "wsdlFile";
	/**
	 * Parameter name: soapOperation
	 */
	private static final String PARAM_SOAP_OPERATION = "soapOperation";
	/**
	 * Parameter name: complexTypes
	 */
	private static final String PARAM_COMPLEX_TYPES = "complexTypes";
	/**
	 * Attribute name: requestObjArray
	 */
	private static final String ATTR_REQUEST_OBJ_ARRAY = "requestObjArray";
	/**
	 * Attribute name: responseObjArray
	 */
	private static final String ATTR_RESPONSE_OBJ_ARRAY = "responseObjArray";
	/**
	 * Attribute name: soapFault
	 */
	private static final String ATTR_SOAP_FAULT = "soapFault";
	/**
	 * NLS Property set holding name-value pairs for the resource.
	 */
	private static ResourceHash sResHash = null;

	static {
		sResHash = new ResourceHash(PROPERTIES_FILE);
	}

	/**
	 * Default constructor that sets the supported mode of this connector.
	 */
	public AxisEasyWSServerConnector() {
		super();
		Trace.entrymid(this, "AxisEasyWSServerConnector");
		setModes(new String[] { ConnectorConfig.SERVER_MODE });
		Trace.exitmid(this, "AxisEasyWSServerConnector");
	}

	/**
	 * {@inheritDoc}
	 */
	@SuppressWarnings("unchecked")
	@Override
	public void initialize(Object obj) throws Exception {
		Trace.entrymin(this, "initialize", obj);
		super.setParam(PARAM_INPUT_TYPE, XML_STRING);
		super.setParam(PARAM_RETURN_XML_TYPE, XML_STRING);
		super.initialize(obj);

		mWsdlFile = (String) getParam(PARAM_WSDL_FILE);
		if (mWsdlFile == null) {
			throw new Exception(sResHash
					.getString("CONNECTOR.AEWSS.MISSING.FILEPATH.EXCEP"));
		}

		if (debugMode()) {
			debug(sResHash
					.getString("CONNECTOR.AEWSS.WSDLFILE.INFO", mWsdlFile));
		}

		mWsdlUrl = mWsdlFile;

		if (!mTagOpEntry) {
			mSoapOperation = (String) getParam(PARAM_SOAP_OPERATION);
			if (mSoapOperation == null || mSoapOperation.equals("")) {
				throw new Exception(
						sResHash
								.getString("CONNECTOR.AEWSS.MISSING.SOAPOPERATION.EXCEP"));
			}
		}

		if (debugMode()) {
			debug(sResHash.getString("CONNECTOR.AEWSS.SOAPOPERATION.INFO",
					mSoapOperation));
		}

		mClasses = (String) getParam(PARAM_COMPLEX_TYPES);

		if (debugMode()) {
			debug(sResHash.getString("CONNECTOR.AEWSS.COMPLEXTYPES.INFO",
					mClasses));
		}

		mServiceOperations = WSDLData.getSoapOperations(mWsdlUrl);

		mAxisSoapToJavaMap = new HashMap<String, AxisSoapToJava>();
		mAxisJavaToSoapMap = new HashMap<String, AxisJavaToSoap>();

		Trace.exitmin(this, "initialize");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ConnectorInterface getNextClient() throws Exception {
		Trace.entrymin(this, "getNextClient");
		ConnectorInterface connector = super.getNextClient();
		if (connector == null) {
			return null;
		}

		AxisEasyWSServerConnector clientSession = new AxisEasyWSServerConnector();
		clientSession.setServerConnector(this);
		clientSession.setConfiguration(getConfiguration());
		clientSession.setName(getName());
		clientSession.setLog(getLog());
		clientSession.initialize(mSocket);
		Trace.exitmin(this, "getNextClient", clientSession);
		return clientSession;
	}

	/**
	 * Uses the super class's getNextEntry() method and then manipulate the data
	 * in the returned by that method entry.
	 * 
	 * @return the next retrieved entry, or null.
	 * @throws Exception
	 *             if an error occurs.
	 */
	public Entry getNextEntry() throws Exception {
		Trace.entrymin(this, "getNextEntry");
		Entry entry = super.getNextEntry();
		if (entry == null) {
			return null;
		}
		if (!entry.getAttribute(ATTR_WSDL_REQUESTED).getValue().equals(TRUE)) {
			AxisFault soapFault = null;
			String soapRequest = (String) entry.getAttribute("soapRequest")
					.getValue(0);
			Object[] requestObjArray = null;

			try {
				mCurrentOperation = null;

				if (mTagOpEntry) {
					Object context = getContext();
					if (context != null && context instanceof AssemblyLine) {
						AssemblyLine al = (AssemblyLine) context;
						Entry opEntry = al.getOpEntry();
						mCurrentOperation = opEntry
								.getString(AssemblyLine.OPENTRY_OPERATION);
					}

					if (mCurrentOperation == null) {
						String funcmsg = sResHash.getString(
								"CONNECTOR.AEWSS.MISSING.OPATTR.EXCEP",
								AssemblyLine.OPENTRY_OPERATION);
						logError(funcmsg);
						throw new Exception(funcmsg);
					}

					if (!operationExists(mCurrentOperation)) {
						String funcmsg = sResHash.getString(
								"CONNECTOR.AEWSS.INVALID.OPATTR.EXCEP",
								mCurrentOperation);
						logError(funcmsg);
						throw new Exception(funcmsg);
					}
				} else {
					mCurrentOperation = mSoapOperation;
				}
				AxisSoapToJava axisSoapToJavaFC = getAxisSoapToJavaFC(mCurrentOperation);
				requestObjArray = (Object[]) axisSoapToJavaFC
						.perform(soapRequest);
			} catch (Exception e) {
				Trace.exception(this, "getNextEntry", e, " ");
				// Create AxisFault using Axis2 1.7.6 syntax
				// In Axis2 1.7.6, the message is set in the constructor
				soapFault = new AxisFault(e.toString());
				soapFault.setFaultCode(new QName("Client"));
				// Role setting is not directly supported in Axis2 1.7.6
			}

			if (soapFault == null) {
				if (debugMode()) {
					debug(sResHash.getString(
							"CONNECTOR.AEWSS.REQUEST.OBJ.ARRAY", WebServiceClient
									.objectArrayToString(requestObjArray)));
				}
				entry.setAttribute(ATTR_REQUEST_OBJ_ARRAY, requestObjArray);
			}

			if (soapFault != null) {
				entry.setAttribute(ATTR_SOAP_FAULT, soapFault);
			}
		} else {
			String wsdl = readFile(mWsdlFile);
			entry.setAttribute(ATTR_SOAP_RESPONSE, wsdl);
		}
		Trace.exitmin(this, "getNextEntry", entry);

		return entry;
	}

	/**
	 * Override replyEntry to wrap body content in SOAP envelope for client compatibility.
	 * AxisJavaToSoap returns body-only content (for WSReceiverServerConnector compatibility),
	 * but AxisEasyWSServerConnector clients expect complete SOAP envelopes.
	 *
	 * @param conn Entry containing the response
	 * @throws Exception if an error occurs
	 */
	@Override
	public void replyEntry(Entry conn) throws Exception {
		Trace.entrymin(this, "replyEntry", conn);
		Entry entry = new Entry();
		entry.merge(conn);

		// ATTR_WSDL_REQUESTED is mapped by user - so check if it is there
		// If it is and its value is "true",
		// then ATTR_SOAP_RESPONSE is assumed to contain the WSDL contents
		Attribute attrWsdlRequested = entry.getAttribute(ATTR_WSDL_REQUESTED);
		if ((attrWsdlRequested == null)
				|| (FALSE.equals(attrWsdlRequested.getValue()))) {
			String soapResponse = null;
			Attribute attrSoapFault = entry.getAttribute(ATTR_SOAP_FAULT);
			if (attrSoapFault == null) {
				Attribute attrResponse = entry
						.getAttribute(ATTR_RESPONSE_OBJ_ARRAY);
				if (attrResponse != null) {
					Object responseObject = attrResponse.getValue(0);
					if (responseObject instanceof Object[]) {
						Object[] responseObjectArray = (Object[]) responseObject;
						if (debugMode()) {
							debug(sResHash
									.getString(
											"CONNECTOR.AEWSS.RESPONSEOP.INFO",
											WebServiceClient
													.objectArrayToString(responseObjectArray)));
						}
						AxisJavaToSoap axisJavaToSoapFC = getAxisJavaToSoapFC(mCurrentOperation);
						soapResponse = (String) axisJavaToSoapFC
								.perform(responseObjectArray);
					}
				}
			} else {
				AxisJavaToSoap axisJavaToSoapFC = getAxisJavaToSoapFC(mCurrentOperation);
				soapResponse = (String) axisJavaToSoapFC
						.perform(new Object[] { attrSoapFault.getValue(0) });
			}
			entry.setAttribute(ATTR_SOAP_RESPONSE, soapResponse);
			
			// Check if response is body-only (no envelope) and wrap it
			Attribute soapResponseAttr = entry.getAttribute(ATTR_SOAP_RESPONSE);
			if (soapResponseAttr != null) {
				String responseStr = (String) soapResponseAttr.getValue(0);
				
				// Check if response is body-only (no envelope)
				if (responseStr != null &&
					!responseStr.contains("<soapenv:Envelope") &&
					!responseStr.contains("<soap:Envelope") &&
					!responseStr.contains("<env:Envelope") &&
					!responseStr.contains("<SOAP-ENV:Envelope")) {
					
					// Wrap body content in SOAP envelope
					String wrappedResponse =
						"<?xml version=\"1.0\" encoding=\"UTF-8\"?>" +
						"<soapenv:Envelope xmlns:soapenv=\"http://schemas.xmlsoap.org/soap/envelope/\">" +
						"<soapenv:Body>" +
						responseStr +
						"</soapenv:Body>" +
						"</soapenv:Envelope>";
					
					// Update the entry with wrapped response
					entry.setAttribute(ATTR_SOAP_RESPONSE, wrappedResponse);
					
					if (debugMode()) {
						debug("Wrapped body-only response in SOAP envelope for client compatibility");
					}
				}
			}
		}
		Trace.exitmin(this, "replyEntry", entry);
		super.replyEntry(entry);
	}

	/**
	 * Version information.
	 * @return version information.
	 */
	public String getVersion() {
		return "3.0-di11.0.0.1 %I%, 2025/10/08";
	}

	/**
	 * Checks whether the provided operation is supported by the server.
	 * 
	 * @param operationName
	 *            name of the operation to be checked
	 * @return <code>true</code> if supported , <code>false</code>
	 *         otherwise.
	 */
	private boolean operationExists(String operationName) {
		return mServiceOperations.contains(operationName);
	}

	/**
	 * This method sets the parsing mechanism from Java to SOAP for the
	 * specified operation.
	 * 
	 * @param operationName
	 *            the name of the operation.
	 * @return AxisSoapToJava instance
	 * @see AxisSoapToJava
	 * @throws Exception
	 *             if an error occurs.
	 */
	private AxisSoapToJava getAxisSoapToJavaFC(String operationName)
			throws Exception {
		AxisSoapToJava axisSoapToJavaFC = mAxisSoapToJavaMap.get(operationName);
		if (axisSoapToJavaFC == null) {
			axisSoapToJavaFC = new AxisSoapToJava();
			FunctionConfig config = new FunctionConfigImpl();
			axisSoapToJavaFC.setConfiguration(config);
			axisSoapToJavaFC.setParam(AxisSoapToJava.PARAM_WSDL_URL, mWsdlUrl);
			axisSoapToJavaFC.setParam(AxisSoapToJava.PARAM_SOAP_OPERATION,
					operationName);
			axisSoapToJavaFC.setParam(AxisSoapToJava.PARAM_COMPLEX_TYPES,
					mClasses);
			axisSoapToJavaFC.setParam(AxisSoapToJava.PARAM_INPUT_TYPE,
					AxisSoapToJava.INPUT_XML_STRING);
			axisSoapToJavaFC.setParam(AxisSoapToJava.PARAM_MODE,
					AxisSoapToJava.MODE_REQUEST);
			axisSoapToJavaFC.initialize(null);

			mAxisSoapToJavaMap.put(operationName, axisSoapToJavaFC);
		}

		return axisSoapToJavaFC;
	}

	/**
	 * This method sets the parsing mechanism from Java to SOAP for the
	 * specified operation.
	 * 
	 * @param operationName
	 *            the name of the operation.
	 * @return AxisJavaToSoap instance
	 * @see AxisJavaToSoap
	 * @throws Exception
	 *             if an error occurs.
	 */
	private AxisJavaToSoap getAxisJavaToSoapFC(String operationName)
			throws Exception {
		AxisJavaToSoap axisJavaToSoapFC = mAxisJavaToSoapMap.get(operationName);
		if (axisJavaToSoapFC == null) {
			axisJavaToSoapFC = new AxisJavaToSoap();
			FunctionConfig config = new FunctionConfigImpl();
			axisJavaToSoapFC.setConfiguration(config);
			axisJavaToSoapFC.setParam(AxisJavaToSoap.PARAM_WSDL_URL, mWsdlUrl);
			axisJavaToSoapFC.setParam(AxisJavaToSoap.PARAM_SOAP_OPERATION,
					operationName);
			axisJavaToSoapFC.setParam(AxisJavaToSoap.PARAM_COMPLEX_TYPES,
					mClasses);
			axisJavaToSoapFC.setParam(AxisJavaToSoap.PARAM_RETURN_XML_TYPE,
					AxisJavaToSoap.RETURN_XML_STRING);
			axisJavaToSoapFC.setParam(AxisJavaToSoap.PARAM_MODE,
					AxisJavaToSoap.MODE_RESPONSE);
			// AxisJavaToSoap is called with an Object array and not with an
			// Entry,
			// hence the PARAM_OPERATION_PARAM_LIST parameter is not used
			axisJavaToSoapFC.setParam(
					AxisJavaToSoap.PARAM_OPERATION_PARAM_LIST, "");
			axisJavaToSoapFC.initialize(null);

			mAxisJavaToSoapMap.put(operationName, axisJavaToSoapFC);
		}

		return axisJavaToSoapFC;
	}
}
