# -------------------------------------------------
# Please refer to the LDAPSync.pdf for instructions on how to
# configure and deploy this solution.
#
# Notes:
#	1. Try a simulated run first so you have metrics for comparison
#		  e.g. ibmdisrv -c LDAPSync/LDAPSync.xml r LDAPMigrate -0 simulate
#	2. Some properties settings disable other properties. Refer to LDAPSync.pdf
#	3. If things are not working, check the logs!
#	3b. Refer to LDAPSync.pdf for Troubleshooting tips
#	3c. Then check <SOLDIR>/LDAPSync/logs for solution log files, e.g. LDAPSync.log
#	4. There is a '-1 nn' commandline argument if you want a progress message every nn entries.
#		  e.g. ibmdisrv -c LDAPSync/LDAPSync.xml -r LDAPMigrate -0 simulate -1 250
#
# -------------------------------------------------

# -------------------------------------------------
# Global settings
#
# -- These first two properties control logging behavior
global.debug=true
global.logDirectory=LDAPSync/logs
global.maxLogFiles=20
global.showProgressCount=25
# -- You can override the simulate setting with the -0 commandline argument when launching
#       LDAPMigrate:   ibmdisrv -c LDAPMigrate/LDAPMigrate.xml -r LDAPMigrate -0 actual
#    NOTE that simulate only applies to LDAPMigrate. LDAPSync cannot be simulated.
simulate=true
# -- If this next property is true then the source hierarchy will be mirrored in the target
#    otherwise, if it's false then the source DIT is flattened when transferred to the target.
#    As a result, you must supply the target.suffixForUsers and target.suffixForGroups
#    Note that this property can be defined specifically for each Flow, for example:
#        SunFlow.preserveSourceContainers=true
#        AD1Flow.preserveSourceContainers=false
# The example property setting below applies to all Flows that are not specifically defined
global.preserveSourceContainers=false

#
# List of Flows (comma separated) - for example: global.flows=AD1Flow,AD2Flow,SunFlow
#
global.flows=

#
# -------------------------------------------------
# Source settings can be defined globally, and per Endpoint or Flow
#
source.ldap.url=
source.ldap.user=
{protect}-source.ldap.password=
source.ldap.searchBase=
#source.ldap.binaryAttributes=objectGUID
source.ldap.pageSize=0
# -- Change detection properties
# This next one can be set to AD, Sun or TDS
source.changeDetectionType=AD
source.ldap.stateKey=SourceSyncState
source.ldap.useNotifications=true
source.ldap.changelogTimeout=0
source.ldap.secondsForPolling=10
# -- For AD change detection
#source.ad.searchBase=
# -- 
source.userObjectClass=inetorgperson
source.groupObjectClass=groupOfUniqueNames
source.container.objectClasses=ou=organizationalUnit, dc=dcObject, c=country, o=organization
source.userRDN=uid

# -- These next two are use to filter entries via sub-string search
#    so you can specify full DNs, or partial.
#    Typically specified per Flow.
source.containersToMigrate=ou=Groups;ou=People
source.containersToSkip=Administrator;Test;$
#
# -------------------------------------------------
# Target settings can be defined globally, and per Endpoint or Flow
#
target.ldap.url=
target.ldap.user=
{protect}-target.ldap.password=
target.ldap.searchBase=
#target.ldap.binaryAttributes=objectGUID
# --
target.userRDN=uid
target.userObjectClass=inetOrgPerson,person,top,organizationalPerson
target.groupObjectClass=groupofuniquenames
target.groupMemberAttribute=uniqueMember
target.userRDN=uid
# -- These properties only apply if global.preserveSourceContainers is false
target.suffixForUsers=
target.suffixForGroups=
#

#
# -------------------------------------------------
#
# Map files can be specified for person, group or container type
#target.person.mapFile=person.map
#target.group.mapFile=group.map
#target.organizationalunit.mapFile=organizationalunit.map
#  ...

# -------------------------------------------------
# Here Endpoints (defined below) are tied to each Flow. For example:
#    AD1Flow.source.endpoint=AD1
#    AD1Flow.target.endpoint=TDS
# -------------------------------------------------
# Endpoint definitions. Note that these properties start with 'ep.' and then the name
#    of the Endpoint (for example, AD1 or SunDS), followed by the rest of the property
#    name. For Endpoint properties you remove 'source.' and 'target.' from the full
#    property name listd in the documentation. So for example, source.ldap.url would
#    become ep.AD1.ldap.url when defining it for the AD1 Endpoint
#
# The following are examples of properties for an Endpoint called 'AD1'
#
#ep.AD1.ldap.url=
#ep.AD1.ldap.user=
#{protect}-ep.AD1.ldap.password=
#ep.AD1.ldap.searchBase=
# ...    
# --------
# Flow-specific settings
#
# Here are examples of Flow-specific settings for AD1Flow. Note that
# these properties are required if preserverSourceContainers=false for
# this Flow. The containers listed must also exist in the target directory prior
# to running migration or synchronization operations.
#
#AD1Flow.target.suffixForUsers=ou=AD1,ou=Employees,dc=ibm.com
#AD1Flow.target.suffixForGroups=ou=AD1,ou=Employees,dc=ibm.com
