CONN_DESC = RAC Connector
CONN_TITLE = RAC Connector
remoteagentname_desc = The name of the remote Logging Agent to be monitored.
remoteagentname_label = Remote Logging Agent Name
achost_desc = Host of the remote Agent Controller.
achost_label = Agent Controller Host
acport_desc = Port of the remote Agent Controller.
acport_label = Agent Controller Port
recqueuesize_desc = The size of the queue, where the received events are buffered before the Connector manages to read them.
recqueuesize_label = Receiving Queue Size
waitfordeadagentdata_desc = Timeout (in seconds) for each data reception after the remote agent dies. If this timeout expires, the agent's data is considered depleted and the Connector starts looking for another agent with the same name.
waitfordeadagentdata_label = Wait For Dead Agent's Data
agentname_desc = The name of the Logging Agent within the local Agent Controller.
agentname_label = Logging Agent Name
waittobemonitored_desc = Time to wait (in seconds) for the agent to be monitored. If zero, waits forever.
waittobemonitored_label = Wait to be monitored
connectiontimeout_desc = Timeout (in seconds) for the connection to the Agent Controller
connectiontimeout_label = Connection Timeout
Advanced = Advanced
