PAR_DESC = Simple XML multi-level parser
In_XSL_isFile_label = Use input XSL file
In_XSL_isFile_desc = Use input XSL file
InputXSLf_label = Input XSL File Name
InputXSLf_desc = Input XSL to transform any xml into IDI internal format
InputXSL_label = Input XSL
InputXSL_desc = Input XSL to transform any xml into IDI internal format
Out_XSL_isFile_label = Use output XSL file
Out_XSL_isFile_desc = Use output XSL file
OutputXSLf_label = Output XSL File Name
OutputXSLf_desc = Output XSL to trasform internal format to original format
OutputXSL_label = Output XSL 
OutputXSL_desc = Output XSL to trasform internal format to original format
indent_label = Indent Output
indent_desc = If checked, causes the output to be neatly indented, improving human readability.
path_script_label = Select...
path_script_help = Browse file system
PAR_TITLE = XSL based XML Parser
INPUT_TITLE = Input
OUTPUT_TITLE = Output
CHARSET_LAB = Character Encoding
CHARSET_DESC = Character encoding to use when reading or writing
Advanced = Advanced
