##{PropertiesConnector} savedBy=administrator, saveDate=Tue Apr 05 16:26:22 IST 2011
baseURL=http://9.182.176.98
authRequired=true
userid=maxadmin
{protect}-password={encr}okcXzo9EhfarD3BFfk/iiRz2yC/yrd1IJfqUBSkU+jwu/c6aVTGpdKVOhFnvV6sNrk7N4BEJENEN22ReIRN8VTAJfFYDaA6AX63E0ktHg6zOgdxhgwM8mmeIX8Yc6i5fFqnP+5f5aXowTMK/2sCZ5djI/PBfEVuUTne9JBkTJzk=
objectstructure=MXASSET
mbo=ASSET
