FC_TITLE = Axis2 Web Service Client Function Component
FUNCTION_DESC = Axis2 Web Service Client Function Component
WSDL_LBL = WSDL URL
WSDL_DESC = The URL to the WSDL file describing the Web Service.
SERVICE_LBL = Service
SERVICE_DESC = The service name which will be invoked.
SERVICE_SCRIPT_LABEL = Service...
SERVICE_SCRIPT_HELP = Retrieve services from WSDL
OP_LBL = Operation
OP_DESC = The SOAP operation name which will be invoked.
OP_SCRIPT_LABEL = Operation...
OP_SCRIPT_HELP = Retrieve operations from WSDL
EP_LBL = Endpoint
EP_DESC = The endpoint to which the request will be sent.
EP_SCRIPT_LABEL = Endpoints...
EP_SCRIPT_HELP = Retrieve endpoints from WSDL
USER_DESC = Username name for login.
USER_LBL = Username
PASS_DESC = Password associated with Login username.
PASS_LBL = Password
Advanced = Advanced
timeout_label = Connection Timeout
timeout_desc = Specify a connection timeout in milliseconds. Default is 60000 (one minute).
WSDL_USERNAME_DESC = WSDL Username name for login
WSDL_USERNAME_LBL = WSDL Login username
WSDL_PASS_DESC = Password associated with WSDL Login username.
WSDL_PASS_LBL = WSDL Login password
