CONN_DESC = Lotus Domino V5.08 or higher
host_desc = Domino server TCP/IP address or hostname. You can also specify the IOR\:<xxx\= string to circumvent automatic discovery of this via HTTP.
host_label = Domino Server IP Address
port_desc = The port on which the Domino HTTP task is running
port_label = HTTP port
log_desc = Internet username
log_label = Username
pass_desc = Internet password
pass_label = Password
type_label = Session Type
type_desc = The type of session to use
for_label = Always use Formula Search
for_desc = Use formula search even if database is full-text indexed (only when View is not specified)
ssl_label = Use SSL
ssl_desc = Enables encrypted communications with the Domino server
ConserveMemory_label = Conserve Memory
ConserveMemory_desc = Set a variable to conserve memory while iterating through a search view
bsae_desc = The database to open
base_label = Database
base_script_label = Select...
base_script_help = Select from server's available databases
view_desc = Database view
view_label = Database View
view_script_label = Select...
view_script_help = Select a view by querying the domino server
sele_desc = LotusFormula Selection criteria (Iterator mode only)
sele_label = Document Selection
ser_desc = Domino server name. Leave blank to use session server
ser_label = Domino Server Name
rt_desc = Enables Domino RichTextItems to be mapped as such in the Entry. Otherwise they will be converted to plain text. WARNING\: As RichTextItems are not serializable, enabling this option will cause an exception if an attribute is mapped to another Domino database or if IBM Security Verify Directory Integrator Server is used remotely. 
rt_label = Support RichText items
CONN_TITLE = Lotus Notes Connector
Localized.IIOP = IIOP
Localized.LocalClient = LocalClient
Localized.LocalServer = LocalServer
Advanced = Advanced
