##{PropertiesConnector} savedBy=jens thomassen, saveDate=Mon Oct 07 10:46:53 SGT 2013
##
# LDAP server where the data will be stored
#
# URL
LDAPServer=ldap://localhost:1389

# Searchbase for users and groups
userSearchBase=ou=People,DC=EXAMPLE,DC=COM
groupSearchBase=ou=Groups,DC=EXAMPLE,DC=COM

# Searchfilter for users and groups
userSearchFilter=objectClass=person
groupSearchFilter=objectClass=groupOfUniqueNames

# objectclass used when creating users and groups
userObjectClass=person,inetOrgPerson,organizationalPerson,top
groupObjectClass=groupOfUniqueNames,top

# When creating new groups, if dummyGroupMember has a value and there are no members in the group,
# this value will be added to avoid ObjectViolation
dummyGroupMember=cn=dummyUser

# Lookup Limit, this is the maximum number of resources that can be found
LDAP.LookupLimit=20000

#
# External name for SCIM server
# This is only used in Location header
Location=https://example.com/v1

# The port the server should listen at. It will always use SSL.
httpPort=8070

# AuthenticationRealm, useful for testing
AuthenticationRealm=IBM SDI SCIM Testing

# Set debugging to true to get more informatin in the log files
debugging=false

#
# Audit logging
# For advanced logging, use log4j.properties to configure a logger for com.ibm.di.ScimService
#
# Set this to true to enable audit logging
audit.log=false

# Audit log file
audit.logFile=SCIM/logs/audit.log

# Date Pattern, decides how often the log file will be rolled
audit.logFileDatePattern='.'yyyy-MM-dd

#
# Audit logging to QRadar using syslog
#
# Set this to true to enable this logging
audit.syslog=false

# The host and port to send syslog to
audit.QRadarHost=localhost
audit.QRadarPort=514

# Facility to use
audit.facility=13

#LEEF properties
audit.eventID=SCIM Service Logging
audit.devTimeFormat=MMM dd yyyy HH:mm:ss.SSS

# Set this property to true to enable a new endpoint, "authentication"
authenticationEndpoint=false

# To allow users of the SCIM service to provide a domain name, instead of a LDAP DN, set mapTenantNames to true
mapTenantNames=false

# If mapTenantNames is true, the next two properties may also be used:

# A tenant with "superuser" access is able to create new tenants. This property specifies where the new tenants should be located.
# This must be an existing container in the LDAP server.
#  tenantBase=ou=something

# When set to true, this property enables the use of tenant specific password policies. tenantBase must also be set,
# and the tenants must be created automatically using the "superuser".
#  usePasswordPolicy=true

# Here is an example of how to use this to add a couple of domains:
# The user domain-admin which can do anything, and domain-auth who can only do authentication


# Here is an example of how to use this to add a couple of domains:
# The user domain-admin which can do anything, and domain-auth who can only do authentication

#domain-admin.ldapName=cn=root
#{protect}-domain-admin.password=Secret
#{protect}-domain-admin.ldapPassword=VerySecret
#domain-admin.access=all

#domain-auth.ldapName=cn=root
#{protect}-domain-auth.password=AuthPass
#{protect}-domain-auth.ldapPassword=VerySecret
#domain-auth.access=auth

# This can also be used to allow multi-tenancy, where different domains see different parts of the LDAP databaseo
# Here is an example that adds a user named "org-domain-admin", which has a different LDAP search base

#org-domain-admin.ldapName=cn=root
#{protect}-org-domain-admin.password=Secret
#{protect}-org-domain-admin.ldapPassword=VerySecret
#org-domain-admin.access=all
#org-domain-admin.userSearchBase=OU=People,OU=org,DC=example,DC=com
#org-domain-admin.groupSearchBase=OU=Groups,OU=org,DC=example,DC=com
