/*
 * Copyright IBM Corp. 2025
 *
 * SPDX-License-Identifier: Apache-2.0
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.10 at 02:47:00 PM CET 
//

package com.ibm.di.ui.webui.bind;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for auth complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="auth">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="enabled" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="localhost" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="remotehost" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ldapurl" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ldapgroup" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "auth", propOrder = {
    "enabled",
    "localhost",
    "remotehost",
    "ldapurl",
    "ldapgroup"
})
public class Auth {

    protected boolean enabled;
    @XmlElement(required = true)
    protected String localhost;
    @XmlElement(required = true)
    protected String remotehost;
    @XmlElement(required = true)
    protected String ldapurl;
    @XmlElement(required = true)
    protected String ldapgroup;

    /**
     * Gets the value of the enabled property.
     * 
     */
    public boolean isEnabled() {
        return enabled;
    }

    /**
     * Sets the value of the enabled property.
     * 
     */
    public void setEnabled(boolean value) {
        this.enabled = value;
    }

    /**
     * Gets the value of the localhost property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocalhost() {
        return localhost;
    }

    /**
     * Sets the value of the localhost property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocalhost(String value) {
        this.localhost = value;
    }

    /**
     * Gets the value of the remotehost property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRemotehost() {
        return remotehost;
    }

    /**
     * Sets the value of the remotehost property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRemotehost(String value) {
        this.remotehost = value;
    }

    /**
     * Gets the value of the ldapurl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLdapurl() {
        return ldapurl;
    }

    /**
     * Sets the value of the ldapurl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLdapurl(String value) {
        this.ldapurl = value;
    }

    /**
     * Gets the value of the ldapgroup property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLdapgroup() {
        return ldapgroup;
    }

    /**
     * Sets the value of the ldapgroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLdapgroup(String value) {
        this.ldapgroup = value;
    }

}
