/*
 * Copyright IBM Corp. 2025
 *
 * SPDX-License-Identifier: Apache-2.0
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.30 at 02:24:47 PM CET 
//

package com.ibm.di.ui.webui.bind;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for logsearch complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="logsearch">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="config" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="assemblyline" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="logfile" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="regex" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="source" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="qualifiers" type="{http://www.ibm.com/xmlns/prod/tdi/72/api}logqualifiers"/>
 *         &lt;element name="location" type="{http://www.ibm.com/xmlns/prod/tdi/72/api}loglocation"/>
 *         &lt;element name="excludesource" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="result" type="{http://www.ibm.com/xmlns/prod/tdi/72/api}logsearchresult" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "logsearch", propOrder = {
    "config",
    "assemblyline",
    "logfile",
    "regex",
    "source",
    "qualifiers",
    "location",
    "excludesource",
    "result"
})
public class Logsearch {

    @XmlElement(required = true)
    protected String config;
    @XmlElement(required = true)
    protected String assemblyline;
    @XmlElement(required = true)
    protected String logfile;
    @XmlElement(required = true)
    protected String regex;
    @XmlElement(required = true)
    protected String source;
    @XmlElement(required = true)
    protected Logqualifiers qualifiers;
    @XmlElement(required = true)
    protected Loglocation location;
    @XmlElement(required = true)
    protected String excludesource;
    @XmlElement(name="result")
    protected List<Logsearchresult> result;

    /**
     * Gets the value of the config property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConfig() {
        return config;
    }

    /**
     * Sets the value of the config property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConfig(String value) {
        this.config = value;
    }

    /**
     * Gets the value of the assemblyline property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAssemblyline() {
        return assemblyline;
    }

    /**
     * Sets the value of the assemblyline property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAssemblyline(String value) {
        this.assemblyline = value;
    }

    /**
     * Gets the value of the logfile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLogfile() {
        return logfile;
    }

    /**
     * Sets the value of the logfile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLogfile(String value) {
        this.logfile = value;
    }

    /**
     * Gets the value of the regex property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegex() {
        return regex;
    }

    /**
     * Sets the value of the regex property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegex(String value) {
        this.regex = value;
    }

    /**
     * Gets the value of the source property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSource() {
        return source;
    }

    /**
     * Sets the value of the source property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSource(String value) {
        this.source = value;
    }

    /**
     * Gets the value of the qualifiers property.
     * 
     * @return
     *     possible object is
     *     {@link Logqualifiers }
     *     
     */
    public Logqualifiers getQualifiers() {
        return qualifiers;
    }

    /**
     * Sets the value of the qualifiers property.
     * 
     * @param value
     *     allowed object is
     *     {@link Logqualifiers }
     *     
     */
    public void setQualifiers(Logqualifiers value) {
        this.qualifiers = value;
    }

    /**
     * Gets the value of the location property.
     * 
     * @return
     *     possible object is
     *     {@link Loglocation }
     *     
     */
    public Loglocation getLocation() {
        return location;
    }

    /**
     * Sets the value of the location property.
     * 
     * @param value
     *     allowed object is
     *     {@link Loglocation }
     *     
     */
    public void setLocation(Loglocation value) {
        this.location = value;
    }

    /**
     * Gets the value of the excludesource property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExcludesource() {
        return excludesource;
    }

    /**
     * Sets the value of the excludesource property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExcludesource(String value) {
        this.excludesource = value;
    }

    /**
     * Gets the value of the result property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the result property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getResult().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Logsearchresult }
     * 
     * 
     */
    public List<Logsearchresult> getResult() {
        if (result == null) {
            result = new ArrayList<Logsearchresult>();
        }
        return this.result;
    }

}
