/*
 * Copyright IBM Corp. 2025
 *
 * SPDX-License-Identifier: Apache-2.0
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.18 at 06:30:57 PM CEST 
//

package com.ibm.di.ui.webui.bind;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for statistics complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="statistics">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="add" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="mod" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="del" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="get" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="request" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="callReply" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="err" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="skip" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="lookup" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="ignore" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="reconnect" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "statistics", propOrder = {
    "add",
    "mod",
    "del",
    "get",
    "request",
    "callReply",
    "err",
    "skip",
    "lookup",
    "ignore",
    "reconnect"
})
public class Statistics {

    protected int add;
    protected int mod;
    protected int del;
    protected int get;
    protected int request;
    protected int callReply;
    protected int err;
    protected int skip;
    protected int lookup;
    protected int ignore;
    protected int reconnect;

    /**
     * Gets the value of the add property.
     * 
     */
    public int getAdd() {
        return add;
    }

    /**
     * Sets the value of the add property.
     * 
     */
    public void setAdd(int value) {
        this.add = value;
    }

    /**
     * Gets the value of the mod property.
     * 
     */
    public int getMod() {
        return mod;
    }

    /**
     * Sets the value of the mod property.
     * 
     */
    public void setMod(int value) {
        this.mod = value;
    }

    /**
     * Gets the value of the del property.
     * 
     */
    public int getDel() {
        return del;
    }

    /**
     * Sets the value of the del property.
     * 
     */
    public void setDel(int value) {
        this.del = value;
    }

    /**
     * Gets the value of the get property.
     * 
     */
    public int getGet() {
        return get;
    }

    /**
     * Sets the value of the get property.
     * 
     */
    public void setGet(int value) {
        this.get = value;
    }

    /**
     * Gets the value of the request property.
     * 
     */
    public int getRequest() {
        return request;
    }

    /**
     * Sets the value of the request property.
     * 
     */
    public void setRequest(int value) {
        this.request = value;
    }

    /**
     * Gets the value of the callReply property.
     * 
     */
    public int getCallReply() {
        return callReply;
    }

    /**
     * Sets the value of the callReply property.
     * 
     */
    public void setCallReply(int value) {
        this.callReply = value;
    }

    /**
     * Gets the value of the err property.
     * 
     */
    public int getErr() {
        return err;
    }

    /**
     * Sets the value of the err property.
     * 
     */
    public void setErr(int value) {
        this.err = value;
    }

    /**
     * Gets the value of the skip property.
     * 
     */
    public int getSkip() {
        return skip;
    }

    /**
     * Sets the value of the skip property.
     * 
     */
    public void setSkip(int value) {
        this.skip = value;
    }

    /**
     * Gets the value of the lookup property.
     * 
     */
    public int getLookup() {
        return lookup;
    }

    /**
     * Sets the value of the lookup property.
     * 
     */
    public void setLookup(int value) {
        this.lookup = value;
    }

    /**
     * Gets the value of the ignore property.
     * 
     */
    public int getIgnore() {
        return ignore;
    }

    /**
     * Sets the value of the ignore property.
     * 
     */
    public void setIgnore(int value) {
        this.ignore = value;
    }

    /**
     * Gets the value of the reconnect property.
     * 
     */
    public int getReconnect() {
        return reconnect;
    }

    /**
     * Sets the value of the reconnect property.
     * 
     */
    public void setReconnect(int value) {
        this.reconnect = value;
    }

}
