CONN_DESC = Template driven database connector
CONN_TITLE = Database Connector (JDBC)
source_desc = JDBC URL
source_label = JDBC URL
login_desc = Login user
login_label = Username
pass_label = Password
schema_label = Schema
select_desc = SQL Select for Iterator mode (also used as statement stub (without "WHERE" keyword) for Link Criteria)
select_label = SQL Select
table_desc = Database table name
table_label = Table Name
table_script_label = Select...
table_script_help = Query server for a list of available tables (may be a big one\!)
driver_desc = JDBC Driver Class
driver_label = JDBC Driver
panel_verify_driver_tt = Verify that the driver class can be found and loaded
panel_verify_driver = Verify
panel_loaddriver_success = Driver was successfully loaded
panel_hostname = Hostname
panel_port = Port
panel_database = Database
panel_login = Login and Table selection
panel_dbtype = Database Type
