CONN_DESC = AssemblyLine Connector
AL_DESC = The AssemblyLine that this Connector will use.
AL_LABEL = AssemblyLine
SERVER_DESC = The SyncWeave server where the AssemblyLine is defined and will be run.
SERVER_LABEL = Remote Server
CONN_TITLE = AssemblyLine Connector
AL_CI_LABEL = Config Instance
AL_CI_DESC = The ID or path of the Config instance on the remote server.
AL_CI_S_LABEL = Query
AL_CI_S_HELP = Query the server for available configuration instances
AL_AL_S_LABEL = Query
AL_AL_S_HELP = Query the server for available AssemblyLines
CUSTOM_SEC_DESC = Check to use the "api.remote.server." java properties instead of standard "javax.net.ssl." properties for keystore configuration
CUSTOM_SEC_LABEL = Custom Keystores
OPERATION_INIT_LABEL = AssemblyLine Parameters
OPERATION_INIT_DESC = AssemblyLine Parameters as defined in the AssemblyLine Operations tab.
SHARE_LOG_LABEL = Share Logging
SHARE_LOG_DESC = If set, the called AssemblyLine will use the same logging as this Component/AssemblyLine.
SIMULATE_LABEL = Simulate
SIMULATE_DESC = If set, the called AssemblyLine will make use of its Simulation Config when interacting with external systems.
Advanced = Advanced
