;*********************************************************
; define constraints to detect windows
;*********************************************************
#constraint WIN9XFAMILY java.os.name=Windows 95 OR java.os.name=Windows 98 OR java.os.name=Windows Me
#constraint WINNTFAMILY java.os.name=Windows 2000 OR java.os.name=Windows XP OR java.os.name=Windows NT OR java.os.name=Windows 2003 AND java.os.version>=4
#constraint REALWIN WIN9XFAMILY OR WINNTFAMILY
#constraint WIN     REALWIN
;*********************************************************
; define constraints to detect unix
;*********************************************************
#constraint AIX     java.os.name=AIX
#constraint SUN     java.os.name=Solaris OR java.os.name=SunOS AND java.os.version>5.4
#constraint LIN     java.os.name=Linux
#constraint HPUX    java.os.name=HP-UX
; #constraint SCO     java.os.name=UnixWare
; #constraint UNIX    AIX OR SUN OR LIN OR HPUX OR SCO
#constraint UNIX    AIX OR SUN OR LIN OR HPUX
#constraint WORKSTATION UNIX OR WIN
;*********************************************************
; define functions to use
;*********************************************************
; AIX LPP functions
#function lppInstalled  com.ibm.commerce.depchecker.tools.LPPTool::pkgInstalled(1)
#function lppFirstPkg   com.ibm.commerce.depchecker.tools.LPPTool::getFirstPkg(1)
#function lppVersion    com.ibm.commerce.depchecker.tools.LPPTool::pkgVersion(1)
#function lppLocation   com.ibm.commerce.depchecker.tools.LPPTool::pkgLocation(2)
; Solaris PKG functions
#function pkgInstalled  com.ibm.commerce.depchecker.tools.PkgTool::pkgInstalled(1)
#function pkgFirstPkg   com.ibm.commerce.depchecker.tools.PkgTool::getFirstPkg(1)
#function pkgVersion    com.ibm.commerce.depchecker.tools.PkgTool::pkgVersion(1)
#function pkgLocation   com.ibm.commerce.depchecker.tools.PkgTool::pkgLocation(2)
#function pkgPatchVersion com.ibm.commerce.depchecker.tools.PkgTool::pkgPatchVersion(1)
#function pkgPatchCompare com.ibm.commerce.depchecker.tools.PkgTool::pkgPatchCompare(3)
#function pkgGetSysParam com.ibm.commerce.depchecker.tools.PkgTool::pkgGetSysParam(1)
; Linux RPM functions
#function rpmInstalled  com.ibm.commerce.depchecker.tools.RPMTool::pkgInstalled(1)
#function rpmFirstPkg   com.ibm.commerce.depchecker.tools.RPMTool::getFirstPkg(1)
#function rpmVersion    com.ibm.commerce.depchecker.tools.RPMTool::pkgVersion(1)
#function rpmLocation   com.ibm.commerce.depchecker.tools.RPMTool::pkgLocation(2)
; HPUX swlist functions
#function swlistInstalled  com.ibm.commerce.depchecker.tools.SwlistTool::pkgInstalled(1)
#function swlistFirstPkg   com.ibm.commerce.depchecker.tools.SwlistTool::getFirstPkg(1)
#function swlistVersion    com.ibm.commerce.depchecker.tools.SwlistTool::pkgVersion(1)
#function swlistLocation   com.ibm.commerce.depchecker.tools.SwlistTool::pkgLocation(2)
; ISMP VPD functions
#function ismpInstalled   com.ibm.commerce.depchecker.tools.VpdPropertiesTool::isInstalled(2)
#function ismpGetField    com.ibm.commerce.depchecker.tools.VpdPropertiesTool::getField(3)

; grep and simpleGrep
; param 1 - a buffer to grep against
; param 2 - a key to search for.  For simpleGrep, there are no characters
;   with special meanings
; returns: All lines in buffer matching key
#function grep            com.ibm.commerce.depchecker.common.StringUtils::grep(2)
#function simpleGrep      com.ibm.commerce.depchecker.common.StringUtils::simpleGrep(2)

; removeStr
; param 1 - A string
; param 2 - A substring to remove from string
; returns: param 1 with all occurances of param 2 removed
#function removeStr       com.ibm.commerce.depchecker.common.StringUtils::removeAll(2)

; compare
; param 1 - A String representing a version of the V.R.P.S form
; param 2 - A String representing a comparison operator (any combo of <>= or !=)
; param 3 - A String representing a version of the V.R.P.S form
; returns: The logical boolean result of the implied comparison. Version
;   numbers are compared on a verion basis and not String basis. (ie - 2.1
;   is equal to 2.1.0.0)
#function compare         com.ibm.commerce.depchecker.common.VersionTool::compare(3)

; isUserAdmin
; returns: true if user has admin privileges, false otherwise
#function isUserAdmin     com.ibm.commerce.depchecker.tools.MiscTool::isUserAdmin(0)

; shellTrim
; param 1 - A command to execute in another process
; returns: stdout from the process, or stderr if stdout was empty, with
;   leading and trailing whitespace removed
#function shellTrim       com.ibm.commerce.depchecker.tools.MiscTool::execTrim(1)

; isValidString
; param 1 - A string
; returns: "true" if the string is not null or empty, "false" otherwise
#function isValidString   com.ibm.commerce.depchecker.common.StringUtils::isValidString(1)

; trim
; param 1 - a String
; returns: param 1 less leading and trailing whitespace
#function trim            com.ibm.commerce.depchecker.common.StringUtils::trim(1)

;*********************************************************
; Check if user has admin priviledges
;*********************************************************
using(WORKSTATION) {
  ADMINUSER.isAdmin     = isUserAdmin()
}

;*********************************************************
;  Check if ITDI is already installed
;*********************************************************
VARS.itdi_component   = "IBMDirInt"
VARS.sun_itdi_component   = "ISIBMDirI"
VARS.dummy_file       = "dummy"
#constraint ITDI_INSTALLED ITDI.installed=true
#constraint ITDI_VERSION_5 ITDI.version=5
#constraint ITDI_VERSION_5_HP ITDI.HPversion=5.2.0
#constraint ITDI_VERSION_5_SUN ITDI.SUNversion=5.2
#constraint ITDI_VERSION_6 ITDI.version=6
#constraint ITDI_SOLDIR_EXISTS ITDI.SOLDIRstring=true

using(WIN){
  ITDI.environment      = shellTrim("cmd /c set")

  WIN.DIR               = simpleGrep("\{ITDI.environment}", "SystemRoot")
  WIN.DIRvalue          = removeStr("\{WIN.DIR}","SystemRoot=")
  WIN.DIRraw            = trim("\{WIN.DIRvalue}")
  WIN.ismp_vpd          = "\{WIN.DIRraw}\vpd.properties"

  ITDI.SOLDIR           = simpleGrep("\{ITDI.environment}", "TDI_SOLDIR")
  ITDI.SOLDIRstring     = isValidString("\{ITDI.SOLDIR}")
  using(ITDI_SOLDIR_EXISTS){
    ITDI.SOLDIRexists   = "true"
  }
  ITDI.SOLDIRkeyValue   = simpleGrep("\{ITDI.environment}", "TDI_SOLDIR")
  ITDI.SOLDIRvalue      = removeStr("\{ITDI.SOLDIRkeyValue}","TDI_SOLDIR=")

  ITDI.userprof         = simpleGrep("\{ITDI.environment}", "USERPROFILE")
  ITDI.userprofvalue    = removeStr("\{ITDI.userprof}","USERPROFILE=")

  ITDI.installed        = ismpInstalled("\{WIN.ismp_vpd}", "\{VARS.itdi_component}")
  using(ITDI_INSTALLED){
    ITDI.location       = ismpGetField("\{WIN.ismp_vpd}", "\{VARS.itdi_component}", "12")
    ITDI.version        = ismpGetField("\{WIN.ismp_vpd}", "\{VARS.itdi_component}", "1")
    using(ITDI_VERSION_5){
      ITDI.version5installed = "true"
    }
    using(ITDI_VERSION_6){
      ITDI.version6installed = "true"
    }
;    ITDI.release            = ismpGetField("\{VARS.ismp_vpd}", "\{VARS.itdi_component}", "2")
;    ITDI.modification       = ismpGetField("\{VARS.ismp_vpd}", "\{VARS.itdi_component}", "3")
;    ITDI.fix                = ismpGetField("\{VARS.ismp_vpd}", "\{VARS.itdi_component}", "4")
  }
}
using(AIX){
; registration on AIX is in vpd.properties as IBMDirInt 5.2.-.0
  AIX.ismp_vpd           = "/usr/lib/objrepos/vpd.properties"
  ITDI.installed         = ismpInstalled("\{AIX.ismp_vpd}", "\{VARS.itdi_component}")
  using(ITDI_INSTALLED){
    ITDI.location        = ismpGetField("\{AIX.ismp_vpd}", "\{VARS.itdi_component}", "12")
    ITDI.version         = ismpGetField("\{AIX.ismp_vpd}", "\{VARS.itdi_component}", "1")
    using(ITDI_VERSION_5){
      ITDI.version5installed = "true"
    }
    using(ITDI_VERSION_6){
      ITDI.version6installed = "true"
    }
  }
;  ITDI.AIX.installed      = lppInstalled("\{VARS.itdi_aix_pkg}")
;  ITDI.AIX.version        = lppVersion("\{VARS.itdi_aix_pkg}")
}
using(LIN){
; registration on Linux is in vpd.properties as IBMDirInt 5.2.-.0
; is this the same for PPC and 390 ??
  LIN.ismp_vpd           = "/root/vpd.properties"
  ITDI.installed         = ismpInstalled("\{LIN.ismp_vpd}", "\{VARS.itdi_component}")
  using(ITDI_INSTALLED){
    ITDI.location        = ismpGetField("\{LIN.ismp_vpd}", "\{VARS.itdi_component}", "12")
    ITDI.version         = ismpGetField("\{LIN.ismp_vpd}", "\{VARS.itdi_component}", "1")
    using(ITDI_VERSION_5){
      ITDI.version5installed = "true"
    }
    using(ITDI_VERSION_6){
      ITDI.version6installed = "true"
    }
  }
;  ITDI.LIN.rpminstalled   = rpmInstalled("\{VARS.itdi_lin_pkg}")
;  ITDI.LIN.rpmversion     = rpmVersion("\{VARS.itdi_lin_pkg}")
}
using(SUN){
; registration on Solaris is in native "pkg" as ISIBMDirI 5.2..0
; NOTE: pkgLocation(using pkgchk)thows an exception because even though the 
; package is installed it reports as empty.  
; Its assumed this is a limitation with the registry done by IS during the 
; install. The result is we cannot report a location for Sun using the 
; pkgLocation method. 
  ITDI.installed          = pkgInstalled("\{VARS.sun_itdi_component}")
  using(ITDI_INSTALLED){
    ITDI.SUNversion       = pkgVersion("\{VARS.sun_itdi_component}")
;    ITDI.location         = pkgLocation("\{VARS.sun_itdi_component}","VARS.dummy_file")
; hack to find location
    ITDI.location = shellTrim("pkginfo -l \{VARS.sun_itdi_component} | grep BASEDIR | awk '{print $2}'")
; this also works
;    ITDI.location = shellTrim("pkginfo -l \{VARS.sun_itdi_component} | grep BASEDIR | cut -d ':' -f2")
    using(ITDI_VERSION_5_SUN){
      ITDI.version5installed = "true"
    }
  }
}
using(HPUX){
; registration on HPUX is native only.IBMDirInt 5.2.0
  ITDI.installed         = swlistInstalled("\{VARS.itdi_component}")
  using(ITDI_INSTALLED){
    ITDI.location        = swlistLocation("\{VARS.itdi_component}","VARS.dummy_file")
    ITDI.HPversion       = swlistVersion("\{VARS.itdi_component}")
    using(ITDI_VERSION_5_HP){
      ITDI.version5installed = "true"
    }
  }
}
using(UNIX){
   ITDI.TDI_SOLDIRenv = shellTrim("echo $TDI_SOLDIR")
   ITDI.HOMEenv = shellTrim("echo $HOME")

}
