CONN_DESC = Properties Connector
CONN_TITLE = Properties Connector
collectiontype_label = Collection Type
collectiontype_desc = Collection Type
Localized.Java-Properties = Java-Properties
Localized.Global-Properties = Global-Properties
Localized.Solution-Properties = Solution-Properties
Localized.System-Properties = System-Properties
Localized.User-Defined = User-Defined
collection_desc = Collection Path/URL
collection_label = Collection Path/URL
coll_script_label = Select...
coll_script_help = Browse file system
createcoll_desc = Check to automatically create file
createcoll_label = Create
encryption_desc = Check to cause this properties file to be encrypted.
encryption_label = Encryption
cipher_desc = Specifies the cipher algorithm for encryption/decryption. The word "server" means to use the default server certificate.
cipher_label = Cipher Alg.
secret_desc = Password used for encrypting/decrypting this file. Only used if Property Key is not specified, Encrypt is checked, and Cipher Alg. is not "server".
secret_label = Password
autorewrite_desc = If checked, then this collection will be re-written if Protected properties are detected. If this parameter is false, the collection must be written back by programmatic means.
autorewrite_label = Auto-Rewrite
Advanced = Advanced
keyAlias_label = Property Key
keyAlias_desc = Specify a key in the server keystore to use for encrypting/decrypting properties or the entire file.
