CONN_DESC = Memory Queue (MemQueue) Connector
CONN_TITLE = Memory Queue (MemQueue) Connector
INSTANCE_LABEL = Instance
INSTANCE_DESC = Server instance name - leave blank for current instance
QUEUE_LABEL = Queue
QUEUE_DESC = Queue/Pipe Name
TIMEOUT_LABEL = Read timeout
TIMEOUT_DESC = read timeout in milliseconds
WATERMARK_LABEL = Watermark
WATERMARK_DESC = Number of messages to keep in memory. Absolute max if paging is turned 'off'.
PAGING_DESC = enable paging using system store
PAGING_LABEL = Enable paging using system store
PAGESIZE_DESC = number of entries in one page
PAGESIZE_LABEL = Page Size
DBNAME_DESC = JDBC URL to the System Store database (or blank for default). Used if paging is enabled.
DBNAME_LABEL = Database name
USERNAME_DESC = Login username for the System Store database. Used if paging is enabled.
USERNAME_LABEL = Username
PASSWORD_LABEL = Password
PASSWORD_DESC = Login password for the System Store database. Used if paging is enabled.
TABLE_DESC = Name of System Store table to use for paging (if paging is enabled).
TABLE_LABEL = Table Name
BLOCKING_ADD_DESC = Specifies that adds are ignored (but logged) when the queue is full and paging disabled. Otherwise they will result in an error/exception.
BLOCKING_ADD_LABEL = Blocking add operation
PERCENTMEMORY_DESC = The percentage of memory that can be utilised by the queue.
PERCENTMEMORY_LABEL = Percentage memory to use
readLockRelease_desc = Determines when the Connector in iterator mode will release the read lock.
readLockRelease_label = Iterator Read Lock Release
Localized.After.single.read = After single read
Localized.End.of.AL.cycle = End of AL cycle
Localized.Connector.close = Connector close
Advanced = Advanced
