CONN_DESC = DSMLv2 SOAP Server Connector
DSML_PORT_DESC = Port for incoming DSML requests
DSML_PORT_LBL = DSML Port
HTTP_AUTH_DESC = Request HTTP Basic authentication
HTTP_AUTH_LBL = HTTP Basic Authentication
AUTH_REALM_DESC = The basic-realm sent to the client in case authentication is requested
AUTH_REALM_LBL = Auth Realm
BINARY_ATTR_DESC = User defined binary attributes delimited by ",".\nThese attributes will be Base64 decoded when parsing DSML messages.
BINARY_ATTR_LBL = Binary Attributes
USE_SSL_DESC = Use SSL to set up the connection
USE_SSL_LBL = Use SSL
CLIENT_AUTH_DESC = Mandate client authentication using SSL
CLIENT_AUTH_LBL = Require Client Authentication
SOAP_BINDING_DESC = Use DSML SOAP Binding
SOAP_BINDING_LBL = Soap Binding
MSG_CHUNKED_DESC = If checked, the body of the message is transferred as a series of chunks
MSG_CHUNKED_LBL = Chunked Transfer Encoding
CONN_TITLE = DSMLv2 SOAP Server Connector
TCP_BACKLOG_DESC = The maximum queue length for incoming connections. If a connection request arrives when the queue is full, the connection will be refused.
TCP_BACKLOG_LABEL = Connection Backlog
Advanced = Advanced
