/*
 * Copyright contributors to the SyncWeave project
 *
 * SPDX-License-Identifier: Apache-2.0
 */
package com.ibm.di.nls;

import java.util.Locale;
import java.util.MissingResourceException;
import java.util.ResourceBundle;

import com.ibm.icu.text.MessageFormat;

/**
 * Provides localization support for property files generated by the TMSXML
 * files.
 * <p>
 * <b> This class is tread safe.</b>
 * 
 * @since 7.2
 */
public abstract class L10N {
	/**
	 * Copyright.
	 */
	@SuppressWarnings("unused")
	private static final String COPYRIGHT = com.ibm.di.CopyRight.OBJECT_CODE;

	/**
	 * @return the NLS string given the resource for the default locale.
	 */
	public String getString(String resource) {
		return getString(resource, Locale.getDefault());
	}

	/**
	 * Returns the NLS string value for the passed "resource" (key) and replaces
	 * the placeholders {0},{1},etc by the corresponding
	 * params[0],params[1],etc.
	 * 
	 * @param resource
	 *            The key whose value is to be retrieved.
	 * @param params
	 *            An array of strings which will replace placeholders
	 * @return The value with placeholders replaced.
	 */
	public String getString(String resource, Object... params) {
		return getString(resource, null, params);
	}

	/**
	 * @return the NLS string given the resource and the specified locale
	 */
	public String getString(String resource, Locale locale) {
		return getString(resource, locale, (Object[]) null);
	}

	/**
	 * Returns the NLS string value for the passed "resource" (key) and replaces
	 * the placeholders {0},{1},etc by the corresponding
	 * params[0],params[1],etc.
	 * 
	 * @param resource
	 *            The key whose value is to be retrieved.
	 * @param params
	 *            An array of strings which will replace placeholders
	 * @return The value with placeholders replaced.
	 */
	public String getString(String resource, Locale locale, Object... params) {
		ResourceBundle res = getResourceBundle(locale);

		// if the string cannot be found, return the string ID instead
		// ...usually when in unit-testing env.
		String theString = resource;
		if (res != null) {
			try {
				theString = res.getString(resource);
			} catch (MissingResourceException mre) {
				// theString will contain the message id instead.
				;
			}
		}

		if (params != null) {
			if (res == null) {
				// couldn't find actual value, so no formatting should be done.
				StringBuilder sb = new StringBuilder(theString);
				sb.append(':');

				for (Object param : params) {
					sb.append(' ');
					sb.append('{');
					sb.append(param);
					sb.append('}');
				}
				theString = sb.toString();
			} else {
				theString = MessageFormat.format(theString, params);
			}
		}
		return theString;
	}

	protected abstract ResourceBundle getResourceBundle(Locale locale);
}
