path_desc = Directory path to be used by the Connector.
path_label = Directory Path
path_sript_label = Select...
path_script_help = Browse files system.
depth_desc = The number (non-negative) of levels to descent in the directory tree.
depth_label = Depth
filter_desc = Enter a filter string. By default glob syntax is expected.
filter_label = Filter
fileonly_desc = Only files will be returned when iterating the directory tree.
fileonly_label = Return Files Only
regexfilter_desc = Change the behavior of the "Filter" field to use regular expression syntax.
regexfilter_label = Use Regular Expression
followsymboliclinks_desc = If enabled, the content of the target of symbolic link directories will be returned.
followsymboliclinks_label = Follow Symbolic Links
forcedelete_desc = Force delete non-empty directories and read-only files.
forcedelete_label = Force Delete
keeporiginal_desc = Keep original files and directories when their path is changed. Thus, a copy operation is performed instead of move.
keeporiginal_label = Keep Original
createfile_desc = Determines whether a file or directory will be created by default.
createfile_label = Create File
CONN_TITLE = File Management Connector
Advanced = Advanced
