/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ibm_di_automation_IDispatch */

#ifndef _Included_com_ibm_di_automation_IDispatch
#define _Included_com_ibm_di_automation_IDispatch
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ibm_di_automation_IDispatch
 * Method:    QueryInterface
 * Signature: (Ljava/lang/String;)Lcom/ibm/di/automation/IDispatch;
 */
JNIEXPORT jobject JNICALL Java_com_ibm_di_automation_IDispatch_QueryInterface
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_ibm_di_automation_IDispatch
 * Method:    createInstance
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ibm_di_automation_IDispatch_createInstance
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_ibm_di_automation_IDispatch
 * Method:    release
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ibm_di_automation_IDispatch_release
  (JNIEnv *, jobject);

/*
 * Class:     com_ibm_di_automation_IDispatch
 * Method:    getIDsOfNames
 * Signature: (Ljava/lang/Object;I[Ljava/lang/String;)[I
 */
JNIEXPORT jintArray JNICALL Java_com_ibm_di_automation_IDispatch_getIDsOfNames
  (JNIEnv *, jclass, jobject, jint, jobjectArray);

/*
 * Class:     com_ibm_di_automation_IDispatch
 * Method:    invokev
 * Signature: (Ljava/lang/Object;Ljava/lang/String;III[Lcom/ibm/di/automation/VARIANT;[I)Lcom/ibm/di/automation/VARIANT;
 */
JNIEXPORT jobject JNICALL Java_com_ibm_di_automation_IDispatch_invokev
  (JNIEnv *, jclass, jobject, jstring, jint, jint, jint, jobjectArray, jintArray);

/*
 * Class:     com_ibm_di_automation_IDispatch
 * Method:    CLSIDfromProgID
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ibm_di_automation_IDispatch_CLSIDfromProgID
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_ibm_di_automation_IDispatch
 * Method:    enumMethods
 * Signature: (Ljava/lang/Object;)Ljava/util/Vector;
 */
JNIEXPORT jobject JNICALL Java_com_ibm_di_automation_IDispatch_enumMethods
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
