/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ibm_di_automation_IUnknown */

#ifndef _Included_com_ibm_di_automation_IUnknown
#define _Included_com_ibm_di_automation_IUnknown
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ibm_di_automation_IUnknown
 * Method:    QueryInterface
 * Signature: (Ljava/lang/String;)Lcom/ibm/di/automation/IUnknown;
 */
JNIEXPORT jobject JNICALL Java_com_ibm_di_automation_IUnknown_QueryInterface
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_ibm_di_automation_IUnknown
 * Method:    AddRef
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ibm_di_automation_IUnknown_AddRef
  (JNIEnv *, jobject);

/*
 * Class:     com_ibm_di_automation_IUnknown
 * Method:    Release
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ibm_di_automation_IUnknown_Release
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
