/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ibm_di_automation_VARIANT */

#ifndef _Included_com_ibm_di_automation_VARIANT
#define _Included_com_ibm_di_automation_VARIANT
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ibm_di_automation_VARIANT
 * Method:    toInt
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ibm_di_automation_VARIANT_toInt
  (JNIEnv *, jobject);

/*
 * Class:     com_ibm_di_automation_VARIANT
 * Method:    toDate
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_ibm_di_automation_VARIANT_toDate
  (JNIEnv *, jobject);

/*
 * Class:     com_ibm_di_automation_VARIANT
 * Method:    toBoolean
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_ibm_di_automation_VARIANT_toBoolean
  (JNIEnv *, jobject);

/*
 * Class:     com_ibm_di_automation_VARIANT
 * Method:    cloneIndirect
 * Signature: ()Lcom/ibm/di/automation/VARIANT;
 */
JNIEXPORT jobject JNICALL Java_com_ibm_di_automation_VARIANT_cloneIndirect
  (JNIEnv *, jobject);

/*
 * Class:     com_ibm_di_automation_VARIANT
 * Method:    toDouble
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_ibm_di_automation_VARIANT_toDouble
  (JNIEnv *, jobject);

/*
 * Class:     com_ibm_di_automation_VARIANT
 * Method:    toCurrency
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_ibm_di_automation_VARIANT_toCurrency
  (JNIEnv *, jobject);

/*
 * Class:     com_ibm_di_automation_VARIANT
 * Method:    toString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ibm_di_automation_VARIANT_toString
  (JNIEnv *, jobject);

/*
 * Class:     com_ibm_di_automation_VARIANT
 * Method:    toDispatch
 * Signature: ()Lcom/ibm/di/automation/IDispatch;
 */
JNIEXPORT jobject JNICALL Java_com_ibm_di_automation_VARIANT_toDispatch
  (JNIEnv *, jobject);

/*
 * Class:     com_ibm_di_automation_VARIANT
 * Method:    toByte
 * Signature: ()B
 */
JNIEXPORT jbyte JNICALL Java_com_ibm_di_automation_VARIANT_toByte
  (JNIEnv *, jobject);

/*
 * Class:     com_ibm_di_automation_VARIANT
 * Method:    toError
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ibm_di_automation_VARIANT_toError
  (JNIEnv *, jobject);

/*
 * Class:     com_ibm_di_automation_VARIANT
 * Method:    toFloat
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_ibm_di_automation_VARIANT_toFloat
  (JNIEnv *, jobject);

/*
 * Class:     com_ibm_di_automation_VARIANT
 * Method:    toSafeArray
 * Signature: (Z)Lcom/ibm/di/automation/SafeArray;
 */
JNIEXPORT jobject JNICALL Java_com_ibm_di_automation_VARIANT_toSafeArray
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_ibm_di_automation_VARIANT
 * Method:    putShortRef
 * Signature: (S)V
 */
JNIEXPORT void JNICALL Java_com_ibm_di_automation_VARIANT_putShortRef
  (JNIEnv *, jobject, jshort);

/*
 * Class:     com_ibm_di_automation_VARIANT
 * Method:    putIntRef
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_ibm_di_automation_VARIANT_putIntRef
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_ibm_di_automation_VARIANT
 * Method:    putDoubleRef
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_com_ibm_di_automation_VARIANT_putDoubleRef
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     com_ibm_di_automation_VARIANT
 * Method:    putDateRef
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_com_ibm_di_automation_VARIANT_putDateRef
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     com_ibm_di_automation_VARIANT
 * Method:    putStringRef
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ibm_di_automation_VARIANT_putStringRef
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_ibm_di_automation_VARIANT
 * Method:    putShort
 * Signature: (S)V
 */
JNIEXPORT void JNICALL Java_com_ibm_di_automation_VARIANT_putShort
  (JNIEnv *, jobject, jshort);

/*
 * Class:     com_ibm_di_automation_VARIANT
 * Method:    putInt
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_ibm_di_automation_VARIANT_putInt
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_ibm_di_automation_VARIANT
 * Method:    putLong
 * Signature: (J)V
 
JNIEXPORT void JNICALL Java_com_ibm_di_automation_VARIANT_putLong
  (JNIEnv *, jobject, jlong);
*/
/*
 * Class:     com_ibm_di_automation_VARIANT
 * Method:    putDate
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_com_ibm_di_automation_VARIANT_putDate
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     com_ibm_di_automation_VARIANT
 * Method:    putBoolean
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_ibm_di_automation_VARIANT_putBoolean
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_ibm_di_automation_VARIANT
 * Method:    putByte
 * Signature: (B)V
 */
JNIEXPORT void JNICALL Java_com_ibm_di_automation_VARIANT_putByte
  (JNIEnv *, jobject, jbyte);

/*
 * Class:     com_ibm_di_automation_VARIANT
 * Method:    putEmpty
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ibm_di_automation_VARIANT_putEmpty
  (JNIEnv *, jobject);

/*
 * Class:     com_ibm_di_automation_VARIANT
 * Method:    putError
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_ibm_di_automation_VARIANT_putError
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_ibm_di_automation_VARIANT
 * Method:    putNoParam
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ibm_di_automation_VARIANT_putNoParam
  (JNIEnv *, jobject);

/*
 * Class:     com_ibm_di_automation_VARIANT
 * Method:    putCurrency
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_ibm_di_automation_VARIANT_putCurrency
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_ibm_di_automation_VARIANT
 * Method:    putObject
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_ibm_di_automation_VARIANT_putObject
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_ibm_di_automation_VARIANT
 * Method:    putDouble
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_com_ibm_di_automation_VARIANT_putDouble
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     com_ibm_di_automation_VARIANT
 * Method:    putFloatRef
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_ibm_di_automation_VARIANT_putFloatRef
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_ibm_di_automation_VARIANT
 * Method:    putCurrencyRef
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_ibm_di_automation_VARIANT_putCurrencyRef
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_ibm_di_automation_VARIANT
 * Method:    putErrorRef
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_ibm_di_automation_VARIANT_putErrorRef
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_ibm_di_automation_VARIANT
 * Method:    putBooleanRef
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_ibm_di_automation_VARIANT_putBooleanRef
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_ibm_di_automation_VARIANT
 * Method:    putByteRef
 * Signature: (B)V
 */
JNIEXPORT void JNICALL Java_com_ibm_di_automation_VARIANT_putByteRef
  (JNIEnv *, jobject, jbyte);

/*
 * Class:     com_ibm_di_automation_VARIANT
 * Method:    putString
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ibm_di_automation_VARIANT_putString
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_ibm_di_automation_VARIANT
 * Method:    putNull
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ibm_di_automation_VARIANT_putNull
  (JNIEnv *, jobject);

/*
 * Class:     com_ibm_di_automation_VARIANT
 * Method:    getNull
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ibm_di_automation_VARIANT_getNull
  (JNIEnv *, jobject);

/*
 * Class:     com_ibm_di_automation_VARIANT
 * Method:    getShortRef
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_com_ibm_di_automation_VARIANT_getShortRef
  (JNIEnv *, jobject);

/*
 * Class:     com_ibm_di_automation_VARIANT
 * Method:    getIntRef
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ibm_di_automation_VARIANT_getIntRef
  (JNIEnv *, jobject);

/*
 * Class:     com_ibm_di_automation_VARIANT
 * Method:    getShort
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_com_ibm_di_automation_VARIANT_getShort
  (JNIEnv *, jobject);

/*
 * Class:     com_ibm_di_automation_VARIANT
 * Method:    getDoubleRef
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_ibm_di_automation_VARIANT_getDoubleRef
  (JNIEnv *, jobject);

/*
 * Class:     com_ibm_di_automation_VARIANT
 * Method:    getDateRef
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_ibm_di_automation_VARIANT_getDateRef
  (JNIEnv *, jobject);

/*
 * Class:     com_ibm_di_automation_VARIANT
 * Method:    getStringRef
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ibm_di_automation_VARIANT_getStringRef
  (JNIEnv *, jobject);

/*
 * Class:     com_ibm_di_automation_VARIANT
 * Method:    getInt
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ibm_di_automation_VARIANT_getInt
  (JNIEnv *, jobject);

/*
 * Class:     com_ibm_di_automation_VARIANT
 * Method:    getDate
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_ibm_di_automation_VARIANT_getDate
  (JNIEnv *, jobject);

/*
 * Class:     com_ibm_di_automation_VARIANT
 * Method:    getBoolean
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_ibm_di_automation_VARIANT_getBoolean
  (JNIEnv *, jobject);

/*
 * Class:     com_ibm_di_automation_VARIANT
 * Method:    getByte
 * Signature: ()B
 */
JNIEXPORT jbyte JNICALL Java_com_ibm_di_automation_VARIANT_getByte
  (JNIEnv *, jobject);

/*
 * Class:     com_ibm_di_automation_VARIANT
 * Method:    getEmpty
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ibm_di_automation_VARIANT_getEmpty
  (JNIEnv *, jobject);

/*
 * Class:     com_ibm_di_automation_VARIANT
 * Method:    getError
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ibm_di_automation_VARIANT_getError
  (JNIEnv *, jobject);

/*
 * Class:     com_ibm_di_automation_VARIANT
 * Method:    getDouble
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_ibm_di_automation_VARIANT_getDouble
  (JNIEnv *, jobject);

/*
 * Class:     com_ibm_di_automation_VARIANT
 * Method:    getCurrency
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_ibm_di_automation_VARIANT_getCurrency
  (JNIEnv *, jobject);

/*
 * Class:     com_ibm_di_automation_VARIANT
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ibm_di_automation_VARIANT_getString
  (JNIEnv *, jobject);

/*
 * Class:     com_ibm_di_automation_VARIANT
 * Method:    getFloatRef
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_ibm_di_automation_VARIANT_getFloatRef
  (JNIEnv *, jobject);

/*
 * Class:     com_ibm_di_automation_VARIANT
 * Method:    getCurrencyRef
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_ibm_di_automation_VARIANT_getCurrencyRef
  (JNIEnv *, jobject);

/*
 * Class:     com_ibm_di_automation_VARIANT
 * Method:    getErrorRef
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ibm_di_automation_VARIANT_getErrorRef
  (JNIEnv *, jobject);

/*
 * Class:     com_ibm_di_automation_VARIANT
 * Method:    getBooleanRef
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_ibm_di_automation_VARIANT_getBooleanRef
  (JNIEnv *, jobject);

/*
 * Class:     com_ibm_di_automation_VARIANT
 * Method:    getObjectRef
 * Signature: ()Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_ibm_di_automation_VARIANT_getObjectRef
  (JNIEnv *, jobject);

/*
 * Class:     com_ibm_di_automation_VARIANT
 * Method:    getByteRef
 * Signature: ()B
 */
JNIEXPORT jbyte JNICALL Java_com_ibm_di_automation_VARIANT_getByteRef
  (JNIEnv *, jobject);

/*
 * Class:     com_ibm_di_automation_VARIANT
 * Method:    putSafeArrayRef
 * Signature: (Lcom/ibm/di/automation/SafeArray;)V
 */
JNIEXPORT void JNICALL Java_com_ibm_di_automation_VARIANT_putSafeArrayRef
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_ibm_di_automation_VARIANT
 * Method:    putSafeArray
 * Signature: (Lcom/ibm/di/automation/SafeArray;)V
 */
JNIEXPORT void JNICALL Java_com_ibm_di_automation_VARIANT_putSafeArray
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_ibm_di_automation_VARIANT
 * Method:    putBSTR
 * Signature: (Lcom/ibm/di/automation/BSTR;)V
 */
JNIEXPORT void JNICALL Java_com_ibm_di_automation_VARIANT_putBSTR
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_ibm_di_automation_VARIANT
 * Method:    getFloat
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_ibm_di_automation_VARIANT_getFloat
  (JNIEnv *, jobject);

/*
 * Class:     com_ibm_di_automation_VARIANT
 * Method:    putFloat
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_ibm_di_automation_VARIANT_putFloat
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_ibm_di_automation_VARIANT
 * Method:    getvt
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_com_ibm_di_automation_VARIANT_getvt
  (JNIEnv *, jobject);

/*
 * Class:     com_ibm_di_automation_VARIANT
 * Method:    toShort
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_com_ibm_di_automation_VARIANT_toShort
  (JNIEnv *, jobject);

/*
 * Class:     com_ibm_di_automation_VARIANT
 * Method:    release
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ibm_di_automation_VARIANT_release
  (JNIEnv *, jobject);

/*
 * Class:     com_ibm_di_automation_VARIANT
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ibm_di_automation_VARIANT_init
  (JNIEnv *, jobject);

/*
 * Class:     com_ibm_di_automation_VARIANT
 * Method:    isNull
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_ibm_di_automation_VARIANT_isNull
  (JNIEnv *, jobject);

/*
 * Class:     com_ibm_di_automation_VARIANT
 * Method:    Save
 * Signature: (Ljava/io/OutputStream;)V
 */
JNIEXPORT void JNICALL Java_com_ibm_di_automation_VARIANT_Save
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_ibm_di_automation_VARIANT
 * Method:    Load
 * Signature: (Ljava/io/InputStream;)V
 */
JNIEXPORT void JNICALL Java_com_ibm_di_automation_VARIANT_Load
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
