<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" xmlns:fmt="http://www.eclipse.org/hyades/schema/Formatter.xsd" xmlns:pu="http://www.eclipse.org/hyades/schema/ProcessUnit.xsd" ecore:nsPrefix="fmt" ecore:package="formatter" elementFormDefault="qualified" targetNamespace="http://www.eclipse.org/hyades/schema/Formatter.xsd">
	<annotation>
	  <documentation xml:lang="en">
        Copyright (c) 2005,2006 IBM Corporation and others.
        All rights reserved.   This program and the accompanying materials
        are made available under the terms of the Eclipse Public License v1.0
        which accompanies this distribution, and is available at
        http://www.eclipse.org/legal/epl-v10.html
	  </documentation>
	 </annotation>
	<import namespace="http://www.eclipse.org/hyades/schema/ProcessUnit.xsd" schemaLocation="ProcessUnit.xsd"/>
	<element name="Formatter" type="fmt:FormatterType"/>
	<complexType name="FormatterType">
		<annotation>
			<documentation>
				A formatter has the role of given the input array of
				(name or ID, value string) pairs creating an object that represents
				that data. Usually the data in the array represents a
				complete message or record of some sort.  In each (name or ID, value
				string) pair, the name or ID maps to a member of the object and the
				value string represents the value of that member.
			</documentation>
		</annotation>
		 <complexContent>
            <extension base="pu:ProcessUnitType">
				<attributeGroup ref="fmt:FormatterAttributes"/>
			</extension>
        </complexContent>
     	 
	</complexType>
	<attributeGroup name="FormatterAttributes">
		<attribute default="false" name="dummyAttr1" type="boolean" use="optional">
			<annotation>
				<documentation>
					Reserved for future use. 
				</documentation>
			</annotation>
		</attribute>
		<attribute default="false" name="dummyAttr2" type="boolean" use="optional">
			<annotation>
				<documentation>
					Reserved for future use. 
				</documentation>
			</annotation>
		</attribute>
	</attributeGroup>
</schema>
