; Licensed Materials - Property of IBM
;
; 5724-Q63
;
; (C) Copyright IBM Corp. year1, year2 All Rights Reserved
;
; US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

[Service]
ServiceName=
WorkingDirectory=""
StartCommand=""
StopCommand=""

