/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_ibm_di_connector_NT4UserMetaDataConnector_NTMetaData */

#ifndef _Included_com_ibm_di_connector_NT4UserMetaDataConnector_NTMetaData
#define _Included_com_ibm_di_connector_NT4UserMetaDataConnector_NTMetaData
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ibm_di_connector_NT4UserMetaDataConnector_NTMetaData
 * Method:    logOn
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_ibm_di_connector_NT4UserMetaDataConnector_NTMetaData_logOn
  (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     com_ibm_di_connector_NT4UserMetaDataConnector_NTMetaData
 * Method:    isPrimaryDomainController
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_ibm_di_connector_NT4UserMetaDataConnector_NTMetaData_isPrimaryDomainController
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_ibm_di_connector_NT4UserMetaDataConnector_NTMetaData
 * Method:    userGetInfo
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Lcom/ibm/di/connector/NT4UserMetaDataConnector/UserInfo;
 */
JNIEXPORT jobject JNICALL Java_com_ibm_di_connector_NT4UserMetaDataConnector_NTMetaData_userGetInfo
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_ibm_di_connector_NT4UserMetaDataConnector_NTMetaData
 * Method:    getUsersNames
 * Signature: (Ljava/lang/String;IILjava/util/Vector;)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_di_connector_NT4UserMetaDataConnector_NTMetaData_getUsersNames
  (JNIEnv *, jclass, jstring, jint, jint, jobject);

/*
 * Class:     com_ibm_di_connector_NT4UserMetaDataConnector_NTMetaData
 * Method:    getUserLocalGroups
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/util/Vector;
 */
JNIEXPORT jobject JNICALL Java_com_ibm_di_connector_NT4UserMetaDataConnector_NTMetaData_getUserLocalGroups
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_ibm_di_connector_NT4UserMetaDataConnector_NTMetaData
 * Method:    getUserGlobalGroups
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/util/Vector;
 */
JNIEXPORT jobject JNICALL Java_com_ibm_di_connector_NT4UserMetaDataConnector_NTMetaData_getUserGlobalGroups
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_ibm_di_connector_NT4UserMetaDataConnector_NTMetaData
 * Method:    userAdd
 * Signature: (Ljava/lang/String;Lcom/ibm/di/connector/NT4UserMetaDataConnector/UserInfo;)V
 */
JNIEXPORT void JNICALL Java_com_ibm_di_connector_NT4UserMetaDataConnector_NTMetaData_userAdd
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     com_ibm_di_connector_NT4UserMetaDataConnector_NTMetaData
 * Method:    userDel
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ibm_di_connector_NT4UserMetaDataConnector_NTMetaData_userDel
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_ibm_di_connector_NT4UserMetaDataConnector_NTMetaData
 * Method:    userSetInfo
 * Signature: (Ljava/lang/String;Ljava/lang/String;Lcom/ibm/di/connector/NT4UserMetaDataConnector/UserInfo;)V
 */
JNIEXPORT void JNICALL Java_com_ibm_di_connector_NT4UserMetaDataConnector_NTMetaData_userSetInfo
  (JNIEnv *, jclass, jstring, jstring, jobject);

/*
 * Class:     com_ibm_di_connector_NT4UserMetaDataConnector_NTMetaData
 * Method:    userSetGlobalGroups
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/util/Vector;)V
 */
JNIEXPORT void JNICALL Java_com_ibm_di_connector_NT4UserMetaDataConnector_NTMetaData_userSetGlobalGroups
  (JNIEnv *, jclass, jstring, jstring, jobject);

/*
 * Class:     com_ibm_di_connector_NT4UserMetaDataConnector_NTMetaData
 * Method:    userSetPrimaryGroup
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ibm_di_connector_NT4UserMetaDataConnector_NTMetaData_userSetPrimaryGroup
  (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     com_ibm_di_connector_NT4UserMetaDataConnector_NTMetaData
 * Method:    userGetPrimaryGroup
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ibm_di_connector_NT4UserMetaDataConnector_NTMetaData_userGetPrimaryGroup
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_ibm_di_connector_NT4UserMetaDataConnector_NTMetaData
 * Method:    globalGroupGetInfo
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Lcom/ibm/di/connector/NT4UserMetaDataConnector/GroupInfo;
 */
JNIEXPORT jobject JNICALL Java_com_ibm_di_connector_NT4UserMetaDataConnector_NTMetaData_globalGroupGetInfo
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_ibm_di_connector_NT4UserMetaDataConnector_NTMetaData
 * Method:    getGlobalGroupsNames
 * Signature: (Ljava/lang/String;IILjava/util/Vector;)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_di_connector_NT4UserMetaDataConnector_NTMetaData_getGlobalGroupsNames
  (JNIEnv *, jclass, jstring, jint, jint, jobject);

/*
 * Class:     com_ibm_di_connector_NT4UserMetaDataConnector_NTMetaData
 * Method:    getGlobalGroupUsers
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/util/Vector;
 */
JNIEXPORT jobject JNICALL Java_com_ibm_di_connector_NT4UserMetaDataConnector_NTMetaData_getGlobalGroupUsers
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_ibm_di_connector_NT4UserMetaDataConnector_NTMetaData
 * Method:    globalGroupAdd
 * Signature: (Ljava/lang/String;Lcom/ibm/di/connector/NT4UserMetaDataConnector/GroupInfo;)V
 */
JNIEXPORT void JNICALL Java_com_ibm_di_connector_NT4UserMetaDataConnector_NTMetaData_globalGroupAdd
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     com_ibm_di_connector_NT4UserMetaDataConnector_NTMetaData
 * Method:    globalGroupAddUser
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ibm_di_connector_NT4UserMetaDataConnector_NTMetaData_globalGroupAddUser
  (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     com_ibm_di_connector_NT4UserMetaDataConnector_NTMetaData
 * Method:    globalGroupDel
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ibm_di_connector_NT4UserMetaDataConnector_NTMetaData_globalGroupDel
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_ibm_di_connector_NT4UserMetaDataConnector_NTMetaData
 * Method:    globalGroupDelUser
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ibm_di_connector_NT4UserMetaDataConnector_NTMetaData_globalGroupDelUser
  (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     com_ibm_di_connector_NT4UserMetaDataConnector_NTMetaData
 * Method:    globalGroupSetUsers
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/util/Vector;)V
 */
JNIEXPORT void JNICALL Java_com_ibm_di_connector_NT4UserMetaDataConnector_NTMetaData_globalGroupSetUsers
  (JNIEnv *, jclass, jstring, jstring, jobject);

/*
 * Class:     com_ibm_di_connector_NT4UserMetaDataConnector_NTMetaData
 * Method:    globalGroupSetInfo
 * Signature: (Ljava/lang/String;Ljava/lang/String;Lcom/ibm/di/connector/NT4UserMetaDataConnector/GroupInfo;)V
 */
JNIEXPORT void JNICALL Java_com_ibm_di_connector_NT4UserMetaDataConnector_NTMetaData_globalGroupSetInfo
  (JNIEnv *, jclass, jstring, jstring, jobject);

/*
 * Class:     com_ibm_di_connector_NT4UserMetaDataConnector_NTMetaData
 * Method:    localGroupGetInfo
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Lcom/ibm/di/connector/NT4UserMetaDataConnector/GroupInfo;
 */
JNIEXPORT jobject JNICALL Java_com_ibm_di_connector_NT4UserMetaDataConnector_NTMetaData_localGroupGetInfo
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_ibm_di_connector_NT4UserMetaDataConnector_NTMetaData
 * Method:    getLocalGroupsNames
 * Signature: (Ljava/lang/String;)Ljava/util/Vector;
 */
JNIEXPORT jobject JNICALL Java_com_ibm_di_connector_NT4UserMetaDataConnector_NTMetaData_getLocalGroupsNames
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_ibm_di_connector_NT4UserMetaDataConnector_NTMetaData
 * Method:    getLocalGroupUsers
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/util/Vector;
 */
JNIEXPORT jobject JNICALL Java_com_ibm_di_connector_NT4UserMetaDataConnector_NTMetaData_getLocalGroupUsers
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_ibm_di_connector_NT4UserMetaDataConnector_NTMetaData
 * Method:    getLocalGroupGlobalGroups
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/util/Vector;
 */
JNIEXPORT jobject JNICALL Java_com_ibm_di_connector_NT4UserMetaDataConnector_NTMetaData_getLocalGroupGlobalGroups
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_ibm_di_connector_NT4UserMetaDataConnector_NTMetaData
 * Method:    localGroupAdd
 * Signature: (Ljava/lang/String;Lcom/ibm/di/connector/NT4UserMetaDataConnector/GroupInfo;)V
 */
JNIEXPORT void JNICALL Java_com_ibm_di_connector_NT4UserMetaDataConnector_NTMetaData_localGroupAdd
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     com_ibm_di_connector_NT4UserMetaDataConnector_NTMetaData
 * Method:    localGroupDel
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ibm_di_connector_NT4UserMetaDataConnector_NTMetaData_localGroupDel
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_ibm_di_connector_NT4UserMetaDataConnector_NTMetaData
 * Method:    localGroupAddUsers
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/util/Vector;)V
 */
JNIEXPORT void JNICALL Java_com_ibm_di_connector_NT4UserMetaDataConnector_NTMetaData_localGroupAddUsers
  (JNIEnv *, jclass, jstring, jstring, jobject);

/*
 * Class:     com_ibm_di_connector_NT4UserMetaDataConnector_NTMetaData
 * Method:    localGroupAddGlobalGroups
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/util/Vector;)V
 */
JNIEXPORT void JNICALL Java_com_ibm_di_connector_NT4UserMetaDataConnector_NTMetaData_localGroupAddGlobalGroups
  (JNIEnv *, jclass, jstring, jstring, jobject);

/*
 * Class:     com_ibm_di_connector_NT4UserMetaDataConnector_NTMetaData
 * Method:    localGroupDelUsers
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/util/Vector;)V
 */
JNIEXPORT void JNICALL Java_com_ibm_di_connector_NT4UserMetaDataConnector_NTMetaData_localGroupDelUsers
  (JNIEnv *, jclass, jstring, jstring, jobject);

/*
 * Class:     com_ibm_di_connector_NT4UserMetaDataConnector_NTMetaData
 * Method:    localGroupDelGlobalGroups
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/util/Vector;)V
 */
JNIEXPORT void JNICALL Java_com_ibm_di_connector_NT4UserMetaDataConnector_NTMetaData_localGroupDelGlobalGroups
  (JNIEnv *, jclass, jstring, jstring, jobject);

/*
 * Class:     com_ibm_di_connector_NT4UserMetaDataConnector_NTMetaData
 * Method:    localGroupSetInfo
 * Signature: (Ljava/lang/String;Ljava/lang/String;Lcom/ibm/di/connector/NT4UserMetaDataConnector/GroupInfo;)V
 */
JNIEXPORT void JNICALL Java_com_ibm_di_connector_NT4UserMetaDataConnector_NTMetaData_localGroupSetInfo
  (JNIEnv *, jclass, jstring, jstring, jobject);

/*
 * Class:     com_ibm_di_connector_NT4UserMetaDataConnector_NTMetaData
 * Method:    localGroupSetMembers
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/util/Vector;)V
 */
JNIEXPORT void JNICALL Java_com_ibm_di_connector_NT4UserMetaDataConnector_NTMetaData_localGroupSetMembers
  (JNIEnv *, jclass, jstring, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
