CONN_DESC = Data Integration Services Bus JMS Connector
CONN_TITLE = DISB Connector
JMS_BROKER_LABEL = Broker
JMS_BROKER_DESC = DISB JMS Server address (ip host and tcp port number)
JMS_SERVER_CHANNEL_LABEL = Server Channel
JMS_SERVER_CHANNEL_DESC = MQ Server Channel
JMS_SSL_SERVER_CHANNEL_LABEL = SSL Server Channel
JMS_SSL_SERVER_CHANNEL_DESC = MQ SSL Server Channel
JMS_QUEUE_MANAGER_LABEL = Queue Manager
JMS_QUEUE_MANAGER_DESC = Specifies MQ Queue Manager Name
JMS_SSL_USE_FLAG_LABEL = Use SSL Connection 
JMS_SSL_USE_FLAG_DESC = If checked, you must have a properly configured DISB JMS provider
JMS_SSL_CIPHERSUITE_LABEL = SSL CipherSuite
JMS_SSL_CIPHERSUITE_DESC = CipherSuite names supported by WebSphere MQ
JMS_DURABLE_LABEL = Durable Topic Subscriber
JMS_DURABLE_DESC = Check if you dont want to miss out on messages when you are disconnected
JMS_USERNAME_LABEL = User Name
JMS_USERNAME_DESC = Login username for specified topic
JMS_PW_LABEL = Password
JMS_PW_DESC = Login password for specified topic
JMS_TOPIC_LABEL = DISB Queue/Topic
JMS_TOPIC_DESC = Enter DISB JMS queue or Topic name
JMS_TOPICTYPE_DESC = Choose the relevant DISB Topic Type
JMS_TOPICTYPE_LABEL = DISB Topic Type
JMS_MSGFLT_LABEL = Message Selection Filter
JMS_MSGFLT_DESC = Used for Iterator mode only and specifies a message filter selection for those messages you want returned
JMS_CONNTYPE_LABEL = Connection Type
JMS_CONNTYPE_DESC = Specify whether you are connecting to a Queue or Topic (Pub/Sub)
JMS_CLIENTID_LABEL = Client ID
JMS_CLIENTID_DESC = The client ID to use for Topic connections (mandatory for durable).
JMS_DRIVER_LABEL = DISB JMS Server Type
JMS_DRIVER_DESC = The full name of class implementing JMSDriver interface
JMS_DRV_ATTR_LABEL = Specific Driver Attributes
JMS_DRV_ATTR_DESC = Specific DISB JMS Driver Attributes
JMS_DRV_SCRIPT_LABEL = DISB JMS Driver Script
JMS_DRV_SCRIPT_DESC = Javascript used for initialization of the DISB JMS provider-specific objects
JMS_AUTOACK_LABEL = Auto Acknowledge
JMS_AUTOACK_DESC = If not checked you must manually acknowledge receipt of messages
JMS_MSGTYPE_LABEL = Select Message Type
JMS_MSGTYPE_DESC = Send TextMessage, BytesMessage or ObjectMessage to the DISB JMS bus.
JMS_LOOKUPMSG_LABEL = Lookup Removes
JMS_LOOKUPMSG_DESC = If checked Lookup operation removes matching messages from the queue
JMS_LOOKUPRETRY_LABEL = Lookup Retries
JMS_LOOKUPRETRY_DESC = Number of lookup retries
JMS_LOOKUPTIMEOUT_LABEL = Lookup Timeout
JMS_LOOKUPTIMEOUT_DESC = Lookup TimeoutNumber milliseconds between each lookup retry 
JMS_HEADERATTRIB_LABEL = DISB JMS Headers as attributes
JMS_HEADERATTRIB_DESC = Set/Get all DISB JMS headers from/to attributes (prefixed by jms.)
JMS_SPECIFIC_HEADERATTRIB_LABEL = Specific DISB JMS Headers
JMS_SPECIFIC_HEADERATTRIB_DESC = Set/Get specific DISB JMS headers from/to attributes (prefixed by jms.)
JMS_PROPERTIESATTRIB_LABEL = DISB JMS Properties as attributes
JMS_PROPERTIESATTRIB_DESC = Set/Get all DISB JMS properties from/to attributes (prefixed by jms.)
JMS_SPECIFIC_PROPERTIESATTRIB_LABEL = Specific DISB JMS Properties
JMS_SPECIFIC_PROPERTIESATTRIB_DESC = Set/Get specific DISB JMS properties from/to attributes (prefixed by jms.)
JMS_TIMEOUT_LABEL = GetNext Timeout
JMS_TIMEOUT_DESC = Number milliseconds to wait for a new entry in Iterator mode (-1 \=\= forever) 
Localized.subscriber = subscriber
Localized.publisher = publisher
Localized.Topic = Topic
Localized.Queue = Queue
Advanced = Advanced
DISB_IDML_MSG_USE_FLAG_LABEL = IDML Input Mode
DISB_IDML_MSG_USE_FLAG_DESC = If checked, you must provide the IDML as an attribute.
DISB_IDML_MSG_VALIDATE_FLAG_LABEL = Validate IDML
DISB_IDML_MSG_VALIDATE_FLAG_DESC = If checked, the provided IDML is validated.
DISB_JSON_MSG_USE_FLAG_LABEL = JSON Input Mode
DISB_JSON_MSG_USE_FLAG_DESC = If checked, you must provide the JSON as an attribute.
